Repository UK-Export-Finance/dtfs2, pull requests merged in 2021-11, with the labels that each got.

#441 update READMEs - notifying other teams of breaking changes
  README.md
  trade-finance-manager-api/README.md
  utils/mock-data-loader/README.md
Labels: documentation

#474 feature(DTFS-4180): Portal - Ability to review a UKEF declined manual inclusion application
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-underwriter-comment-gef.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/underwriter-managers-decision-decline.spec.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/nunjucks-configuration/filter-getStatusLabel.js
  gef-ui/templates/includes/application-preview/ukef-decision.njk
  gef-ui/templates/partials/application-preview.njk
  portal/server/nunjucks-configuration/filter-getStatusLabel.js
  portal/server/nunjucks-configuration/filter-getStatusLabel.test.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/placeholder.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/api-tests/v1/mappings/map-deal.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-team-members.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-user.api-test.js
  trade-finance-manager-api/graphql-query-tests/graphql-authentication.api-test.js
  trade-finance-manager-api/graphql-query-tests/mock-deal.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-credit-rating.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-facilities.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-facility-risk-profile.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-lead-underwriter.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-loss-given-default.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-parties.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-probability-of-default.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-task.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-underwriting-managers-decision.api-test.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/azure-env/index.js
  trade-finance-manager-api/src/constants/deals.js
  trade-finance-manager-api/src/constants/tasks.js
  trade-finance-manager-api/src/createApp.js
  trade-finance-manager-api/src/drivers/db-client.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapDeals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapEligibility.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapFacilityType.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDeal.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.js
  trade-finance-manager-api/src/scheduler/jobs/check-azure-number-generator-function.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/src/v1/controllers/number-generator.controller.js
  trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-bss.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.api-test.js
  trade-finance-manager-api/src/v1/helpers/is-facility-valid-for-premium-schedule.api-test.js
Labels: feature

#442 DTFS2-4998 - Added helmet to improve security
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/createApp.js
  dtfs-central-api/src/drivers/db-client.js
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/index.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/createApp.js
  portal/package-lock.json
  portal/package.json
  portal/server/index.js
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/createApp.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/createApp.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/index.js
Labels: feature, tech debt
