Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-11, with the labels that each got.

#1226 fix: Failing e2e tests
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/portal/cypress/e2e/journeys/checker/currency-conversion-date/deal-first-submission.js
  e2e-tests/portal/cypress/e2e/journeys/checker/return-a-deal-to-maker/dealWithSomeIssuedFacilitiesReadyForReview.js
  e2e-tests/portal/cypress/e2e/journeys/checker/submit-a-deal/test-data/dealReadyToSubmit.js
  e2e-tests/portal/cypress/e2e/journeys/checker/submit-a-deal/test-data/dealWithInvalidBondCoverStartDate.js
  e2e-tests/portal/cypress/e2e/journeys/checker/submit-a-deal/test-data/dealWithInvalidLoanCoverStartDate.js
  e2e-tests/portal/cypress/e2e/journeys/checker/submit-a-deal/test-data/submittedDealWithBondCoverStartDateInThePast.js
  e2e-tests/portal/cypress/e2e/journeys/checker/submit-a-deal/test-data/submittedDealWithLoanCoverStartDateInThePast.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bond/bond-form-values.js
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/MIA-accepted-deal-status-maker-cannot-resubmit-until-confirmed-all-issued-facilities-cover-start-date/MIA-deal-with-accepted-status-issued-facilities.js
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/MIA-accepted-deal-status-maker-must-change-cover-start-date-on-facilities-with-cover-start-date-in-the-past.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/fixtures/MIA-draft-deal-with-issued-facilities.js
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/maker-can-edit-issued-facilities-after-checker-returns-to-maker-after-submit-to-ukef/MIA-deal-submitted-to-ukef-with-issued-facilities-after-checker-returned-to-maker.js
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/maker-can-edit-issued-facilities-after-checker-returns-to-maker-after-submit-to-ukef/maker-can-edit-issued-facilities-after-checker-returns-to-maker-after-submit-to-ukef.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/maker-cannot-edit-issued-facilities-after-submit-to-ukef/deal-multiple-facility-types-ready-to-submit-to-ukef.js
  e2e-tests/portal/cypress/e2e/journeys/maker/fill-and-submit-issue-facility-form/fillAndSubmitIssueBondFacilityForm.js
  e2e-tests/portal/cypress/e2e/journeys/maker/fill-and-submit-issue-facility-form/fillAndSubmitIssueLoanFacilityForm.js
  e2e-tests/portal/cypress/e2e/journeys/maker/fixtures/dealFullyCompleted.js
  e2e-tests/portal/cypress/e2e/journeys/maker/loan/loan-form-values.js
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review/dealWithNoBondCoverStartDate.js
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review/dealWithNoLoanCoverStartDate.js
  e2e-tests/portal/cypress/e2e/journeys/number-generator/test-data/dealReadyToSubmit.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/submit-deal-with-issued-facilities/test-data/dealReadyToSubmit.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/submit-deal-with-non-gbp-facilities/test-data/dealReadyToSubmit.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/test-data/AIN-deal/dealReadyToSubmit.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/test-data/MIA-deal/dealReadyToSubmit.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/test-data/MIN-deal-unissued-facilities/dealReadyToSubmit.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/test-data/MIN-deal/dealReadyToSubmit.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/8. amendment-details-manual-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/add-bank-decision-proceed.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/deal-AIN.spec.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-AIN.js
Labels: Type: Fix

#1223 fix(DTFS2-6139): Property name correction whilst de-constructing
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: Type: Bug, Type: ACBS, Type: Fix

#1222 chore: updated Nodejs to `v18.12-alpine3.16`
  README.md
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: Type: Chore, dependencies

#1227 fix(DTFS2-6143): Payload construction
  portal/server/helpers/constructPayload.js
  portal/server/helpers/constructPayload.test.js
  portal/server/helpers/index.js
  portal/server/routes/user/profile.js
Labels: Type: Docs, Type: Fix, Type: Security

#1213 fix(DTFS-6107): partyURN validation
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/parties/agent.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/parties/bond-beneficiary.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/parties/bond-issuer.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/parties/buyer.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/parties/exporter.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/parties/indemnifier.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/pages/agentPage.js
  e2e-tests/trade-finance-manager/cypress/e2e/pages/bondBeneficiaryPage.js
  e2e-tests/trade-finance-manager/cypress/e2e/pages/bondIssuerPage.js
  e2e-tests/trade-finance-manager/cypress/e2e/pages/buyerPage.js
  e2e-tests/trade-finance-manager/cypress/e2e/pages/exporterPage.js
  e2e-tests/trade-finance-manager/cypress/e2e/pages/indemnifierPage.js
  e2e-tests/trade-finance-manager/cypress/plugins/index.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/helpers.js
  trade-finance-manager-ui/server/controllers/case/parties/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.js
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/partyUrnValidation.validate.js
  trade-finance-manager-ui/server/controllers/case/parties/partyUrnValidation.validate.test.js
  trade-finance-manager-ui/server/graphql/queries/deal-query.js
  trade-finance-manager-ui/templates/case/parties/_macros/parties-agent-area.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-bond-beneficiary-edit.component-test.js
  trade-finance-manager-ui/templates/case/parties/_macros/parties-bond-beneficiary-edit.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-bond-issuer-edit.component-test.js
  trade-finance-manager-ui/templates/case/parties/_macros/parties-bond-issuer-edit.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-buyer-area.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-exporter-area.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-indemnifier-area.njk
  trade-finance-manager-ui/templates/case/parties/edit/agent-edit.njk
  trade-finance-manager-ui/templates/case/parties/edit/bonds-beneficiary-edit.njk
  trade-finance-manager-ui/templates/case/parties/edit/bonds-issuer-edit.njk
  trade-finance-manager-ui/templates/case/parties/edit/buyer-edit.njk
  trade-finance-manager-ui/templates/case/parties/edit/exporter-edit.njk
  trade-finance-manager-ui/templates/case/parties/edit/indemnifier-edit.njk
Labels: Type: Fix

#1229 fix(DTFS2-6143): payload being passed instead of req.body
  portal/server/routes/admin/users.js
  portal/server/routes/user/profile.js
Labels: Type: Fix

#1228 fix(DTFS2-6142): GEF validation coverStartDate issue facility MIA
  gef-ui/server/controllers/unissued-facilities/validation.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
Labels: Type: Fix

#1224 feat(DTFS2-5850): Dashboard filtering and logic
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-filter-by-multiple-fields-multiple-values.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-filter-by-multiple-fields.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-main-container-filter-remove.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-multiple-fields-multiple-values.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-multiple-fields.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-main-container-filter-remove.spec.js
  e2e-tests/portal/cypress/e2e/pages/dashboardDeals.js
  e2e-tests/trade-finance-manager/cypress/plugins/index.js
  portal/server/controllers/dashboard/deals/deals-filters-query.js
  portal/server/controllers/dashboard/deals/deals-filters-query.test.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
  portal/server/controllers/dashboard/filters/remove-filter-from-session.js
Labels: Type: Bug, Type: Feature

#1231 fix(DTFS2-6142): Unissued Tables deadline
  e2e-tests/gef/cypress/e2e/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  gef-ui/server/utils/facility-helpers.js
  gef-ui/server/utils/facility-helpers.test.js
Labels: Type: Fix

#1237 feat(DTFS2-5960): Portal facilities created by you
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-created-by-you.spec.js
  e2e-tests/portal/cypress/e2e/pages/dashboardFacilities.js
  portal/server/constants/field-names.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
  portal/server/controllers/dashboard/facilities/selected-filters.js
  portal/server/controllers/dashboard/facilities/template-filters.js
  portal/server/controllers/dashboard/facilities/template-filters.test.js
Labels: Type: Feature

#1238 fix(DTFS2-6161): Added unique reference to all outgoing email addresses
  reference-data-proxy/src/v1/controllers/email.controller.ts
Labels: Type: Bug, Type: Fix

#1239 fix(DTFS2-6157): Loader utils upgraded to 2.0.4
  gef-ui/package-lock.json
  portal/package-lock.json
  trade-finance-manager-ui/package-lock.json
Labels: Type: Fix, dependencies

#1240 feat(DTFS2-6154): Amended EC18 for BSS/EWCS v6 EC
  portal/public/files/BSS EWCS Manual Inclusion Questionnaire.pdf
  portal/public/files/BSS_EWCS Manual Inclusion Questionnaire.docx
  trade-finance-manager-api/src/v1/content-strings/index.js
Labels: Type: Feature
