Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-01, with the labels that each got.

#562 DTFS2-4391 : GEF deal record - multiple currencies
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-value.js
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-value.js
Labels: bug

#560 DTFS2-4812 : Create GEF Customer
  azure-functions/acbs-function/mappings/deal/deal.js
  portal-api/src/v1/gef/mappings/map-companies-house-data.api-test.js
  portal-api/src/v1/gef/mappings/map-companies-house-data.js
Labels: bug

#558 GEF deal with maker object instead of userId
  dtfs-central-api/src/v1/controllers/portal/deal/get-deal.controller.js
  dtfs-central-api/src/v1/swagger-definitions/portal/deal-gef.js
  e2e-tests/gef/cypress/integration/application-activities-AIN.spec.js
  e2e-tests/gef/cypress/integration/application-activities-MIA.spec.js
  e2e-tests/gef/cypress/integration/application-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/admin/reports/reconciliation-report/report-filter-by-bank.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/dashboard/bss-deals/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/dashboard/gef-deals/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal-api/api.js
  e2e-tests/portal/cypress/support/portal-api/insertManyGefApplications.js
  e2e-tests/portal/cypress/support/portal-api/listAllUsers.js
  e2e-tests/portal/cypress/support/portal-api/removeUserIfPresent.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/controllers/clone-gef-deal/index.test.js
  gef-ui/server/controllers/confirm-cover-start-date/index.test.js
  gef-ui/server/controllers/mocks/index.js
  gef-ui/server/utils/MOCKS/mock_applications.js
  gef-ui/server/utils/MOCKS/mock_users.js
  gef-ui/server/utils/user-authorisation-level.test.js
  portal-api/api-tests/fixtures/gef/application.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/clone-application.api-test.js
  portal-api/api-tests/v1/gef/files.api-test.js
  portal-api/src/graphql/schemas/index.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/gef/models/application.js
  portal-api/src/v1/users/sanitizeUserData.js
  portal/server/controllers/dashboard/deals.js
  portal/server/controllers/dashboard/deals.test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
  utils/mock-data-loader/gef/application.js
Labels: tech debt

#564 ACBS
  azure-functions/acbs-function/constants/deal.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-currency.js
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-cover-start-date.js
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-issue-status.js
  azure-functions/acbs-function/mappings/facility/helpers/get-issue-date.js
  azure-functions/acbs-function/mappings/facility/helpers/index.js
Labels: bug, documentation

#571 DTFS2-4812 : Create ACBS GEF customer record
  trade-finance-manager-api/src/v1/controllers/deal.controller.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
Labels: bug

#573 DTFS2-4054 : TFM ACBS interaction activites
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/helpers/activity.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-currency.js
Labels: bug

#574 Align BSS UI constants
  e2e-tests/portal/cypress/integration/journeys/admin/reports/audit-supply-contracts/report-filter-by-status.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/reports/audit-supply-contracts/report-paginate.spec.js
  portal/component-tests/contract/contract-view.component-test.js
  portal/server/constants/status.js
  portal/server/constants/submission-type.js
  portal/server/controllers/dashboard/deals.js
  portal/server/controllers/dashboard/deals.test.js
  portal/server/controllers/dashboard/facilities.js
  portal/server/controllers/dashboard/facilities.test.js
  portal/server/routes/buildDashboardFilters.js
  portal/server/routes/contract/isDealEditable.js
  portal/server/routes/contract/userCanSubmitDeal.js
  portal/templates/dashboard/_macros/deal-advanced-filters.njk
  portal/templates/reports/_macros/audit-supply-contracts-filters.njk
Labels: tech debt

#575 DTFS 4320 Ability to search on the "All facilities" page
  dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js
  e2e-tests/trade-finance-manager/cypress/fixtures/constants.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-AIN.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-MIA.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/facility/facilities.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/facilitiesPage.js
  trade-finance-manager-api/src/graphql/resolvers/query-facilities.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/facility.controller.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/public/images/chevron-right.svg
  trade-finance-manager-ui/public/images/search.svg
  trade-finance-manager-ui/templates/facilities/_macros/facilities-table-search-form.njk
  trade-finance-manager-ui/templates/facilities/facilities.njk
  trade-finance-manager-ui/webpack.common.config.js
  trade-finance-manager-ui/webpack.dev.config.js
Labels: feature

#580 DTFS2-4583 : ACBS GEF MIN Records
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Labels: bug

#584 DTFS2-4054 : 'async' keyword for all ACBS calls
  azure-functions/acbs-function/api.js
Labels: bug

#585 fix typos in TFM e2e mock deals after data changes
  e2e-tests/trade-finance-manager/cypress/fixtures/create-mock-deal.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-AIN.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-MIA.js
Labels: bug

#582 fix/bug - add lastUpdated to TFM deals query/schema
  trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-ui/server/graphql/queries/deals-query.js
Labels: bug

#587 Mock-data-loader clear gef-facilities and durable-functions-log
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions-controller.js
  dtfs-central-api/src/v1/controllers/portal/gef-facility/get-facilities.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  portal-api/src/v1/api.js
  utils/mock-data-loader/clean-all-tables-gef.js
  utils/mock-data-loader/gef/api.js
Labels: tech debt

#583 DTFS2-4155 : Review UKEF approval application, confirm facility cover start date and issue unissued facilities
  e2e-tests/gef/cypress/fixtures/constants.js
  e2e-tests/gef/cypress/fixtures/helpers.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js
  e2e-tests/gef/cypress/integration/application-activities-AIN.spec.js
  e2e-tests/gef/cypress/integration/application-activities-MIA.spec.js
  e2e-tests/gef/cypress/integration/application-details.spec.js
  e2e-tests/gef/cypress/integration/pages/application-details.js
  e2e-tests/gef/cypress/integration/pages/application-preview.js
  e2e-tests/gef/cypress/integration/pages/cover-start-date.js
  e2e-tests/gef/cypress/integration/return-to-maker-mia.spec.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/submit-to-ukef-mia.spec.js
  e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/support/commands/api.js
  e2e-tests/gef/cypress/support/index.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/controllers/application-submission/index.js
  gef-ui/server/controllers/application-submission/index.test.js
  gef-ui/server/controllers/mocks/index.js
  gef-ui/server/controllers/review-decision/index.js
  gef-ui/server/controllers/review-decision/index.test.js
  gef-ui/server/controllers/submit-to-ukef/index.js
  gef-ui/server/controllers/submit-to-ukef/index.test.js
  gef-ui/server/utils/deal-helpers.js
  gef-ui/server/utils/facility-helpers.js
  gef-ui/server/utils/facility-helpers.test.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/server/utils/mocks/mock_applications.js
  gef-ui/templates/_macros/submit-confirmation-title.njk
  gef-ui/templates/application-details-submitted.njk
  gef-ui/templates/includes/application-details/supporting-information.njk
  gef-ui/templates/includes/application-preview/task-comments.njk
  gef-ui/templates/partials/confirm-cover-start-date.njk
  gef-ui/templates/partials/cover-start-date.njk
  gef-ui/templates/partials/review-decision.njk
  gef-ui/templates/partials/submit-to-ukef-confirmation.njk
  gef-ui/templates/partials/unissued-facilities.njk
  package-lock.json
  package.json
  portal-api/api-tests/v1/gef/application-submit.api-test.js
  portal-api/src/v1/gef/controllers/application-submit.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/validation/application.js
  portal-api/src/v1/gef/models/facilities.js
Labels: feature, peer

#591 DTFS2-5078 : Update cover start date
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-MIN.spec.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/server/utils/mocks/mock_applications.js
Labels: feature

#599 fix - TFM graphQL reducer adding totals to a GEF deal
  trade-finance-manager-api/src/graphql/reducers/deals.api-test.js
  trade-finance-manager-api/src/graphql/reducers/deals.js
Labels: bug

#602 DTFS2-4174 - TFM tasks patches (update unlocking task rule, send emails for underwriting tasks unlocking)
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA-all-tasks.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-helpers.js
  trade-finance-manager-api/src/v1/controllers/send-tfm-email.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
  trade-finance-manager-api/src/v1/helpers/tasks.api-test.js
  trade-finance-manager-api/src/v1/helpers/tasks.js
  trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.api-test.js
  trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.js
Labels: bug, feature

#608 fix - GEF status update emails
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/src/v1/gef/controllers/application.controller.js
Labels: bug

#609 DTFS2-4586 : ACBS Facility update
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-facility-master/index.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
  reference-data-proxy/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js
Labels: bug, documentation, tech debt

#613 rename BSS/EWCS issuedFacilitySubmittedToUkefTimestamp
  dtfs-central-api/src/v1/swagger-definitions/portal/facility-bss.js
  dtfs-central-api/src/v1/swagger-definitions/portal/facility-ewcs.js
  e2e-tests/portal/cypress/fixtures/templates/aDealWithOneBond.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm.spec.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued.spec.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued.spec.js
  portal-api/api-tests/v1/deal-summary/index.api-test.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted-updates-unsubmitted-issued-facilities.api-test.js
  portal-api/src/v1/controllers/deal-status/update-submitted-issued-facilities.js
  portal-api/src/v1/deal-summary/index.js
  trade-finance-manager-api/graphql-query-tests/mock-deal.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapDates.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapDates.js
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-api/src/v1/__mocks__/mock-cash-contingent-facilities.js
  trade-finance-manager-api/src/v1/__mocks__/mock-facilities.js
  utils/data-migration/maps/map-bond-transactions.js
  utils/data-migration/maps/map-loan-transactions.js
Labels: tech debt

#614 fix TFM client side JS
  trade-finance-manager-ui/server/index.js
Labels: bug

#615 DTFS2-5301 : Portal UI SSH Access
  portal/Dockerfile
  portal/sshd_config
Labels: feature, tech debt, dependencies

#616 DTFS2-5301 : Portal UI SSH
  portal/Dockerfile
  portal/ssh_setup.sh
Labels: feature, dependencies

#624 fix/DTFS2-5326 - change team for "file all deal emails" TFM task
  e2e-tests/trade-finance-manager/cypress/fixtures/tasks-MIA.js
  trade-finance-manager-api/src/constants/tasks.js
  trade-finance-manager-api/src/v1/__mocks__/mock-MIA-tasks-populated.js
  trade-finance-manager-api/src/v1/__mocks__/mock-MIA-tasks.js
Labels: bug

#627 fix TFM deals query issue, improve graphQL error handling
  trade-finance-manager-api/api-tests/v1/mappings/map-deals.api-test.js
  trade-finance-manager-api/src/createApp.js
  trade-finance-manager-api/src/v1/mappings/map-deals.js
Labels: bug, tech debt

#635 Remove Sentry integration
  docker-compose.dev.yml
  docker-compose.yml
  e2e-tests/portal/cypress/integration/journeys/reports/review-ukef-decision.spec.js
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/index.js
  gef-ui/server/utils/sentry.js
  portal-api/api-tests/v1/reports/review-ukef-decision.api-test.js
  portal-api/src/v1/controllers/reports/review-ukef-decision.controller.js
  portal/package-lock.json
  portal/package.json
  portal/server/index.js
  portal/server/utils/sentry.js
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/createApp.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/createApp.js
Labels: tech debt

#637 DTFS2-5301 : SSH Access
  azure-functions/acbs-function/init.sh
  azure-functions/number-generator-function/init.sh
  reference-data-proxy/Dockerfile
  reference-data-proxy/api-tests/v1/exposure-period.api-test.js
Labels: bug

#639 Fix/DTFS2-5238 DTFS2-5239 - fix GEF mappings in TFM
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.js
Labels: bug
