Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-10, with the labels that each got.

#1187 fix: TFM failing e2e tests
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-changes-multiple-single-amendments.spec.js
Labels: Type: Bug, Type: Amendments

#1191 fix: Removed `main-amendments` from GHA
  .github/workflows/README.md
  .github/workflows/deploy.sh
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/pr_no_tests.yml
  .github/workflows/scan_codeql_analysis.yml
Labels: Type: Fix, BREAKING

#1193 fix: `ObjectId` facility IDs instead of `String`
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deal.controller.js
Labels: Type: Fix

#1195 feat(Reporting): RAD Reporting
  utils/reporting/tfm/.eslintignore
  utils/reporting/tfm/.eslintrc.js
  utils/reporting/tfm/rad-reporting.js
Labels: Type: Feature

#1198 fix(acbs): GEF facility loan record ML amendment
  azure-functions/acbs-function/acbs-amend-facility/index.js
Labels: Type: ACBS, Type: Fix

#1199 feat(DTFS2-6098): Show exchange rate in TFM
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-non-gbp-facilities/submit-deal-with-non-gbp-facilities.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/facilityPage.js
  trade-finance-manager-ui/templates/case/facility/_macros/facility_details.component-test.js
  trade-finance-manager-ui/templates/case/facility/_macros/facility_details.njk
Labels: Type: Docs, Type: Feature

#1200 fix(DTFS2-6023): Facility amendment decrement
  azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-amount-difference.js
Labels: Type: ACBS, Type: Fix

#1201 feat(DTFS2-6023): Facility amendment SOFs
  azure-functions/acbs-function/acbs-amend-facility-loan-record/function.json
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility-master-record/function.json
  azure-functions/acbs-function/acbs-amend-facility-master-record/index.js
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
Labels: Type: Docs, Type: ACBS, Type: Fix

#1185 feat(DTFS2-5961): Portal facility exporter column and sorting
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-exporter-name.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-sort.spec.js
  e2e-tests/portal/cypress/integration/pages/dashboardFacilities.js
  e2e-tests/portal/cypress/support/portal-api/api.js
  e2e-tests/portal/cypress/support/portal-api/insertManyGefFacilities.js
  portal-api/src/v1/controllers/facilities.controller.js
  portal/server/constants/field-names.js
  portal/server/controllers/dashboard/facilities/facilities-filters-keyword-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-keyword-query.test.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
  portal/server/controllers/dashboard/facilities/index.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/routes/dashboard.js
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
  portal/templates/dashboard/facilities.njk
Labels: Type: Feature

#1204 fix: failing coverEndDate e2e tests
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-AIN.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/6. cover-end-date.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/8. amendment-details-manual-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-proceed.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-underwriter-declined.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-withdraw.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-should-change-all-facilities-values.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendments-version-order.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/facility/facilities.spec.js
Labels: Type: Fix

#1203 fix(DTFS2-5961): Uppercase lowercase sorting fix
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-sort.spec.js
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/controllers/facilities.controller.js
  portal/server/controllers/dashboard/sort/helpers.js
Labels: Type: Bug

#1206 fix: Added optional chaining where userProfile will be null
  portal-api/src/v1/gef/controllers/portal-activities.controller.js
Labels: Type: Fix

#1205 fix(DTFS2-6108): tasks locked to user groups
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-AIN.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA-all-tasks.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA.spec.js
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.component-test.js
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk
  trade-finance-manager-ui/templates/case/tasks/tasks.njk
Labels: Type: Fix

#1207 fix(DTFS2-6108): Amendment tasks lock
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-automatic.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-manual.spec.js
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
Labels: Type: Fix

#1211 fix(DTFS-6093): BSS Issue Facility Validation
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/AIN-facility-cover-start-date-validation-past-3-months.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/fixtures/AIN-deal-submitted-3-months-more.js
  e2e-tests/portal/cypress/integration/pages/loanIssueFacility.js
  e2e-tests/portal/cypress/support/utils/dateFuncs.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility-validation.api-test.js
  portal-api/src/v1/validation/fields/cover-end-date.js
  portal-api/src/v1/validation/fields/issue-facility/requested-cover-start-date.js
Labels: Type: Fix

#1212 fix(DTFS2-6116): Facilities mapping on existence only
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilities.js
Labels: Type: Fix

#1215 fix(DTFS2-6116): Void facility validations
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapFacilities.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapFacility.js
Labels: Type: Fix

#1216 fix(DTFS2-6116): Object validation + DTFS Central API Resource upgrade
  dtfs-central-api/src/createApp.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapDeals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.js
Labels: Type: Fix

#1219 fix(DTFS2-6116): Payload size & void object check
  dtfs-central-api/src/createApp.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/amendment-should-change-all-facilities-values.spec.js
  trade-finance-manager-api/src/graphql/reducers/deals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapFacilityTfm.js
Labels: Type: Fix

#1221 fix(DTFS-6128): Users with multiple teams not being able to access tasks
  e2e-tests/e2e-fixtures/tfm-users.fixture.js
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk
Labels: Type: Bug, Type: Amendments
