Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-04, with the labels that each got.

#897 DTFS2-ACBS : Facility & Party
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/mappings/party/agent.js
  azure-functions/acbs-function/mappings/party/bank.js
  azure-functions/acbs-function/mappings/party/bondBeneficary.js
  azure-functions/acbs-function/mappings/party/bondIssuer.js
  azure-functions/acbs-function/mappings/party/buyer.js
  azure-functions/acbs-function/mappings/party/indemnifier.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: bug, documentation

#907 DTFS2-5438- TFM Bug - Missing facility data
  dtfs-central-api/src/createApp.js
  e2e-tests/trade-finance-manager/cypress/fixtures/mock-gef-facilities.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/deal-page-GEF.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/facility/facility.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/facilityPage.js
  trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.js
  trade-finance-manager-api/src/v1/__mocks__/mock-cash-contingent-facilities.js
Labels: bug

#908 DNS
  .github/workflows/tfm-dns.yml
Labels: dependencies

#909 DTFS2-Security : Proxy
  gef-ui/server/index.js
  portal/README.md
  portal/server/index.js
  trade-finance-manager-ui/server/index.js
Labels: bug

#917 DTFS2-Bugs : CSP + Start + PII
  azure-functions/acbs-function/mappings/party/agent.js
  azure-functions/acbs-function/mappings/party/bank.js
  azure-functions/acbs-function/mappings/party/bondBeneficary.js
  azure-functions/acbs-function/mappings/party/bondIssuer.js
  azure-functions/acbs-function/mappings/party/buyer.js
  azure-functions/acbs-function/mappings/party/exporter.js
  azure-functions/acbs-function/mappings/party/indemnifier.js
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  gef-ui/server/middleware/headers/security.js
  portal-api/src/v1/middleware/headers/security.js
  portal/server/routes/middleware/headers/security.js
  portal/templates/_partials/before-you-start.njk
  reference-data-proxy/src/middleware/headers/security.ts
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/server/middleware/headers/security.js
Labels: bug

#918 DTFS2-ACBS : Party constants
  azure-functions/acbs-function/constants/party.js
  azure-functions/acbs-function/mappings/party/agent.js
  azure-functions/acbs-function/mappings/party/bank.js
  azure-functions/acbs-function/mappings/party/bondBeneficary.js
  azure-functions/acbs-function/mappings/party/bondIssuer.js
  azure-functions/acbs-function/mappings/party/buyer.js
  azure-functions/acbs-function/mappings/party/helpers/get-sme-type.js
  azure-functions/acbs-function/mappings/party/indemnifier.js
Labels: tech debt, ACBS

#922 DTFS2-5626 : EWCS Facility
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
Labels: bug, documentation, ACBS

#920 DTFS2-Collation : Reduced strength
  portal-api/src/v1/users/controller.js
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
Labels: bug

#923 DTFS2-CSP : connect-src
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  gef-ui/server/middleware/headers/security.js
  portal-api/src/v1/middleware/headers/security.js
  portal/server/routes/middleware/headers/security.js
  reference-data-proxy/src/middleware/headers/security.ts
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/server/middleware/headers/security.js
Labels: bug

#915 DTFS2-5467 - Bug - Admin dashboard enable links
  dtfs-central-api/api-tests/v1/gef-deals/add-min-activities.api-test.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/portal/cypress/integration/journeys/admin/dashboard/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-name-link.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/dashboard/facilities/dashboard-table-data.spec.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/models/application.js
  gef-ui/templates/includes/application-details/applicationReferenceAndActions.njk
  gef-ui/templates/includes/application-details/automatic-cover.njk
  gef-ui/templates/includes/application-details/facilities.njk
  gef-ui/templates/includes/application-preview/facilities.njk
  gef-ui/templates/partials/application-activity.njk
  portal-api/api-tests/v1/gef/portal-activities.controller.api-test.js
  portal-api/src/v1/gef/routes.js
  portal-api/src/v1/portalActivity-object-generator/index.js
  portal-api/src/v1/routes.js
  portal/templates/contract/components/bond-transactions-table.njk
  portal/templates/contract/components/loan-transactions-table.njk
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
  utils/mock-data-loader/portal/users.js
Labels: bug

#926 DTFS2-User-Passwords : Password module
  e2e-tests/gef/cypress/integration/companies-house.spec.js
  e2e-tests/portal/cypress/integration/journeys/admin/activate-deactivate-user/activate-deactivate-user.spec.js
  e2e-tests/portal/cypress/integration/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/integration/journeys/admin/create-user/update-a-user.spec.js
  e2e-tests/portal/cypress/integration/journeys/login/change-password.spec.js
  e2e-tests/portal/cypress/integration/pages/admin/users/createUser.js
  e2e-tests/portal/cypress/integration/pages/admin/users/users.js
  e2e-tests/portal/cypress/integration/pages/user/changePassword.js
  e2e-tests/portal/cypress/integration/pages/user/profile.js
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/v1/loan/loan-validation.api-test.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/api-tests/v1/users/test-data.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/constants/email-template-ids.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/reset-password.controller.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/validation/index.js
  portal/server/routes/admin/users.js
  portal/server/routes/login.js
  portal/server/routes/user/profile.js
  portal/templates/admin/dashboard.njk
  portal/templates/admin/user-change-password.njk
  portal/templates/admin/user-edit.njk
  portal/templates/user/change-password.njk
  portal/templates/user/profile.njk
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
  trade-finance-manager-ui/templates/user/change-password.njk
  utils/data-migration/helpers/logs.js
  utils/data-migration/temporary-token-handler.js
  utils/data-migration/tfm/migrate-tfm-users.js
  utils/mock-data-loader/clean-all-tables-gef.js
  utils/mock-data-loader/clean-all-tables.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/portal/users.js
  utils/mock-data-loader/refresh-reference-data.js
  utils/mock-data-loader/tfm/clean-all-tables-tfm.js
  utils/mock-data-loader/tfm/insert-mocks-tfm.js
Labels: bug, documentation, tech debt

#940 DTF2 - TFM API
  .github/workflows/pipeline_trade_finance_manager-api.yml
Labels: bug

#932 DTFS2-5374 - BSS - formatting issues
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-criteria.spec.js
  e2e-tests/portal/cypress/integration/pages/eligibilityCriteria.js
  portal/templates/bond/_macros/bond-stage-unissued-form-fields.njk
  portal/templates/bond/bond-details.njk
  portal/templates/eligibility/eligibility-criteria.njk
  portal/templates/eligibility/eligibility-supporting-documentation.njk
  portal/templates/loan/loan-guarantee-details.njk
Labels: bug

#946 DTFS2-5671 : Reset password bugs
  e2e-tests/portal/cypress/integration/journeys/login/reset-password.spec.js
  e2e-tests/portal/cypress/integration/pages/resetPassword.js
  e2e-tests/portal/cypress/integration/pages/user/changePassword.js
  portal-api/src/v1/users/validation/index.js
  portal/server/routes/login.js
  portal/server/routes/user/profile.js
  portal/templates/admin/user-edit.njk
  portal/templates/reset-password.njk
  portal/templates/user/change-password.njk
Labels: bug

#947 DTFS2-5504 : GovUK Redirect
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/crypto/utils.js
  portal/server/routes/login.js
  portal/server/routes/middleware/validate-token.js
Labels: documentation, tech debt

#934 DTFS2-4072- GEF - Facility guidance
  e2e-tests/gef/cypress/integration/application-details.spec.js
  e2e-tests/gef/cypress/integration/pages/application-details.js
  e2e-tests/gef/cypress/integration/pages/application-preview.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  gef-ui/templates/_macros/facility-guidance.njk
  gef-ui/templates/includes/application-details/facilities.njk
  gef-ui/templates/includes/application-preview/facilities.njk
Labels: feature

#933 DTFS2-5613 - GEF Bug - fix GEF interest margin
  e2e-tests/gef/cypress/integration/facility-value.spec.js
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/controllers/facility-value/facility-value.js
  gef-ui/server/controllers/facility-value/facility-value.test.js
  gef-ui/server/controllers/facility-value/index.js
Labels: bug

#952 DTFS2 : Dash if empty
  gef-ui/server/nunjucks-configuration/filter-dashIfEmpty.js
  gef-ui/server/nunjucks-configuration/filter-dashIfEmpty.test.js
  portal/server/nunjucks-configuration/filter-dashIfEmpty.js
  portal/server/nunjucks-configuration/filter-dashIfEmpty.test.js
  trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.js
  trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.test.js
  trade-finance-manager-ui/templates/case/facility/_macros/premium_schedule.njk
Labels: bug

#950 DTFS2-5630 : Loan disbursement amount
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
Labels: tech debt, ACBS

#914 DTFS2-5616 - GEF - Unissued to Issued to Unissued journey
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-issued-to-unissued.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facility-change-from-preview-MIN.spec.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/models/application.js
  gef-ui/server/routes/__tests__/unissued-facilities.test.js
  gef-ui/server/routes/unissued-facilities.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/templates/includes/application-details/applicationReferenceAndActions.njk
  gef-ui/templates/includes/application-details/automatic-cover.njk
  gef-ui/templates/includes/application-details/facilities.njk
Labels: bug, feature

#967 feat: Added notification to bank's general inbox
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-second-submit-facilities-unissued-to-issued.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-submitted-non-gbp-contract-value.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-not-submitted.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-second-submit-facilities-unissued-to-issued.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-second-submit.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-submitted.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIN-second-submit-facilities-unissued-to-issued.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIN.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-acbs.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-facilities-USD-currency.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-issued-facilities.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-no-companies-house.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-no-party-db.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-no-ukef-id.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal.js
  trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
  trade-finance-manager-api/src/v1/__mocks__/mock-portal-users.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-bss.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js
Labels: feature

#968 DTFS2-5637 : Credentials
  .github/workflows/staging_deploy.yml
Labels: bug

#971 DTFS2-Trigger : E2E Environment
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/pr_integration_tests.yml
  portal/README.md
Labels: bug

#972 DTFS2-Feature : Removed `Burkina Faso` from the countries list
  portal-api/src/reference-data/__mocks__/countries.js
  portal/README.md
  reference-data-proxy/src/reference-data/countries.ts
Labels: feature

#970 Bug - Mock data loader fix
  e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js
  utils/mock-data-loader/gef/facilities.js
Labels: bug

#974 feat(DTFS2-4288): add amendment request date. add `amendment` endpoints in central-api
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-amendments-get.api-test.js
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-amendments-put.api-test.js
  dtfs-central-api/src/constants/amendments.constant.js
  dtfs-central-api/src/constants/index.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-post-amendments.controller.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-put-amendments.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-issued-to-unissued.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-amendment-request.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/show-amendment-button.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/amendments/amendmentsPage.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/amendments/amendmentsRequestPage.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/controllers/facility.controller.js
  trade-finance-manager-api/src/v1/helpers/hasValidObjectId.helper.js
  trade-finance-manager-api/src/v1/helpers/hasValidUri.helper.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/constants/amendments.js
  trade-finance-manager-ui/server/constants/index.js
  trade-finance-manager-ui/server/constants/teams.js
  trade-finance-manager-ui/server/controllers/case/amendments/index.js
  trade-finance-manager-ui/server/controllers/case/amendments/index.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/requestDateValidation.js
  trade-finance-manager-ui/server/controllers/case/amendments/requestDateValidation.test.js
  trade-finance-manager-ui/server/controllers/case/helpers.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/routes/case/index.js
  trade-finance-manager-ui/server/routes/case/index.test.js
  trade-finance-manager-ui/templates/case/amendments/amendment-request.njk
  trade-finance-manager-ui/templates/case/facility/_macros/amendments.njk
  trade-finance-manager-ui/templates/case/facility/facility.njk
Labels: peer, amendments

#956 feat: `PIM` user should have read-only access
  e2e-tests/trade-finance-manager/cypress/integration/journeys/users/PIM_user.spec.js
  trade-finance-manager-ui/templates/case/facility/_macros/amendments.njk
Labels: feature, amendments
