Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-12, with the labels that each got.

#1243 refactor(DTFS2-4678): Remove commented out code
  azure-functions/acbs-function/acbs/index.js
  azure-functions/number-generator-function/numbergenerator/index.js
  e2e-tests/gef/cypress/e2e/application-details-submit-to-checker.spec.js
  e2e-tests/gef/cypress/e2e/enter-exporters-corr-address.spec.js
  e2e-tests/gef/cypress/e2e/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/dashboard/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/dashboard/deals/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/e2e/journeys/reports/unissued-facilities-reports.spec.js
  e2e-tests/portal/cypress/e2e/pages/user/changePassword.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/amendment-tasks-manual.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/tasks/tasks.spec.js
  e2e-tests/trade-finance-manager/cypress/support/portal-api/createFacilities.js
  gef-ui/server/controllers/provided-facility/index.test.js
  gef-ui/server/controllers/supporting-information/supporting-documents/index.test.js
  gef-ui/server/healthcheck.js
  portal-api/api-tests/v1/deals/deal-clone.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted.api-test.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/gef/external-api.api-test.js
  portal-api/api-tests/v1/industry-sectors/industry-sectors.api-test.js
  portal-api/src/drivers/fileshare.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
  portal-api/src/v1/gef/routes.js
  portal-api/src/v1/gef/utils.service.js
  portal-api/src/v1/users/controller.js
  portal/component-tests/contract/contract-view.component-test.js
  portal/server/healthcheck.js
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/src/fileshare-test.js
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
  utils/data-migration/bss-ewcs/maps/map-deal-files.js
  utils/data-migration/gef/map-facilities.js
  utils/mock-data-loader/api.js
Labels: Type: Chore

#1242 feat(rad-reporting): RAD Reporting
  .gitignore
  utils/data-migration/constant/amendment.js
  utils/data-migration/constant/database.js
  utils/data-migration/constant/deal.js
  utils/data-migration/constant/facility.js
  utils/data-migration/constant/index.js
  utils/data-migration/constant/workflow.js
  utils/data-migration/helpers/database.js
  utils/data-migration/helpers/io.js
  utils/reporting/tfm/rad-reporting.js
Labels: Type: Fix

#1245 fix(e2e-tenor): Fixed tenor
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/8. amendment-details-manual-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/add-bank-decision-proceed.spec.js
Labels: Type: Fix, Test

#1250 feat(DTFS2-6224): Added Emirates NBD Bank
  portal/templates/_partials/before-you-start.njk
Labels: Type: Feature

#1253 fix(DTFS2-6235): Code quality improvement and Data sanitisation
  reference-data-proxy/src/v1/controllers/premium-schedule.controller.ts
  trade-finance-manager-api/src/utils/string.api-test.js
  trade-finance-manager-api/src/utils/string.js
  trade-finance-manager-api/src/v1/__mocks__/mock-facilities.js
  trade-finance-manager-api/src/v1/mappings/premium-schedule/index.api-test.js
  trade-finance-manager-api/src/v1/mappings/premium-schedule/index.js
Labels: Type: Bug, Type: Fix

#1254 feat(DTFS2-6236): Return tenor across products for all facilities
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenor.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenor.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenorDate.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenorDate.js
Labels: Type: Bug, Type: Docs, Type: Fix, Test

#1259 chore(deps-update): Bumped dependencies
  portal-api/package-lock.json
  portal-api/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
Labels: dependencies

#1261 feat(DTFS2-6237): TFM Non Delegated Banks amendment tasks
  trade-finance-manager-api/src/constants/index.js
  trade-finance-manager-api/src/constants/tasks-ndb-amendment.constant.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js
  trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.api-test.js
  trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.js
Labels: Type: Feature, Type: Amendments

#1263 chore(deps-update): Reference data proxy
  reference-data-proxy/Dockerfile
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
Labels: dependencies

#1264 fix(DTFS2-6239): Facility level default currency
  azure-functions/acbs-function/mappings/facility/facility-master.js
Labels: Type: Bug, Type: ACBS, Type: Fix

#1265 fix(DTFS2-6239): ACBS Facility mapping
  azure-functions/acbs-function/mappings/facility/facility-master.js
Labels: Type: Bug, Type: ACBS

#1272 feat(DTFS2-6213): NDB EC mapping
  trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapDealSnapshot.js
  trade-finance-manager-api/src/v1/mappings/map-deal.js
  trade-finance-manager-api/src/v1/mappings/map-eligibility-criteria-content-strings.js
Labels: Type: Feature
