Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-07, with the labels that each got.

#1061 fix: removed supporting docs and submission details from cloned deals
  e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js
  portal-api/.eslintrc.js
  portal-api/api-tests/v1/deals/deal-clone.api-test.js
  portal-api/package-lock.json
  portal-api/src/v1/controllers/deal-clone.controller.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
Labels: bug

#1070 chore: updated `nodemon` to v2.0.19 and `momentjs` to v2.29.4
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: tech debt, dependencies

#1085 feat(DTFS2-5910): Amendments UW Managers decision component
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/amendments/amendmentsPage.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/templates/case/amendments/_includes/amendment-ukef-decision-submitted-summary.njk
  trade-finance-manager-ui/templates/case/amendments/_macros/amendment-ukef-decision-summary.njk
  trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk
Labels: feature, amendments

#1086 fix(lint) : ACBS Azure DF
  azure-functions/acbs-function/__mocks__/durable-functions.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-http/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-facility-master/index.js
  azure-functions/acbs-function/activity-update-facility-master/index.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
Labels: tech debt, ACBS

#1087 fix(DTFS2-5930): Facility fixed fee income class code
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/helpers/get-income-class-code.js
Labels: bug, documentation, ACBS

#1088 fix(DTFS2-5912): Portal Bug fix - cover end date further validation
  e2e-tests/portal/cypress/integration/journeys/checker/cover-end-date/cover-end-date-validation.spec.js
  e2e-tests/portal/cypress/integration/journeys/checker/cover-end-date/deal.js
  portal-api/src/v1/validation/bond-issue-facility-rules/index.js
  portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/index.js
  portal-api/src/v1/validation/facility-change-cover-start-date-rules/index.js
  portal-api/src/v1/validation/fields/cover-dates.js
  portal-api/src/v1/validation/fields/cover-end-date.js
  portal-api/src/v1/validation/helpers/isReadyForValidation.helper.js
  portal-api/src/v1/validation/loan-issue-facility-rules/index.js
  portal-api/src/v1/validation/loan-rules/facility-stage-unconditional/index.js
Labels: bug

#1094 fix(Deployment) : Staging GitHub secret name update
  .github/workflows/staging_deploy.yml
Labels: bug, tech debt, dependencies

#1095 fix(ACBS) : Inclusion of payload and status in logs
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
Labels: tech debt, ACBS

#1096 chore: updated all NPM packages
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
Labels: dependencies

#1097 chore: updated Node.JS to `v18.6-apline3.16`
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: dependencies

#1099 feat(DTFS-5944): Add submissionType = Manual/Automatic to amendments
  trade-finance-manager-ui/server/constants/amendments.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentRequestApproval.controller.js
Labels: Type: Amendments

#1100 fix(DTFS2-gitignore) : Added json directory
  .gitignore
Labels: Type: Security
