Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-09, with the labels that each got.

#1152 fix: EC - Criterion existence check
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js
  trade-finance-manager-api/src/v1/mappings/map-eligibility-criteria-content-strings.js
Labels: Type: Bug, Type: Fix

#1134 chore(DTFS2-5946) : Data migration checks removed
  portal-api/src/v1/controllers/deal-status.controller.js
  trade-finance-manager-api/src/constants/email-template-ids.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-facilities-USD-currency.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/helpers/activity.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.api-test.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.js
Labels: Type: Chore

#1155 fix(EC): Added EC Criterions version 1
  trade-finance-manager-api/src/v1/content-strings/index.js
Labels: Type: Bug, Type: Fix

#1156 fix(DTFS2-5967): TFM facilities decimal places
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  trade-finance-manager-api/src/graphql/helpers/facilityValueFormatted.helper.api-test.js
  trade-finance-manager-api/src/graphql/helpers/facilityValueFormatted.helper.js
  trade-finance-manager-api/src/graphql/resolvers/query-facilities.js
Labels: Type: Bug

#1158 fix(DTFS2-6025): Group 2 task moved from `UW manager` to `UW`
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-manual.spec.js
  trade-finance-manager-api/src/constants/tasks-amendment.constant.js
Labels: Type: Bug, Type: Fix

#1159 fix(DTFS2-6024): BSS date validation
  e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/validation/cover-end-date.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js
  portal-api/src/v1/validation/fields/cover-end-date.js
  portal-api/src/v1/validation/fields/issue-facility/requested-cover-start-date.js
  portal-api/src/v1/validation/loan-rules/facility-stage-unconditional/requested-cover-start-date.js
Labels: Type: Bug

#1154 feat(DTFS2-5215): Portal deal exporter sorting
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js
  e2e-tests/portal/cypress/integration/pages/dashboardDeals.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js
  portal/server/constants/dashboard.js
  portal/server/constants/index.js
  portal/server/constants/sort.js
  portal/server/controllers/dashboard/deals/index.js
  portal/server/controllers/dashboard/deals/index.test.js
  portal/server/controllers/dashboard/sort/helpers.js
  portal/server/routes/dashboard.js
  portal/templates/dashboard/_macros/dashboard-deals-table.njk
  portal/templates/dashboard/deals.njk
Labels: Type: Feature

#1161 fix(DTFS2-6037): Amendment dates year
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/1. add-amendment-request.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/3. amendment-effective-date.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/6. cover-end-date.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-proceed.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-withdraw.spec.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendCoverEndDate.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendCoverEndDateDate.validate.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentBankDecisionDate.validate.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentBankDecisionDate.validate.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentEffectiveDate.validate.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentRequestDate.validate.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentRequestDateValidation.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentYearValidation.validate.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentYearValidation.validate.test.js
Labels: Type: Bug, Type: Amendments

#1160 feat(DTFS2-6022): Facility amendments updates TFM properties
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js
Labels: Type: Bug, Type: Amendments, Type: Fix

#1165 fix: GQL resolver exceptional handling and optional chaining
  trade-finance-manager-api/src/graphql/resolvers/query-deal.js
  trade-finance-manager-ui/server/api.js
Labels: Type: Bug, Type: Fix

#1167 chore: updated all npm packages to their latest version
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Chore, dependencies

#1166 chore: updated Nodejs to `v18.9-alpine3.16`
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: Type: Chore, dependencies

#1163 fix(DTFS2-6036): Cover End Date validation
  e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js
  e2e-tests/gef/cypress/integration/about-facility.spec.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-MIN.spec.js
  gef-ui/server/controllers/about-facility/index.js
  gef-ui/server/controllers/about-facility/index.test.js
  gef-ui/server/controllers/confirm-cover-start-date/index.js
  gef-ui/server/controllers/confirm-cover-start-date/index.test.js
  gef-ui/server/controllers/unissued-facilities/index.test.js
  gef-ui/server/controllers/unissued-facilities/validation.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
Labels: Type: Bug

#1170 fix(DTFS2-6035): TFM UI - Indemnifier address overlap
  trade-finance-manager-ui/templates/case/parties/_macros/parties-indemnifier-area.njk
Labels: Type: Bug, Type: Fix

#1169 fix(DTFS2-6047): GEF coverStartDate coverEndDate validation
  e2e-tests/gef/cypress/integration/about-facility.spec.js
  gef-ui/server/controllers/about-facility/index.js
  gef-ui/server/controllers/about-facility/index.test.js
Labels: Type: Bug

#1153 fix(DTFS2-6002): TFM all facilities graphql query fix
  trade-finance-manager-api/graphql-query-tests/query-facilities.api-test.js
  trade-finance-manager-api/src/graphql/resolvers/query-facilities.js
  trade-finance-manager-ui/templates/facilities/facilities.njk
Labels: Type: Bug

#1173 fix: Removed frivolous env files
  utils/mock-data-loader/.env.azure_dev
  utils/mock-data-loader/.env.azure_test
  utils/mock-data-loader/.env.local
Labels: Type: Fix, Type: Security

#1171 fix(DTFS2-6038): Dashboard sorting on other pages
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  portal/server/controllers/dashboard/deals/index.js
  portal/server/controllers/dashboard/deals/index.test.js
  portal/templates/dashboard/_macros/dashboard-deals-table.njk
Labels: Type: Bug

#1174 fix(DTFS2-ACBS): Mandatory field verfication + Updated Package lock
  azure-functions/acbs-function/helpers/mandatoryFields.js
  azure-functions/acbs-function/package-lock.json
Labels: Type: ACBS, Type: Fix

#1175 fix(DTFS2-6047): GEF validation issue facility
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js
  gef-ui/server/controllers/unissued-facilities/validation.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
  gef-ui/server/utils/coverDatesValidation.helper.js
  gef-ui/server/utils/coverDatesValidation.helper.test.js
Labels: Type: Bug

#1178 fix: ACBS Exposure period - Null cover start and end date
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
Labels: Type: ACBS, Type: Fix

#1176 fix(DTFS2-6036): shouldCoverStartOnSubmission validation
  e2e-tests/gef/cypress/fixtures/dateConstants.js
  e2e-tests/gef/cypress/integration/about-facility.spec.js
  gef-ui/server/controllers/about-facility/index.js
  gef-ui/server/controllers/about-facility/index.test.js
Labels: Type: Bug

#1177 fix(DTFS2-4614): Facility Amendment - Premium Schedule/Fixed Fee calculation disabled
  e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js
  e2e-tests/gef/cypress/integration/about-facility.spec.js
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
Labels: Type: Fix

#1179 fix(DTFS2-6046): BSS dates validation
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-financial-details.spec.js
  portal-api/api-tests/v1/validation/conversion-rate-date.api-test.js
  portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js
  portal-api/src/v1/validation/fields/currency-not-the-same-as-supply-contract-rules/conversion-rate-date.js
Labels: Type: Bug

#1180 fix(DTFS2-6055): BSS invalid date dashboard
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-guarantee-details.spec.js
  portal-api/api-tests/v1/bonds/bonds.api-test.js
  portal-api/api-tests/v1/facility-dates/cover-end-date.api-test.js
  portal-api/api-tests/v1/validation/conversion-rate-date.api-test.js
  portal-api/src/v1/controllers/bonds.controller.js
  portal-api/src/v1/controllers/loans.controller.js
  portal-api/src/v1/facility-dates/cover-end-date.js
  portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js
  portal-api/src/v1/validation/fields/cover-end-date.js
  portal-api/src/v1/validation/loan-rules/facility-stage-unconditional/requested-cover-start-date.js
  portal/templates/contract/components/bond-transactions-table.njk
  portal/templates/contract/components/loan-transactions-table.njk
Labels: Type: Bug

#1181 fix(DTFS2-6056): All facilities - fix dealId conversion to string
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/facilitiesPage.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/facilityPage.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.api-test.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.js
Labels: Type: Bug

#1182 fix(DTFS2-6065): Null ukefFacilityId fix
  trade-finance-manager-api/graphql-query-tests/query-facilities.api-test.js
  trade-finance-manager-api/src/graphql/resolvers/query-facilities.js
Labels: Type: Bug

#1183 fix(DTFS2-6056): show all MIN facilities - change to _id
  dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js
Labels: Type: Bug
