Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-03, with the labels that each got.

#744 DTFS2-5425 : Exporter meta data correction
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/constants/deal.js
  azure-functions/acbs-function/mappings/party/exporter.js
  azure-functions/acbs-function/mappings/party/helpers/get-sme-type.js
Labels: bug

#746 DTFS2-ACBS-Bugs : Activity bug
  trade-finance-manager-api/src/constants/facilities.js
  trade-finance-manager-api/src/v1/__mocks__/mock-TFM-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/tfm.controller.js
  trade-finance-manager-api/src/v1/helpers/activity.js
Labels: bug

#745 DTFS2-5412 TFM beta banner and logo
  e2e-tests/trade-finance-manager/cypress/integration/journeys/login/login.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/partials/header.js
  e2e-tests/trade-finance-manager/cypress/integration/partials/primaryNavigation.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/images/UK-Export-Finance-logo.png
  trade-finance-manager-ui/public/images/UK-Export-Finance-logo.svg
  trade-finance-manager-ui/public/js/govukFrontend.js
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/public/js/mojFrontend.js
  trade-finance-manager-ui/public/js/mojFrontend.js.map
  trade-finance-manager-ui/styles/header.scss
  trade-finance-manager-ui/styles/styles.scss
  trade-finance-manager-ui/templates/_macros/header.njk
  trade-finance-manager-ui/templates/_partials/beta-banner.njk
  trade-finance-manager-ui/templates/_partials/primary-navigation.njk
  trade-finance-manager-ui/templates/index.njk
Labels: bug, feature

#748 DTFS2-5428 : Password reset verification
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/src/v1/users/routes.js
  portal/server/api.js
  portal/server/routes/login.js
Labels: bug

#755 DTFS2-5431 : Production deployment infrastrcuture
  .github/workflows/Azure.md
  .github/workflows/README.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/container-prune.txt
  .github/workflows/delete-dev-subnets.sh
  .github/workflows/deploy.sh
  .github/workflows/dns.yml
  .github/workflows/env_demo.yml
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
  .github/workflows/env_test.yml
  .github/workflows/infrastructure.yml
  .github/workflows/promote_to_dev.yml
  .github/workflows/promote_to_prod.yml
  .github/workflows/promote_to_staging.yml
  .github/workflows/promote_to_test.yml
  .github/workflows/update-demo.sh
  .github/workflows/update-environment.sh
  .github/workflows/update-infrastructure.sh
  .github/workflows/update-prod.sh
  .github/workflows/update-staging.sh
  .github/workflows/update-test.sh
Labels: documentation, tech debt, dependencies, draft

#752 DTFS2- 5444 - ACCESSIBILITY - non descriptive links
  e2e-tests/portal/cypress/integration/journeys/maker/abandon-a-deal.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/delete-a-bond.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/clone-deal/clone-deal.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/edit-deal-name.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/delete-a-loan.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-guarantee-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/loan.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/deal-page-GEF.spec.js
  portal/component-tests/contract/components/edit-deal-name-link.component-test.js
  portal/component-tests/contract/components/issue-or-delete-facility-link.component-test.js
  portal/templates/contract/components/abandon-deal-link.njk
  portal/templates/contract/components/bond-link.njk
  portal/templates/contract/components/clone-deal-link.njk
  portal/templates/contract/components/edit-deal-name-link.njk
  portal/templates/contract/components/issue-or-delete-facility-link.njk
  portal/templates/contract/components/loan-link.njk
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityDates.api-test.js
Labels: Accessibility

#774 DTFS2-Infra : Updated README + Files removed
  .github/workflows/README.md
  .github/workflows/delete-dev-subnets.sh
  .github/workflows/delete-test-subnets.sh
Labels: documentation

#776 fix BSS deal creation error with mandatory criteria API response
  portal/server/api.js
Labels: bug

#751 DTFS2-3410 : Facility issue
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/constants/product.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-capital-conversion-factor-code.js
  azure-functions/acbs-function/mappings/facility/helpers/get-cover-start-date.js
  azure-functions/acbs-function/mappings/facility/helpers/get-description.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
  azure-functions/acbs-function/mappings/facility/helpers/get-interest-or-fee-rate.js
  azure-functions/acbs-function/mappings/facility/helpers/get-interest-percentage.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-due-date.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-group.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
  azure-functions/acbs-function/mappings/facility/helpers/get-year-basis.js
  azure-functions/acbs-function/mappings/facility/helpers/index.js
  reference-data-proxy/src/v1/controllers/exposure-period.controller.ts
  reference-data-proxy/src/v1/controllers/premium-schedule.controller.ts
  service-unavailable/README.md
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/number-generator.controller.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js
Labels: bug, documentation

#769 DTFS2-5445 - Accessibility - BSS - Optional supporting documentation fields
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-documentation.spec.js
  e2e-tests/portal/cypress/integration/pages/eligibilityDocumentation.js
  portal/templates/eligibility/eligibility-supporting-documentation.njk
Labels: Accessibility

#777 fix BSS Mandatory Criteria not displaying on before-you-start page
  e2e-tests/portal/cypress/integration/journeys/maker/before-you-start.spec.js
  e2e-tests/portal/cypress/integration/pages/beforeYouStart.js
  portal/server/routes/start.js
  portal/templates/before-you-start/before-you-start.njk
Labels: bug

#778 DTFS2-5447- BSS Accessibility - eligibility criteria aria label
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-criteria.spec.js
  portal/templates/eligibility/eligibility-criteria.njk
Labels: Accessibility

#785 DTFS2-5498 : ACBS Facility type code
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
Labels: bug, documentation

#783 DTFS2-5501 : Global SEO headers
  app-service-tail.txt
  dtfs-central-api/src/createApp.js
  gef-ui/public/humans.txt
  gef-ui/public/robots.txt
  gef-ui/server/azure-hack.txt
  gef-ui/server/index.js
  portal-api/src/createApp.js
  portal/public/humans.txt
  portal/public/robots.txt
  portal/server/azure-hack.txt
  portal/server/index.js
  reference-data-proxy/src/createApp.ts
  reverse-proxy/default.conf.template
  service-unavailable/index.html
  service-unavailable/robots.txt
  trade-finance-manager-api/src/createApp.js
  trade-finance-manager-ui/server/index.js
  trade-finance-manager-ui/static/humans.txt
  trade-finance-manager-ui/static/robots.txt
Labels: documentation, feature

#784 DTFS2-5513 - GEF Accessibility & Bug - fix error skip link and undefined bug
  e2e-tests/gef/cypress/integration/facilities.spec.js
  gef-ui/server/controllers/facilities/index.js
  gef-ui/server/controllers/facilities/index.test.js
  gef-ui/server/controllers/provided-facility/index.js
  gef-ui/server/controllers/provided-facility/index.test.js
Labels: bug, Accessibility

#786 DTFS2 - E2E execution test
  gef-ui/README.md
  portal/README.md
  reverse-proxy/default.conf.template
Labels: draft

#790 DTFS2-5513 - GEF Bug - fix failure to create facility
  gef-ui/server/controllers/facilities/index.js
  gef-ui/server/controllers/facilities/index.test.js
  gef-ui/server/services/api.js
Labels: bug

#791 DTFS2-5520 : Facility fee record
  azure-functions/acbs-function/mappings/facility/facility-fee.js
Labels: bug

#788 DTFS2-4703 : Currency properties
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-currency-exchange-rate.js
  trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-api/src/v1/controllers/convert-facility-currency.js
  trade-finance-manager-ui/server/graphql/queries/deal-query.js
  trade-finance-manager-ui/server/graphql/queries/facility-query.js
Labels: feature, tech debt

#794 Facility loan exchange rate
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-currency-exchange-rate.js
Labels: bug

#789 DTFS2-5521 - portal BSS/EWCS - update facilityStage when manually issuing facility
  README.md
  portal-api/api-tests/v1/bonds/bond-issue-facility.api-test.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility.api-test.js
  portal-api/src/v1/controllers/bond-issue-facility.controller.js
  portal-api/src/v1/controllers/bonds.controller.js
  portal-api/src/v1/controllers/deal-status/update-issued-facilities.js
  portal-api/src/v1/controllers/deal-status/update-submitted-issued-facilities.js
  portal-api/src/v1/controllers/loan-issue-facility.controller.js
  portal-api/src/v1/controllers/loans.controller.js
  portal/component-tests/contract/components/contract-actions/proceed-to-review-button.component-test.js
  portal/server/routes/contract/canIssueOrEditIssueFacility.js
  portal/server/routes/contract/canIssueOrEditIssueFacility.test.js
  portal/templates/contract/components/contract-actions/proceed-to-review-button.njk
  trade-finance-manager-api/api-tests/send-tfm-email.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
Labels: feature

#796 DTFS2-5531 : Collections and indices
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
Labels: tech debt

#797 DTFS2-5528 : ACBS Facility issue
  azure-functions/acbs-function/acbs-issue-facility/index.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: bug, documentation

#798 DTFS2-5448 - Accessibility Portal - Dashboard filters aria
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-filter-by-multiple-fields-multiple-values.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-filters.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-multiple-fields-multiple-values.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filters.spec.js
  portal/server/controllers/dashboard/deals/index.js
  portal/server/controllers/dashboard/deals/index.test.js
  portal/server/controllers/dashboard/facilities/index.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/controllers/dashboard/filters/helpers.js
  portal/server/controllers/dashboard/filters/helpers.test.js
  portal/templates/_macros/dashboard-sub-nav.njk
  portal/templates/dashboard/_macros/dashboard-heading-and-tabs.njk
  portal/templates/dashboard/_macros/dashboard-page-content.njk
  portal/templates/dashboard/deals.njk
  portal/templates/dashboard/facilities.njk
Labels: Accessibility

#806 DTFS2-Collection : Typo fix
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
Labels: bug

#807 DTFS2-5546 : BSS/EWCS Compatibility
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-type.js
  azure-functions/acbs-function/mappings/facility/helpers/get-year-basis.js
Labels: bug

#804 DTFS2-5513 - GEF Bug/Accessibility - Error in govukCheckbox component
  e2e-tests/gef/cypress/integration/provided-facility.spec.js
  gef-ui/templates/partials/provided-facility.njk
Labels: bug, Accessibility

#812 DTFS2-DNS
  .github/workflows/dns.yml
Labels: tech debt

#814 DTFS2-2220 - Accessibility BSS - page titles
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/about-supply-contract-page-titles.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-fee-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-financial-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-dates-repayments.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-financial-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-guarantee-details.spec.js
  e2e-tests/portal/cypress/integration/pages/bondDetails.js
  e2e-tests/portal/cypress/integration/pages/bondFeeDetails.js
  e2e-tests/portal/cypress/integration/pages/bondFinancialDetails.js
  e2e-tests/portal/cypress/integration/pages/contract/about/about-buyer.js
  e2e-tests/portal/cypress/integration/pages/contract/about/about-financial.js
  e2e-tests/portal/cypress/integration/pages/contract/about/about-supplier.js
  e2e-tests/portal/cypress/integration/pages/loanDatesRepayments.js
  e2e-tests/portal/cypress/integration/pages/loanFinancialDetails.js
  e2e-tests/portal/cypress/integration/pages/loanGuaranteeDetails.js
  portal/templates/bond/bond-fee-details.njk
  portal/templates/bond/bond-financial-details.njk
  portal/templates/contract/about/about-supply-buyer.njk
  portal/templates/contract/about/about-supply-financial.njk
  portal/templates/loan/loan-dates-repayments.njk
  portal/templates/loan/loan-financial-details.njk
Labels: Accessibility

#816 DTFS2-5466- Portal GEF Bug - Issue date appearing on cloned deal
  e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
Labels: bug

#817 DTFS2-5465- Portal Bug - Name link not present if no name
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-name-link.spec.js
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
Labels: bug

#811 GEF facilities - save details as value instead of uppercase constant
  dtfs-central-api/src/v1/swagger-definitions/portal/facility-gef.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js
  e2e-tests/trade-finance-manager/cypress/fixtures/mock-gef-facilities.js
  gef-ui/server/controllers/provided-facility/index.js
  gef-ui/server/controllers/provided-facility/index.test.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/templates/partials/provided-facility.njk
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/src/v1/gef/controllers/validation/facilities.js
  portal-api/src/v1/gef/enums.js
  trade-finance-manager-api/src/constants/facilities.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.js
Labels: tech debt

#819 DTFS2-ACBS : Bug fixes + Updated logics
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/mappings/deal/deal-guarantee.js
  azure-functions/acbs-function/mappings/deal/deal-investor.js
  azure-functions/acbs-function/mappings/deal/deal.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-currency.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-value.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-value.js
  azure-functions/acbs-function/mappings/deal/helpers/index.js
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/helpers/get-base-currency.js
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-value.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency-months.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-type.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-due-date.js
  azure-functions/acbs-function/mappings/facility/helpers/index.js
  azure-functions/acbs-function/mappings/facility/helpers/map-fee-frequency.js
  azure-functions/acbs-function/mappings/facility/helpers/map-fee-type.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.api-test.js
Labels: bug, documentation, feature

#826 DTFS2 : GitHub Actions
  .github/workflows/Environments/Development/Infrastructure.yml
  .github/workflows/Environments/Production/Deploy.yml
  .github/workflows/Environments/Production/Infrastructure.yml
  .github/workflows/Environments/Staging/Deploy.yml
  .github/workflows/Environments/Staging/Infrastructure.yml
  .github/workflows/Infrastructure/DNS.yml
  .github/workflows/Infrastructure/IaC.yml
  .github/workflows/PR/acbs.yml
  .github/workflows/PR/dts-central-api.yml
  .github/workflows/PR/gef-ui.yml
  .github/workflows/PR/no-tests.yml
  .github/workflows/PR/number-generator.yml
  .github/workflows/PR/portal-api.yml
  .github/workflows/PR/portal-ui.yml
  .github/workflows/PR/reference-data-proxy.yml
  .github/workflows/PR/trade-finance-manager-api.yml
  .github/workflows/PR/trade-finance-manager-ui.yml
  .github/workflows/Pipeline/ACBS.yml
  .github/workflows/Pipeline/acbs.yml
  .github/workflows/Pipeline/dts-central-api.yml
  .github/workflows/Pipeline/gef-ui.yml
  .github/workflows/Pipeline/number-generator.yml
  .github/workflows/Pipeline/portal-api.yml
  .github/workflows/Pipeline/portal-ui.yml
  .github/workflows/Pipeline/reference-data-proxy.yml
  .github/workflows/Pipeline/trade-finance-manager-ui.yml
  .github/workflows/Pipeline/trade_finance_manager-api.yml
  .github/workflows/QA/codeql-analysis.yml
  .github/workflows/README.md
  .github/workflows/promote_to_dev.yml
Labels: documentation, tech debt, dependencies

#829 DTFS2-5453 - add facility coverEndDate to TFM - GEF confirmation email
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js
Labels: bug

#832 DTFS2 GHA : Documentation update
  .github/workflows/README.md
  .github/workflows/infrastructure.yml
  .github/workflows/promote_to_dev.yml
Labels: documentation

#839 DTFS2-ACBS : Bugs
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-value.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: bug

#833 DTFS2 : GitHub
  .github/workflows/README.md
  .github/workflows/deploy.sh
  .github/workflows/infrastructure.yml
Labels: tech debt

#846 DTFS2 : Updated the YML files to trigger all E2E and API tests
  .github/workflows/pr_dts-central-api.yml
  .github/workflows/pr_gef-ui.yml
  .github/workflows/pr_portal-api.yml
  .github/workflows/pr_portal-ui.yml
  .github/workflows/pr_reference_data_proxy.yml
  .github/workflows/pr_trade-finance-manager-ui.yml
  .github/workflows/pr_trade_finance_manager-api.yml
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: bug, tech debt, 1

#827 DTFS2-5525 - add new TFM task - Check adverse history check, fix BSS EC issue
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIA-deal-creates-task-in-tfm/submit-MIA-deal-creates-task-in-tfm.spec.js
  e2e-tests/trade-finance-manager/cypress.json
  e2e-tests/trade-finance-manager/cypress/fixtures/tasks-MIA.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA-EC-11-false.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/tasksPage.js
  trade-finance-manager-api/src/constants/tasks.js
  trade-finance-manager-api/src/v1/__mocks__/mock-MIA-tasks-populated.js
  trade-finance-manager-api/src/v1/__mocks__/mock-MIA-tasks.js
  trade-finance-manager-api/src/v1/controllers/task-emails.api-test.js
  trade-finance-manager-api/src/v1/controllers/task-emails.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.component-test.js
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk
Labels: bug, feature, 4

#841 Fix/DTFS2-5452 - GEF facilities - limit decimals in guaranteeFee calculation
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/src/v1/gef/calculations/facility-calculations.js
Labels: bug, 6

#842 DTFS2-5572- GEF Accessibility - accessibility for clone, abandon and delete facility
  e2e-tests/gef/cypress/integration/application-details.spec.js
  e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js
  e2e-tests/gef/cypress/integration/facility-confirm-deletion.spec.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/templates/includes/application-details/applicationReferenceAndActions.njk
  gef-ui/templates/includes/application-details/facilities.njk
Labels: 7, Accessibility

#843 Build: Update all packages to their latest version
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: 8

#845 DTFS2-Activity : Property verification
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/helpers/activity.js
Labels: bug, 9

#847 DTFS2-5576 : Facility records bugs
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-premium-frequency-code.js
Labels: bug, documentation

#850 DTFS2-5456 : TFM-API Crash bug
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: bug

#840 DTFS2-5508 : Security document
  portal/server/security.txt
  portal/server/thanks.txt
Labels: tech debt, draft, 10

#849 fix/DTFS2-5056 - TFM tasks - add emailSent flag to a task when an email has been sent
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/add-first-task-email-sent-flag.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/add-first-task-email-sent-flag.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-tfm-tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
  trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.js
Labels: bug

#815 DNS
  .github/workflows/dns.yml
Labels: tech debt

#855 fix/DTFS2-5411 - TFM - prevent Underwriting tasks from sending multiple emails
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
  trade-finance-manager-api/src/v1/helpers/tasks.js
  trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.js
Labels: bug

#857 DTFS2 2958 - Security headers
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/createApp.js
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/index.js
  gef-ui/server/middleware/headers/security.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/createApp.js
  portal-api/src/v1/middleware/headers/security.js
  portal/package-lock.json
  portal/package.json
  portal/server/index.js
  portal/server/routes/middleware/headers/security.js
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/createApp.ts
  reference-data-proxy/src/middleware/headers/security.ts
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/createApp.js
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/index.js
  trade-finance-manager-ui/server/middleware/headers/security.js
Labels: documentation, tech debt, dependencies

#859 DTFS2-DNS
  .github/workflows/dns.yml
Labels: tech debt

#858 eStore: Added 3 re-tries for deal folder creation
  reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  reference-data-proxy/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts
  reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  reference-data-proxy/src/v1/controllers/estore/eStoreApi.ts
Labels: bug

#854 DTFS2-5579 - Accessiblity GEF and portal- empty headings
  e2e-tests/gef/cypress/integration/pages/application-submission.js
  e2e-tests/gef/cypress/integration/pages/submit-to-ukef-confirmation.js
  e2e-tests/gef/cypress/integration/submit-to-checker-mia.spec.js
  e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js
  gef-ui/templates/application-details-submitted.njk
  gef-ui/templates/partials/submit-to-ukef-confirmation.njk
  portal/templates/dashboard/_macros/dashboard-heading-and-tabs.njk
Labels: Accessibility

#866 DTFS2-2962 : Cookies + CSP
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  gef-ui/server/index.js
  gef-ui/server/middleware/headers/security.js
  portal-api/src/v1/middleware/headers/security.js
  portal/server/index.js
  portal/server/routes/middleware/headers/security.js
  reference-data-proxy/src/middleware/headers/security.ts
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/server/index.js
  trade-finance-manager-ui/server/middleware/headers/security.js
  trade-finance-manager-ui/server/session-configuration/index.js
Labels: bug

#864 DTFS2-Env : Cosmo DB
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
Labels: tech debt

#867 DTFS2-5586 - 5587 - TFM accessibility
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/activities/activities.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/parties/parties.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/assign-lead-underwriter.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/pricing-and-risk.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/underwriter-managers-decision.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/activities/activitiesPage.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/partiesPage.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/tasksPage.js
  e2e-tests/trade-finance-manager/cypress/integration/partials/underwritingSubNav.js
  trade-finance-manager-ui/templates/case/activity/activity-comment.njk
  trade-finance-manager-ui/templates/case/activity/activity.njk
  trade-finance-manager-ui/templates/case/deal/deal.njk
  trade-finance-manager-ui/templates/case/documents/documents.njk
  trade-finance-manager-ui/templates/case/parties/parties.njk
  trade-finance-manager-ui/templates/case/tasks/tasks.njk
  trade-finance-manager-ui/templates/case/underwriting/layout.njk
  trade-finance-manager-ui/templates/deals/deals.njk
  trade-finance-manager-ui/templates/facilities/facilities.njk
Labels: Accessibility

#868 DTFS2- 5600 - GEF Bug - word missing from submit ukef
  e2e-tests/gef/cypress/integration/submit-to-ukef-mia.spec.js
  e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js
  gef-ui/templates/partials/submit-to-ukef.njk
Labels: bug

#877 DTFS2-5452 - DTFS2-5387 - fix TFM GEF confirmation email not sending
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.js
Labels: bug

#879 DTFS2-5508 - Security.txt
  portal/server/routes/index.js
  portal/server/routes/static.js
  portal/server/security.txt
  portal/server/thanks.txt
Labels: bug

#873 DTFS2-5557 - GEF Bug - facility journey
  e2e-tests/gef/cypress/integration/facilities-change-from-details-journey.spec.js
  gef-ui/server/controllers/about-facility/index.js
  gef-ui/server/controllers/facilities/index.js
  gef-ui/server/controllers/facilities/index.test.js
  gef-ui/server/controllers/provided-facility/index.js
  gef-ui/server/controllers/provided-facility/index.test.js
Labels: bug

#891 DTFS2-5608 : Bond beneficiary & Exporter credit rating
  azure-functions/acbs-function/constants/deal.js
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-credit-rating-code.js
  azure-functions/acbs-function/mappings/facility/helpers/index.js
  trade-finance-manager-ui/server/controllers/case/index.js
Labels: bug, documentation, feature, dependencies

#890 DTFS2-2958 : X-Content-Type-Options
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  gef-ui/server/middleware/headers/security.js
  portal-api/src/v1/middleware/headers/security.js
  portal/server/routes/middleware/headers/security.js
  reference-data-proxy/src/middleware/headers/security.ts
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/server/middleware/headers/security.js
Labels: bug

#893 DTFS2 - Infrastructure
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
Labels: bug

#895 DTFS2-Cookie : Secure
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
  gef-ui/server/index.js
  portal/server/index.js
  trade-finance-manager-ui/server/index.js
  trade-finance-manager-ui/server/session-configuration/index.js
Labels: bug

#905 DTFS2-5608 : Facility value
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-value.js
Labels: bug, documentation
