Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-05, with the labels that each got.

#975 fix: update the security.txt file
  portal/server/routes/static.js
Labels: tech debt

#965 DTFS2-PR-Test : Added main-amendment
  .github/workflows/pr_integration_tests.yml
Labels: tech debt

#976 DTFS2-5710 : Cover start date validation
  e2e-tests/gef/cypress/integration/unissued-facility-to-issued-cover-start-date.spec.js
  gef-ui/server/controllers/unissued-facilities/index.test.js
  gef-ui/server/controllers/unissued-facilities/validation.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
Labels: bug, documentation

#980 DTFS2-5759 : Migrated deal notification
  gef-ui/server/controllers/mocks/index.js
  trade-finance-manager-api/src/constants/email-template-ids.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
Labels: tech debt

#978 fix: formatted the eStore file name and exporter name
  e2e-tests/gef/cypress/integration/application-activities-MIA.spec.js
  e2e-tests/gef/cypress/integration/return-to-maker-mia.spec.js
  e2e-tests/gef/cypress/integration/scenarios/eligibility-criterion-16/eligibility-criterion-16.spec.js
  e2e-tests/gef/cypress/integration/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-add-document.spec.js
  e2e-tests/gef/cypress/integration/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-delete-document.spec.js
  e2e-tests/gef/cypress/integration/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-security-questions.spec.js
  e2e-tests/gef/cypress/integration/submit-to-ukef-mia.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-documentation.spec.js
  portal-api/api-tests/v1/deals/deal-eligibility-documentation.api-test.js
  portal-api/src/utils/formatFilenameForSharepoint.js
  reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
  trade-finance-manager-api/src/v1/helpers/formatNameForSharepoint.js
Labels: bug

#981 DTFS2-5759 : ABCS interaction
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Labels: bug

#982 DTFS2-5759 : Migrated deal
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Labels: tech debt

#983 DTFS2-5783 - TFM- MIN stage confirmed
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIN-changes-tfm-stage-to-confirmed/submit-MIN-changes-tfm-stage-to-confirmed.spec.js
  e2e-tests/trade-finance-manager/cypress/fixtures/constants.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/src/constants/deals.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dealStage.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Labels: feature

#903 docs: TFM Tasks documentation, update main README
  README.md
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIA-deal-creates-tasks-in-tfm/submit-MIA-deal-creates-tasks-in-tfm.spec.js
  trade-finance-manager-api/README.md
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-api/src/v1/controllers/deal.tasks.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
  trade-finance-manager-api/src/v1/helpers/create-tasks.js
  trade-finance-manager-api/src/v1/helpers/tasks.js
  trade-finance-manager-api/src/v1/tasks/assign-group-tasks-to-one-user.js
  trade-finance-manager-api/src/v1/tasks/generate-task-dates.js
  trade-finance-manager-api/src/v1/tasks/map-task-history-object.api-test.js
  trade-finance-manager-api/src/v1/tasks/map-task-history-object.js
  trade-finance-manager-api/src/v1/tasks/map-task-object.js
  trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.js
  trade-finance-manager-api/tasks.md
  trade-finance-manager-ui/README.md
Labels: documentation

#910 fix: fixes for data migration
  portal-api/src/v1/controllers/data-migration/migrate-azure-files-gef.controller.js
  utils/data-migration/bss-ewcs/maps/map-eligibility.js
  utils/data-migration/bss-ewcs/maps/map-mandatory-criteria.js
  utils/data-migration/gef/map-deal.js
  utils/data-migration/gef/map-facilities.js
  utils/data-migration/gef/mapping-errors.js
  utils/mock-data-loader/gef/eligibilityCriteria.js
  utils/mock-data-loader/gef/mandatoryCriteriaVersioned.js
Labels: tech debt

#985 fix: prevent test deals from reaching eStore. + updated the notifications email
  reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
  reference-data-proxy/src/v1/controllers/estore/eStoreApi.ts
Labels: bug

#987 fix: fixed the searching functionality in TFM and Portal. Fixed the sorting of deals in Portal
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals.controller.js
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/controllers/facilities.controller.js
  portal/server/constants/field-names.js
  portal/server/controllers/dashboard/deals/deals-filters-keyword-query.js
  portal/server/controllers/dashboard/deals/deals-filters-keyword-query.test.js
Labels: bug

#988 fix: used `facilityValueExportCurrency` to determine the current value for a facility
  trade-finance-manager-ui/server/controllers/case/amendments/amendFacilityValue.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/requestDateValidation.js
  trade-finance-manager-ui/server/controllers/case/amendments/requestDateValidation.test.js
Labels: amendments

#991 fix: updated the amendment currency to match the facility currency
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/MIA-underwriter-managers-approved-decision-updates-portal-deal-and-submission-type-to-MIN/MIA-underwriter-managers-approved-decision-updates-portal-deal-and-submission-type-to-MIN.spec.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-with-conditions-updates-portal-deal.spec.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-without-conditions-updates-portal-deal.spec.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendFacilityValue.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentAnswers.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentRequestDate.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendFacilityValue.validate.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/templates/case/amendments/amendment-facility-value.njk
  trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk
Labels: amendments

#994 ACBS Bugs : Typo + Typecasting
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
Labels: bug, ACBS

#986 chore: updated nodejs to v.18.2-alpine3.14. & updated all npm packages
  .github/workflows/pr_api_tests.yml
  azure-functions/acbs-function/.dockerignore
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/.dockerignore
  azure-functions/number-generator-function/Dockerfile
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/.dockerignore
  dtfs-central-api/Dockerfile
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  gef-ui/.dockerignore
  gef-ui/Dockerfile
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/.dockerignore
  portal-api/Dockerfile
  portal-api/package-lock.json
  portal-api/package.json
  portal/.dockerignore
  portal/Dockerfile
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/.dockerignore
  reference-data-proxy/Dockerfile
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  trade-finance-manager-api/.dockerignore
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/.dockerignore
  trade-finance-manager-ui/Dockerfile
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: tech debt

#996 DTFS2-5498 : Facility product code
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
Labels: bug, ACBS
