Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-02, with the labels that each got.

#650 DTFS2-5301 : SSH Access
  .github/workflows/dns.yml
  .github/workflows/env_demo.yml
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
  .github/workflows/env_test.yml
  .github/workflows/infrastructure.yml
  .github/workflows/pipeline_azure_function_acbs.yml
  .github/workflows/pipeline_azure_function_number_generator.yml
  .github/workflows/pipeline_dts-central-api.yml
  .github/workflows/pipeline_gef-ui.yml
  .github/workflows/pipeline_portal-api.yml
  .github/workflows/pipeline_portal-ui.yml
  .github/workflows/pipeline_reference-data-proxy.yml
  .github/workflows/pipeline_trade-finance-manager-ui.yml
  .github/workflows/pipeline_trade_finance_manager-api.yml
  .github/workflows/promote_to_demo.yml
  .github/workflows/promote_to_prod.yml
  .github/workflows/promote_to_staging.yml
  .github/workflows/promote_to_test.yml
  azure-functions/acbs-function/Dockerfile
  azure-functions/number-generator-function/Dockerfile
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  reverse-proxy/Dockerfile
  reverse-proxy/sshd_config
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: bug

#634 Added self-hosted runner
  .github/workflows/pr_dts-central-api.yml
  docker-compose.gha.yml
  dtfs-central-api/README.md
Labels: tech debt

#642 DTFS2-4054 : ACBS Interaction activities
  azure-functions/acbs-function/api-dtfs-cental-api.js
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/constants/index.js
  azure-functions/acbs-function/helpers/activity.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  portal-api/src/v1/gef/controllers/externalApi.controller.js
  trade-finance-manager-api/src/constants/activity.js
  trade-finance-manager-api/src/constants/index.js
  trade-finance-manager-api/src/v1/__mocks__/mock-TFM-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/tfm.controller.js
  trade-finance-manager-api/src/v1/helpers/activity.api-test.js
  trade-finance-manager-api/src/v1/helpers/activity.js
Labels: bug, dependencies, draft

#658 DTFS2-5301 : GHA version update
  .github/workflows/pipeline_azure_function_acbs.yml
  .github/workflows/pipeline_azure_function_number_generator.yml
  .github/workflows/pipeline_dts-central-api.yml
  .github/workflows/pipeline_gef-ui.yml
  .github/workflows/pipeline_portal-api.yml
  .github/workflows/pipeline_portal-ui.yml
  .github/workflows/pipeline_reference-data-proxy.yml
  .github/workflows/pipeline_trade-finance-manager-ui.yml
  .github/workflows/pipeline_trade_finance_manager-api.yml
  .github/workflows/pr_azure_function_acbs.yml
  .github/workflows/pr_azure_function_number_generator.yml
  .github/workflows/pr_dts-central-api.yml
  .github/workflows/pr_gef-ui.yml
  .github/workflows/pr_portal-api.yml
  .github/workflows/pr_portal-ui.yml
  .github/workflows/pr_reference_data_proxy.yml
  .github/workflows/pr_trade-finance-manager-ui.yml
  .github/workflows/pr_trade_finance_manager-api.yml
Labels: dependencies

#645 DTFS2 - Anonymisation of PII
  azure-functions/acbs-function/mappings/deal/deal.js
  dtfs-central-api/src/v1/swagger-definitions/portal/deal-bss.js
  e2e-tests/portal/cypress/integration/journeys/checker/submit-a-deal/test-data/template.json
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/dealWithFirstPageComplete.json
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/dealWithSecondPageComplete.json
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/fill-in-about-supply-contract-unhappy-path.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/fixtures/dealFullyCompleted.js
  e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealThatJustNeedsConversionDate.json
  e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealWithIncompleteEligibility.json
  e2e-tests/portal/cypress/integration/journeys/number-generator/test-data/template.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/test-data/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-non-gbp-facilities/test-data/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/AIN-deal/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIA-deal/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal-unissued-facilities/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal/dealThatJustNeedsDates.json
  portal-api/api-tests/fixtures/deal-fully-completed.js
  portal-api/api-tests/fixtures/deal-with-complete-about-section.json
  portal/component-tests/fixtures/deal-fully-completed.js
  reference-data-proxy/src/utils/swagger-definitions/portal-bss-deal.ts
  reference-data-proxy/src/v1/routes/external-apis.route.ts
  trade-finance-manager-api/src/v1/__mocks__/mock-TFM-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
Labels: documentation, tech debt, 1

#657 DTFS2-4615 - improve/update dashboard table & filter templates
  portal/styles/form.scss
  portal/templates/_macros/pagination.njk
  portal/templates/dashboard/_macros/dashboard-deals-table.njk
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
  portal/templates/dashboard/_macros/dashboard-filters-action-bar.njk
  portal/templates/dashboard/_macros/dashboard-filters-form.njk
  portal/templates/dashboard/_macros/dashboard-heading-and-tabs.njk
  portal/templates/dashboard/_macros/dashboard-page-content.njk
  portal/templates/dashboard/_macros/deal-advanced-filters.njk
  portal/templates/dashboard/deals.njk
  portal/templates/dashboard/facilities.njk
Labels: feature, 1

#647 fix TFM email variables - update mappings
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js
  trade-finance-manager-api/src/v1/emails/MIA-confirmation/generate-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/MIA-confirmation/generate-email-variables.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-deal.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-deal.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.js
Labels: bug, 3

#660 DTFS2-2220 Changed supporting documentation page title
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-criteria.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-documentation.spec.js
  e2e-tests/portal/cypress/integration/pages/eligibilityCriteria.js
  e2e-tests/portal/cypress/integration/pages/eligibilityDocumentation.js
  portal/templates/contract/components/task-list-header.njk
  portal/templates/eligibility/eligibility-supporting-documentation.njk
Labels: bug, 4

#649 DTFS2-5350 - GEF bug fix for accepting UKEF conditions text
  e2e-tests/gef/cypress/integration/pages/application-preview.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  gef-ui/templates/includes/application-preview/task-comments.njk
Labels: bug

#659 DTFS2-5349 GEF bug - fix change link showing on submitted
  gef-ui/server/utils/helpers.js
Labels: bug

#640 DTFS2-5313 GEF only bank create application redirect
  dtfs-central-api/api-tests/v1/gef-deals/add-min-activities.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  e2e-tests/portal/cypress/fixtures/users.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-create-deal.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-filter-by-keyword.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-filter-remove-all-filters.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-filters-reset-after-navigating-away.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-filters.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-main-container-filter-remove.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-panel-filter-remove.spec.js
  e2e-tests/portal/cypress/integration/journeys/login/change-password.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/fill-in-about-financial-validation.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/fill-in-about-supply-contract-clearing-data-via-next-page.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/fill-in-about-supply-contract-clearing-data-via-save-and-go-back.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/fill-in-about-supply-contract-unhappy-path.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/fill-in-about-supply-contract-validation.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-fee-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/check-deal-details/check-deal-details.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/dashboard/deals/dashboard-empty.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/dashboard/facilities/dashboard-empty.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/edit-deal-name.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility-criteria.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/eligibility.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/xss.spec.js
  e2e-tests/portal/cypress/integration/journeys/reports/unissued-facilities-reports.spec.js
  e2e-tests/portal/cypress/integration/pages/dashboardDeals.js
  gef-ui/templates/partials/mandatory-criteria.njk
  portal/templates/dashboard/_macros/dashboard-heading-and-tabs.njk
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  utils/mock-data-loader/banks/index.js
  utils/mock-data-loader/portal/users.js
Labels: 2

#664 Align supporting documents for GEF and BSS deals
  e2e-tests/portal/cypress/integration/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-today/deal.js
  e2e-tests/portal/cypress/integration/journeys/checker/issued-specs-new/MIA-deal-with-unissued-facilities.js
  e2e-tests/portal/cypress/integration/journeys/checker/issued-specs-new/submit-MIN-deal-with-issued-facility/MIN-deal-accepted-status-with-unissued-facilities.js
  e2e-tests/portal/cypress/integration/journeys/checker/return-a-deal-to-maker/dealWithSomeIssuedFacilitiesReadyForReview.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/MIA-accepted-deal-status-maker-cannot-resubmit-until-confirmed-all-issued-facilities-cover-start-date/MIA-deal-with-accepted-status-issued-facilities.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/fixtures/MIA-deal-with-accepted-status-issued-facilities-cover-start-date-in-past.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/fixtures/MIA-draft-deal-with-issued-facilities.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/maker-can-edit-issued-facilities-after-checker-returns-to-maker-after-submit-to-ukef/MIA-deal-submitted-to-ukef-with-issued-facilities-after-checker-returned-to-maker.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/maker-cannot-edit-issued-facilities-after-submit-to-ukef/deal-multiple-facility-types-ready-to-submit-to-ukef.js
  e2e-tests/portal/cypress/integration/journeys/maker/fixtures/dealFullyCompleted.js
  e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
  e2e-tests/portal/cypress/integration/journeys/maker/submit-issued-facilities-for-review/dealWithNotStartedFacilityStatuses.js
  e2e-tests/portal/cypress/integration/journeys/maker/submit-issued-facilities-for-review/submit-MIN-deal-with-issued-facilities-for-review-without-cover-start-dates/MINDealWithNotStartedFacilityStatuses.js
  e2e-tests/portal/cypress/integration/journeys/number-generator/test-data/MIA-deal-ready-to-submit-with-already-submitted-issued-facilities.js
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-MIA.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/bank-security.spec.js
  portal-api/api-tests/fixtures/deal-fully-completed.js
  portal-api/api-tests/v1/deals/deal-eligibility-documentation.api-test.js
  portal-api/src/v1/controllers/deal-eligibility-criteria.controller.js
  portal-api/src/v1/controllers/deal-eligibility-documentation.controller.js
  portal-api/src/v1/validation/eligibility-documentation.js
  portal/component-tests/fixtures/deal-fully-completed.js
  portal/server/routes/contract/eligibility/index.js
  portal/templates/_macros/eligibility-documentation-preview.njk
  portal/templates/contract/contract-submission-details.njk
  portal/templates/eligibility/eligibility-check-your-answers.njk
  portal/templates/eligibility/eligibility-supporting-documentation.njk
  trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
  trade-finance-manager-api/src/graphql/reducers/deals.api-test.js
  trade-finance-manager-api/src/graphql/reducers/deals.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.js
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/bank-security.test.js
  trade-finance-manager-ui/server/graphql/queries/deal-query.js
  trade-finance-manager-ui/server/graphql/queries/deals-query.js
  trade-finance-manager-ui/templates/case/underwriting/bank-security/bank-security.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/bank-security/bank-security.njk
  utils/mock-data-loader/bss/deals/1.js
  utils/mock-data-loader/bss/deals/10.js
  utils/mock-data-loader/bss/deals/11.js
  utils/mock-data-loader/bss/deals/2.js
  utils/mock-data-loader/bss/deals/3.js
  utils/mock-data-loader/bss/deals/4.js
  utils/mock-data-loader/bss/deals/5.js
  utils/mock-data-loader/bss/deals/6.js
  utils/mock-data-loader/bss/deals/7.js
  utils/mock-data-loader/bss/deals/8.js
  utils/mock-data-loader/bss/deals/9.js
Labels: tech debt

#662 Removed the PR limits for Central-API and 3rd Party APIs in GHA
  .github/workflows/pr_reference_data_proxy.yml
  .github/workflows/pr_trade_finance_manager-api.yml
  docker-compose.gha.yml
  dtfs-central-api/api-test-sequencer.jest.js
  dtfs-central-api/api-test.jest.config.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  utils/mock-data-loader/centralApi.js
Labels: feature, 5

#670 Add exporter.companyName to mock BSS deals used in E2E tests
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal-unissued-facilities/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal/dealThatJustNeedsDates.json
Labels: bug

#673 BSS - Change for to from
  portal/templates/contract/about/components/about-submission-details.njk
  portal/templates/contract/about/components/indemnifier-correspondence-address.njk
Labels: bug

#678 fix - TFM GEF email variables typo
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.js
Labels: bug

#679 DTFS2-Infrastructure : Dev environment
  .github/workflows/pipeline_azure_function_acbs.yml
  .github/workflows/pipeline_azure_function_number_generator.yml
  .github/workflows/pipeline_dts-central-api.yml
  .github/workflows/pipeline_gef-ui.yml
  .github/workflows/pipeline_portal-api.yml
  .github/workflows/pipeline_portal-ui.yml
  .github/workflows/pipeline_reference-data-proxy.yml
  .github/workflows/pipeline_trade-finance-manager-ui.yml
  .github/workflows/pipeline_trade_finance_manager-api.yml
Labels: tech debt

#676 DTFS2-4607 - Facility loan record creation
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-create-facility-loan/function.json
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/helpers/date.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-currency-exchange-rate.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency-months.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-type.js
  azure-functions/acbs-function/mappings/facility/helpers/get-interest-percentage.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-due-date.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-group.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
  azure-functions/acbs-function/mappings/facility/helpers/get-year-basis.js
  azure-functions/acbs-function/mappings/facility/helpers/index.js
  azure-functions/acbs-function/mappings/facility/index.js
Labels: documentation, feature, dependencies

#684 DTFS2-5370 GEF Bug - Fix created by and date submitted to UKEF bugs
  e2e-tests/gef/cypress/integration/application-details-submit-to-checker.spec.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/controllers/mocks/index.js
  gef-ui/server/models/application.js
  gef-ui/templates/partials/application-activity.njk
Labels: bug

#685 DTFS2-5369 GEF Bug - Show incomplete exporter fields
  e2e-tests/gef/cypress/integration/exporters-incomplete-details.spec.js
  e2e-tests/gef/cypress/integration/pages/dashboard-page.js
  gef-ui/server/controllers/companies-house/index.js
Labels: bug

#688 DTFS2-5355 : GEF Email
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal-MIN.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.js
  trade-finance-manager-api/src/v1/helpers/get-submission-date.api-test.js
  trade-finance-manager-api/src/v1/helpers/get-submission-date.js
Labels: bug, documentation

#693 DTFS2-5389 - GEF Bug - 3 months MINSubmissionDate
  e2e-tests/gef/cypress/fixtures/dateConstants.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
  e2e-tests/gef/cypress/integration/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/integration/unissued-facilities-change-all-MIN.spec.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/unissued-facilities/validation.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
  gef-ui/server/utils/facility-helpers.js
Labels: bug

#697 DTFS 5405 5404 5403 5402 5401: Fix bugs on Reports page
  e2e-tests/portal/cypress/integration/journeys/reports/review-ukef-decision.spec.js
  e2e-tests/portal/cypress/integration/journeys/reports/unissued-facilities-reports.spec.js
  portal-api/api-tests/v1/reports/review-ukef-decision.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/controllers/reports/review-ukef-decision.controller.js
  portal-api/src/v1/controllers/reports/unissued-facilities.controller.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/validation/application.js
  portal/server/controllers/dashboard/reports.controller.js
  portal/templates/reports/reports-dashboard.njk
Labels: bug

#700 DTFS2-5073 - BSS Bug - Cover end date validation
  gef-ui/package-lock.json
  package-lock.json
  portal-api/api-tests/v1/bonds/bonds-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-validation.api-test.js
  portal-api/package-lock.json
  portal-api/src/v1/validation/fields/cover-dates.js
Labels: bug

#702 DTFS2-4585 : Facility issue - Loan & Fee records creations
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/helpers/date.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
  azure-functions/acbs-function/mappings/facility/helpers/get-income-class-code.js
  reference-data-proxy/src/utils/swagger-definitions/acbs.ts
  reference-data-proxy/src/v1/controllers/acbs.controller.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: bug, documentation, dependencies

#704 DTFS2-4615 - Filter dashboard facilities by keyword. Reusable keyword query functions
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-keyword.spec.js
  portal/server/constants/field-names.js
  portal/server/controllers/dashboard/deals/deals-filters-keyword-query.js
  portal/server/controllers/dashboard/deals/deals-filters-keyword-query.test.js
  portal/server/controllers/dashboard/deals/deals-filters-query.js
  portal/server/controllers/dashboard/deals/deals-filters-query.test.js
  portal/server/controllers/dashboard/deals/selected-filters.js
  portal/server/controllers/dashboard/deals/selected-filters.test.js
  portal/server/controllers/dashboard/facilities/facilities-filters-keyword-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-keyword-query.test.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
  portal/server/controllers/dashboard/facilities/index.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/controllers/dashboard/facilities/selected-filters.js
  portal/server/controllers/dashboard/facilities/selected-filters.test.js
  portal/server/controllers/dashboard/filters/generate-keyword-query.js
  portal/server/controllers/dashboard/filters/generate-keyword-query.test.js
  portal/templates/dashboard/facilities.njk
Labels: feature, tech debt

#698 DTFS2-5300: TFM - "Value (export currency)" field missing the value after decimal place
  e2e-tests/trade-finance-manager/cypress/integration/journeys/facility/facilities.spec.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/graphql/resolvers/query-facilities.js
Labels: bug

#706 DTFS2-4615 - ability to remove dashboard facility filters
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-remove-all-filters.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-main-container-filter-remove.spec.js
  e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-panel-filter-remove.spec.js
  portal/server/constants/dashboard-filters.js
  portal/server/constants/dashboard.js
  portal/server/constants/index.js
  portal/server/controllers/dashboard/deals/index.js
  portal/server/controllers/dashboard/deals/index.test.js
  portal/server/controllers/dashboard/facilities/index.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/controllers/dashboard/facilities/selected-filters.js
  portal/server/controllers/dashboard/facilities/selected-filters.test.js
  portal/server/controllers/dashboard/filters/generate-selected-filters.js
  portal/server/controllers/dashboard/filters/generate-selected-filters.test.js
  portal/server/controllers/dashboard/filters/remove-filter-from-session.js
  portal/server/controllers/dashboard/filters/remove-filter-from-session.test.js
  portal/server/controllers/dashboard/index.js
  portal/server/routes/dashboard.js
  portal/server/routes/login.js
  portal/templates/dashboard/_macros/dashboard-filters-action-bar.njk
Labels: feature, tech debt

#707 fix/DTFS2-5395 - wipe previousStatus when cloning a BSS/EWCS deal
  e2e-tests/portal/cypress/integration/journeys/maker/clone-deal/clone-deal.spec.js
  portal-api/api-tests/v1/deals/deal-clone.api-test.js
  portal-api/src/v1/controllers/deal-clone.controller.js
Labels: bug

#713 DTFS2-5357 - add line break to each facility in GEF confirmation email
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js
Labels: bug

#714 GHA - Self-hosted runners
  .github/workflows/env_dev.yml
  .github/workflows/promote_to_test.yml
Labels: feature

#709 DTFS2-2948 : Password reset
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/src/v1/users/reset-password.controller.js
  portal-api/src/v1/users/routes.js
  portal/server/routes/login.js
  portal/templates/_partials/password-create.njk
  portal/templates/user/change-password.njk
Labels: bug, documentation, dependencies

#720 fix/DTFS2-5417 - TFM all deals default sort order
  trade-finance-manager-ui/server/constants/deals.js
  trade-finance-manager-ui/server/controllers/deals/index.test.js
Labels: bug

#723 DTFS2-ACBS : Date bug fix
  azure-functions/acbs-function/helpers/date.js
Labels: bug

#719 DTFS2 - Git Hub Runners
  .github/workflows/dns.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_staging.yml
  .github/workflows/infrastructure.yml
  .github/workflows/pipeline_azure_function_acbs.yml
  .github/workflows/pipeline_azure_function_number_generator.yml
  .github/workflows/pipeline_dts-central-api.yml
  .github/workflows/pipeline_gef-ui.yml
  .github/workflows/pipeline_portal-api.yml
  .github/workflows/pipeline_portal-ui.yml
  .github/workflows/pipeline_reference-data-proxy.yml
  .github/workflows/pipeline_trade-finance-manager-ui.yml
  .github/workflows/pipeline_trade_finance_manager-api.yml
  .github/workflows/pr_azure_function_acbs.yml
  .github/workflows/pr_azure_function_number_generator.yml
  .github/workflows/pr_gef-ui.yml
  .github/workflows/pr_no_tests.yml
  .github/workflows/pr_portal-api.yml
  .github/workflows/pr_portal-ui.yml
  .github/workflows/pr_trade-finance-manager-ui.yml
  .github/workflows/pr_trade_finance_manager-api.yml
  .github/workflows/promote_to_demo.yml
  .github/workflows/promote_to_prod.yml
  .github/workflows/promote_to_staging.yml
Labels: feature, tech debt

#728 DTFS2-5394 - GEF Bug - Comments name not showing
  e2e-tests/gef/cypress/integration/application-details-submit-to-checker.spec.js
  e2e-tests/gef/cypress/integration/return-to-maker-mia.spec.js
  e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js
  gef-ui/server/controllers/return-to-maker/index.js
  gef-ui/server/controllers/return-to-maker/index.test.js
  gef-ui/server/controllers/submit-to-ukef/index.js
  gef-ui/templates/includes/application-preview/task-comments.njk
  portal-api/package-lock.json
Labels: bug

#731 DTFS2-ACBS : Date bug
  azure-functions/acbs-function/helpers/date.js
  reference-data-proxy/src/v1/controllers/party-db.controller.ts
Labels: bug

#725 fix/DTFS2-5386 - add manualInclusionNoticeSubmissionDate to TFM submission mapping
  trade-finance-manager-api/src/v1/helpers/get-submission-date.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.js
Labels: bug

#732 DTFS2 : File restored
  reference-data-proxy/src/v1/controllers/party-db.controller.ts
Labels: bug

#734 DTFS2-5417 - TFM - add dateReceivedTimestamp, fix Fee Record tests
  e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-search.spec.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dateReceived.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dateReceived.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.js
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
  trade-finance-manager-ui/server/constants/deals.js
  trade-finance-manager-ui/server/controllers/deals/index.test.js
Labels: bug, feature, tech debt

#737 DTFS2 - ACBS Bugs
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-quarter-date.js
Labels: bug

#739 DTFS2-ACBS-Bug : Cover start date
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-effective-date.js
Labels: bug

#740 DTFS2-TD : GH Runners
  .github/workflows/dns.yml
  .github/workflows/env_dev.yml
  .github/workflows/env_prod.yml
  .github/workflows/env_test.yml
  .github/workflows/pipeline_azure_function_acbs.yml
  .github/workflows/pipeline_azure_function_number_generator.yml
  .github/workflows/pipeline_dts-central-api.yml
  .github/workflows/pipeline_gef-ui.yml
  .github/workflows/pipeline_portal-api.yml
  .github/workflows/pipeline_portal-ui.yml
  .github/workflows/pipeline_reference-data-proxy.yml
  .github/workflows/pipeline_trade-finance-manager-ui.yml
  .github/workflows/pipeline_trade_finance_manager-api.yml
  .github/workflows/pr_azure_function_acbs.yml
  .github/workflows/pr_azure_function_number_generator.yml
  .github/workflows/pr_gef-ui.yml
  .github/workflows/pr_portal-api.yml
  .github/workflows/pr_portal-ui.yml
  .github/workflows/pr_trade-finance-manager-ui.yml
  .github/workflows/pr_trade_finance_manager-api.yml
  .github/workflows/promote_to_demo.yml
  .github/workflows/promote_to_prod.yml
  .github/workflows/promote_to_staging.yml
  .github/workflows/promote_to_test.yml
Labels: tech debt
