Repository UK-Export-Finance/dtfs2, pull requests merged in 2022-06, with the labels that each got.

#995 Bug - BSS - mock data loader eligibility
  utils/mock-data-loader/bss/deals/1.js
  utils/mock-data-loader/bss/deals/10.js
  utils/mock-data-loader/bss/deals/11.js
  utils/mock-data-loader/bss/deals/2.js
  utils/mock-data-loader/bss/deals/3.js
  utils/mock-data-loader/bss/deals/4.js
  utils/mock-data-loader/bss/deals/5.js
  utils/mock-data-loader/bss/deals/6.js
  utils/mock-data-loader/bss/deals/7.js
  utils/mock-data-loader/bss/deals/8.js
  utils/mock-data-loader/bss/deals/9.js
Labels: tech debt

#997 feat: added eligibility and mandatory criteria to emails
  dtfs-central-api/src/v1/controllers/portal/mandatory-criteria/mandatory-criteria.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js
  e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  e2e-tests/trade-finance-manager/cypress/fixtures/mock-gef-facilities.js
  gef-ui/package-lock.json
  gef-ui/package.json
  portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/reference-data/currencies.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/currencies.controller.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
  portal-api/src/v1/gef/controllers/validation/application.js
  portal-api/src/v1/gef/models/application.js
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  reference-data-proxy/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts
  reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/constants/email-template-ids.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/generate-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/generate-email-variables.js
  trade-finance-manager-api/src/v1/helpers/generate-eligibility-criteria-string.js
  trade-finance-manager-api/src/v1/helpers/generate-mandatory-criteria-string.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
Labels: feature

#1003 revert: reverted `DTFS2-5821` and `DTFS2-5498` + typo & typecasting
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
Labels: git

#1006 ACBS - Typecast, Fee Frequency & Exposure period fixes
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency-months.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
  azure-functions/acbs-function/mappings/facility/helpers/map-fee-type.js
Labels: bug, ACBS

#1007 DTFS2-5854 : Facility fee type mapping
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityFeeType.api-test.js
  trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityFeeType.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js
Labels: bug, ACBS

#1010 fix: prevent `Abandoned` deals from showing on unissued facilities report
  portal-api/src/v1/controllers/reports/unissued-facilities.controller.js
Labels: bug

#1012 fix(DTFS2-5816): Probability of default validation
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/probability-of-default.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/underwriting/probabilityOfDefaultPage.js
  trade-finance-manager-api/src/graphql/resolvers/mutation-update-probability-of-default.js
  trade-finance-manager-api/src/graphql/schemas/index.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.test.js
  trade-finance-manager-ui/server/controllers/deals/index.js
  trade-finance-manager-ui/server/controllers/deals/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/index.js
  trade-finance-manager-ui/server/controllers/helpers/index.test.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/probability-of-default.njk
Labels: bug

#1013 fix: return the latest eligibility criteria for GEF and BSS/EWCS deals
  e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js
  portal-api/api-tests/v1/deals/deal-clone.api-test.js
  portal-api/src/v1/controllers/deal-clone.controller.js
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
Labels: bug

#1011 Eligibility Criteria : Capture network errors & array index number typecaste
  trade-finance-manager-api/src/v1/mappings/map-eligibility-criteria-content-strings.js
  trade-finance-manager-ui/server/api.js
Labels: bug

#1014 fix(DTFS2-5817): TFM - Missing price risk info
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-MIA.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/change-facility-risk-profile.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/underwriting/pricingAndRiskPage.js
  trade-finance-manager-ui/server/graphql/queries/deal-query.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.njk
Labels: bug

#1015 feat(DTFS2-5727): Underwriting page updates
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/public/js/jsEnabled.js.map
  trade-finance-manager-ui/public/js/main.js.map
  trade-finance-manager-ui/public/js/mojFrontend.js
  trade-finance-manager-ui/public/js/mojFrontend.js.map
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.test.js
  trade-finance-manager-ui/styles/typography.scss
  trade-finance-manager-ui/templates/case/underwriting/managers-decision/_macros/managers-decision-submitted.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/managers-decision/_macros/managers-decision-submitted.njk
Labels: feature

#1016 fix(DTFS2-5859): Amendments bug - change bank decision
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-withdraw.spec.js
  trade-finance-manager-ui/server/controllers/case/amendments/bankDecision.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/bankDecision.controller.test.js
  trade-finance-manager-ui/server/test-mocks/amendment-test-mocks.js
Labels: bug, amendments

#1018 DTFS2-5821 : Unissued facility exposure period
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
Labels: bug, ACBS

#1021 feat(DTFS2-5856-5857-5842-5845): Amendments - UW and bank decision emails
  azure-functions/acbs-function/docker-compose.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js
  trade-finance-manager-api/src/constants/deals.js
  trade-finance-manager-api/src/constants/email-template-ids.js
  trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/emails/amendments/automatic-approval-email-variables.js
  trade-finance-manager-api/src/v1/emails/amendments/manual-amendment-decision-email-variables.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-ui/server/controllers/case/amendments/bankDecision.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/managersConditionsAndComments.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentUnderwriterManagersDecisionConditions.validate.js
  trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments-summary.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments.njk
Labels: feature, amendments

#1026 DTFS2-5870 : Moment `utc()` calls removed.
  azure-functions/acbs-function/helpers/date.js
  trade-finance-manager-api/src/utils/date.js
  trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.js
Labels: bug, ACBS

#1028 fix(DTFS2-5760): Portal BSS - cover start date backdate
  e2e-tests/portal/cypress/integration/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-min-submission-date/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-min-submission-date.spec.js
  e2e-tests/portal/cypress/integration/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-min-submission-date/deal.js
  e2e-tests/portal/cypress/integration/journeys/checker/submit-a-deal/submit-a-deal.spec.js
  e2e-tests/portal/cypress/integration/journeys/maker/facilities/fixtures/MIA-deal-with-accepted-status-issued-facilities-cover-start-date-in-past.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/bonds/bonds-validation.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-validation.api-test.js
  portal-api/api-tests/v1/validation/ready-for-check-cover-start-dates.api-test.js
  portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js
  portal-api/src/v1/validation/checker-submit-deal-facility-ready-for-check-cover-start-dates/index.js
  portal-api/src/v1/validation/completeDealValidation-flat.js
  portal-api/src/v1/validation/fields/issue-facility/requested-cover-start-date.js
  portal-api/src/v1/validation/fields/issued-date.js
  portal-api/src/v1/validation/loan-rules/facility-stage-unconditional/requested-cover-start-date.js
Labels: bug, feature

#1031 build: updated Node.JS to `node:18.4-alpine3.16`
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: tech debt

#1040 fix(DTFS2-5871-5825): Amendments - deal stage and uw managers decision fixes
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-in-progress-deal-stage.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/pages/index.js
  e2e-tests/trade-finance-manager/cypress/integration/partials/caseSubNavigation.js
  trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/activity/index.js
  trade-finance-manager-ui/server/controllers/case/activity/index.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/managersConditionsAndComments.controller.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.js
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
  trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments.njk
Labels: amendments

#1044 DTFS2-5882 : ACBS - Exception handling & helper function usage
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
Labels: ACBS

#1046 DTFS2-5582 : disbursementAmount undefined - FLR
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
Labels: bug, ACBS

#1051 DTFS2-5882 : ABCS improved exceptional handling for facility records
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
Labels: bug, ACBS

#1053 fix(DTFS2-5824): Amendments in progress bar bug
  trade-finance-manager-ui/templates/case/amendments/_macros/amendment-in-progress-bar.njk
Labels: bug, amendments

#1050 fix(DTFS2-5887/5892): Amendment task fixes
  e2e-tests/trade-finance-manager/cypress/fixtures/constants.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-automatic.spec.js
  e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-manual.spec.js
  trade-finance-manager-api/src/constants/tasks-amendment.constant.js
  trade-finance-manager-api/src/constants/teams.js
Labels: bug, amendments

#1052 fix(DTFS2-5878/5879): BSS amendments email fix
  trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/emails/amendments/automatic-approval-email-variables.js
  trade-finance-manager-api/src/v1/emails/amendments/manual-amendment-decision-email-variables.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js
Labels: bug, amendments

#1054 fix: updated the eStore timers to execute after 59s
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/cronJobs/eStoreCronJobManager.ts
  reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
Labels: bug
