Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-08, with the labels that each got.

#1885 feat(FN-685) A record generation
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/external-api.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/gef-ui.bicep
  infrastructure/resource_group_level/modules/portal-api.bicep
  infrastructure/resource_group_level/modules/portal-ui.bicep
  infrastructure/resource_group_level/modules/privatelink-azurewebsites-net.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-ui.bicep
Labels: Type: Feature

#1884 feat(FN-429): front door - tfm
  infrastructure/arm_templates/front-door-tfm/parameters.json
  infrastructure/arm_templates/front-door-tfm/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/external-api.bicep
  infrastructure/resource_group_level/modules/front-door-tfm.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/gef-ui.bicep
  infrastructure/resource_group_level/modules/portal-api.bicep
  infrastructure/resource_group_level/modules/portal-ui.bicep
  infrastructure/resource_group_level/modules/privatelink-azurewebsites-net.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-ui.bicep
Labels: Type: Feature

#1882 feat(FN-428):application gateway tfm
  infrastructure/arm_templates/application-gateway-tfm/parameters.json
  infrastructure/arm_templates/application-gateway-tfm/template.json
  infrastructure/arm_templates/front-door-tfm/parameters.json
  infrastructure/arm_templates/front-door-tfm/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/application-gateway-tfm.bicep
  infrastructure/resource_group_level/modules/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/external-api.bicep
  infrastructure/resource_group_level/modules/front-door-tfm.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/gef-ui.bicep
  infrastructure/resource_group_level/modules/portal-api.bicep
  infrastructure/resource_group_level/modules/portal-ui.bicep
  infrastructure/resource_group_level/modules/privatelink-azurewebsites-net.bicep
  infrastructure/resource_group_level/modules/tfs-ip.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-ui.bicep
Labels: Type: Feature

#1939 fix(security): mitigated various GH security alerts
  .gitignore
  azure-functions/acbs-function/.dockerignore
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/.dockerignore
  azure-functions/number-generator-function/package-lock.json
  cspell.json
  dtfs-central-api/.dockerignore
  dtfs-central-api/package-lock.json
  external-api/.dockerignore
  external-api/package-lock.json
  gef-ui/.dockerignore
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/templates/includes/exporters-address/seperate-correspondence.njk
  gef-ui/templates/index.njk
  gef-ui/templates/partials/upload-supporting-documents.njk
  package-lock.json
  portal-api/.dockerignore
  portal-api/package-lock.json
  portal/.dockerignore
  portal/package-lock.json
  portal/package.json
  portal/public/js/mojFrontend.js
  portal/public/js/mojFrontend.js.map
  portal/templates/_macros/facility-inputs/guarantee-fee-payable-by-bank.njk
  portal/templates/_macros/facility-inputs/ukef-exposure.njk
  portal/templates/_partials/print-button.njk
  portal/templates/index.njk
  trade-finance-manager-api/.dockerignore
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/.dockerignore
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/templates/index.njk
  utils/data-migration/package-lock.json
Labels: Type: Fix, Type: Security

#1942 fix(dockerignore): fixed docker ignore paths
  .gitignore
  azure-functions/acbs-function/.dockerignore
  azure-functions/number-generator-function/.dockerignore
  dtfs-central-api/.dockerignore
  external-api/.dockerignore
  gef-ui/.dockerignore
  portal-api/.dockerignore
  portal/.dockerignore
  trade-finance-manager-api/.dockerignore
  trade-finance-manager-ui/.dockerignore
Labels: Type: Fix

#1944 fix(csp): removed inline <script> tag
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  external-api/src/middleware/headers/security/index.api-test.ts
  external-api/src/middleware/headers/security/index.ts
  gef-ui/server/middleware/headers/security.middleware.js
  portal-api/src/v1/middleware/headers/security.js
  portal/public/js/main.js
  portal/public/js/main.js.map
  portal/scripts/change-industry-classes.js
  portal/scripts/main.js
  portal/server/helpers/mapIndustrySectors.js
  portal/server/routes/middleware/headers/security.middleware.js
  portal/templates/contract/about/about-supplier.njk
  portal/templates/contract/about/components/industry-sectors-dropdown.njk
  portal/templates/index.njk
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/server/middleware/headers/security.js
  utils/mock-data-loader/api.js
Labels: Type: Security

#1947 feat(DTFS2-6493): TFM UI - updated accessibility statement content
  trade-finance-manager-ui/templates/accessibility-statement.njk
Labels: Type: Feature

#1943 feat(FN-712): commonise webapps
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/external-api.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/gef-ui.bicep
  infrastructure/resource_group_level/modules/portal-ui.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-ui.bicep
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/external-api.bicep
  infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
  infrastructure/resource_group_level/modules/webapps/webapp.bicep
Labels: Type: Feature

#1950 fix(csp)!: TFM `CSP` fix
  cspell.json
  trade-finance-manager-ui/public/js/govukFrontend.js
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/public/js/jsEnabled.js
  trade-finance-manager-ui/public/js/jsEnabled.js.map
  trade-finance-manager-ui/public/js/main.js
  trade-finance-manager-ui/public/js/main.js.map
  trade-finance-manager-ui/public/js/mojFrontend.js
  trade-finance-manager-ui/public/js/mojFrontend.js.map
  trade-finance-manager-ui/scripts/main.js
  trade-finance-manager-ui/scripts/submit.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
  trade-finance-manager-ui/server/middleware/headers/security.js
  trade-finance-manager-ui/templates/case/activity/_macros/activity-comment-filter.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/task-filters.njk
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: Fix, BREAKING

#1955 fix(SR-8): sanitise db input additional changes
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
  dtfs-central-api/src/v1/controllers/portal/mandatory-criteria/mandatory-criteria.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.js
  portal-api/src/v1/controllers/banks.controller.js
  portal-api/src/v1/controllers/mandatoryCriteria.controller.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/files.controller.js
  portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
  utils/data-migration/helpers/database.js
Labels: Type: Fix

#1951 feat(FN-923): update infrastructure with main - vars
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/external-api.bicep
  infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
Labels: Type: Feature

#1961 fix(DTFS2-6615): allow most csp headers in e2e tests
  cspell.json
  e2e-tests/gef/cypress.config.js
  e2e-tests/portal/cypress.config.js
  e2e-tests/submit-to-trade-finance-manager/cypress.config.js
  e2e-tests/trade-finance-manager/cypress.config.js
  portal/public/js/main.js
  portal/public/js/main.js.map
  portal/scripts/change-industry-classes.js
  portal/scripts/change-industry-classes.test.js
  portal/scripts/main.js
  portal/scripts/show-hide-element.js
  portal/templates/_macros/eligibility-documentation-file-input.njk
  portal/templates/contract/about/components/industry-sectors-dropdown.njk
  portal/templates/index.njk
  trade-finance-manager-ui/public/js/main.js
  trade-finance-manager-ui/public/js/main.js.map
  trade-finance-manager-ui/scripts/main.js
  trade-finance-manager-ui/scripts/submit.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/middleware/headers/security.js
  trade-finance-manager-ui/templates/case/activity/_macros/activity-comment-filter.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/task-filters.njk
  trade-finance-manager-ui/templates/index.njk
Labels: Type: Fix, security fix

#1966 fix(DTFS2-6614): remove `errorLog` collection usage
  portal-api/src/v1/controllers/log-controller.js
Labels: Type: Fix

#1963 fix(sr-8): update error message name
  cspell.json
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/clone-gef-deal.api-test.js
  portal-api/api-tests/v1/gef/external-api.api-test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/src/v1/gef/controllers/externalApi.controller.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/validation/application.js
  portal-api/src/v1/gef/controllers/validation/external.js
  portal-api/src/v1/gef/controllers/validation/facilities.js
Labels: Type: Fix

#1967 feat(auto-release): auto release based on conventional commit messages
  .github/workflows/publish.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  cspell.json
  dtfs-central-api/api-tests/v1/facilities/facilities.api-test.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/v1/routes/portal-routes.js
  e2e-tests/gef/cypress/e2e/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm.spec.js
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/gef/controllers/application-submit.js
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/api.js
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
  utils/mock-data-loader/portal/users.js
  utils/mock-data-loader/user-helper.js
Labels: Type: Feature

#1969 chore(deps): dependecies updates
  .github/workflows/publish.yml
  .husky/commit-msg
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
Labels: dependencies

#1972 feat(countries): Disabled countries
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  e2e-tests/portal/cypress/e2e/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-min-submission-date/deal.js
  e2e-tests/portal/cypress/fixtures/deal.js
  external-api/package-lock.json
  external-api/package.json
  external-api/src/external-api/countries.ts
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/external-api/__mocks__/countries.js
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
Labels: Type: Feature

#1973 feat(codecov): `CodeCov` introduction
  .github/workflows/sca.yml
  .github/workflows/test.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  cspell.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Feature
