Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-06, with the labels that each got.

#1694 fix(lint): lint fixes
  .eslintignore
  azure-functions/acbs-function/.eslintrc.js
  azure-functions/number-generator-function/.eslintrc.js
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/api-tests/api.js
  dtfs-central-api/api-tests/wipeDB.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-put-amendments.controller.js
  e2e-tests/gef/cypress/e2e/application-activities-AIN.spec.js
  e2e-tests/gef/cypress/e2e/application-activities-MIA.spec.js
  e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/amendment-should-change-all-facilities-values.spec.js
  gef-ui/.eslintrc.js
  portal-api/.eslintrc.js
  portal-api/api-tests/api-test-eligibilityCriteria.js
  portal-api/api-tests/drivers/fileshare.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/deals/deal-eligibility-documentation.api-test.js
  portal-api/api-tests/v1/deals/deals-status-accepted-facilities-cover-start-date.api-test.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/gef/validation/exporter.api-test.js
  portal-api/api-tests/wipeDB.js
  portal/.eslintrc.js
  portal/component-tests/componentRenderer.js
  portal/component-tests/contract/contract-view.component-test.js
  portal/component-tests/pageRenderer.js
  reference-data-proxy/.eslintignore
  reference-data-proxy/src/cronJobs/eStoreCronJobManager.ts
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/component-tests/componentRenderer.js
  trade-finance-manager-ui/component-tests/pageRenderer.js
  trade-finance-manager-ui/templates/case/tasks/_macros/task-status-tag.component-test.js
  utils/data-migration/.eslintrc.js
  utils/data-migration/bss-ewcs/helpers/fileshare_local.js
  utils/data-migration/bss-ewcs/helpers/industry-sectors.js
  utils/data-migration/bss-ewcs/maps/findPortalValue.js
  utils/data-migration/bss-ewcs/maps/map-deal-files.js
  utils/data-migration/bss-ewcs/maps/map-eligibility.js
  utils/data-migration/bss-ewcs/maps/map-loan-transactions.js
  utils/data-migration/bss-ewcs/migrate-deals.js
  utils/data-migration/bss-ewcs/migrate-users.js
  utils/data-migration/export-tables.js
  utils/data-migration/gef/map-deal.js
  utils/data-migration/gef/map-facilities.js
  utils/data-migration/gef/mapping-errors.js
  utils/data-migration/gef/migrate-deals.js
  utils/data-migration/gef/migrate.js
  utils/data-migration/helpers/banks.js
  utils/data-migration/helpers/io.js
  utils/data-migration/helpers/users.js
  utils/data-migration/tfm/migrate-tfm-users.js
  utils/mock-data-loader/.eslintrc.js
  utils/mock-data-loader/bss/deals/index.js
  utils/mock-data-loader/bss/facilities/index.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/refresh-reference-data.js
  utils/mock-data-loader/tfm/re-insert-mocks-tfm.js
  utils/reporting/tfm/.eslintrc.js
Labels: Type: chore, Type: Fix, dependencies

#1698 feat(mongodb): mongodb-serilisation-express dependency introduction
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/README.md
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/createApp.js
  e2e-tests/portal/cypress/e2e/journeys/checker/dashboard/dashboard.spec.js
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/helpers/escapeOperators.api-test.js
  portal-api/api-tests/utils/string.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/createApp.js
  portal-api/src/utils/string.js
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/controllers/facilities.controller.js
  portal-api/src/v1/helpers/escapeOperators.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/validation/feedback-rules/email-address.js
  portal/package-lock.json
  portal/package.json
  portal/server/controllers/dashboard/deals/deals-filters-query.js
  portal/server/controllers/dashboard/deals/deals-filters-query.test.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
  portal/server/controllers/dashboard/filters/generate-keyword-query.js
  portal/server/controllers/dashboard/filters/generate-keyword-query.test.js
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/createApp.ts
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/createApp.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/data-migration/tfm/migrate-tfm-users.js
  utils/mock-data-loader/clean-all-tables-gef.js
  utils/mock-data-loader/clean-all-tables.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/portal/users.js
  utils/mock-data-loader/tfm/clean-all-tables-tfm.js
  utils/mock-data-loader/tfm/insert-mocks-tfm.js
Labels: Type: Feature, Type: Security

#1700 fix(DTFS2-6147): vulnerabilities test coverage
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/fixtures/users.js
  portal-api/api-tests/v1/users/users.api-test.js
Labels: Type: Feature, Type: Fix, Type: Security

#1752 feat(rename): renamed reference data proxy to external api
  .github/workflows/development_deploy.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/pr_api_tests.yml
  .github/workflows/production_deploy.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_deploy.yml
  .github/workflows/staging_infrastructure.yml
  README.md
  azure-functions/README.md
  azure-functions/number-generator-function/controllers/number-generator.controller.js
  e2e-tests/trade-finance-manager/cypress/support/external-api/api.js
  e2e-tests/trade-finance-manager/cypress/support/portal-api/createFacilities.js
  e2e-tests/trade-finance-manager/cypress/support/portal-api/createGefFacility.js
  e2e-tests/trade-finance-manager/cypress/support/portal-api/insertManyDeals.js
  e2e-tests/trade-finance-manager/cypress/support/portal-api/insertManyGefDeals.js
  external-api/.env.sample
  external-api/README.md
  external-api/src/external-api/countries.ts
  external-api/src/external-api/currencies.ts
  external-api/src/external-api/index.ts
  external-api/src/external-api/industry-sectors.ts
  external-api/src/utils/swagger.util.ts
  external-api/src/v1/controllers/countries.controller.ts
  external-api/src/v1/controllers/currencies.controller.ts
  external-api/src/v1/controllers/industry-sectors.controller.ts
  external-api/src/v1/controllers/number-generator.controller.ts
  portal-api/api-test-setup.jest.config.js
  portal-api/api-tests/v1/countries/countries.api-test.js
  portal-api/api-tests/v1/currencies/currencies.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted-updates-unsubmitted-issued-facilities.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted.api-test.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/industry-sectors/industry-sectors.api-test.js
  portal-api/src/external-api/__mocks__/api.js
  portal-api/src/external-api/__mocks__/countries.js
  portal-api/src/external-api/__mocks__/currencies.js
  portal-api/src/external-api/__mocks__/industry-sectors.js
  portal-api/src/external-api/__mocks__/number-generator.js
  portal-api/src/external-api/__mocks__/send-email.js
  portal-api/src/external-api/api.js
  portal-api/src/external-api/countries.js
  portal-api/src/external-api/currencies.js
  portal-api/src/external-api/industry-sectors.js
  portal-api/src/external-api/number-generator.js
  portal-api/src/external-api/send-email.js
  portal-api/src/v1/controllers/countries.controller.js
  portal-api/src/v1/controllers/currencies.controller.js
  portal-api/src/v1/controllers/deal-status/create-ukef-ids.js
  portal-api/src/v1/controllers/industrySectors.controller.js
  portal-api/src/v1/gef/controllers/application-submit.js
  portal-api/src/v1/gef/controllers/application.controller.js
  utils/mock-data-loader/refresh-reference-data.js
Labels: Type: Fix

#1702 feat(DTFS2-6506): sanitize user input for vulnerable forms
  e2e-tests/portal/cypress/e2e/journeys/feedback/feedback-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/about-supply-contract/fill-in-buyer-page-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/about-supply-contract/fill-in-financial-page-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/about-supply-contract/fill-in-supply-contract-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bank-details-created-field.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bond/submit-bond-with-created-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/loan/submit-loan-with-created-elements.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-issued-facilities-for-review/submit-issued-bond-facility-with-created-field.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-issued-facilities-for-review/submit-issued-loan-facility-with-created-field.spec.js
  e2e-tests/portal/cypress/fixtures/constants.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal-api/api.js
  e2e-tests/portal/cypress/support/portal-api/getAllFeedback.js
  e2e-tests/portal/cypress/support/portal-api/getBSSFacility.js
  e2e-tests/portal/cypress/support/portal-api/getDeal.js
  e2e-tests/portal/cypress/support/utils/insertElement.js
  portal-api/src/v1/controllers/feedback.controller.js
  portal/server/api.js
  portal/server/constants/currency.js
  portal/server/constants/facility-stage.js
  portal/server/constants/index.js
  portal/server/routes/contract/about/buyerPage.js
  portal/server/routes/contract/about/financialPage.js
  portal/server/routes/contract/about/supplierPage.js
  portal/server/routes/contract/bond/index.js
  portal/server/routes/contract/loan/index.js
  portal/server/routes/contract/saveFacilityAndGoBack.js
  portal/server/routes/start.js
  portal/templates/before-you-start/before-you-start-bank-deal.njk
  portal/templates/bond/bond-details.njk
  portal/templates/bond/bond-fee-details.njk
  portal/templates/bond/bond-financial-details.njk
  portal/templates/bond/bond-issue-facility.njk
  portal/templates/contract/about/about-supplier.njk
  portal/templates/contract/about/about-supply-buyer.njk
  portal/templates/contract/about/about-supply-financial.njk
  portal/templates/feedback/feedback-form.njk
  portal/templates/loan/loan-dates-repayments.njk
  portal/templates/loan/loan-financial-details.njk
  portal/templates/loan/loan-guarantee-details.njk
  portal/templates/loan/loan-issue-facility.njk
Labels: Type: Feature, Type: Fix, Type: Security

#1754 fix(typo): GHA job name
  .github/workflows/development_deploy.yml
  .github/workflows/staging_deploy.yml
Labels: Type: Fix

#1757 fix(DTFS2-5768): Fix deal and facility portal filtering
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-filter-on-wrong-pagination-page.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-on-wrong-pagination-page.spec.js
  portal-api/api-tests/helpers/computeSkipPosition.api-test.js
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/controllers/facilities.controller.js
  portal-api/src/v1/helpers/computeSkipPosition.js
Labels: Type: Bug

#1706 feat(DTFS2-6355): Make amendment button (GEF)
  e2e-tests/gef/cypress/e2e/amend-facility.spec.js
  e2e-tests/gef/cypress/e2e/pages/application-preview.js
  gef-ui/server/constants/index.js
  gef-ui/server/controllers/amend-facility/what-do-you-need-to-change/index.js
  gef-ui/server/controllers/amend-facility/what-do-you-need-to-change/index.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/mocks/index.js
  gef-ui/server/routes/__tests__/amend-facility.test.js
  gef-ui/server/routes/__tests__/index.test.js
  gef-ui/server/routes/amend-facility.js
  gef-ui/server/routes/index.js
  gef-ui/server/utils/facility-helpers.js
  gef-ui/server/utils/facility-helpers.test.js
  gef-ui/templates/includes/application-preview/facilities.njk
  gef-ui/templates/partials/amend-facility/what-do-you-need-to-change.njk
Labels: Type: Feature

#1701 feat(fn-417): storage
  infrastructure/arm_templates/storage-private-endpoint/parameters.json
  infrastructure/arm_templates/storage-private-endpoint/template.json
  infrastructure/arm_templates/storage/parameters.json
  infrastructure/arm_templates/storage/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/storage.bicep
  infrastructure/resource_group_level/modules/vnet.bicep
Labels: Type: Feature

#1705 feat(fn-416): cosmosdb
  infrastructure/arm_templates/cosmosdb/errors.json
  infrastructure/arm_templates/cosmosdb/parameters.json
  infrastructure/arm_templates/cosmosdb/private-endpoint/parameters.json
  infrastructure/arm_templates/cosmosdb/private-endpoint/template.json
  infrastructure/arm_templates/cosmosdb/serverless_example/parameters.json
  infrastructure/arm_templates/cosmosdb/serverless_example/template.json
  infrastructure/arm_templates/cosmosdb/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/cosmosdb.bicep
  infrastructure/resource_group_level/modules/privatelink-mongo-cosmos-azure-com.bicep
Labels: Type: Feature

#1765 feat(FN-573): Configure automatic A Record generation
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/privatelink-file-core-windows-net.bicep
  infrastructure/resource_group_level/modules/storage.bicep
Labels: Type: Feature
