Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-11, with the labels that each got.

#2187 feat(FN-995): notify bank confirmation email
  portal-api/src/constants/email-template-ids.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/src/v1/helpers/convertUtcDateToDateTimeString.test.js
  portal-api/src/v1/helpers/covertUtcDateToDateTimeString.js
  portal/component-tests/utilisation-report-service/confirmation.component-test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/templates/utilisation-report-service/utilisation-report-upload/confirmation.njk
Labels: Type: Fintech

#2195 feat(FN-967): upload file to azure and db
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/constants/dbCollections.js
  dtfs-central-api/src/constants/regex.js
  dtfs-central-api/src/constants/utilisationReportHeaders.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.test.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo.test.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/upload-utilisation-report.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-data-validator.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-data-validator.test.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-report-validator.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-report-validator.test.js
  portal-api/src/utils/getMonthName.js
  portal-api/src/utils/getMonthName.test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/src/v1/routes.js
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#2263 fix(private-runners): Moved workflow jobs to public runners
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Fix, dependencies

#2200 feat(DTFS2-6750): generate sign in link token
  e2e-tests/portal/cypress/e2e/journeys/login/login.spec.js
  portal-api/.eslintrc.js
  portal-api/api-tests/common-tests/client-authentication-tests.js
  portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
  portal-api/package.json
  portal-api/src/crypto/cryptographically-strong-generator.js
  portal-api/src/crypto/cryptographically-strong-generator.test.js
  portal-api/src/crypto/hasher.js
  portal-api/src/crypto/hasher.test.js
  portal-api/src/crypto/pbkdf2-sha512-hash-strategy.js
  portal-api/src/v1/email/index.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/users/authentication-email.controller.js
  portal-api/src/v1/users/authentication-email.controller.test.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/repository.js
  portal-api/src/v1/users/repository.test.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
  portal-api/src/v1/users/sign-in-link.controller.js
  portal-api/src/v1/users/sign-in-link.controller.test.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal-api/src/v1/users/sign-in-link.service.test.js
  portal/.eslintrc.js
  portal/api-tests/admin-routes.api-test.js
  portal/api-tests/contract/about-routes.api-test.js
  portal/api-tests/contract/bond-routes.api-test.js
  portal/api-tests/contract/contract-routes.api-test.js
  portal/api-tests/contract/loan-routes.api-test.js
  portal/api-tests/dashboard-routes.api-test.js
  portal/api-tests/eligibility-routes.api-test.js
  portal/api-tests/feedback-routes.api-test.js
  portal/api-tests/footer-routes.api-test.js
  portal/api-tests/login-routes/get-login.api-test.js
  portal/api-tests/login-routes/other-login-routes.api-test.js
  portal/api-tests/login-routes/post-login.api-test.js
  portal/api-tests/portal-routes.api-test.js
  portal/api-tests/scheme-type-routes.api-test.js
  portal/api-tests/start-routes.api-test.js
  portal/api-tests/static-routes.api-test.js
  portal/api-tests/user-routes.api-test.js
  portal/package-lock.json
  portal/package.json
  portal/server/api.js
  portal/server/api.test.js
  portal/server/routes/login/index.js
Labels: Type: Feature

#2270 feat(FN-1432): handle formulas and new lines in excel cells
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#2273 feat(FN-995): fix report submitted by param
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
Labels: Type: Fintech

#2201 fix(DTFS-6752): improve css for check your email screen
  portal/component-tests/login/_macros/request-new-sign-in-link.component-test.js
  portal/public/css/styles.css
  portal/styles/button.scss
  portal/templates/_macros/eligibility-documentation-file-input.njk
  portal/templates/login/_macros/request-new-sign-in-link.njk
Labels: Type: Fix

#2268 feat(DTFS2-6769): create additional variants of check email page
  portal/component-tests/login/new-sign-in-link-sent.component-test.js
  portal/component-tests/login/temporarily-suspended.component-test.js
  portal/component-tests/login/we-have-sent-you-another-link.component-test.js
  portal/templates/_partials/contact-us.njk
  portal/templates/login/_macros/request-new-sign-in-link.njk
  portal/templates/login/check-your-email.njk
  portal/templates/login/new-sign-in-link-sent.njk
  portal/templates/login/temporarily-suspended.njk
  portal/templates/login/we-have-sent-you-another-link.njk
Labels: Type: Feature

#2277 feat(FN-1472): remove commas from cell values
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Feature, Type: Fintech

#2282 fix: lock down report upload journey
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/utils/csv-utils.js
Labels: Type: Fintech

#2088 chore(package): tidy root package json
  e2e-tests/.eslintrc.js
  package-lock.json
  package.json
Labels: Type: chore

#2285 chore(deps): dependencies updates
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
Labels: dependencies

#2292 feat(FN-1432): handle formulas where value.result is undefined
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#2289 feat(DTfS2-6784): update built mojFrontend files to reflect jQuery version bump
  README.md
  gef-ui/templates/index.njk
  portal/public/js/mojFrontend.js
  portal/public/js/mojFrontend.js.LICENSE.txt
  portal/public/js/mojFrontend.js.map
  portal/templates/index.njk
Labels: Type: chore

#2264 WIP fix(DTFS-6458): remove current-page aria
  trade-finance-manager-ui/templates/_macros/header.njk
Labels: Status: In Progress, Type: Fix

#2291 feat(FN-1295): back link and error positioning
  portal/templates/admin/user-edit.njk
  portal/templates/index.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/confirm-and-send.njk
Labels: Type: Fintech

#2197 feat(FN-970): Monthly status on file upload page
  external-api/api-test.jest.config.js
  external-api/api-tests/test-mocks/bank-holidays.ts
  external-api/api-tests/v1/bank-holidays.api-test.ts
  external-api/src/external-api/bank-holidays.ts
  external-api/src/external-api/index.ts
  external-api/src/interfaces/bankHolidays.interface.ts
  external-api/src/interfaces/index.ts
  external-api/src/utils/swagger-definitions/bank-holidays-division.ts
  external-api/src/utils/swagger-definitions/bank-holidays.ts
  external-api/src/utils/swagger.util.ts
  external-api/src/v1/controllers/bank-holidays.controller.ts
  external-api/src/v1/routes/external-apis.route.ts
  portal-api/api-tests/v1/bank-holidays/bank-holidays.api-test.js
  portal-api/src/external-api/api.js
  portal-api/src/external-api/bank-holidays.js
  portal-api/src/v1/controllers/bank-holidays.controller.js
  portal-api/src/v1/routes.js
  portal/package-lock.json
  portal/package.json
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.test.js
  portal/server/helpers/addBusinessDays.js
  portal/server/helpers/addBusinessDays.test.js
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#2296 fix(DTFS2-6789): allow read-only users to have access to all banks
  gef-ui/server/constants/all-banks-id.js
  gef-ui/server/constants/index.js
  gef-ui/server/middleware/validateBank/index.js
  gef-ui/server/middleware/validateBank/index.test.js
  portal/server/constants/all-banks-id.js
  portal/server/constants/index.js
  portal/server/controllers/dashboard/deals/deals-filters-query.test.js
  portal/server/controllers/dashboard/deals/index.test.js
  portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/helpers/isSuperUser.js
  portal/server/helpers/isSuperUser.test.js
  portal/server/routes/admin/users.js
  portal/server/routes/middleware/validateBank/index.js
  portal/server/routes/middleware/validateBank/index.test.js
Labels: Type: Fix

#2295 fix(DTFS2-6788): nunjucks boolean check
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/templates/case/deal/_macros/eligibility-criteria-answer-tag.component-test.js
  trade-finance-manager-ui/templates/case/deal/_macros/eligibility-criteria-answer-tag.njk
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Fix, dependencies

#2272 feat(DTFS2-6762): add environment variable portal-ui-url
  .github/workflows/bicep_az_deployment_group.yml
  .github/workflows/bicep_workflow_feature.yml
  infrastructure/resource_group_level/main.bicep
Labels: Type: Feature

#2301 fix(gef-readonly): added read-only to GEF deals users
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/models/application.js
Labels: Type: Fix

#2299 feat(FN-970): fix month indexing in session
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.test.js
  portal/server/helpers/getOneIndexedMonth.js
  portal/server/helpers/getOneIndexedMonth.test.js
  portal/server/helpers/index.js
Labels: Type: Fintech

#2279 feat(DTFS2-6778): add typescript compatibility to portal and fix jsdocs
  dtfs-central-api/src/v1/routes/middleware/headers/check-api-key.js
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  dtfs-central-api/src/v1/routes/middleware/headers/seo.js
  dtfs-central-api/src/v1/routes/middleware/remove-csrf-token.js
  external-api/src/middleware/check-api-key/index.ts
  external-api/src/middleware/headers/security/index.ts
  external-api/src/middleware/headers/seo.ts
  gef-ui/server/middleware/headers/security.middleware.js
  gef-ui/server/middleware/headers/seo.middleware.js
  portal-api/src/v1/middleware/headers/check-api-key.js
  portal-api/src/v1/middleware/headers/security.js
  portal-api/src/v1/middleware/headers/seo.js
  portal-api/src/v1/middleware/remove-csrf-token.js
  portal/init.sh
  portal/package-lock.json
  portal/package.json
  portal/scripts/main.ts
  portal/server/azure-env/index.js
  portal/server/azure-env/index.ts
  portal/server/index.ts
  portal/server/routes/middleware/headers/security.middleware.js
  portal/server/routes/middleware/headers/seo.middleware.js
  portal/tsconfig.eslint.json
  portal/tsconfig.json
  portal/webpack.common.config.js
  trade-finance-manager-api/src/v1/middleware/headers/check-api-key.js
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-api/src/v1/middleware/headers/seo.js
  trade-finance-manager-api/src/v1/middleware/remove-csrf-token.js
  trade-finance-manager-api/src/v1/validation/route-validators/validation-handler.js
  trade-finance-manager-ui/server/middleware/headers/security.js
  trade-finance-manager-ui/server/middleware/headers/seo.js
Labels: Type: chore

#2288 feat(FN-1480): remove duplicate bank routes in Central API
  dtfs-central-api/src/v1/routes/portal-routes.js
Labels: Type: Fintech

#2298 feat(FN-978): handle report upload failures and 409 on double submission
  dtfs-central-api/src/services/repositories/utilisation-data-repo.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.test.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo.test.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/upload-utilisation-report.controller.js
  dtfs-central-api/src/v1/routes/bank-routes.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisationReport.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-report-validator.js
  portal-api/api-tests/v1/validation/validateIds.api-test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/validation/validateIds.js
  portal/server/api.js
Labels: Type: Feature, Type: Fintech

#2303 feat(FN-1162/3/4): add infra env vars for scheduled report emails
  .github/workflows/bicep_az_deployment_group.yml
  infrastructure/resource_group_level/main.bicep
Labels: Type: Fintech

#2276 feat(FN-1162): add reporting period started email job
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  cspell.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/api-tests/mocks/banks.js
  dtfs-central-api/api-tests/v1/bank/bank-get.api-test.js
  dtfs-central-api/api-tests/v1/bank/bank-post.api-test.js
  dtfs-central-api/api-tests/v1/bank/banks-get.api-test.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/constants/payloads.js
  dtfs-central-api/src/v1/controllers/bank/get-banks.controller.js
  dtfs-central-api/src/v1/routes/bank-routes.js
  portal-api/.eslintrc.js
  portal-api/api-test-setup.jest.config.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/constants/email-template-ids.js
  portal-api/src/constants/payloads.js
  portal-api/src/external-api/__mocks__/api.js
  portal-api/src/external-api/__mocks__/bank-holidays.js
  portal-api/src/external-api/api.js
  portal-api/src/external-api/bank-holidays.js
  portal-api/src/index.js
  portal-api/src/scheduler/index.js
  portal-api/src/scheduler/jobs/index.js
  portal-api/src/scheduler/jobs/send-reporting-period-start-emails-job/helpers.js
  portal-api/src/scheduler/jobs/send-reporting-period-start-emails-job/index.js
  portal-api/src/scheduler/jobs/send-reporting-period-start-emails-job/index.test.js
  portal-api/src/scheduler/types/scheduler-job.d.ts
  portal-api/src/utils/date.js
  portal-api/src/utils/date.test.js
  portal-api/src/utils/getMonthName.js
  portal-api/src/utils/getMonthName.test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/bank-holidays.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  portal-api/test-helpers/mock-banks.js
  trade-finance-manager-api/src/constants/payloads.js
  utils/mock-data-loader/banks/index.js
Labels: Type: Fintech

#2284 feat(FN-1163): add report due email job
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/api-tests/v1/bank/banks-get.api-test.js
  portal-api/src/constants/email-template-ids.js
  portal-api/src/scheduler/jobs/helpers/utilisation-report-helpers.js
  portal-api/src/scheduler/jobs/helpers/utilisation-report-helpers.test.js
  portal-api/src/scheduler/jobs/index.js
  portal-api/src/scheduler/jobs/send-report-due-emails-job/index.js
  portal-api/src/scheduler/jobs/send-report-due-emails-job/index.test.js
  portal-api/src/scheduler/jobs/send-reporting-period-start-emails-job/helpers.js
  portal-api/src/scheduler/jobs/send-reporting-period-start-emails-job/index.js
  portal-api/src/scheduler/jobs/send-reporting-period-start-emails-job/index.test.js
  portal-api/src/utils/date.js
  portal-api/test-helpers/mock-banks.js
  portal-api/test-helpers/mock-utilisation-reports.js
Labels: Type: Fintech

#2309 test(FN-1163): add env vars to CI
  .github/workflows/test.yml
Labels: Type: Fintech

#2313 chore(DTFS2-NONE): update package-lock for portal
  portal/package-lock.json
Labels: Type: chore

#2203 feat(DTFS2-5659): added tests for sorting Facility Stage column
  e2e-tests/tfm/cypress/e2e/journeys/facility/facilities.spec.js
Labels: Test

#2286 feat(DTFS-6777): add magic sign in link e2e tests
  .github/workflows/test.yml
  e2e-tests/portal/cypress.config.js
  e2e-tests/portal/cypress/e2e/journeys/AD integration/activedirectory.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/activate-deactivate-user/activate-deactivate-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/change-password.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/login.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/login/index.js
  e2e-tests/portal/cypress/e2e/pages/login/sign-in-link.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal-api/api.js
  e2e-tests/portal/cypress/support/portal-api/removeUserIfPresent.js
  e2e-tests/portal/cypress/support/portal/enterUsernameAndPassword.js
  e2e-tests/portal/cypress/support/portal/login.js
  e2e-tests/portal/cypress/support/portal/overrideUserSignInTokenByUsername.js
  e2e-tests/support/db-client.js
  portal/server/api.js
  portal/server/routes/login/index.js
  portal/templates/_partials/problem-with-service.njk
Labels: Type: Feature

#2287 feat(DTFS2-6780): add typescript compatibility to dtfs-central-api
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/init.sh
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/azure-env/index.js
  dtfs-central-api/src/azure-env/index.ts
  dtfs-central-api/src/index.ts
  dtfs-central-api/tsconfig.eslint.json
  dtfs-central-api/tsconfig.json
Labels: Type: chore

#2310 feat(DTFS2-6793): add e2e test for TFM Eligibility criteria
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-AIN.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-MIA.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-page-GEF.spec.js
  e2e-tests/tfm/cypress/e2e/pages/caseDealPage.js
Labels: Type: Feature, Test

#2321 feat(FN-1385): implement clamav as Azure Container App
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/clamav-aca.bicep
  infrastructure/resource_group_level/modules/clamav.bicep
  infrastructure/resource_group_level/modules/vnet.bicep
Labels: Type: Feature, Type: Fintech

#2319 feat(FN-1507): update title on upload report page
  dtfs-central-api/src/v1/controllers/bank/get-bank.controller.js
  dtfs-central-api/src/v1/routes/bank-routes.js
  portal-api/api-tests/api.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
  trade-finance-manager-api/src/v1/api.js
Labels: Type: Fintech

#2329 chore: add typescript parser to portal-api to fix linting error
  package-lock.json
  package.json
  portal-api/.eslintrc.js
Labels: Type: Fintech

#2331 Fix: use mongodb transactions
  dtfs-central-api/src/drivers/db-client.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/upload-utilisation-report.controller.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
Labels: Type: Fix, Type: Fintech

#2320 feat(FN-1089): report is not due
  cspell.json
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-no-longer-upload-report.spec.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  portal-api/api-tests/v1/utilisation-report-service/lastest-report.api-test.js
  portal-api/src/v1/controllers/utilisation-report-service/due-report-dates.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/due-report-dates.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/index.js
  portal-api/src/v1/controllers/utilisation-report-service/latest-report.controller.js
  portal-api/src/v1/routes.js
  portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-details.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-details.test.js
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#2327 fix: fix mock-data-loader clearing gef-eligibilityCriteria
  utils/mock-data-loader/gef/api.js
Labels: Type: chore

#2278 feat(DTFS2-5659): add component tests for TFM UI
  trade-finance-manager-ui/component-tests/case/activity.component-test.js
  trade-finance-manager-ui/component-tests/case/assign-lead-underwriter.component-test.js
  trade-finance-manager-ui/component-tests/case/case.component-test.js
  trade-finance-manager-ui/component-tests/case/deals.component-test.js
  trade-finance-manager-ui/component-tests/case/documents.component-test.js
  trade-finance-manager-ui/component-tests/case/edit-managers-decision.component-test.js
  trade-finance-manager-ui/component-tests/case/facility.component-test.js
  trade-finance-manager-ui/component-tests/case/lead-underwriter.component-test.js
  trade-finance-manager-ui/component-tests/case/managers-decision.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/bond-beneficiary-facilities-table.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/bond-issuer-facilities-table.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-agent-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-bond-beneficiary-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-bond-beneficiary-edit.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-bond-issuer-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-bond-issuer-edit.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-buyer-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-edit-unique-reference-link.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-exporter-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-indemnifier-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-key-value-array-grid-row.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-key-value-grid-row.component-test.js
  trade-finance-manager-ui/component-tests/case/task.component-test.js
  trade-finance-manager-ui/component-tests/case/tasks.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/edit-pricing-and-risk.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/loss-given-default.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk1/edit-facility-risk-profile/edit-facility-risk-profile.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/probability-of-default.component-test.js
  trade-finance-manager-ui/component-tests/deal/default-view-deal.component-test.js
  trade-finance-manager-ui/component-tests/login/sign-in.component-test.js
Labels: Type: Feature, Test

#2293 feat(DTFS2 6783): add typescript compatibility to trade-finance-manager-UI
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  trade-finance-manager-ui/init.sh
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/scripts/main.ts
  trade-finance-manager-ui/server/index.ts
  trade-finance-manager-ui/tsconfig.eslint.json
  trade-finance-manager-ui/tsconfig.json
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: chore

#2300 feat(DTFS2-6757): add tests to sign in link validation
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/v1/users/sign-in-link.controller.test.js
  portal-api/test-helpers/api-test-helpers/database/database.config.js
  portal-api/test-helpers/api-test-helpers/database/user-repository.js
  utils/mock-data-loader/database/database.config.js
Labels: Type: Security

#2336 fix(DTFS2-NONE): fix pipeline
  .github/workflows/test.yml
  dtfs-central-api/src/drivers/db-client.js
  e2e-tests/support/db-client.js
  external-api/src/database/mongo-client.ts
  portal-api/src/drivers/db-client.js
  portal-api/test-helpers/api-test-helpers/database/database-client.js
  trade-finance-manager-api/src/drivers/db-client.js
  utils/data-migration/export-tables.js
  utils/data-migration/helpers/database.js
  utils/mock-data-loader/database/database-client.js
Labels: Type: Fix

#2338 feat(FN-1134): fix validate filename year
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js
Labels: Type: Fintech

#2339 feat(FN-1089): fix next report period start
  portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#2283 fix(DTFS2-6520): made aria-labels in Deal page tabs headings more consistent
  trade-finance-manager-ui/templates/case/activity/activity.njk
  trade-finance-manager-ui/templates/case/documents/documents.njk
  trade-finance-manager-ui/templates/case/parties/parties.njk
  trade-finance-manager-ui/templates/case/tasks/tasks.njk
  trade-finance-manager-ui/templates/case/underwriting/underwriting.njk
Labels: Type: Fix

#2341 feat(FN-1089): fix report uploadedBy schema
  dtfs-central-api/src/services/repositories/utilisation-reports-repo.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo.test.js
  dtfs-central-api/src/v1/swagger-definitions/utilisationReport.js
  portal-api/test-helpers/mock-utilisation-reports.js
Labels: Type: Fintech

#2343 feat(DTFS2-none): remove aria label tests and update underwriting heading test
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/underwriting-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/parties.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/tasks/tasks.spec.js
Labels: Type: Fix

#2332 feat(FN-967): add an environment variable for utilisation reports shareclient
  .github/workflows/bicep_az_deployment_group.yml
  cspell.json
  infrastructure/resource_group_level/main.bicep
Labels: Type: Fintech

#2342 feat(DTFS2-6461): change p to h2 tags for visual headings on TFM deal page
  trade-finance-manager-ui/templates/case/deal/deal.njk
Labels: Type: Fix

#2344 fix: add back eslint parser typescript defs
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  package-lock.json
  package.json
  portal/server/api.js
  portal/server/routes/middleware/validateRole/index.js
  portal/templates/admin/user-edit.njk
Labels: Type: Fintech

#2325 feat(DTFS-6693): add expiry functionality to 2FA sign in links
  portal-api/.eslintrc.js
  portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
  portal-api/src/constants/index.js
  portal-api/src/constants/sign-in-link-duration.js
  portal-api/src/constants/sign-in-link-expiry-minutes.js
  portal-api/src/v1/users/repository.js
  portal-api/src/v1/users/repository.test.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
  portal-api/src/v1/users/sanitizeUserData.test.js
  portal-api/src/v1/users/sign-in-link.controller.js
  portal-api/src/v1/users/sign-in-link.controller.test.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal-api/src/v1/users/sign-in-link.service.test.js
  portal-api/src/v1/users/transform-database-user.js
  portal-api/src/v1/users/transform-database-user.test.js
  portal-api/test-helpers/unit-test-mocks/mock-user.js
  portal/.eslintrc.js
  portal/api-tests/login/other-login-routes.api-test.js
  portal/server/routes/login/index.js
Labels: Type: Security

#2349 fix: get correct report period due date
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
Labels: Type: Fintech

#2340 chore: only use --legacy-peer-deps on TFM UI package
  .github/workflows/sca.yml
  azure-functions/acbs-function/Dockerfile
  azure-functions/number-generator-function/Dockerfile
  dtfs-central-api/Dockerfile
  external-api/Dockerfile
  gef-ui/Dockerfile
  package.json
  portal-api/Dockerfile
  portal/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/.npmrc
Labels: Type: Fintech

#2350 fix: fix e2e injection test for user creation
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
Labels: Type: Fix

#2352 fix(DTFS2-6532): replace illogical facility heading levels
  trade-finance-manager-ui/templates/case/facility/facility.njk
Labels: Type: Fix

#2359 fix: ensure pipeline fails if dtfs-central and external api tests fail
  README.md
  azure-functions/acbs-function/api-test-file.jest.config.js
  dtfs-central-api/README.md
  dtfs-central-api/api-test-file.jest.config.js
  dtfs-central-api/api-test.jest.config.js
  dtfs-central-api/package.json
  dtfs-central-api/test-teardown-globals.js
  external-api/README.md
  external-api/api-test-teardown.jest.config.js
  external-api/api-test.jest.config.js
  external-api/package.json
  portal-api/api-test-file.jest.config.js
  portal-api/package.json
  portal-api/test-teardown-globals.js
  trade-finance-manager-api/README.md
  trade-finance-manager-api/api-test-file.jest.config.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/test-teardown-globals.js
Labels: Type: Fix

#2365 fix/add environment to clamav app name
  cspell.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/clamav-aca.bicep
Labels: Type: Feature, Type: Fintech
