Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-02, with the labels that each got.

#1294 feat(DTFS2-6225): ACBS Exceptional handling
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
Labels: Type: Bug, Type: Feature, Type: ACBS, Type: Fix

#1297 feat(DTFS2-6283): Bond - Facility loan record amendment
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility/index.js
Labels: Type: ACBS, Type: Amendments, Type: Fix

#1296 feat(npm-lint): Various npm audit and lint fixes
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/.eslintignore
  azure-functions/number-generator-function/.eslintrc.js
  azure-functions/number-generator-function/activity-get-number-from-generator/index.js
  azure-functions/number-generator-function/package.json
  azure-functions/number-generator-function/testing/defaultContext.js
  azure-functions/number-generator-function/testing/defaultTimer.js
  package-lock.json
  portal-api/package-lock.json
Labels: Type: Chore, Type: Fix, Type: Security, dependencies, security fix

#1299 chore(nginx): Dockerfile image upgrade to 1.23
  reverse-proxy/Dockerfile
Labels: Type: Chore, Type: Security

#1300 feat(DTFS2-6284): GCD and GED for TCM and ACBS
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-expiry-date.js
  azure-functions/acbs-function/mappings/facility/code-value-transaction.js
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-guarantee.js
  azure-functions/acbs-function/mappings/facility/facility-investor.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-dates.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-due-date.js
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
  trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.api-test.js
  trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.js
Labels: Type: Bug, Type: ACBS, Type: Fix

#1301 chore(security.txt): Expire updated
  portal/server/routes/static.js
Labels: Type: Security

#1302 fix(tfm): Deal submission logging
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dealStage.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.js
  trade-finance-manager-api/src/v1/controllers/should-update-deal-from-MIA-to-MIN.js
Labels: Type: Bug, Type: Fix

#1307 chore(npm-package-bump): Updated @sideway/formula to 3.0.1
  gef-ui/package-lock.json
  portal-api/package-lock.json
  reference-data-proxy/package-lock.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/package-lock.json
Labels: Type: Chore, Type: Security

#1317 chore: updated NodeJS to v`18.14-alpine3.17`
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: Type: Chore, Type: Security

#1318 fix(no-activities): Prevents TFM crash when no acitivity exist
  trade-finance-manager-ui/server/controllers/case/activity/index.js
Labels: Type: Fix

#1319 chore(cookie): Added cookie related documentation
  README.md
Labels: Type: Docs

#1323 chore(npm): NPM Major update and packages update
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  gef-ui/package-lock.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal/package-lock.json
  reference-data-proxy/package-lock.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/package-lock.json
Labels: Type: Chore

#1326 fix(no-currency): Default to `GBP` on void currency
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-investor.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
Labels: Type: ACBS, Type: Fix

#1327 chore(npm): NPM updates
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package.json
  utils/mock-data-loader/package.json
Labels: Type: Chore

#1331 fix: updated the eStore intervals
  reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
Labels: Type: Fix

#1332 fix(dockerfile): Node v10 incompatible with npm 9.5.1
  azure-functions/acbs-function/Dockerfile
  azure-functions/number-generator-function/Dockerfile
Labels: Type: Fix
