Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-10, with the labels that each got.

#2085 feat(FN-1172): do not restart webapps after a slot swap
  .github/workflows/feature_deploy.yml
Labels: Type: Feature

#2086 feat(FN-1173): deploy app code from main stbr
  .github/workflows/feature_deploy.yml
Labels: Type: Feature

#2072 feat(country): updated `Serbia` country code.
  external-api/src/external-api/countries.ts
  portal-api/src/external-api/__mocks__/countries.js
Labels: Type: Feature

#2078 feat(FN-966): validate utilisation report content
  cspell.json
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/utilisationReportUpload.js
  e2e-tests/portal/cypress/fixtures/invalid-utilisation-report.csv
  e2e-tests/portal/cypress/fixtures/invalid-utilisation-report.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report.xlsx
  portal/api-tests/service-options-routes.api-test.js
  portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
  portal/jest.config.js
  portal/package-lock.json
  portal/package.json
  portal/server/constants/file-upload.js
  portal/server/constants/index.js
  portal/server/constants/regex.js
  portal/server/constants/utilisation-report-headers.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-base-currency-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-base-currency-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-exchange-rate-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-facility-utilisation-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-facility-utilisation-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-monthly-fees-paid-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-monthly-fees-paid-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-currency-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-currency-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-ukef-facility-id-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-ukef-facility-id-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
Labels: Type: Fintech

#2039 feat(DTFS2-6182): replace get deal and get deals graphql endpoints with REST endpoints
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals.controller.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/src/v1/graphql-mappings/filters/filterActivities.api-test.js
  trade-finance-manager-api/src/v1/graphql-mappings/filters/filterActivities.js
  trade-finance-manager-api/src/v1/graphql-mappings/filters/filterTasks.api-test.js
  trade-finance-manager-api/src/v1/graphql-mappings/filters/filterTasks.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/activity/index.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/facility-risk-profile/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/loss-given-default/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/index.js
  trade-finance-manager-ui/server/controllers/deals/index.js
  trade-finance-manager-ui/server/controllers/deals/index.test.js
Labels: Type: Feature

#2151 Feat(FN-966): handle weird excel data that strips cell address
  portal/server/utils/csv-utils.js
Labels: Type: Fintech

#2144 fix(e2e-tests): seed random company names to prevent 3% chance of collision that causes test failure
  e2e-tests/.eslintrc.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-filter-on-wrong-pagination-page.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-exporter-name.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-on-wrong-pagination-page.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-sort.spec.js
  e2e-tests/support/random-value-generator.js
Labels: Type: Fix

#2154 fix(FN-966): fix back button on upload page
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
Labels: Type: Fintech

#2147 feat(DTFS2-6715): migrate get team members in tfm to rest
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/api.js
  trade-finance-manager-api/api-tests/common-tests/client-authentication-tests.js
  trade-finance-manager-api/api-tests/v1/teams/get-team-members.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-team-members.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/graphql-mappings/teamMembers.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-api/src/v1/swagger.js
  trade-finance-manager-api/src/v1/teams/routes.js
  trade-finance-manager-api/src/v1/teams/team-id-param.validator.js
  trade-finance-manager-api/src/v1/teams/teams.js
  trade-finance-manager-api/src/v1/teams/teams.test.js
  trade-finance-manager-api/src/v1/validation/validateIds.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentTasks.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/leadUnderwriter.controller.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
  trade-finance-manager-ui/server/graphql/queries/team-members-query.js
Labels: Type: Security

#2156 fix(release): release version manager
  .github/workflows/publish.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
Labels: Type: Fix

#2159 fix: redeploy code
  portal/server/utils/csv-utils.js
Labels: Type: Fintech

#2149 feat(DTFS2-6717): replace graphql update lead underwriter in tfm with rest
  docker-compose.dev.yml
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/api-tests/api.js
  gef-ui/.eslintrc.js
  portal/.eslintrc.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/v1/amendments/update-tfm-deal-amendment-completion.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-party-db.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-lead-underwriter.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js
  trade-finance-manager-api/graphql-query-tests/graphql-authentication.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-credit-rating.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-lead-underwriter.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-loss-given-default.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-parties.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-probability-of-default.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-task.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-underwriting-managers-decision.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/__mocks__/common-api-mocks.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deals.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.api-test.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-bss.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-tfm-tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.api-test.js
  trade-finance-manager-api/src/v1/helpers/get-assignee-full-name.api-test.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-api/src/v1/tasks/assign-group-tasks-to-one-user.api-test.js
  trade-finance-manager-api/src/v1/tasks/assign-group-tasks-to-one-user.js
  trade-finance-manager-api/src/v1/tasks/map-task-object.api-test.js
  trade-finance-manager-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
Labels: Type: Security

#2158 feat(DTFS2-6718): migrate update underwriters managers decision in tfm to rest
  e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/underwriting/underwriter-managers-decision.spec.js
  e2e-tests/tfm/cypress/support/commands.js
  e2e-tests/tfm/cypress/support/ui/type-without-delay.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-lead-underwriter.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-task.api-test.js
  trade-finance-manager-api/src/graphql/resolvers/mutation-update-underwriter-managers-decision.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/__mocks__/common-api-mocks/find-one-team.js
  trade-finance-manager-api/src/v1/__mocks__/common-api-mocks/index.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-underwriter-managers-decision.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.update-tfm-underwriter-managers-decision.test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-tfm-tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/task-emails.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/index.test.js
  trade-finance-manager-ui/server/graphql/mutations/update-underwriter-managers-decision.js
Labels: Type: Security

#2150 chore(FN-684): Remove unnecessary code
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/cosmosdb.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/privatelink-azurewebsites-net.bicep
  infrastructure/resource_group_level/modules/privatelink-mongo-cosmos-azure-com.bicep
  infrastructure/resource_group_level/modules/redis.bicep
  infrastructure/resource_group_level/modules/storage.bicep
  infrastructure/resource_group_level/modules/webapps/webapp.bicep
Labels: Type: chore

#2146 feat(FN-927): wire up tfm-ui url
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/front-door-tfm.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-connection-strings.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-no-connection-strings.bicep
Labels: Type: Feature

#2143 feat(FN-1203): disable function-acbs in non-prod environments
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
Labels: Type: Feature

#2153 feat(FN-980): list previous reports backend
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/v1/controllers/portal/utilisation-report-service/previous-reports.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  dtfs-central-api/src/v1/validation/route-validators/route-validators.js
  dtfs-central-api/src/v1/validation/route-validators/validation-handler.js
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/previous-reports/list-previous-reports.spec.js
  portal-api/api-tests/fixtures/utilisation-report-service/reports.js
  portal-api/api-tests/v1/utilisation-report-service/previous-reports.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/index.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.test.js
  portal-api/src/v1/roles/roles.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/validation/route-validators/route-validators.js
  portal-api/src/v1/validation/route-validators/validation-handler.js
  portal-api/src/v1/validation/validateIds.js
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/previous-reports/data.json
  portal/server/controllers/utilisation-report-service/previous-reports/index.js
  portal/server/controllers/utilisation-report-service/previous-reports/index.test.js
  portal/server/validation/validate-ids.js
Labels: Type: Fintech

#2162 fix(DTFS2-6182): remove passport from put deals submit
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-api/src/v1/graphql-mappings/filters/filterActivities.api-test.js
  trade-finance-manager-api/src/v1/routes.js
Labels: Type: Fix

#2148 fix(DTFS2-6678): remove auto-create password for new user as not needed
  e2e-tests/portal/cypress.config.js
  e2e-tests/portal/cypress/e2e/journeys/admin/activate-deactivate-user/activate-deactivate-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/change-password.spec.js
  e2e-tests/portal/cypress/e2e/pages/admin/users/createUser.js
  e2e-tests/portal/cypress/e2e/pages/admin/users/editUser.js
  e2e-tests/portal/cypress/e2e/pages/resetPassword.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/userSetPassword.js
  e2e-tests/portal/db-client.js
  package-lock.json
  package.json
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/routes.js
  portal/templates/admin/user-edit.njk
Labels: Type: Bug

#2160 feat(dtfs2-6716):replace graphql update task in tfm with rest
  trade-finance-manager-api/api-tests/api.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-lead-underwriter.api-test.js
  trade-finance-manager-api/api-tests/v1/tasks/tasks-update-task.api-test.js
  trade-finance-manager-api/src/graphql/resolvers/mutation-update-task.js
  trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/tasks.controller.js
  trade-finance-manager-api/src/v1/graphql-mappings/mappings/facilities/mapPremiumSchedule.api-test.js
  trade-finance-manager-api/src/v1/graphql-mappings/mappings/facilities/mapTenor.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-api/src/v1/tasks/routes.js
  trade-finance-manager-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/constants/regex.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/helpers/validateIds.js
Labels: Type: Security

#2152 feat(fn 997): file type validation and virus scanning
  .github/workflows/feature_deploy.yml
  .github/workflows/test.yml
  .gitignore
  cspell.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/fixtures/password-protected-report.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report.xlsx
  portal/package-lock.json
  portal/package.json
  portal/server/constants/file-upload.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/routes/middleware/index.js
  portal/server/routes/middleware/virusScanUpload/index.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/utils/multer-filter.utils.js
Labels: Type: Fintech

#2155 feat(FN-972): file type validation on re upload
  .github/workflows/feature_deploy.yml
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/routes/middleware/virusScanUpload/index.js
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
Labels: Type: Fintech

#2161 feat(FN-974): Notify email for incoming report
  .env.sample
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/common-tests/role-authorisation-tests.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js
  portal-api/src/constants/email-template-ids.js
  portal-api/src/v1/controllers/utilisation-report-service/index.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/users/reset-password.controller.js
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/templates/admin/user-edit.njk
Labels: Type: Fintech

#2168 feat(FN-715):deploy stbr infra
  .github/workflows/bicep_workflow_feature.yml
Labels: chore

#2167 feat(FN-927): Remove TFM_UI_URL variable injection
  .github/workflows/bicep_az_deployment_group.yml
  .github/workflows/bicep_deploy.yml
  .github/workflows/bicep_workflow_feature.yml
  infrastructure/resource_group_level/main.bicep
Labels: Type: Feature

#2165 feat(mongodb): Fix vulnerable version of `mongodb`
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Fix, Type: Security, dependencies

#2179 feat(FN-1145): add clamav infra
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/clamav.bicep
  infrastructure/resource_group_level/modules/vnet.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
Labels: Type: Feature

#2183 feat(FN-974): create environment variable pdc inputter email
  .github/workflows/bicep_az_deployment_group.yml
  .github/workflows/bicep_deploy.yml
  .github/workflows/bicep_workflow_feature.yml
  cspell.json
  infrastructure/resource_group_level/main.bicep
Labels: Type: Feature, Type: Fintech

#2188 fix(DTFS2-6746): do not remove parties after updating bond beneficiary or issuer urns
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond-beneficiary.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond-issuer.spec.js
  e2e-tests/tfm/cypress/e2e/pages/partiesPage.js
  e2e-tests/tfm/cypress/fixtures/constants.js
  trade-finance-manager-ui/server/controllers/case/index.js
Labels: Type: Fix

#2190 feat(DTFS2-6751): add sign in link expired page
  portal/component-tests/login/_macros/request-new-sign-in-link.component-test.js
  portal/component-tests/login/check-your-email.component-test.js
  portal/component-tests/login/sign-in-link-expired.component-test.js
  portal/server/routes/login.js
  portal/templates/check-your-email.njk
  portal/templates/login/_macros/request-new-sign-in-link.njk
  portal/templates/login/check-your-email.njk
  portal/templates/login/index.njk
  portal/templates/login/sign-in-link-expired.njk
Labels: Type: Feature

#2164 feat(FN-980): update error handling
  dtfs-central-api/src/v1/controllers/portal/utilisation-report-service/previous-reports.controller.js
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/previous-reports/list-previous-reports.spec.js
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/v1/utilisation-report-service/previous-reports.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  portal-api/src/v1/roles/user-has-at-least-one-allowed-role.test.js
  portal/server/controllers/utilisation-report-service/previous-reports/index.js
Labels: Type: Fix

#2193 docs: improve setup instructions in the README
  README.md
Labels: Type: Docs

#2189 feat(DTFS2-6743): send email on login
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/src/constants/email-template-ids.js
  portal-api/src/constants/index.js
  portal-api/src/constants/sign-in-link-expiry-minutes.js
  portal-api/src/v1/email/index.js
  portal-api/src/v1/email/index.test.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
Labels: Type: Feature

#2196 fix(DTFS2): update external api api jest config
  external-api/api-test.jest.config.js
Labels: Type: Fix

#2192 feat(FN-1294): add payment report officer nav items to shared nav bar
  .github/workflows/test.yml
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/restrict-access/restrict-access.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/previous-reports/list-previous-reports.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/service-options/service-options.spec.js
  e2e-tests/portal/cypress/fixtures/constants.js
  e2e-tests/portal/cypress/fixtures/users.js
  gef-ui/component-tests/includes/primary-navigation.component-test.js
  gef-ui/server/constants/roles.js
  gef-ui/templates/includes/primary-navigation.njk
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/common-tests/role-authorisation-tests.js
  portal-api/api-tests/v1/utilisation-report-service/previous-reports.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js
  portal-api/src/v1/roles/roles.js
  portal-api/src/v1/roles/user-has-at-least-one-allowed-role.test.js
  portal-api/src/v1/routes.js
  portal/component-tests/admin/user-edit.component-test.js
  portal/component-tests/partials/primary-navigation.component-test.js
  portal/server/constants/roles.js
  portal/server/controllers/service-options/index.js
  portal/server/helpers/getUserRoles.js
  portal/server/routes/utilisation-report-service/previous-reports/index.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
  portal/templates/_partials/primary-navigation.njk
  portal/templates/admin/user-edit.njk
  portal/templates/utilisation-report-service/_partials/header.njk
  portal/templates/utilisation-report-service/_partials/primary-navigation.njk
  portal/templates/utilisation-report-service/index.njk
  portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/confirm-and-send.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/confirmation.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
  utils/data-migration/constant/roles.js
  utils/mock-data-loader/gef/application.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/portal/roles.js
  utils/mock-data-loader/portal/users.js
Labels: Type: Fintech

#2191 feat(DTFS2-6747): update login token handling
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/constants/index.js
  portal-api/src/constants/login-statuses.js
  portal-api/src/crypto/utils.js
  portal-api/src/crypto/utils.test.js
  portal-api/src/generateApp.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/users/authentication-email.controller.js
  portal-api/src/v1/users/authentication-email.controller.test.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/controller.test.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/passport.js
  portal-api/src/v1/users/routes.js
  portal/api-tests/admin-routes.api-test.js
  portal/api-tests/common-tests/role-validation-api-tests.js
  portal/api-tests/contract/about-routes.api-test.js
  portal/api-tests/contract/bond-routes.api-test.js
  portal/api-tests/contract/contract-routes.api-test.js
  portal/api-tests/contract/loan-routes.api-test.js
  portal/api-tests/dashboard-routes.api-test.js
  portal/api-tests/eligibility-routes.api-test.js
  portal/api-tests/feedback-routes.api-test.js
  portal/api-tests/footer-routes.api-test.js
  portal/api-tests/helpers/login.js
  portal/api-tests/helpers/loginAsRole.js
  portal/api-tests/helpers/validateAuthenticationEmailAsRole.js
  portal/api-tests/login-routes.api-test.js
  portal/api-tests/portal-routes.api-test.js
  portal/api-tests/scheme-type-routes.api-test.js
  portal/api-tests/start-routes.api-test.js
  portal/api-tests/static-routes.api-test.js
  portal/api-tests/user-routes.api-test.js
  portal/component-tests/contract/components/bond-transactions-table.component-test.js
  portal/server/api.js
  portal/server/helpers/requestParams.js
  portal/server/routes/login.js
  utils/mock-data-loader/api.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/user-helper.js
Labels: Type: Security

#2198 feat(DTFS2-6756): update token expiry time
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/crypto/utils.js
  portal-api/src/crypto/utils.test.js
  portal/server/routes/login.js
Labels: Type: Security

#2199 fix(DTFS2-6759): fix token expiry
  portal-api/src/crypto/utils.js
  portal-api/src/crypto/utils.test.js
  portal-api/src/v1/users/login.controller.test.js
  trade-finance-manager-api/src/utils/crypto.util.js
Labels: Type: Security
