Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-07, with the labels that each got.

#1768 fix(SR-3): External API - API key middleware
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/api.js
  azure-functions/number-generator-function/package-lock.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/Dockerfile
  dtfs-central-api/package-lock.json
  external-api/Dockerfile
  external-api/README.md
  external-api/api-tests/api.ts
  external-api/api-tests/v1/api.api-test.ts
  external-api/package-lock.json
  external-api/package.json
  external-api/src/createApp.ts
  external-api/src/middleware/check-api-key/index.api-test.ts
  external-api/src/middleware/check-api-key/index.ts
  external-api/src/middleware/headers/security/index.api-test.ts
  external-api/src/middleware/headers/security/index.ts
  external-api/src/test-mocks/index.ts
  external-api/src/v1/controllers/acbs.controller.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  external-api/src/v1/routes/external-apis.route.ts
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  portal-api/Dockerfile
  portal-api/api-test-common.jest.config.js
  portal-api/api-tests/api.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/external-api/countries.js
  portal-api/src/external-api/currencies.js
  portal-api/src/external-api/industry-sectors.js
  portal-api/src/external-api/number-generator.js
  portal-api/src/external-api/send-email.js
  portal-api/src/v1/gef/controllers/externalApi.controller.js
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
Labels: Type: chore, Type: Security, dependencies

#1769 feat(FN-419): Add ACBS function to Bicep
  infrastructure/arm_templates/function-acbs/application-insights/errors.json
  infrastructure/arm_templates/function-acbs/application-insights/parameters.json
  infrastructure/arm_templates/function-acbs/application-insights/template.json
  infrastructure/arm_templates/function-acbs/errors.json
  infrastructure/arm_templates/function-acbs/parameters.json
  infrastructure/arm_templates/function-acbs/private-endpoint/parameters.json
  infrastructure/arm_templates/function-acbs/private-endpoint/template.json
  infrastructure/arm_templates/function-acbs/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/storage.bicep
Labels: Type: Feature

#1779 feat(FN-422): Add dtfs-central-api webapp
  infrastructure/arm_templates/app-service-plan/parameters.json
  infrastructure/arm_templates/app-service-plan/template.json
  infrastructure/arm_templates/dtfs-central-api/application-insights/parameters.json
  infrastructure/arm_templates/dtfs-central-api/application-insights/template.json
  infrastructure/arm_templates/dtfs-central-api/errors.json
  infrastructure/arm_templates/dtfs-central-api/parameters.json
  infrastructure/arm_templates/dtfs-central-api/private-endpoint/parameters.json
  infrastructure/arm_templates/dtfs-central-api/private-endpoint/template.json
  infrastructure/arm_templates/dtfs-central-api/template.json
  infrastructure/arm_templates/log-analytics-workspace/parameters.json
  infrastructure/arm_templates/log-analytics-workspace/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/cosmosdb.bicep
  infrastructure/resource_group_level/modules/dtfs-central-api.bicep
Labels: Type: Feature

#1778 fix(SR-4): Add x-api-key header authentication to dtfs-central-api
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  docker-compose.dev.yml
  docker-compose.yml
  dtfs-central-api/api-tests/api.js
  dtfs-central-api/api-tests/v1/facilities/facility-delete.api-test.js
  dtfs-central-api/api-tests/v1/mocks/index.js
  dtfs-central-api/api-tests/v1/routes/middleware/headers/checkApiKey.api-test.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/createApp.js
  dtfs-central-api/src/v1/routes/middleware/headers/check-api-key.js
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  e2e-tests/gef/cypress.config.js
  e2e-tests/gef/cypress/support/commands/api.js
  e2e-tests/portal/cypress.config.js
  e2e-tests/portal/cypress/support/central-api/api.js
  e2e-tests/submit-to-trade-finance-manager/cypress.config.js
  e2e-tests/trade-finance-manager/cypress.config.js
  e2e-tests/trade-finance-manager/cypress/support/central-api/api.js
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/api.js
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/mock-data-loader/.env
  utils/mock-data-loader/centralApi.js
  utils/mock-data-loader/gef/api.js
  utils/mock-data-loader/tfm/api.js
Labels: security fix

#1810 fix(apim/tfs): party + deal records
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/mappings/deal/deal-guarantee.js
  azure-functions/acbs-function/mappings/deal/deal-investor.js
Labels: Type: Feature, BREAKING

#1811 fix(api/tfm/facility): dtfs DOF mulesoft to apim migration
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-update-facility-master/index.js
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/deal/deal-guarantee.js
  azure-functions/acbs-function/mappings/deal/deal-investor.js
  azure-functions/acbs-function/mappings/deal/deal.js
  azure-functions/acbs-function/mappings/facility/code-value-transaction.js
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-guarantee.js
  azure-functions/acbs-function/mappings/facility/facility-investor.js
  azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master-amend.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
  azure-functions/acbs-function/mappings/facility/helpers/get-interest-or-fee-rate.js
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  external-api/package-lock.json
  external-api/package.json
  external-api/src/utils/swagger-definitions/acbs.ts
  gef-ui/package-lock.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/package-lock.json
  utils/data-migration/package-lock.json
  utils/mock-data-loader/package-lock.json
Labels: Type: Feature

#1816 feat(FN-686): remove Mulesoft config
  infrastructure/resource_group_level/modules/function-acbs.bicep
Labels: Type: Feature

#1770 fix(SR-1): Add JWT authentication to all endpoints in portal-api
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/api-tests/v1/routes/middleware/headers/check-api-key.api-test.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/dashboard/deals/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/dashboard/facilities/dashboard-table-data.spec.js
  e2e-tests/portal/cypress/support/portal-api/listAllUsers.js
  portal-api/README.md
  portal-api/api-tests/api-test-eligibilityCriteria.js
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/v1/feedback/feedback.api-test.js
  portal-api/api-tests/v1/gef/application-submit.api-test.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/api-tests/wipeDB.js
  portal-api/src/v1/middleware/headers/check-api-key.js
  portal-api/src/v1/routes.js
  portal/server/api.js
  portal/server/routes/feedback.js
  utils/data-migration/api.js
  utils/data-migration/bss-ewcs/migrate-deals.js
  utils/data-migration/bss-ewcs/migrate-users.js
  utils/data-migration/gef/migrate.js
  utils/data-migration/temporary-token-handler.js
  utils/mock-data-loader/.env.sample
  utils/mock-data-loader/api.js
  utils/mock-data-loader/clean-all-tables-gef.js
  utils/mock-data-loader/clean-all-tables.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/portal/users.js
  utils/mock-data-loader/re-insert-mocks.js
  utils/mock-data-loader/tfm/clean-all-tables-tfm.js
  utils/mock-data-loader/tfm/insert-mocks-tfm.js
  utils/mock-data-loader/user-helper.js
Labels: security fix

#1818 fix(SR10): fixed the incomplete string escaping
  portal/server/controllers/dashboard/filters/helpers.js
  portal/server/controllers/dashboard/filters/helpers.test.js
Labels: Type: Fix, Type: Security

#1817 fix(portal-api): Replaced `authRouterAllowXss` with `authRouter`
  portal-api/src/createApp.js
  portal-api/src/v1/controllers/mandatoryCriteria.controller.js
  portal-api/src/v1/routes.js
Labels: Type: Fix

#1830 feat(UI): removed footer telephone number
  gef-ui/templates/includes/footer.njk
  gef-ui/templates/partials/accessibility-statement.njk
  portal/templates/_partials/footer.njk
  portal/templates/accessibility-statement.njk
  trade-finance-manager-ui/templates/_partials/footer.njk
  trade-finance-manager-ui/templates/accessibility-statement.njk
Labels: Type: Feature

#1829 fix(lint): Lint error fixed & variables renamed
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/api-tests/api.js
  dtfs-central-api/api-tests/v1/facilities/facility-delete.api-test.js
  dtfs-central-api/api-tests/v1/routes/middleware/headers/check-api-key.api-test.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/src/v1/controllers/portal/facility/get-facilities.controller.js
  dtfs-central-api/src/v1/routes/middleware/headers/check-api-key.js
  external-api/api-tests/api.ts
  external-api/package-lock.json
  external-api/package.json
  external-api/src/middleware/check-api-key/index.ts
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/services/axios.js
  package-lock.json
  package.json
  portal-api/api-tests/api.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/api.js
  portal-api/src/v1/gef/controllers/files.controller.js
  portal-api/src/v1/middleware/headers/check-api-key.js
  portal/package-lock.json
  portal/server/api.js
  trade-finance-manager-api/api-tests/api.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/middleware/headers/check-api-key.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/api.js
  utils/data-migration/bss-ewcs/migrate-deals.js
  utils/data-migration/package-lock.json
  utils/data-migration/temporary-token-handler.js
  utils/mock-data-loader/.env.sample
  utils/mock-data-loader/api.js
  utils/mock-data-loader/centralApi.js
  utils/mock-data-loader/clean-all-tables.js
  utils/mock-data-loader/gef/api.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/temporary-token-handler-tfm.js
  utils/mock-data-loader/temporary-token-handler.js
  utils/mock-data-loader/tfm/api.js
  utils/mock-data-loader/user-helper.js
Labels: Type: Fix

#1837 fix(apim): apim tfs migration
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility-master-record/index.js
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-loan-id/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
  azure-functions/acbs-function/activity-update-facility-loan/index.js
  azure-functions/acbs-function/mappings/facility/code-value-transaction.js
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-guarantee.js
  azure-functions/acbs-function/mappings/facility/facility-investor.js
  azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
  external-api/src/utils/swagger-definitions/acbs.ts
Labels: Type: Feature, Type: Fix

#1840 fix(tfm): array validation
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-ui/server/controllers/deals/index.js
  trade-finance-manager-ui/server/controllers/facilities/index.js
Labels: Type: Fix

#1844 refactor(code): code simplification
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  external-api/package-lock.json
  gef-ui/package-lock.json
  portal-api/package-lock.json
  portal/package-lock.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
  utils/mock-data-loader/api.js
  utils/mock-data-loader/centralApi.js
  utils/mock-data-loader/gef/api.js
  utils/mock-data-loader/tfm/api.js
Labels: Type: Fix

#1845 feat: migrated the `/customers` APIs to APIM
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  README.md
  azure-functions/README.md
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-amount-difference.js
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  external-api/README.md
  external-api/src/utils/swagger.util.ts
  external-api/src/v1/controllers/currency-exchange-rate.controller.ts
  external-api/src/v1/controllers/exposure-period.controller.ts
  external-api/src/v1/controllers/industry-sectors.controller.ts
  external-api/src/v1/controllers/party-db.controller.ts
  external-api/src/v1/controllers/party-urn.controller.ts
  external-api/src/v1/controllers/premium-schedule.controller.ts
  external-api/src/v1/routes/external-apis.route.ts
  external-api/src/v1/routes/healthcheck.route.ts
  external-api/src/validations/schemas.ts
  trade-finance-manager-api/README.md
  utils/mock-data-loader/README.md
Labels: Type: Feature

#1839 feat(FN-423): portal api to Bicep
  infrastructure/arm_templates/portal-api/parameters.json
  infrastructure/arm_templates/portal-api/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/portal-api.bicep
Labels: Type: Feature

#1850 fix(allowed-extensions): removed zip and msg
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/utils/multer-filter.utils.js
  gef-ui/server/utils/validateFile.js
  gef-ui/server/utils/validateFile.test.js
  gef-ui/templates/partials/manual-inclusion-questionnaire.njk
  gef-ui/templates/partials/upload-supporting-documents.njk
  package-lock.json
  package.json
  portal-api/api-tests/v1/deals/deal-eligibility-documentation.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/gef/controllers/files.controller.js
  portal-api/src/v1/middleware/file-upload.js
  portal/package-lock.json
  portal/package.json
  portal/templates/_macros/eligibility-documentation-file-input.njk
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
Labels: Type: Fix, Type: Security

#1849 feat(apim): facility amendment
  azure-functions/acbs-function/acbs-http/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/number-generator-function/activity-get-number-from-generator/index.js
  azure-functions/number-generator-function/api.js
  azure-functions/number-generator-function/controllers/number-generator.controller.js
  azure-functions/number-generator-function/numbergenerator-http/index.js
  azure-functions/number-generator-function/numbergenerator/index.js
  docker-compose.gha.yml
  dtfs-central-api/api-tests/mocks/gef/gef-facilities.js
  e2e-tests/portal/cypress/e2e/journeys/maker/dashboard/fixtures/facilities.js
  external-api/src/v1/controllers/number-generator.controller.ts
  gef-ui/server/controllers/review-decision/index.test.js
  portal-api/api-tests/fixtures/gef/facilities.js
  portal-api/src/external-api/number-generator.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/__mocks__/mock-cash-contingent-facilities.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-second-submit.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal.js
  trade-finance-manager-api/src/v1/__mocks__/mock-facilities.js
  trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/number-generator.controller.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.api-test.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.js
  trade-finance-manager-ui/server/test-mocks/amendment-test-mocks.js
Labels: Type: Amendments, Type: Fix, Type: Security

#1848 fix(SR-5): protect `external-api` from SSRF
  external-api/api-tests/api.ts
  external-api/api-tests/v1/acbs-industry-sectors.api-test.ts
  external-api/api-tests/v1/acbs.api-test.ts
  external-api/api-tests/v1/companies-house.api-test.ts
  external-api/api-tests/v1/countries.api-test.ts
  external-api/api-tests/v1/currencies.api-test.ts
  external-api/api-tests/v1/currency-exchange-rate.api-test.ts
  external-api/api-tests/v1/eStore.api-test.ts
  external-api/api-tests/v1/email.api-test.ts
  external-api/api-tests/v1/exposure-period.api-test.ts
  external-api/api-tests/v1/healthcheck.api-test.ts
  external-api/api-tests/v1/industry-sectors.api-test.ts
  external-api/api-tests/v1/number-generator.api-test.ts
  external-api/api-tests/v1/ordnance-survey.api-test.ts
  external-api/api-tests/v1/party-db.api-test.ts
  external-api/api-tests/v1/party-urn.api-test.ts
  external-api/api-tests/v1/premium-schedule.api-test.ts
  external-api/package-lock.json
  external-api/package.json
  external-api/src/constants/regex.constants.ts
  external-api/src/utils/inputValidations.ts
  external-api/src/v1/controllers/companies-house.controller.ts
  external-api/src/v1/controllers/currency-exchange-rate.controller.ts
  external-api/src/v1/controllers/exposure-period.controller.ts
  external-api/src/v1/controllers/industry-sectors.controller.ts
  external-api/src/v1/controllers/ordnance-survey.controller.ts
  external-api/src/v1/controllers/party-db.controller.ts
  external-api/src/v1/controllers/party-urn.controller.ts
  external-api/src/v1/controllers/premium-schedule.controller.ts
  external-api/src/validations/index.ts
  gef-ui/server/controllers/companies-house/index.js
  gef-ui/server/controllers/exporters-address/index.js
  gef-ui/server/utils/helpers.js
  portal-api/src/v1/gef/controllers/externalApi.controller.js
  portal-api/src/v1/gef/controllers/validation/external.js
  utils/mock-data-loader/api.js
Labels: security fix

#1855 security(SR-5): Add SSRF protection to portal
  e2e-tests/portal/cypress/e2e/journeys/maker/about-supply-contract/fill-in-about-supply-contract-validation.spec.js
  portal/package-lock.json
  portal/package.json
  portal/server/api-ssrf.test.js
  portal/server/api.js
  portal/server/companies-house-api.js
  portal/server/validation/validate-ids.js
  portal/server/validation/validate-ids.test.js
Labels: security fix

#1860 fix(SR-12): Stop exposing full error messages and stack traces
  dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.js
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.js
  portal/server/api.js
  trade-finance-manager-api/src/v1/api.js
Labels: Type: Security

#1851 Feat/FN-737/update env vars
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/external-api.bicep
  infrastructure/resource_group_level/modules/portal-api.bicep
  infrastructure/resource_group_level/modules/route-tables.bicep
  infrastructure/resource_group_level/modules/trade-finance-manager-api.bicep
Labels: Type: Feature

#1864 fix(iac): environment variables for number generator
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  dtfs-central-api/package-lock.json
  external-api/package-lock.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  portal-api/package-lock.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
Labels: Type: Fix

#1824 feat: migrated eStore to APIM
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .husky/pre-commit
  .lintstagedrc.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  external-api/api-tests/v1/eStore.api-test.ts
  external-api/package-lock.json
  external-api/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreSiteCreationJob.cron.ts
  external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  external-api/src/interfaces/eStore.interface.ts
  external-api/src/utils/swagger-definitions/estore.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  external-api/src/v1/controllers/estore/eStoreApi.ts
  external-api/src/validations/schemas.ts
  portal-api/src/drivers/fileshare.js
  portal-api/src/v1/gef/controllers/files.controller.js
  trade-finance-manager-api/src/v1/mappings/map-create-estore.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.js
Labels: Type: Feature

#1854 Feat(FN-425) Add portal-ui to Bicep
  infrastructure/arm_templates/portal-ui/errors.json
  infrastructure/arm_templates/portal-ui/parameters.json
  infrastructure/arm_templates/portal-ui/private-endpoint/parameters.json
  infrastructure/arm_templates/portal-ui/private-endpoint/template.json
  infrastructure/arm_templates/portal-ui/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/portal-ui.bicep
  infrastructure/resource_group_level/modules/redis.bicep
Labels: Type: Feature

#1856 Feat(FN-426): Add gef-ui to bicep
  infrastructure/arm_templates/gef-ui/errors.json
  infrastructure/arm_templates/gef-ui/parameters.json
  infrastructure/arm_templates/gef-ui/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/gef-ui.bicep
Labels: Type: Feature

#1866 fix(portal-api-exception-text): Portal-API - error return
  .commitlintrc.json
  .husky/pre-commit
  .lintstagedrc.json
  package-lock.json
  package.json
  portal-api/src/v1/api.js
  portal-api/src/v1/gef/controllers/files.controller.js
Labels: security fix

#1863 Feat(FN-427): application gateway portal
  infrastructure/arm_templates/application-gateway-portal/parameters.json
  infrastructure/arm_templates/application-gateway-portal/template.json
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/application-gateway-portal.bicep
  infrastructure/resource_group_level/modules/gw-nsg.bicep
  infrastructure/resource_group_level/modules/tfs-ip.bicep
Labels: Type: Feature

#1870 fix(tfm-api-email): JOI validation for feedback email
  trade-finance-manager-api/src/v1/validation/feedback-rules/email-address.js
Labels: security fix

#1869 DRAFT: security: Fix critical security issues
  portal-api/src/v1/gef/controllers/validation/application.js
Labels: Status: In Progress

#1871 fix(External-API-console): Correct format for console.info and errors
  external-api/src/cronJobs/eStoreCronJobManager.ts
  external-api/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreSiteCreationJob.cron.ts
  external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  external-api/src/v1/controllers/acbs.controller.ts
  external-api/src/v1/controllers/companies-house.controller.ts
  external-api/src/v1/controllers/currency-exchange-rate.controller.ts
  external-api/src/v1/controllers/email.controller.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  external-api/src/v1/controllers/exposure-period.controller.ts
  external-api/src/v1/controllers/industry-sectors.controller.ts
  external-api/src/v1/controllers/ordnance-survey.controller.ts
  external-api/src/v1/controllers/party-db.controller.ts
  external-api/src/v1/controllers/party-urn.controller.ts
  external-api/src/v1/controllers/premium-schedule.controller.ts
Labels: security fix

#1875 fix: fixed forward slash for file location
  trade-finance-manager-api/src/v1/mappings/map-create-estore.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.js
Labels: Type: Fix

#1873 security: remove vulnerable dicer dependency in apollo-server-testing
  trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js
  trade-finance-manager-api/graphql-query-tests/get-team-members.api-test.js
  trade-finance-manager-api/graphql-query-tests/graphql-authentication.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-activity-comment.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-credit-rating.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-facilities.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-facility-risk-profile.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-lead-underwriter.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-loss-given-default.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-parties.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-probability-of-default.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-task.api-test.js
  trade-finance-manager-api/graphql-query-tests/mutation-update-underwriting-managers-decision.api-test.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
Labels: Type: Fix

#1886 fix(env): fixed environment variables
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/healthcheck.js
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/controllers/supporting-information/supporting-documents/index.js
  gef-ui/server/index.js
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/controllers/feedback.controller.js
  portal-api/src/v1/gef/controllers/files.controller.js
  portal/package-lock.json
  portal/package.json
  portal/server/index.js
  portal/server/routes/contract/eligibility/index.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-tfm-tasks.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/index.js
  utils/data-migration/package-lock.json
Labels: Type: Fix

#1880 fix: updated the timer settings for eStore
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  external-api/src/cronJobs/eStoreSiteCreationJob.cron.ts
  external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
Labels: Type: Fix

#1887 fix(commit): git pre-commit hook
  .commitlintrc.json
  .lintstagedrc.json
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  commitlint.config.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  e2e-tests/portal/cypress/e2e/journeys/maker/facilities/AIN-facility-cover-start-date-validation-past-3-months.spec.js
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package.json
  utils/mock-data-loader/package.json
Labels: Type: chore
