Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-12, with the labels that each got.

#2356 fix(DTFS2-6822): fix linting in typescript services; remove typescript support from webpack builds
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/azure-env/index.ts
  dtfs-central-api/src/index.ts
  external-api/.eslintrc.js
  external-api/package-lock.json
  external-api/package.json
  gef-ui/.eslintrc.js
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/scripts/main.js
  gef-ui/server/azure-env/index.ts
  gef-ui/server/index.ts
  gef-ui/webpack.common.config.js
  package-lock.json
  package.json
  portal-api/.eslintrc.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/azure-env/index.ts
  portal-api/src/index.ts
  portal-api/tsconfig.eslint.json
  portal/.eslintrc.js
  portal/package-lock.json
  portal/package.json
  portal/scripts/main.js
  portal/server/azure-env/index.ts
  portal/server/index.ts
  portal/webpack.common.config.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/azure-env/index.ts
  trade-finance-manager-api/src/index.ts
  trade-finance-manager-api/tsconfig.eslint.json
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/scripts/main.js
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: Fix

#2367 fix(FN-1683): correct portal previous reports header
  portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
Labels: Type: Fintech

#2337 feat(FN-1041): add report period details to TFM 'Bank reports' screen
  .github/workflows/lint.yml
  .github/workflows/test.yml
  portal-api/src/external-api/bank-holidays.js
  portal-api/src/external-api/types/bank-holidays.d.ts
  portal-api/src/scheduler/jobs/helpers/utilisation-report-helpers.test.js
  portal/component-tests/utilisation-report-service/previous-reports.component-test.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/v1/bank-holidays/bank-holidays.api-test.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/types/bank-holidays.d.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/__mocks__/mock-bank-holidays.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/bank-holidays/get-bank-holidays.controller.js
  trade-finance-manager-api/src/v1/controllers/bank-holidays/get-bank-holidays.controller.test.js
  trade-finance-manager-api/src/v1/controllers/bank-holidays/index.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/api.test.js
  trade-finance-manager-ui/server/constants/bank-holiday-region.js
  trade-finance-manager-ui/server/constants/index.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.js
  trade-finance-manager-ui/server/helpers/date.js
  trade-finance-manager-ui/server/helpers/date.test.js
  trade-finance-manager-ui/server/routes/index.js
  trade-finance-manager-ui/server/routes/index.test.js
  trade-finance-manager-ui/server/routes/utilisation-reports/index.js
  trade-finance-manager-ui/server/services/utilisation-report-service.js
  trade-finance-manager-ui/server/services/utilisation-report-service.test.js
  trade-finance-manager-ui/server/test-mocks/mock-bank-holidays.js
  trade-finance-manager-ui/templates/_partials/primary-navigation.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
Labels: Type: Fintech

#2370 fix(FN-1683): fix component test
  portal/component-tests/utilisation-report-service/previous-reports.component-test.js
Labels: Type: Fintech

#2369 feat(FN-1501): add new collections and fileshare to bicep infra
  infrastructure/resource_group_level/modules/cosmosdb.bicep
  infrastructure/resource_group_level/modules/storage.bicep
Labels: Type: Feature, Type: Fintech

#2421 fix(FN-1686): update error copy for large file
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
Labels: Type: Fintech

#2424 fix: fix about-facility UI test failing after 5/12/2023
  gef-ui/server/controllers/about-facility/index.test.js
Labels: Type: Fix, Test

#2355 fix(DTFS-6464): use summary lists on underwriting page
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/pricing-and-risk-risk-managers.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/pricing-and-risk.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/underwriting-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/users/PIM_user.spec.js
  e2e-tests/tfm/cypress/e2e/pages/underwriting/pricingAndRiskPage.js
  e2e-tests/tfm/cypress/e2e/pages/underwriting/underwritingPage.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN-deal-creates-default-credit-rating-in-tfm/submit-AIN-deal-creates-default-credit-rating-in-tfm.spec.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/exporter-table.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/exporter-table.njk
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/section-exporter.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.njk
Labels: Type: Fix

#2417 fix(DTFS2-6463): add 'Task' and 'Status' headings to deal tasks tables
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.component-test.js
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.component-test.js
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk
Labels: Type: Fix

#2430 chore: swap feature deployments to TFM 5 release
  .github/workflows/feature_deploy.yml
Labels: Type: Fintech

#2280 fix(DTFS2-6522): Accessibility - Description list
  gef-ui/public/css/styles.css
  gef-ui/styles/footer.scss
  gef-ui/templates/includes/footer.njk
  portal/public/css/styles.css
  portal/styles/footer.scss
  portal/templates/_partials/footer.njk
  service-unavailable/index.html
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/styles/case-summary.scss
  trade-finance-manager-ui/styles/footer.scss
  trade-finance-manager-ui/styles/list.scss
  trade-finance-manager-ui/styles/styles.scss
  trade-finance-manager-ui/templates/_partials/footer.njk
  trade-finance-manager-ui/templates/case/_macros/case-summary-ndb.njk
  trade-finance-manager-ui/templates/case/_macros/case-summary.njk
  trade-finance-manager-ui/templates/case/_macros/ukef-deal-stage.njk
  trade-finance-manager-ui/templates/case/amendments/_macros/amendment-ukef-decision-summary.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-answers.njk
  trade-finance-manager-ui/templates/case/deal/deal.njk
  trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk
  trade-finance-manager-ui/templates/case/facility/_macros/facility_details.njk
  trade-finance-manager-ui/templates/case/facility/_macros/premium_schedule.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-key-value-array-grid-row.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-key-value-grid-row.njk
Labels: Type: chore, Type: Fix

#2422 fix(DTFS-6466): accessibility - added text for screen readers to make input field prefix/suffix known
  trade-finance-manager-ui/component-tests/case/underwriting/loss-given-default.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/probability-of-default.component-test.js
  trade-finance-manager-ui/templates/case/amendments/amendment-facility-value.njk
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/loss-given-default.njk
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/probability-of-default.njk
Labels: Type: chore, Type: Fix

#2432 fix(DTFS2-6786): added EC21 to GEF-UI model
  gef-ui/server/models/application.js
  portal-api/README.md
  portal-api/api-tests/fixtures/gef/coverTerms.js
  utils/mock-data-loader/bss/deals/1.js
  utils/mock-data-loader/bss/deals/10.js
  utils/mock-data-loader/bss/deals/11.js
  utils/mock-data-loader/bss/deals/2.js
  utils/mock-data-loader/bss/deals/3.js
  utils/mock-data-loader/bss/deals/4.js
  utils/mock-data-loader/bss/deals/5.js
  utils/mock-data-loader/bss/deals/6.js
  utils/mock-data-loader/bss/deals/7.js
  utils/mock-data-loader/bss/deals/8.js
  utils/mock-data-loader/bss/deals/9.js
Labels: Type: Bug

#2435 fix(dtfs2-6864): Remove `azure-env` directory
  dtfs-central-api/src/azure-env/index.ts
  dtfs-central-api/src/index.ts
  gef-ui/server/azure-env/index.ts
  gef-ui/server/index.ts
  portal-api/src/azure-env/index.ts
  portal-api/src/index.ts
  portal/server/azure-env/index.ts
  portal/server/index.ts
  trade-finance-manager-api/src/azure-env/index.ts
  trade-finance-manager-api/src/index.ts
  trade-finance-manager-ui/server/azure-env/index.js
  trade-finance-manager-ui/server/generateApp.js
Labels: Type: Fix

#2433 feat(FN-1620): Update csv validation for fees paid currency
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-September_2023.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-next_week.xlsx
  portal/server/constants/utilisation-report-headers.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-monthly-fees-paid-currency-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-monthly-fees-paid-currency-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-currency-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-currency-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
Labels: Type: Fintech

#2437 feat(FN-1404): fix tfm teams
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-users.controller.js
  e2e-tests/e2e-fixtures/tfm-users.fixture.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-tfm-user.js
  e2e-tests/tfm/cypress/e2e/journeys/header/header.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/login/login-with-role.spec.js
  e2e-tests/ukef/cypress/fixtures/tfm-users.js
  trade-finance-manager-ui/server/constants/teamIds.js
  trade-finance-manager-ui/server/controllers/case/activity/index.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentRequestDate.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/bankDecision.controller.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/underwriterManagerDecision.test.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/facility-risk-profile/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/loss-given-default/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.test.js
  trade-finance-manager-ui/server/controllers/home/index.test.js
  trade-finance-manager-ui/server/controllers/login/index.test.js
  trade-finance-manager-ui/server/helpers/user.js
  trade-finance-manager-ui/server/helpers/user.test.js
  trade-finance-manager-ui/server/middleware/validateUserTeam/index.js
  trade-finance-manager-ui/server/test-mocks/amendment-test-mocks.js
  trade-finance-manager-ui/server/types/team-id.d.ts
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.component-test.js
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk
  utils/mock-data-loader/tfm/mocks/users.js
Labels: Type: Fintech

#2439 feat(FN-1042): add utilisation report due date env var to TFM UI infra
  infrastructure/resource_group_level/main.bicep
Labels: Type: Fintech

#2420 feat(FN-1501): Update deployment scripts
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.yml
Labels: Type: Fintech

#2444 feat(DTFS2-6863): added table headers for amendment tasks
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
Labels: Type: Feature, Type: Fix

#2426 fix(DTFS2-6538): added invisible text to 'Change' links
  trade-finance-manager-ui/templates/case/activity/activity-comment.njk
  trade-finance-manager-ui/templates/case/amendments/_macros/summary-table.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-add-banks-decision-check-answers.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-answers.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments-summary.njk
  trade-finance-manager-ui/templates/case/parties/summary/bond.njk
  trade-finance-manager-ui/templates/case/parties/summary/party.njk
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/exporter-table.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/exporter-table.njk
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.njk
Labels: Type: chore, Type: Fix

#2448 chore(azure-cli): update `azure-cli` to v1.0.9.
  .github/workflows/development_deploy.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/dns.yml
  .github/workflows/dns_tfm.yml
  .github/workflows/infrastructure.yml
  .github/workflows/production_deploy.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_deploy.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  cspell.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/mock-data-loader/package-lock.json
Labels: Type: chore

#2450 fix: fix all lint errors
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/drivers/db-client.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller.ts
  e2e-tests/e2e-fixtures/tfm-users.fixture.js
  e2e-tests/tfm/cypress/fixtures/users.js
  external-api/.eslintrc.js
  external-api/package.json
  portal-api/.eslintrc.js
  portal/.eslintrc.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/types/team.d.ts
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/package.json
  utils/mock-data-loader/package.json
Labels: Type: Fix, Type: Fintech

#2442 feat(FN-1043): add all required data to TFM 'Bank reports' table
  dtfs-central-api/api-tests/mocks/azure-file-info.ts
  dtfs-central-api/api-tests/mocks/utilisation-data.ts
  dtfs-central-api/api-tests/mocks/utilisation-reports.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report.api-test.js
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/api-tests/v1/utils/string.api-test.js
  dtfs-central-api/src/constants/db-collections.ts
  dtfs-central-api/src/constants/index.js
  dtfs-central-api/src/drivers/db-client.js
  dtfs-central-api/src/drivers/db-client.ts
  dtfs-central-api/src/helpers/mongodb.test.ts
  dtfs-central-api/src/helpers/mongodb.ts
  dtfs-central-api/src/helpers/validation.test.ts
  dtfs-central-api/src/helpers/validation.ts
  dtfs-central-api/src/services/repositories/utilisation-data-repo.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.test.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.js
  dtfs-central-api/src/types/azure-file-info.d.ts
  dtfs-central-api/src/types/date.d.ts
  dtfs-central-api/src/types/db-models/db-collection-name.d.ts
  dtfs-central-api/src/types/db-models/db-model.d.ts
  dtfs-central-api/src/types/db-models/tfm-users.d.ts
  dtfs-central-api/src/types/db-models/utilisation-data.d.ts
  dtfs-central-api/src/types/db-models/utilisation-reports.d.ts
  dtfs-central-api/src/types/tfm/tfm-session-user.d.ts
  dtfs-central-api/src/types/utilisation-reports.d.ts
  dtfs-central-api/src/utils/date.js
  dtfs-central-api/src/utils/date.test.js
  dtfs-central-api/src/utils/string.js
  dtfs-central-api/src/utils/string.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller.test.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/upload-utilisation-report.controller.js
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  portal-api/test-helpers/mock-utilisation-reports.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.js
  trade-finance-manager-ui/server/test-mocks/mock-banks.js
  trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.js
  trade-finance-manager-ui/server/types/utilisation-reports.d.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
Labels: Type: Fintech

#2447 fix(DTFS2-6876): fix order dependency in Portal login journey E2E tests
  e2e-tests/portal/cypress/e2e/journeys/login/login.spec.js
Labels: Type: Bug

#2451 chore(merge): fix tests on main-stbr-tfm-5
  dtfs-central-api/api-test.jest.config.js
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report.api-test.js
  dtfs-central-api/src/utils/string.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller.ts
  e2e-tests/tfm/cypress/e2e/pages/facilityPage.js
  external-api/api-tests/v1/bank-holidays.api-test.ts
Labels: Type: Fintech

#2454 fix: replace connection strings with environment variables
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-calculated-variables.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-no-calculated-variables.bicep
Labels: Type: Feature, Type: Fintech

#2429 fix(DTFS2-6531): accessibility - added text for screen readers which w…
  trade-finance-manager-ui/component-tests/case/parties/_macros/bond-beneficiary-facilities-table.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/bond-issuer-facilities-table.component-test.js
  trade-finance-manager-ui/component-tests/case/task.component-test.js
  trade-finance-manager-ui/templates/_macros/facility-link.component-test.js
  trade-finance-manager-ui/templates/_macros/facility-link.njk
  trade-finance-manager-ui/templates/case/deal/_macros/facilities-table.component-test.js
  trade-finance-manager-ui/templates/case/deal/_macros/facilities-table.njk
  trade-finance-manager-ui/templates/case/tasks/task.component-test.js
  trade-finance-manager-ui/templates/case/tasks/task.njk
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.component-test.js
  trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.njk
  trade-finance-manager-ui/templates/deals/_macros/deals-table.component-test.js
  trade-finance-manager-ui/templates/deals/_macros/deals-table.njk
  trade-finance-manager-ui/templates/facilities/facilities.njk
Labels: Type: Fix, chore

#2357 feat(DTFS2-5659): added component tests for cookies, accessibility pages
  trade-finance-manager-ui/component-tests/accessibility/accessibility.component-test.js
  trade-finance-manager-ui/component-tests/cookies/cookies.component-test.js
  trade-finance-manager-ui/component-tests/user/change-password.component-test.js
  trade-finance-manager-ui/templates/_partials/cookies.njk
  trade-finance-manager-ui/templates/accessibility-statement.njk
  trade-finance-manager-ui/templates/cookies.njk
  trade-finance-manager-ui/templates/user/change-password.njk
Labels: Type: Feature, Test

#2460 Feat/dtfs2 5659/extend component tests tfm UI new
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk/edit-facility-risk-profile/_macros/section-exporter/exporter-table.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk/edit-facility-risk-profile/_macros/section-exporter/section-exporter.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk/edit-facility-risk-profile/_macros/section-facilities/facility-pricing-risk-table.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk/edit-facility-risk-profile/_macros/section-facilities/section-facilities.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk/edit-facility-risk-profile/edit-facility-risk-profile.component-test.js
  trade-finance-manager-ui/component-tests/case/underwriting/pricing-and-risk/edit-facility-risk-profile/edit-facility-risk-profile/_macros/legend-html.component-test.js
  trade-finance-manager-ui/component-tests/facilities/facilities-table-search-form.component-test.js
Labels: Type: Feature, Test

#2459 feat(DTFS2-6897): added style to publish.yml
  .github/workflows/publish.yml
Labels: Type: Feature

#2462 feat(FN-1483): add AZURE env vars to TFM API infra
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-calculated-variables.bicep
Labels: Type: Fintech

#2463 feat(FN-1483): add AZURE env vars to TFM API disaster recovery scripts
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
Labels: Type: Fintech

#2464 fix(publish): added missing comma
  .github/workflows/publish.yml
Labels: Type: Fix

#2455 feat(FN-1685): add accrual currency and fx to spreadsheet
  dtfs-central-api/src/constants/utilisationReportHeaders.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.test.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-data-validator.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-data-validator.test.js
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-report-validator.js
  portal/server/constants/utilisation-report-headers.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-currency-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-currency-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-exchange-rate-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js
Labels: Type: Fintech

#2465 fix(gha): `release-please` v4 upgrade
  .github/workflows/publish.yml
  .github/workflows/release.json
  README.md
Labels: Type: Docs, Type: Fix

#2483 fix(gha): publish
  .github/workflows/publish.yml
  .github/workflows/release.json
  .release-please-manifest.json
  release-please-config.json
Labels: Type: Fix

#2449 fix(DTFS2-6672): check user authorisation when updating details
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
Labels: Type: Fix

#2466 feat(FN-692): infrastructure improvements
  .github/workflows/bicep_deploy.yml
  .github/workflows/bicep_lint.yml
  .github/workflows/feature_deploy.yml
  cspell.json
Labels: Type: Fintech

#2486 feat(FN-1261): reorder to authorise healthcheck
  dtfs-central-api/src/generateApp.js
  external-api/src/generateApp.ts
Labels: Type: Fintech

#2484 chore(main): release 1.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2446 fix(DTFS2-6472): improve /deals page sorting
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-buyer.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-exporter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-product.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-receivedDate-default-sort.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-stage.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-ukefDealId.spec.js
  e2e-tests/tfm/cypress/e2e/pages/dealsPage.js
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table-heading.component-test.js
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/deals/_macros/deals-table-heading.njk
  trade-finance-manager-ui/templates/deals/_macros/deals-table.njk
Labels: Type: Fix
