Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-05, with the labels that each got.

#1629 chore: updated NodeJS to `v20.0.0-alpine3.17`
  dtfs-central-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reference-data-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: Type: chore, Type: Fix, Type: Security

#1632 fix(DTFS2-6419): `/currency/exchange` endpoint migration
  .github/workflows/development_infrastructure.yml
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/.env.sample
  dtfs-central-api/package-lock.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/.env.sample
  reference-data-proxy/README.md
  reference-data-proxy/api-tests/v1/currency-exchange-rate.api-test.ts
  reference-data-proxy/docker-compose.yml
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/v1/controllers/currency-exchange-rate.controller.ts
  reference-data-proxy/src/v1/controllers/exposure-period.controller.ts
  reference-data-proxy/src/v1/controllers/industry-sectors.controller.ts
  reference-data-proxy/src/validations/schemas.ts
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
Labels: Type: Docs, Type: Fix

#1634 feat(DTFS2-6419): MDM APIM migration
  .github/workflows/development_infrastructure.yml
  .github/workflows/pr_api_tests.yml
  .github/workflows/pr_e2e_tests.yml
  .github/workflows/pr_integration_tests.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/README.md
  azure-functions/acbs-function/.env.sample
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/api-ukef-mdm-ea.js
  azure-functions/acbs-function/apim-mdm.js
  azure-functions/acbs-function/docker-compose.yml
  azure-functions/acbs-function/mappings/deal/helpers/get-industry-classification.js
  azure-functions/number-generator-function/.env.sample
  azure-functions/number-generator-function/README.md
  azure-functions/number-generator-function/activity-get-number-from-generator/index.js
  azure-functions/number-generator-function/api.js
  azure-functions/number-generator-function/controllers/number-generator.controller.js
  azure-functions/number-generator-function/docker-compose.yml
  azure-functions/number-generator-function/numbergenerator-http/index.js
  azure-functions/number-generator-function/numbergenerator/index.js
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/.env.sample
  dtfs-central-api/package-lock.json
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review/dealThatJustNeedsConversionDate.json
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review/dealWithIncompleteAbout.json
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review/dealWithIncompleteEligibility.json
  e2e-tests/portal/cypress/e2e/pages/contract/contract-confirmSubmission.js
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/submit-deal-with-non-gbp-facilities/test-data/dealThatJustNeedsDates.json
  e2e-tests/submit-to-trade-finance-manager/cypress/e2e/journeys/portal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued/test-data/dealThatJustNeedsConversionDate.json
  e2e-tests/trade-finance-manager/cypress/fixtures/deal-AIN.js
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  portal-api/package-lock.json
  portal/package-lock.json
  portal/package.json
  reference-data-proxy/.env.sample
  reference-data-proxy/api-tests/v1/exposure-period.api-test.ts
  reference-data-proxy/package-lock.json
  reference-data-proxy/package.json
  reference-data-proxy/src/v1/controllers/currency-exchange-rate.controller.ts
  reference-data-proxy/src/v1/controllers/exposure-period.controller.ts
  reference-data-proxy/src/v1/controllers/industry-sectors.controller.ts
  reference-data-proxy/src/v1/controllers/premium-schedule.controller.ts
  reference-data-proxy/src/validations/schemas.ts
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
Labels: Type: Docs, Type: Feature, dependencies

#1637 fix(npm): updated deps + new services
  azure-functions/acbs-function/package-lock.json
  dtfs-central-api/package-lock.json
  gef-ui/package-lock.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal/package-lock.json
  reference-data-proxy/package-lock.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-ui/package-lock.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: dependencies

#1641 feat(DTFS2-6439): countries disabled
  portal-api/src/reference-data/__mocks__/countries.js
  reference-data-proxy/src/reference-data/countries.ts
Labels: Type: chore

#1638 fix(portal-api): azure webapp healthcheck
  portal-api/src/createApp.js
Labels: Type: Fix

#1642 fix: reverted redis changes
  .github/workflows/pr_e2e_tests.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/server/index.js
  gef-ui/server/session-configuration/index.js
  portal/package-lock.json
  portal/package.json
  portal/server/index.js
  portal/server/session-configuration/index.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/session-configuration/index.js
Labels: Type: Bug

#1644 fix(currency-exchange-rate): Currency exchange rate calculation
  reference-data-proxy/api-tests/v1/currency-exchange-rate.api-test.ts
  reference-data-proxy/src/utils/swagger-definitions/currency-exchange-rate.ts
  reference-data-proxy/src/v1/controllers/currency-exchange-rate.controller.ts
  reference-data-proxy/src/v1/routes/external-apis.route.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/controllers/convert-facility-currency.js
  trade-finance-manager-api/src/v1/controllers/deal.convert-deal-currencies.js
  trade-finance-manager-ui/templates/case/facility/_macros/premium_schedule.njk
Labels: Type: Bug, Type: Docs, Type: Fix

#1648 fix(acbs): exposure period calculation
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
Labels: Type: Fix
