Repository UK-Export-Finance/dtfs2, pull requests merged in 2023-09, with the labels that each got.

#1987 feat(DTFS2-6566): added virgin money bank to the portal
  portal/templates/_partials/before-you-start.njk
Labels: Type: Feature

#1970 feat(FN-939):use parameter sets
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/cosmosdb.bicep
Labels: Type: Feature

#1977 fix(mongo): Remove MongoDB URI with credentials
  .github/workflows/test.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
Labels: security fix

#1976 feat(FN-742): Set values from GitHub
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/privatelink-file-core-windows-net.bicep
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/external-api.bicep
  infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
Labels: Type: Feature

#1991 fix: fixing json format error in github action publish.yml
  .github/workflows/publish.yml
Labels: Type: Feature

#1979 fix: fixed the `siteName` not updating in tfm
  external-api/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreSiteCreationJob.cron.ts
  external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
Labels: Type: Fix

#2045 fix(DTFS2-6681): extract reset password payload
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
Labels: security fix

#1968 feat(DTFS2-6623): allow read only role assignment in portal UI
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/restrict-access/restrict-access.spec.js
  e2e-tests/portal/cypress/fixtures/constants.js
  e2e-tests/portal/cypress/fixtures/users.js
  portal/component-tests/admin/user-edit.component-test.js
  portal/component-tests/assertions.js
  portal/templates/admin/user-edit.njk
  utils/mock-data-loader/portal/users.js
Labels: Type: Feature

#2046 feat(DTFS2-6556): rename bank
  azure-functions/acbs-function/package-lock.json
  azure-functions/number-generator-function/package-lock.json
  cspell.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.js
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.js
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  portal/templates/_partials/before-you-start.njk
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/mappings/map-deals.api-test.js
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/mappings/map-deal.js
  trade-finance-manager-api/src/v1/mappings/map-deals.js
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/amendments/bankDecision.controller.js
  utils/data-migration/package-lock.json
Labels: Type: Fix

#1971 feat(DTFS2-6626): add read only role to portal api
  e2e-tests/portal/cypress/e2e/journeys/admin/restrict-access/restrict-access.spec.js
  portal-api/src/role-validator.js
  portal-api/src/v1/controllers/deal-status/user-can-submit-deal.js
  portal-api/src/v1/facility-issuance/index.js
  portal-api/src/v1/gef/controllers/files.controller.js
  portal-api/src/v1/gef/routes.js
  portal-api/src/v1/roles/roles.js
  portal-api/src/v1/roles/user-has-sufficient-role.js
  portal-api/src/v1/roles/user-has-sufficient-role.test.js
  portal-api/src/v1/roles/validate-user-has-sufficient-role.js
  portal-api/src/v1/roles/validate-user-has-sufficient-role.test.js
  portal-api/src/v1/routes.js
Labels: Type: Feature

#2048 feat(FN-712):commonise webapps fix
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/external-api.bicep
  infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
Labels: Type: Feature

#2054 fix(ukefid): UKEF ID validation
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/constants/deal.js
  external-api/src/constants/number-generator.constant.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
Labels: Type: Fix

#1980 feat(DTFS2-6625): add read-only limitation on Portal UI routes
  portal/api-tests/admin-routes.api-test.js
  portal/api-tests/common-tests/role-validation-api-tests.js
  portal/api-tests/contract/about-routes.api-test.js
  portal/api-tests/contract/bond-routes.api-test.js
  portal/api-tests/contract/contract-routes.api-test.js
  portal/api-tests/contract/loan-routes.api-test.js
  portal/api-tests/create-api.js
  portal/api-tests/dashboard-routes.api-test.js
  portal/api-tests/eligibility-routes.api-test.js
  portal/api-tests/feedback-routes.api-test.js
  portal/api-tests/footer-routes.api-test.js
  portal/api-tests/helpers/mockProvide.js
  portal/api-tests/login-routes.api-test.js
  portal/api-tests/portal-routes.api-test.js
  portal/api-tests/scheme-type-routes.api-test.js
  portal/api-tests/start-routes.api-test.js
  portal/api-tests/static-routes.api-test.js
  portal/api-tests/user-routes.api-test.js
  portal/server/constants/index.js
  portal/server/constants/roles.js
  portal/server/routes/admin/index.js
  portal/server/routes/admin/users.js
  portal/server/routes/contract/about/buyerPage.js
  portal/server/routes/contract/about/financialPage.js
  portal/server/routes/contract/about/previewPage.js
  portal/server/routes/contract/about/supplierPage.js
  portal/server/routes/contract/bond/index.js
  portal/server/routes/contract/canIssueOrEditIssueFacility.test.js
  portal/server/routes/contract/dealWithCanIssueOrEditIssueFacilityFlags.test.js
  portal/server/routes/contract/eligibility/eligibilityCheckYourAnswersValidationErrors/index.js
  portal/server/routes/contract/eligibility/eligibilityCheckYourAnswersValidationErrors/index.test.js
  portal/server/routes/contract/eligibility/index.js
  portal/server/routes/contract/index.js
  portal/server/routes/contract/isDealEditable.test.js
  portal/server/routes/contract/loan/index.js
  portal/server/routes/contract/userCanSubmitDeal.test.js
  portal/server/routes/middleware/isMaker/index.js
  portal/server/routes/middleware/isMaker/index.test.js
  portal/server/routes/middleware/validateBank/index.js
  portal/server/routes/middleware/validateRole/index.js
  portal/server/routes/reports.route.js
  portal/server/routes/schemeType/index.js
  portal/server/routes/schemeType/index.test.js
  portal/server/routes/start.js
Labels: Type: Feature, security fix

#2051 feat(DTFS2-6647): forbid read only users from having another role
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/v1/roles/roles.js
  portal-api/src/v1/users/validation/index.js
  portal-api/src/v1/users/validation/rules/current-password-must-match.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-8-characters.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-lowercase.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-number.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-special-character.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-uppercase.test.js
  portal-api/src/v1/users/validation/rules/passwords-cannot-be-reused.test.js
  portal-api/src/v1/users/validation/rules/passwords-must-match.test.js
  portal-api/src/v1/users/validation/rules/read-only-role-cannot-be-assigned-with-other-roles.js
  portal-api/src/v1/users/validation/rules/read-only-role-cannot-be-assigned-with-other-roles.test.js
  portal-api/test-helpers/common-role-lists.js
  portal/component-tests/admin/user-edit.component-test.js
  portal/server/routes/admin/users.js
  portal/templates/admin/user-edit.njk
Labels: Type: Feature

#2052 Feat(FN-965): Add upload utilisation report page
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/utilisationReportUpload.js
  portal/server/constants/file-upload.js
  portal/server/controllers/utilisation-report-service/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/routes/index.js
  portal/server/routes/utilisation-report-service/index.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/utils/multer-filter.utils.js
  portal/server/utils/multer-filter.utils.test.js
  portal/templates/utilisation-report-service/_partials/header.njk
  portal/templates/utilisation-report-service/_partials/primary-navigation.njk
  portal/templates/utilisation-report-service/index.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#2055 Feat(FN-980): List previous reports page
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/previous-reports/list-previous-reports.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/previousReports.js
  portal/README.md
  portal/component-tests/utilisation-report-service/previous-reports.component-test.js
  portal/server/constants/index.js
  portal/server/controllers/utilisation-report-service/index.js
  portal/server/controllers/utilisation-report-service/previous-reports/data.json
  portal/server/controllers/utilisation-report-service/previous-reports/index.js
  portal/server/controllers/utilisation-report-service/previous-reports/index.test.js
  portal/server/controllers/utilisation-report-service/previous-reports/no-data.json
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/routes/utilisation-report-service/index.js
  portal/server/routes/utilisation-report-service/previous-reports/index.js
  portal/templates/utilisation-report-service/index.njk
  portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#2074 feat(FN-1086): Sync env vars with main
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/external-api.bicep
  infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
  infrastructure/resource_group_level/modules/webapps/webapp.bicep
Labels: Type: Feature

#2061 fix(DTFS2-6694): remove shared user token in gef-ui api calls
  gef-ui/api-tests/test-helpers/storage/storage.js
  gef-ui/server/controllers/about-exporter/index.js
  gef-ui/server/controllers/about-exporter/index.test.js
  gef-ui/server/controllers/about-facility/index.js
  gef-ui/server/controllers/about-facility/index.test.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/controllers/application-abandon/index.js
  gef-ui/server/controllers/application-abandon/index.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/controllers/application-submission/index.js
  gef-ui/server/controllers/application-submission/index.test.js
  gef-ui/server/controllers/automatic-cover/index.js
  gef-ui/server/controllers/automatic-cover/index.test.js
  gef-ui/server/controllers/clone-gef-deal/index.js
  gef-ui/server/controllers/clone-gef-deal/index.test.js
  gef-ui/server/controllers/companies-house/index.js
  gef-ui/server/controllers/companies-house/index.test.js
  gef-ui/server/controllers/confirm-cover-start-date/index.js
  gef-ui/server/controllers/confirm-cover-start-date/index.test.js
  gef-ui/server/controllers/downloadFile/index.js
  gef-ui/server/controllers/enter-exporters-correspondence-address/index.js
  gef-ui/server/controllers/enter-exporters-correspondence-address/index.test.js
  gef-ui/server/controllers/exporters-address/index.js
  gef-ui/server/controllers/facilities/index.js
  gef-ui/server/controllers/facilities/index.test.js
  gef-ui/server/controllers/facility-confirm-deletion/index.js
  gef-ui/server/controllers/facility-confirm-deletion/index.test.js
  gef-ui/server/controllers/facility-currency/index.js
  gef-ui/server/controllers/facility-currency/index.test.js
  gef-ui/server/controllers/facility-guarantee/index.js
  gef-ui/server/controllers/facility-guarantee/index.test.js
  gef-ui/server/controllers/facility-value/index.js
  gef-ui/server/controllers/facility-value/index.test.js
  gef-ui/server/controllers/mandatory-criteria/index.js
  gef-ui/server/controllers/mandatory-criteria/index.test.js
  gef-ui/server/controllers/name-application/index.js
  gef-ui/server/controllers/name-application/index.test.js
  gef-ui/server/controllers/provided-facility/index.js
  gef-ui/server/controllers/provided-facility/index.test.js
  gef-ui/server/controllers/return-to-maker/index.js
  gef-ui/server/controllers/return-to-maker/index.test.js
  gef-ui/server/controllers/review-decision/index.js
  gef-ui/server/controllers/review-decision/index.test.js
  gef-ui/server/controllers/select-exporters-correspondence-address/index.js
  gef-ui/server/controllers/submit-to-ukef/index.js
  gef-ui/server/controllers/supporting-information/security-details/index.js
  gef-ui/server/controllers/unissued-facilities/index.js
  gef-ui/server/controllers/unissued-facilities/index.test.js
  gef-ui/server/controllers/unissued-facilities/validation.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
  gef-ui/server/middleware/validateBank/index.js
  gef-ui/server/models/application.js
  gef-ui/server/models/facility.js
  gef-ui/server/services/__mocks__/api.js
  gef-ui/server/services/__tests__/api.test.js
  gef-ui/server/services/api.js
  gef-ui/server/utils/fileUtils.js
  gef-ui/server/utils/fileUtils.test.js
Labels: Type: Security

#2062 fix(DTFS2-6679): display errors on the edit user page
  portal/server/routes/admin/users.js
Labels: Type: Bug

#2075 feat(FN-72): integrate build pipeline
  .github/workflows/bicep_az_deployment_group.yml
  .github/workflows/bicep_deploy.yml
  .github/workflows/bicep_workflow_feature.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  infrastructure/development_scripts/export_environment_variables.azcli
  infrastructure/development_scripts/sort_lists.js
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/cosmosdb.bicep
  infrastructure/resource_group_level/modules/function-acbs.bicep
  infrastructure/resource_group_level/modules/function-number-generator.bicep
  infrastructure/resource_group_level/modules/gw-nsg.bicep
  infrastructure/resource_group_level/modules/privatelink-mongo-cosmos-azure-com.bicep
  infrastructure/resource_group_level/modules/vnet.bicep
  infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
  infrastructure/resource_group_level/modules/webapps/external-api.bicep
  infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
  infrastructure/resource_group_level/modules/webapps/portal-api.bicep
  infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
Labels: Type: Feature

#2076 feat(FN-1133): deploy app code
  .github/workflows/feature_deploy.yml
Labels: Type: Feature

#2083 feat(FN-1113): matrix deploy
  .github/workflows/feature_deploy.yml
Labels: Type: Feature

#2080 feat(FN-969): Report uploaded and show confirmation page
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/confirmAndSend.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/confirmation.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/utilisationReportUpload.js
  portal/component-tests/utilisation-report-service/confirm-and-send.component-test.js
  portal/component-tests/utilisation-report-service/confirmation.component-test.js
  portal/server/constants/roles.js
  portal/server/controllers/utilisation-report-service/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
  portal/templates/utilisation-report-service/utilisation-report-upload/confirm-and-send.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/confirmation.njk
Labels: Type: Fintech

#2063 feat(FN-958): Display service options page
  e2e-tests/gef/cypress/support/commands/login.js
  e2e-tests/portal/cypress/e2e/journeys/AD integration/activedirectory.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/activate-deactivate-user/activate-deactivate-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/restrict-access/restrict-access.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-filter-by-keyword.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/change-password.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/login.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/reset-password.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/scheme-select.spec.js
  e2e-tests/portal/cypress/e2e/journeys/service-options/service-options.spec.js
  e2e-tests/portal/cypress/e2e/journeys/skip-link.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/service-options.js
  e2e-tests/portal/cypress/fixtures/users.js
  e2e-tests/portal/cypress/support/portal/createBSSSubmission.js
  portal/api-tests/dashboard-routes.api-test.js
  portal/api-tests/service-options-routes.api-test.js
  portal/component-tests/service-options/service-options.component-test.js
  portal/server/controllers/service-options/index.js
  portal/server/controllers/utilisation-report-service/previous-reports/index.js
  portal/server/helpers/getUserRoles.js
  portal/server/routes/dashboard.js
  portal/server/routes/index.js
  portal/server/routes/login.js
  portal/server/routes/service-options.js
  portal/server/routes/utilisation-report-service/previous-reports/index.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
  portal/templates/service-options/index.njk
  portal/templates/service-options/service-options.njk
  utils/mock-data-loader/portal/users.js
Labels: Type: Fintech

#2079 feat(DTFS-6702): update login journey
  e2e-tests/portal/cypress/e2e/journeys/login/reset-password.spec.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/constants/login-results.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/reset-password.controller.js
  portal-api/src/v1/users/routes.js
  portal/server/api.js
  portal/server/routes/login.js
  portal/templates/login.njk
  portal/templates/select-scheme.njk
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/constants/login-results.constant.js
  trade-finance-manager-api/src/v1/controllers/user/helpers/loginCallback.helper.js
  trade-finance-manager-api/src/v1/controllers/user/helpers/loginCallback.helper.test.js
  trade-finance-manager-api/src/v1/controllers/user/user.routes.js
Labels: Type: Security
