Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-03, with the labels that each got.

#2691 chore(DTFS2-6994): remove moment js from portal-api
  e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
  portal-api/src/constants/date-formats.ts
  portal-api/src/now.js
  portal-api/src/v1/controllers/deal-status/create-approval-date.js
  portal-api/src/v1/controllers/deal-status/create-mia-submission-date.js
  portal-api/src/v1/controllers/deal-status/create-submission-date.js
  portal-api/src/v1/gef/controllers/application-submit.js
  portal-api/src/v1/users/controller.js
Labels: Type: chore, Type: ACBS

#2799 chore(DTFS2-6994): remove moment from portal-api facility-dates directory
  package-lock.json
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/controllers/bond-issue-facility.controller.js
  portal-api/src/v1/controllers/loan-issue-facility.controller.js
  portal-api/src/v1/facility-dates/cover-end-date.js
  portal-api/src/v1/facility-dates/cover-end-date.test.js
  portal-api/src/v1/facility-dates/issued-date.js
  portal-api/src/v1/facility-dates/requested-cover-start-date.js
  portal-api/src/v1/facility-dates/timestamp.js
  portal-api/src/v1/validation/checker-submit-deal-facility-ready-for-check-cover-start-dates/index.test.js
  portal-api/src/v1/validation/fields/cover-end-date.test.js
  portal-api/src/v1/validation/fields/currency-not-the-same-as-supply-contract-rules/conversion-rate-date.test.js
Labels: Type: chore

#2805 chore(DTFS2-6996): remove moment from dtfs-central-api
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/helpers/getDateFromSearchString.test.ts
  dtfs-central-api/src/helpers/getDateFromSearchString.ts
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals.controller.js
  package-lock.json
Labels: Type: chore

#2769 chore(DTFS2-7037): refactor and add test coverage to azure-functions date helpers
  .github/workflows/test.yml
  azure-functions/acbs-function/acbs-http/index.api-test.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
  azure-functions/acbs-function/activity-update-facility-loan/index.js
  azure-functions/acbs-function/activity-update-facility-master/index.js
  azure-functions/acbs-function/helpers/date.add-day.test.js
  azure-functions/acbs-function/helpers/date.add-month.test.js
  azure-functions/acbs-function/helpers/date.add-year.test.js
  azure-functions/acbs-function/helpers/date.format-date.test.js
  azure-functions/acbs-function/helpers/date.format-timestamp.test.js
  azure-functions/acbs-function/helpers/date.format-year.test.js
  azure-functions/acbs-function/helpers/date.get-date-string-from-year-month-day.test.js
  azure-functions/acbs-function/helpers/date.get-inclusive-month-difference.test.js
  azure-functions/acbs-function/helpers/date.get-now-as-iso-string.test.js
  azure-functions/acbs-function/helpers/date.is-date.test.js
  azure-functions/acbs-function/helpers/date.is-epoch.test.js
  azure-functions/acbs-function/helpers/date.is-string.test.js
  azure-functions/acbs-function/helpers/date.js
  azure-functions/acbs-function/helpers/date.now.test.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.test.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency-months.js
  azure-functions/acbs-function/package.json
  azure-functions/acbs-function/test-helpers/date-formats.js
  azure-functions/acbs-function/test-helpers/defaultContext.js
  azure-functions/acbs-function/testing/defaultTimer.js
  azure-functions/acbs-function/unit.jest.config.js
  package-lock.json
Labels: Type: chore

#2790 chore(dtfs2-6998): remove moment from tfm api
  package-lock.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/now.js
  trade-finance-manager-api/src/types/date.ts
  trade-finance-manager-api/src/utils/date.js
  trade-finance-manager-api/src/utils/date.test.js
  trade-finance-manager-api/src/utils/date.ts
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
  trade-finance-manager-api/src/v1/controllers/get-facility-exposure-period.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.js
  trade-finance-manager-api/src/v1/formattedTimestamp.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/helpers/calculateUkefExposure.js
  trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.js
  trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapDates.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapTenor.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapTenorDate.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapTenorDate.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilityDates.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilityDates.js
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: chore

#2807 feat(FN-1862): refactor TFM reports page
  .github/workflows/test.yml
  dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-data.ts
  dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-report-reconciliation-summary.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/index.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/utilisation-data-repo.test.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/utilisation-data-repo.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/utilisation-data-sql.repo.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report-sql.repo.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.ts
  e2e-tests/.eslintrc.js
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/previous-reports/list-previous-reports.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-no-longer-upload-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/insertUtilisationReports.js
  e2e-tests/portal/cypress/support/portal/removeAllUtilisationReports.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/mark-report-as-done.spec.js
  e2e-tests/tfm/cypress/fixtures/mock-utilisation-report-details.js
  libs/common/src/sql-db-connection/migrations/1709731032407-AddOnDeleteCascadeToAzureFileInfo.ts
  libs/common/src/sql-db-entities/azure-file-info/azure-file-info.entity.ts
  libs/common/src/sql-db-entities/azure-file-info/azure-file-info.types.ts
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.ts
  libs/common/src/sql-db-entities/helpers/user-id.helper.ts
  libs/common/src/sql-db-entities/utilisation-data/utilisation-data.entity.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.ts
  libs/common/src/test-helpers/mock-data/auditable.base-entity.mock.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/utilisation-data.entity.mock.ts
  libs/common/src/test-helpers/mock-data/utilisation-report.entity.mock-builder.ts
Labels: Type: Fintech

#2852 chore(dtfs2-6995): remove moment from azure-functions
  azure-functions/acbs-function/helpers/date.add-day.test.js
  azure-functions/acbs-function/helpers/date.add-month.test.js
  azure-functions/acbs-function/helpers/date.add-year.test.js
  azure-functions/acbs-function/helpers/date.format-date.test.js
  azure-functions/acbs-function/helpers/date.format-timestamp.test.js
  azure-functions/acbs-function/helpers/date.get-date-string-from-year-month-day.test.js
  azure-functions/acbs-function/helpers/date.get-inclusive-month-difference.test.js
  azure-functions/acbs-function/helpers/date.get-year-and-mmdd.test.js
  azure-functions/acbs-function/helpers/date.is-epoch.test.js
  azure-functions/acbs-function/helpers/date.is-string.test.js
  azure-functions/acbs-function/helpers/date.js
  azure-functions/acbs-function/mappings/deal/deal.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-effective-date.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-expiry-date.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
  azure-functions/acbs-function/mappings/facility/helpers/get-issue-date.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-quarter-date.js
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/acbs-function/test-helpers/date-formats.js
  package-lock.json
Labels: Type: chore

#2801 feat(dtfs2-2960): add check for duplicated email addresses
  portal-api/api-tests/v1/users/post-create-user.api-test.js
  portal-api/api-tests/v1/users/put-update-user.api-test.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/api-tests/v1/users/validate-username-and-email.api-tests.js
  portal-api/api-tests/v1/users/with-validate-email-is-correct-format.api-tests.js
  portal-api/api-tests/v1/users/with-validate-email-is-unique.api-tests.js
  portal-api/api-tests/v1/users/with-validate-password.api-tests.js
  portal-api/api-tests/v1/users/with-validate-username-and-email-match.api-tests.js
  portal-api/src/v1/errors/index.js
  portal-api/src/v1/errors/invalid-email-address.error.js
  portal-api/src/v1/errors/invalid-email-address.error.test.js
  portal-api/src/v1/users/controller.findByEmail.test.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
  portal-api/src/v1/users/validation/index.applyCreateRules.test.js
  portal-api/src/v1/users/validation/index.applyUpdateRules.test.js
  portal-api/src/v1/users/validation/index.js
  portal-api/src/v1/users/validation/rules/currentPasswordMustMatch.js
  portal-api/src/v1/users/validation/rules/email-must-be-unique.js
  portal-api/src/v1/users/validation/rules/email-must-be-unique.test.js
  portal-api/src/v1/users/validation/rules/email-must-be-valid-email-address.js
  portal-api/src/v1/users/validation/rules/passwordAtLeast8Characters.js
  portal-api/src/v1/users/validation/rules/passwordAtLeastOneLowercase.js
  portal-api/src/v1/users/validation/rules/passwordAtLeastOneNumber.js
  portal-api/src/v1/users/validation/rules/passwordAtLeastOneSpecialCharacter.js
  portal-api/src/v1/users/validation/rules/passwordAtLeastOneUppercase.js
  portal-api/src/v1/users/validation/rules/passwordsCannotBeReUsed.js
  portal-api/src/v1/users/validation/rules/passwordsMustMatch.js
  portal-api/src/v1/users/validation/rules/read-only-role-cannot-be-assigned-with-other-roles.js
  portal-api/src/v1/users/validation/rules/username-and-email-must-match.js
  portal-api/test-helpers/unit-test-helpers/users/validation/user-validation.test-cases.js
  portal-api/test-helpers/unit-test-helpers/users/validation/user-validation.test-helpers.js
  utils/mock-data-loader/.eslintrc.js
  utils/mock-data-loader/api.js
  utils/mock-data-loader/bss/toJson.js
  utils/mock-data-loader/centralApi.js
  utils/mock-data-loader/clean-all-tables-gef.js
  utils/mock-data-loader/clean-all-tables.js
  utils/mock-data-loader/database/user-repository.js
  utils/mock-data-loader/errors/api.error.js
  utils/mock-data-loader/errors/failed-to-create-logged-in-user-session.error.js
  utils/mock-data-loader/errors/failed-to-create-user.error.js
  utils/mock-data-loader/errors/failed-to-delete-bank.error.js
  utils/mock-data-loader/errors/get-banks.error.js
  utils/mock-data-loader/errors/user-not-found.error.js
  utils/mock-data-loader/gef/api.js
  utils/mock-data-loader/helpers/logger.helper.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/re-insert-mocks.js
  utils/mock-data-loader/temporary-token-handler.js
  utils/mock-data-loader/tfm/api.js
  utils/mock-data-loader/tfm/clean-all-tables-tfm.js
  utils/mock-data-loader/tfm/insert-mocks-tfm.js
  utils/mock-data-loader/tfm/re-insert-mocks-tfm.js
  utils/mock-data-loader/user-helper.js
Labels: Type: Feature

#2895 fix(DTFS2-NONE): fix URNs with e2e tests
  e2e-tests/tfm/cypress/fixtures/constants.js
Labels: Type: Fix

#2578 fix(DTFS2-5227): redirect URL when saving unissued facility to issued
  README.md
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/controllers/confirm-cover-start-date/index.test.js
  gef-ui/server/controllers/mocks/index.js
  gef-ui/server/controllers/unissued-facilities/index.js
  gef-ui/server/controllers/unissued-facilities/index.test.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
Labels: Type: Bug, Type: Fix

#2890 feat(FN-2510): refactor schedule job to use SQL
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.ts
Labels: Type: Fintech

#2894 chore(DTFS2-NONE): fix error handling in mock data loader
  utils/mock-data-loader/centralApi.js
  utils/mock-data-loader/gef/api.js
  utils/mock-data-loader/tfm/api.js
Labels: Type: chore

#2899 fix(DTFS2-NONE): fix error handling in mock data loader
  utils/mock-data-loader/api.js
Labels: Type: Fix

#2892 feat(DTFS2-6862): add cron job to delete acbs logs
  .env.sample
  .github/workflows/test.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  dtfs-central-api/src/cron-scheduler-jobs/delete-acbs-durable-function-logs/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/delete-acbs-durable-function-logs/index.ts
  dtfs-central-api/src/cron-scheduler-jobs/index.ts
  dtfs-central-api/src/errors/database.error.test.ts
  dtfs-central-api/src/errors/database.error.ts
  dtfs-central-api/src/errors/index.ts
  dtfs-central-api/src/errors/write-concern.error.test.ts
  dtfs-central-api/src/errors/write-concern.error.ts
  dtfs-central-api/src/services/repositories/durable-functions-repo.test.ts
  dtfs-central-api/src/services/repositories/durable-functions-repo.ts
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.js
  external-api/src/v1/errors/invalid-entity-type.error.test.ts
  external-api/src/v1/errors/invalid-entity-type.error.ts
  libs/common/src/constants/durable-functions-log.constant.ts
  libs/common/src/constants/index.ts
  libs/common/src/cron-scheduler/scheduler.types.ts
  libs/common/src/index.ts
  trade-finance-manager-api/src/constants/durable-functions.js
  trade-finance-manager-api/src/constants/index.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: Type: Feature

#2882 feat(DTFS2-6968): include user audit details in external api
  external-api/api-tests/v1/durable-functions.api-test.ts
  external-api/package-lock.json
  external-api/src/cronJobs/eStoreCronJobManager.ts
  external-api/src/cronJobs/eStoreDealFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts
  external-api/src/cronJobs/eStoreSiteCreationJob.cron.ts
  external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
  external-api/src/v1/controllers/durable-functions-log.controller.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  libs/common/src/helpers/changeStream/generateAuditDetails.ts
Labels: Type: Feature

#2907 fix(dtfs2-7063): facility id record are missing in acbs
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  azure-functions/acbs-function/helpers/date.format-date.test.js
  azure-functions/acbs-function/helpers/date.js
Labels: Type: Fix

#2909 feat(FN-2331): accessibility update title on check report page to mention error
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
Labels: Type: Fintech

#2914 fix(dtfs2-7063): facility id record are missing in acbs (#2907)
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  azure-functions/acbs-function/helpers/date.format-date.test.js
  azure-functions/acbs-function/helpers/date.js
Labels: Type: Fix

#2916 feat(FN-2405): exchange rate validation portal UI
  .env.sample
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-exchange-rate-error.test.js
Labels: Type: Fintech

#2883 feat(FN-1862): refactor TFM mark report as completed
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/errors/index.ts
  dtfs-central-api/src/errors/transaction-failed.error.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/index.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/update-report-status.test.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/update-report-status.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/mark-report-as-done.spec.js
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.test.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.types.ts
  libs/common/src/test-helpers/mock-data/auditable.base-entity.mock.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/utilisation-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/utilisation-data.entity.mock.ts
Labels: Type: Fintech

#2910 feat(FN-2334): accessibility update labels on previous reports page
  portal/component-tests/utilisation-report-service/previous-reports.component-test.js
  portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
Labels: Type: Fintech

#2912 fix(typo): ENV sample
  .env.sample
  cspell.json
  portal/README.md
Labels: Type: Fix, chore

#2908 feat(FN-1853): fix portal e2e test mock reports
  dtfs-central-api/src/helpers/fee-record.helper.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report-sql.repo.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/previous-reports/list-previous-reports.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  e2e-tests/support/tasks.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
Labels: Type: Fintech

#2922 chore(dtfs2 none): fix error handling
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility-master-record/index.js
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-facility-master/index.js
  azure-functions/acbs-function/activity-get-loan-id/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
  azure-functions/acbs-function/activity-update-facility-loan/index.js
  azure-functions/acbs-function/activity-update-facility-master/index.js
  azure-functions/acbs-function/apim-mdm.js
  azure-functions/acbs-function/mappings/facility/code-value-transaction.js
  azure-functions/acbs-function/mappings/facility/facility-covenant.js
  azure-functions/acbs-function/mappings/facility/facility-fee.js
  azure-functions/acbs-function/mappings/facility/facility-guarantee.js
  azure-functions/acbs-function/mappings/facility/facility-investor.js
  azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master-amend.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
Labels: Type: chore

#2774 fix(DTFS2-6853): warning text not displayed for supply contract page
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-validation.spec.js
  portal/package.json
  portal/server/helpers/pageSpecificValidationErrors.js
  portal/server/helpers/pageSpecificValidationErrors.test.js
  portal/server/routes/contract/about/buyerPage.js
  portal/server/routes/contract/about/financialPage.js
  portal/server/routes/contract/about/supplierPage.js
  portal/server/routes/contract/bond/index.js
  portal/server/routes/contract/loan/index.js
Labels: Type: Fix

#2928 feat(FN-2331&FN-2334): Updating labels & titles to be more descriptive
  portal/component-tests/utilisation-report-service/previous-reports.component-test.js
  portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
Labels: Type: Fintech

#2918 feat(FN-1864): update activity logs columns
  dtfs-central-api/src/helpers/fee-record.helper.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
  libs/common/.eslintrc.js
  libs/common/src/sql-db-connection/migrations/1710850659016-UpdateActivityLogsColumns.ts
  libs/common/src/sql-db-entities/azure-file-info/azure-file-info.entity.ts
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.test.ts
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/helpers/user-id.helper.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.test.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/utilisation-report.entity.mock-builder.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.helper.ts
Labels: Type: Fintech

#2896 feat(DTFS2-7053): include user audit details in TFM api
  libs/common/package.json
  libs/common/src/helpers/changeStream/generateAuditDetails.ts
  package-lock.json
  trade-finance-manager-api/api-tests/helpers/clear-acbs-log.ts
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/src/constants/payloads.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/feedback-controller.js
  trade-finance-manager-api/src/v1/controllers/gef.controller.js
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
  trade-finance-manager-api/src/v1/controllers/user/user.routes.js
Labels: Type: Feature

#2940 feat(FN-1864): add default value for lastUpdatedByIsSystemUser column
  libs/common/src/sql-db-connection/migrations/1711452223370-UpdateActivityLogsColumns.ts
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.ts
Labels: Type: Fintech

#2933 fix(DTFS2-7061): regression portal proceed next button is missing after issuing the ain facilities
  portal-api/api-tests/fixtures/deal-fully-completed.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/src/v1/controllers/deal-status.controller.js
  portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.js
  portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.test.js
  portal-api/src/v1/helpers/date.test.ts
  portal-api/src/v1/helpers/date.ts
  portal/server/routes/contract/index.js
  portal/templates/_macros/facility-inputs/guarantee-fee-payable-by-bank.njk
Labels: Type: Fix

#2941 feat(FN-2335): accessibility fix for utilisation report upload buttons
  portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#2944 fix(acbs):
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility-master-record/index.js
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-facility-master/index.js
  azure-functions/acbs-function/activity-get-loan-id/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
  azure-functions/acbs-function/activity-update-facility-loan/index.js
  azure-functions/acbs-function/activity-update-facility-master/index.js
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: ACBS, Type: Fix

#2942 fix(DTFS2-6144): set portal deal status to acknowledged for notice
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.test.js
Labels: Type: Fix

#2947 chore(merge): merge `DTFS2-70621 to `release-1.5`
  portal/server/routes/contract/eligibility/submittedDocumentationMatchesOriginalData.js
  portal/server/routes/contract/eligibility/submittedDocumentationMatchesOriginalData.test.js
Labels: Type: chore

#2945 chore(merge): merge `release-1.5` to `main`
  portal-api/api-tests/fixtures/deal-fully-completed.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/src/v1/controllers/deal-status.controller.js
  portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.js
  portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.test.js
  portal-api/src/v1/helpers/date.test.ts
  portal-api/src/v1/helpers/date.ts
  portal/server/routes/contract/index.js
  portal/templates/_macros/facility-inputs/guarantee-fee-payable-by-bank.njk
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.test.js
Labels: Type: chore

#2926 feat(FN-1862): remove mark not received as completed
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/mark-report-as-done.spec.js
  libs/common/src/test-helpers/mock-data/utilisation-report.entity.mock-builder.ts
  portal-api/api-tests/v1/utilisation-report-service/previous-reports.api-test.js
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.js
  portal-api/src/v1/controllers/utilisation-report-service/last-uploaded.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.ts
  trade-finance-manager-api/api-tests/v1/utilisation-reports/update-utilisation-report-service.api-test.ts
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.test.ts
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
Labels: Type: Fintech

#2887 chore(DTFS2-6889): update durable functions package
  azure-functions/acbs-function/__mocks__/durable-functions.js
  azure-functions/acbs-function/acbs-amend-facility-loan-record/function.json
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility-master-record/function.json
  azure-functions/acbs-function/acbs-amend-facility-master-record/index.js
  azure-functions/acbs-function/acbs-amend-facility/function.json
  azure-functions/acbs-function/acbs-amend-facility/index.js
  azure-functions/acbs-function/acbs-facility-bond/function.json
  azure-functions/acbs-function/acbs-facility-bond/index.js
  azure-functions/acbs-function/acbs-facility-loan/function.json
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/acbs-facility/function.json
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-http/function.json
  azure-functions/acbs-function/acbs-http/index.api-test.js
  azure-functions/acbs-function/acbs-http/index.js
  azure-functions/acbs-function/acbs-issue-facility/function.json
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/acbs/function.json
  azure-functions/acbs-function/acbs/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/function.json
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/function.json
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/function.json
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/function.json
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/function.json
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/function.json
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/function.json
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/function.json
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/function.json
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/function.json
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/function.json
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/function.json
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/function.json
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-facility-master/function.json
  azure-functions/acbs-function/activity-get-facility-master/index.js
  azure-functions/acbs-function/activity-get-loan-id/function.json
  azure-functions/acbs-function/activity-get-loan-id/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/function.json
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
  azure-functions/acbs-function/activity-update-facility-loan/function.json
  azure-functions/acbs-function/activity-update-facility-loan/index.js
  azure-functions/acbs-function/activity-update-facility-master/function.json
  azure-functions/acbs-function/activity-update-facility-master/index.js
  azure-functions/acbs-function/package.json
  package-lock.json
Labels: Type: chore

#2927 feat(FN-2150): send bank notifications to multiple emails
  doc/sql-db.md
  dtfs-central-api/api-tests/mocks/banks.ts
  libs/common/src/types/mongo-db-models/banks.ts
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.js
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.test.js
  portal-api/src/cron-scheduler-jobs/send-report-due-emails-job/index.test.js
  portal-api/src/cron-scheduler-jobs/send-report-overdue-emails-job/index.test.js
  portal-api/src/cron-scheduler-jobs/send-report-submission-period-start-emails-job/index.test.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/test-helpers/mock-banks.js
  portal/component-tests/utilisation-report-service/confirmation.component-test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/test-mocks/mock-portal-session-user.ts
  portal/server/types/bank.ts
  portal/templates/utilisation-report-service/utilisation-report-upload/confirmation.njk
  portal/test-helpers/mock-banks.js
  trade-finance-manager-ui/server/test-mocks/mock-banks.ts
  utils/mock-data-loader/banks/index.js
Labels: Type: Fintech
