Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-02, with the labels that each got.

#2702 fix(DTFS2-7011): refactored dockerfile
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/Dockerfile
  dtfs-central-api/init.sh
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/sshd_config
  external-api/Dockerfile
  external-api/init.sh
  external-api/package-lock.json
  external-api/package.json
  external-api/sshd_config
  gef-ui/Dockerfile
  gef-ui/init.sh
  gef-ui/package-lock.json
  gef-ui/package.json
  gef-ui/sshd_config
  package-lock.json
  package.json
  portal-api/Dockerfile
  portal-api/init.sh
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/sshd_config
  portal/Dockerfile
  portal/init.sh
  portal/package-lock.json
  portal/package.json
  portal/sshd_config
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-api/init.sh
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/sshd_config
  trade-finance-manager-ui/Dockerfile
  trade-finance-manager-ui/init.sh
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/sshd_config
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Fix

#2711 chore(FN-2153): remove flaky 'dateFuncs' e2e test helpers
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/portal/cypress/e2e/journeys/checker/cover-end-date/deal.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-financial-validation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-facilities/MIA-accepted-deal-status-maker-cannot-resubmit-until-confirmed-all-issued-facilities-cover-start-date/MIA-accepted-deal-status-maker-cannot-resubmit-until-confirmed-all-issued-facilities-cover-start-date.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-facilities/MIA-accepted-deal-status-maker-changing-cover-start-date-on-facilities-does-not-update-if-invalid.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/fill-and-submit-issue-facility-form/fillAndSubmitIssueBondFacilityForm.js
  e2e-tests/portal/cypress/e2e/journeys/maker/fill-and-submit-issue-facility-form/fillAndSubmitIssueLoanFacilityForm.js
  e2e-tests/portal/cypress/support/utils/dateFuncs.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-receivedDate-default-sort.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-ukefDealId.spec.js
  e2e-tests/tfm/cypress/support/utils/dateFuncs.js
  e2e-tests/ukef/cypress/support/utils/dateFuncs.js
Labels: Type: chore

#2695 feat(FN-1947): add scheduler to create utilisation reports
  .env.sample
  .github/workflows/test.yml
  cspell.json
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/index.ts
  dtfs-central-api/src/scheduler/index.ts
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.ts
  dtfs-central-api/src/scheduler/jobs/index.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
  dtfs-central-api/src/types/db-models/banks.ts
  dtfs-central-api/src/types/db-models/utilisation-reports.ts
  dtfs-central-api/src/types/scheduler-job.ts
  dtfs-central-api/src/utils/report-period.test.ts
  dtfs-central-api/src/utils/report-period.ts
Labels: Type: Fintech

#2657 fix(durable-functions): Error reporting for `acbs-functions`
  azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js
  azure-functions/acbs-function/acbs-amend-facility-master-record/index.js
  azure-functions/acbs-function/acbs-facility-loan/index.js
  azure-functions/acbs-function/acbs-facility/index.js
  azure-functions/acbs-function/acbs-issue-facility/index.js
  azure-functions/acbs-function/activity-create-code-value-transaction/index.js
  azure-functions/acbs-function/activity-create-deal-guarantee/index.js
  azure-functions/acbs-function/activity-create-deal-investor/index.js
  azure-functions/acbs-function/activity-create-deal/index.js
  azure-functions/acbs-function/activity-create-facility-covenant/index.js
  azure-functions/acbs-function/activity-create-facility-fee/index.js
  azure-functions/acbs-function/activity-create-facility-guarantee/index.js
  azure-functions/acbs-function/activity-create-facility-investor/index.js
  azure-functions/acbs-function/activity-create-facility-loan/index.js
  azure-functions/acbs-function/activity-create-facility-master/index.js
  azure-functions/acbs-function/activity-create-party/index.js
  azure-functions/acbs-function/activity-get-acbs-country-code/index.js
  azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js
  azure-functions/acbs-function/activity-get-facility-master/index.js
  azure-functions/acbs-function/activity-get-loan-id/index.js
  azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
  azure-functions/acbs-function/activity-update-facility-loan/index.js
  azure-functions/acbs-function/activity-update-facility-master/index.js
  azure-functions/acbs-function/helpers/http.js
Labels: Type: Docs, Type: ACBS, Type: Fix

#2705 feat(FN-1947): update functions to use existing reports
  .github/workflows/test.yml
  cspell.json
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/utils/report-period.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report.controller.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/upload-utilisation-report.controller.js
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-report.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-reports-reconciliation-summary.js
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/e2e-fixtures/dbCollections.js
  e2e-tests/support/alias-selector.js
  e2e-tests/support/db-client.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/header/header.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/login/login-with-role.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/login/login.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/mark-report-as-done.spec.js
  e2e-tests/tfm/cypress/e2e/pages/index.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportsPage.js
  e2e-tests/tfm/cypress/fixtures/mock-utilisation-report-details.js
  e2e-tests/tfm/cypress/fixtures/teams.js
  e2e-tests/tfm/cypress/support/utils/dateHelpers.js
  trade-finance-manager-api/api-tests/v1/utilisation-reports/update-utilisation-report-service.api-test.ts
  trade-finance-manager-api/src/types/utilisation-reports.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/update-utilisation-report-status.controller.test.ts
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.test.ts
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.ts
  trade-finance-manager-api/src/v1/validation/validate-payloads.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/server/test-mocks/mock-banks.ts
  trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.ts
  trade-finance-manager-ui/server/types/utilisation-reports.ts
  trade-finance-manager-ui/templates/_macros/table-cell-checkbox.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
  utils/mock-data-loader/tfm/insert-mocks-tfm.js
  utils/mock-data-loader/tfm/mocks/users.js
Labels: Type: Fintech

#2753 feat(FN-1856): run sql migrations in deployment pipelines
  .github/workflows/deployment.yml
  .github/workflows/feature_deploy.yml
Labels: Type: Fintech

#2749 fix(DTFS2-7021): Ensure EC with draft mode set to `false` are used
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/controllers/eligibilityCriteria.api-test.js
  portal-api/src/v1/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
  portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
Labels: Type: Fix

#2754 feat(FN-1859): add type-safe entity create function
  libs/common/src/sql-db-connection/data-source.ts
  libs/common/src/sql-db-entities/azure-file-info/azure-file-info.entity.ts
  libs/common/src/sql-db-entities/azure-file-info/index.ts
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.ts
  libs/common/src/sql-db-entities/base-entities/index.ts
  libs/common/src/sql-db-entities/helpers/index.ts
  libs/common/src/sql-db-entities/helpers/user-id.helper.ts
  libs/common/src/sql-db-entities/partial-entities/index.ts
  libs/common/src/sql-db-entities/partial-entities/month-and-year.partial-entity.ts
  libs/common/src/sql-db-entities/partial-entities/report-period.partial-entity.ts
  libs/common/src/sql-db-entities/partial-entities/report-period.ts
  libs/common/src/sql-db-entities/utilisation-data/index.ts
  libs/common/src/sql-db-entities/utilisation-data/utilisation-data.entity.ts
  libs/common/src/sql-db-entities/utilisation-report/index.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.types.ts
Labels: Type: Fintech

#2656 chore(DTFS2-6993): replace moment.js in portal
  portal/component-tests/contract/components/contract-overview-table.component-test.js
  portal/package-lock.json
  portal/package.json
  portal/server/constants/date.ts
  portal/server/constants/index.js
  portal/server/helpers/date.ts
  portal/server/helpers/formattedTimestamp.js
  portal/server/helpers/index.js
  portal/server/nunjucks-configuration/filter-localiseTimestamp.js
  portal/server/nunjucks-configuration/filter-localiseTimestamp.test.ts
  portal/server/nunjucks-configuration/filter-localiseTimestamp.ts
  portal/server/nunjucks-configuration/index.js
  portal/server/routes/contract/bond/index.js
  portal/server/routes/contract/loan/index.js
  portal/templates/admin/dashboard.njk
  portal/templates/bond/_macros/bond-stage-issued-form-fields.njk
  portal/templates/bond/_macros/bond-submission-details.njk
  portal/templates/bond/bond-issue-facility.njk
  portal/templates/contract/components/bond-transactions-table.njk
  portal/templates/contract/components/contract-overview-table.njk
  portal/templates/contract/components/loan-transactions-table.njk
  portal/templates/contract/contract-view-comments.njk
  portal/templates/contract/contract-view.njk
  portal/templates/dashboard/_macros/dashboard-deals-table.njk
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
  portal/templates/loan/_macros/facility-stage-unconditional-form-fields.njk
  portal/templates/loan/_macros/loan-submission-details.njk
  portal/templates/loan/loan-issue-facility.njk
  portal/templates/user/profile.njk
Labels: Type: chore

#2750 fix(DTFS2-7022): restrict sign in link expired path
  gef-ui/README.md
  portal/README.md
  portal/api-tests/login/get-sign-in-link-expired.api-test.js
  portal/api-tests/login/other-login-routes.api-test.js
  portal/server/routes/login/index.js
  trade-finance-manager-ui/README.md
Labels: Type: Fix

#2690 chore(DTFS2-6993): remove moment.js from tests in portal
  e2e-tests/portal/cypress/e2e/journeys/maker-facilities/AIN-facility-cover-start-date-validation-past-3-months.spec.js
  e2e-tests/portal/cypress/fixtures/constants.js
  portal/component-tests/admin/user-edit.component-test.js
  portal/component-tests/bond/_macros/bond-submission-details.component-test.js
  portal/component-tests/contract/components/bond-transactions-table.component-test.js
  portal/component-tests/contract/components/contract-overview-table.component-test.js
  portal/component-tests/contract/components/loan-transactions-table.component-test.js
  portal/component-tests/contract/contract-submission-details.component-test.js
  portal/component-tests/contract/contract-view.component-test.js
  portal/component-tests/fixtures/deal-fully-completed.js
  portal/component-tests/loan/_macros/loan-submission-details.component-test.js
  portal/package-lock.json
  portal/package.json
  portal/server/constants/date.ts
  portal/server/constants/index.js
  portal/server/helpers/date.ts
Labels: Type: chore, Type: ACBS

#2594 chore(DTFS2-7023): add typescript to portal routes
  dtfs-central-api/src/types/db-models/users.ts
  portal/package-lock.json
  portal/package.json
  portal/server/constants/index.js
  portal/server/constants/login-status.ts
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-upload-errors.test.ts
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-upload-errors.ts
  portal/server/generateApp.js
  portal/server/generateApp.ts
  portal/server/helpers/express-session.ts
  portal/server/helpers/index.js
  portal/server/routes/admin/index.js
  portal/server/routes/admin/index.ts
  portal/server/routes/index.js
  portal/server/routes/index.ts
  portal/server/test-mocks/mock-portal-session-user.ts
  portal/server/types/bank.ts
  portal/server/types/date.ts
  portal/server/types/express-session.d.ts
  portal/server/types/portal-session-user.ts
  portal/server/types/session-bank.ts
Labels: Type: chore

#2766 feat(FN-1947): add utilisation report creation schedule env variable
  .github/workflows/bicep_az_deployment_group.yml
  infrastructure/resource_group_level/main.bicep
Labels: Type: Fintech

#2761 chore(DTFS2-4533): remove moment from gef-ui, tfm-api and tfm-ui tests
  e2e-tests/package.json
  gef-ui/server/utils/helpers.test.js
  package-lock.json
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/utils/date.test.js
  trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapCoverEndDate.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilityDates.api-test.js
  trade-finance-manager-ui/server/nunjucks-configuration/filter-formatDateString.test.js
Labels: Type: chore, Type: ACBS

#2771 feat(FN-1947): only upload reports for banks which are visible in TFM
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.ts
Labels: Type: Fintech

#2768 feat(FN-1951): refactor query options for utilisation reports endpoint
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller/index.ts
  dtfs-central-api/src/v1/routes/bank-routes.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  portal-api/api-tests/v1/utilisation-report-service/due-report-periods.api-test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/due-report-periods.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/due-report-periods.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/last-uploaded.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/last-uploaded.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/src/v1/validation/validateIds.js
  portal/server/controllers/utilisation-report-service/previous-reports/index.js
Labels: Type: Fintech

#2775 chore: update 'no-underscore-dangle' eslint rule exceptions
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/index.test.ts
  external-api/.eslintrc.js
  gef-ui/.eslintrc.js
  gef-ui/server/controllers/application-abandon/index.js
  gef-ui/server/controllers/application-details/index.js
  libs/common/.eslintrc.js
  portal-api/.eslintrc.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-download.controller.test.js
  portal/.eslintrc.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.test.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/src/v1/controllers/bank-holidays/get-bank-holidays.controller.test.js
  trade-finance-manager-api/src/v1/controllers/should-update-deal-from-MIA-to-MIN.api-test.js
  trade-finance-manager-api/src/v1/controllers/task-emails.api-test.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-download.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-reports-reconciliation-summary.controller.test.js
  trade-finance-manager-api/src/v1/rest-mappings/deals-light.api-test.js
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table-heading.component-test.js
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table-search-form.component-test.js
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table.component-test.js
  trade-finance-manager-ui/component-tests/facilities/facilities-table-search-form.component-test.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/helpers.test.js
  trade-finance-manager-ui/server/controllers/home/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/report-download/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
  trade-finance-manager-ui/server/helpers/team.test.js
  trade-finance-manager-ui/server/helpers/user.test.ts
  trade-finance-manager-ui/server/middleware/validateMongoId/index.test.ts
Labels: Type: chore

#2707 feat(DTFS2-6965): setup change stream for audit API
  .env.sample
  .github/workflows/test.yml
  docker-compose.dev.yml
  docker-compose.gha.yml
  docker-compose.yml
  dtfs-central-api/src/createApp.js
  dtfs-central-api/src/services/changeStream/changeStreamApi.test.ts
  dtfs-central-api/src/services/changeStream/changeStreamApi.ts
  dtfs-central-api/src/services/changeStream/setupChangeStream.ts
  mongodb/Dockerfile
  utils/mock-data-loader/database/user-repository.js
Labels: Type: Feature

#2706 chore(DTFS2-6994): remove moment from portal-api tests
  gef-ui/server/controllers/ukef-cover-start-date/index.js
  gef-ui/server/controllers/unissued-facilities/validation.test.js
  portal-api/.eslintrc.js
  portal-api/api-tests/fixtures/deal-fully-completed-issued-and-unissued-facilities.js
  portal-api/api-tests/fixtures/deal-fully-completed.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/bonds/bond-issue-facility.api-test.js
  portal-api/api-tests/v1/bonds/bonds-validation.api-test.js
  portal-api/api-tests/v1/bonds/bonds.api-test.js
  portal-api/api-tests/v1/deals/deal-status-accepted.api-test.js
  portal-api/api-tests/v1/deals/deals-status-accepted-facilities-cover-start-date.api-test.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted-updates-unsubmitted-issued-facilities.api-test.js
  portal-api/api-tests/v1/deals/deals-status-submitted.api-test.js
  portal-api/api-tests/v1/deals/deals-submission-details-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility-validation.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility.api-test.js
  portal-api/api-tests/v1/loan/loan-validation.api-test.js
  portal-api/api-tests/v1/loan/loan.api-test.js
  portal-api/jest.common.config.js
  portal-api/src/constants/date-formats.ts
  portal-api/src/constants/index.js
  portal-api/src/v1/deal-summary/index.test.js
  portal-api/src/v1/facility-dates/cover-end-date.test.js
  portal-api/src/v1/gef/controllers/validation/eligibilityCriteria.test.js
  portal-api/src/v1/gef/controllers/validation/exporter.test.js
  portal-api/src/v1/gef/controllers/validation/supportingInfo.test.js
  portal-api/src/v1/helpers/date.test.ts
  portal-api/src/v1/helpers/date.ts
  portal-api/src/v1/portalActivity-object-generator/index.test.js
  portal-api/src/v1/section-calculations/index.test.js
  portal-api/src/v1/section-status/bonds.test.js
  portal-api/src/v1/section-status/loans.test.js
  portal-api/src/v1/validation/checker-submit-deal-facility-ready-for-check-cover-start-dates/index.test.js
  portal-api/src/v1/validation/eligibility-criteria.test.js
  portal-api/src/v1/validation/fields/cover-end-date.test.js
  portal-api/src/v1/validation/fields/currency-not-the-same-as-supply-contract-rules/conversion-rate-date.test.js
  portal-api/src/v1/validation/fields/date.test.js
  portal-api/src/v1/validation/validateIds.test.js
  portal/templates/contract/about/about-supplier.njk
  portal/templates/contract/about/about-supply-buyer.njk
Labels: Type: chore, Type: ACBS

#2773 feat(FN-2146): add error logging to cron scheduler. commonise logic
  dtfs-central-api/api-test-setup.jest.config.js
  dtfs-central-api/package.json
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.ts
  dtfs-central-api/src/cron-scheduler-jobs/index.ts
  dtfs-central-api/src/index.ts
  dtfs-central-api/src/scheduler/index.ts
  dtfs-central-api/src/scheduler/jobs/index.ts
  dtfs-central-api/src/types/scheduler-job.ts
  libs/common/.eslintrc.js
  libs/common/package.json
  libs/common/src/cron-scheduler/index.ts
  libs/common/src/cron-scheduler/scheduler.helpers.ts
  libs/common/src/cron-scheduler/scheduler.ts
  libs/common/src/cron-scheduler/scheduler.types.ts
  libs/common/src/index.ts
  package-lock.json
  portal-api/api-test-setup.jest.config.js
  portal-api/package.json
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.js
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.test.js
  portal-api/src/cron-scheduler-jobs/index.ts
  portal-api/src/cron-scheduler-jobs/send-report-due-emails-job/index.js
  portal-api/src/cron-scheduler-jobs/send-report-due-emails-job/index.test.js
  portal-api/src/cron-scheduler-jobs/send-report-overdue-emails-job/index.js
  portal-api/src/cron-scheduler-jobs/send-report-overdue-emails-job/index.test.js
  portal-api/src/cron-scheduler-jobs/send-report-submission-period-start-emails-job/index.js
  portal-api/src/cron-scheduler-jobs/send-report-submission-period-start-emails-job/index.test.js
  portal-api/src/index.ts
  portal-api/src/scheduler/index.js
  portal-api/src/scheduler/jobs/index.js
  trade-finance-manager-api/api-test-setup.jest.config.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/cron-scheduler-jobs/check-azure-acbs-function.js
  trade-finance-manager-api/src/cron-scheduler-jobs/check-azure-number-generator-function.js
  trade-finance-manager-api/src/cron-scheduler-jobs/index.ts
  trade-finance-manager-api/src/generateApp.js
  trade-finance-manager-api/src/scheduler/index.js
  trade-finance-manager-api/src/scheduler/jobs/check-azure-acbs-function.js
  trade-finance-manager-api/src/scheduler/jobs/check-azure-number-generator-function.js
  trade-finance-manager-api/src/scheduler/jobs/index.js
  trade-finance-manager-api/tsconfig.json
Labels: Type: Fintech

#2708 feat(DTFS2-6621): ensure usernames are email addresses
  dtfs-central-api/api-tests/v1/user/user-get.api-test.js
  dtfs-central-api/api-tests/v1/user/user-post.api-test.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
  e2e-tests/portal/cypress/e2e/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-min-submission-date/deal.js
  e2e-tests/portal/cypress/e2e/journeys/login/reset-password.spec.js
  e2e-tests/portal/cypress/e2e/journeys/number-generator/test-data/baseBssDeal.js
  e2e-tests/portal/cypress/fixtures/deal.js
  e2e-tests/tfm/cypress/fixtures/deal-AIN.js
  e2e-tests/tfm/cypress/fixtures/mock-gef-deals.js
  gef-ui/api-tests/test-helpers/user-generator.js
  gef-ui/server/utils/mocks/mock_requests.js
  gef-ui/server/utils/mocks/mock_users.js
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/v1/users/login-with-sign-in-link.api-test.js
  portal-api/api-tests/v1/users/post-create-user.api-test.js
  portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
  portal-api/api-tests/v1/users/put-update-user.api-test.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/api-tests/v1/users/test-data.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/api-tests/v1/users/validate-username-and-email.api-tests.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
  portal-api/src/v1/users/validation/index.js
  portal-api/src/v1/users/validation/rules/email-must-be-valid-email-address.js
  portal-api/src/v1/users/validation/rules/email-must-be-valid-email-address.test.js
  portal-api/src/v1/users/validation/rules/username-and-email-must-match.js
  portal-api/src/v1/users/validation/rules/username-and-email-must-match.test.js
  portal-api/src/v1/validation/route-validators/express-validator-result-handler.js
  portal-api/src/v1/validation/route-validators/express-validator-result-handler.ts
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/mock-TFM-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/__mocks__/mock-portal-users.js
  utils/mock-data-loader/api.js
  utils/mock-data-loader/bss/deals/1.js
  utils/mock-data-loader/bss/deals/10.js
  utils/mock-data-loader/bss/deals/11.js
  utils/mock-data-loader/bss/deals/2.js
  utils/mock-data-loader/bss/deals/3.js
  utils/mock-data-loader/bss/deals/4.js
  utils/mock-data-loader/bss/deals/5.js
  utils/mock-data-loader/bss/deals/6.js
  utils/mock-data-loader/bss/deals/7.js
  utils/mock-data-loader/bss/deals/8.js
  utils/mock-data-loader/bss/deals/9.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/portal/users.js
  utils/mock-data-loader/tfm/mocks/teams.js
  utils/mock-data-loader/user-helper.js
Labels: Type: Feature, Type: Fix

#2797 chore(DTFS2-6994): remove moment from portal-api validation
  portal-api/src/v1/helpers/date.test.ts
  portal-api/src/v1/helpers/date.ts
  portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js
  portal-api/src/v1/validation/checker-submit-deal-facility-ready-for-check-cover-start-dates/index.js
  portal-api/src/v1/validation/fields/cover-dates.js
  portal-api/src/v1/validation/fields/cover-end-date.js
  portal-api/src/v1/validation/fields/currency-not-the-same-as-supply-contract-rules/conversion-rate-date.js
  portal-api/src/v1/validation/fields/date.js
  portal-api/src/v1/validation/fields/date.test.js
  portal-api/src/v1/validation/fields/issue-facility/requested-cover-start-date.js
  portal-api/src/v1/validation/fields/issued-date.js
  portal-api/src/v1/validation/loan-rules/facility-stage-unconditional/requested-cover-start-date.js
  portal-api/src/v1/validation/submission-details-rules/supply-contract-conversion-rate-date-is-required-for-non-GBP.js
Labels: Type: chore

#2806 chore(DTFS2-6829): change mocked data at EOM
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/8. amendment-details-manual-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-proceed.spec.js
  portal-api/src/v1/helpers/date.test.ts
  portal-api/src/v1/helpers/date.ts
Labels: Type: chore
