Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-01, with the labels that each got.

#2546 feat(fn 692): disable function apps in feature deployments
  .github/workflows/feature_deploy.yml
Labels: Type: Fintech

#2547 feat(FN-692): disable function apps in feature deployments
  .github/workflows/feature_deploy.yml
Labels: Type: Fintech

#2487 fix(DTFS-6470): remove auto-submit from tasks and comments page filters
  e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/tasks/tasks.spec.js
  e2e-tests/tfm/cypress/e2e/pages/activities/activitiesPage.js
  e2e-tests/tfm/cypress/e2e/pages/tasksPage.js
  trade-finance-manager-ui/component-tests/assertions.js
  trade-finance-manager-ui/component-tests/case/tasks/_macros/task-filters.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/main.js
  trade-finance-manager-ui/public/js/main.js.map
  trade-finance-manager-ui/scripts/main.js
  trade-finance-manager-ui/scripts/submit.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/templates/case/activity/_macros/activity-comment-filter.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/task-filters.njk
Labels: Type: Fix

#2491 fix(DTFS2-6526): focus user to the table header button if it was clicked just now
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table-heading.component-test.js
  trade-finance-manager-ui/component-tests/deals/_macros/deals-table.component-test.js
  trade-finance-manager-ui/server/controllers/deals/index.js
  trade-finance-manager-ui/server/controllers/deals/index.test.js
  trade-finance-manager-ui/templates/deals/_macros/deals-table-heading.njk
  trade-finance-manager-ui/templates/deals/_macros/deals-table.njk
  trade-finance-manager-ui/templates/deals/deals.njk
Labels: Type: Fix

#2548 fix: bicep refactor
  infrastructure/resource_group_level/main.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-calculated-variables.bicep
  infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-no-calculated-variables.bicep
  infrastructure/resource_group_level/modules/webapps/webapp.bicep
Labels: Type: Fintech

#2549 fix(dtfs2 6899): fix blocked user logging in with most recent sign in link
  e2e-tests/portal/cypress/e2e/journeys/login/resend-sign-in-link.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/sign-in-link-session-edge-cases.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/login/sign-in-link-expired.js
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/v1/deals/deals-status-submitted.api-test.js
  portal-api/api-tests/v1/deals/deals-status.api-test.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/users/login-with-sign-in-link.api-test.js
  portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/repository.js
  portal-api/src/v1/users/repository.test.js
  portal-api/src/v1/users/sanitizeUserData.test.js
  portal-api/src/v1/users/sign-in-link.controller.js
  portal-api/src/v1/users/sign-in-link.controller.login-with-sign-in-link.test.js
  portal-api/src/v1/users/sign-in-link.service.create-and-email-sign-in-link.test.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal-api/src/v1/users/sign-in-link.service.login-user.test.js
  portal-api/test-helpers/unit-test-mocks/mock-user.js
Labels: Type: Bug, Type: Fix

#2551 fix(FN-1363): update new 2fa login controller
  portal/server/controllers/login/index.js
  portal/server/controllers/login/login-with-sign-in-link.js
  portal/server/controllers/login/login-with-sign-in-link.test.js
  portal/templates/login/post-login-redirect.njk
Labels: Type: Fintech

#2554 feat(FN-1290): store reporting schedule against banks
  dtfs-central-api/api-tests/mocks/banks.js
  dtfs-central-api/src/constants/payloads.js
  dtfs-central-api/src/types/db-models/banks.d.ts
  portal-api/src/constants/payloads.js
  portal-api/test-helpers/mock-banks.js
  portal/test-helpers/mock-banks.js
  trade-finance-manager-ui/server/test-mocks/mock-banks.js
  utils/mock-data-loader/banks/index.js
Labels: Type: Fintech

#2489 feat(FN-1536): mark report as done
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/errors/invalid-payload.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.ts
  dtfs-central-api/src/types/utilisation-reports.d.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller.js
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller.test.js
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  trade-finance-manager-api/api-tests/v1/utilisation-reports/update-utilisation-report-service.api-test.ts
  trade-finance-manager-api/src/utils/validation.test.ts
  trade-finance-manager-api/src/utils/validation.ts
  trade-finance-manager-api/src/v1/__mocks__/mock-tfm-session-user.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-api/src/v1/validation/route-validators/route-validators.test.js
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.test.ts
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.ts
  trade-finance-manager-api/src/v1/validation/validate-payloads.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-status.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/constants/index.js
  trade-finance-manager-ui/server/constants/utilisation-report-reconciliation-status.js
  trade-finance-manager-ui/server/constants/utilisation-report-reconciliation-status.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/report-download/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/server/helpers/validation.js
  trade-finance-manager-ui/server/helpers/validation.test.js
  trade-finance-manager-ui/server/routes/utilisation-reports/index.js
  trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.js
  trade-finance-manager-ui/server/types/types-helper.d.ts
  trade-finance-manager-ui/server/types/utilisation-reports.d.ts
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
  trade-finance-manager-ui/tsconfig.json
Labels: Type: Fintech

#2492 fix(DTFS2-6613): fix validation error on loan financial details page
  portal/server/helpers/constructPayload.js
  portal/server/helpers/constructPayload.test.js
  portal/server/routes/contract/bond/index.js
  portal/server/routes/contract/loan/index.js
Labels: Type: Bug

#2461 chore(DTFS2-6666): remove filter vulnerabilities
  portal-api/api-tests/helpers/escapeOperators.api-test.js
  portal-api/package-lock.json
  portal-api/package.json
  portal-api/src/v1/helpers/escapeOperators.js
  portal/server/controllers/dashboard/filters/generate-keyword-query.js
  portal/server/controllers/dashboard/filters/generate-keyword-query.test.js
Labels: Type: chore, BREAKING

#2458 chore(DTFS2-6700): remove tfm search vulnerabilities
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/api-test-common.jest.config.js
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals.controller.js
  dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js
Labels: Type: Fix, BREAKING

#2558 feat(FN-1685): fix csv parsing for rows with empty data at end of row
  portal/jest.config.js
  portal/server/constants/file-upload.js
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#2556 fix(FN-1615): convert repository files to typescript
  dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-data.ts
  dtfs-central-api/src/constants/currencies.ts
  dtfs-central-api/src/constants/index.js
  dtfs-central-api/src/constants/utilisation-report-headers.ts
  dtfs-central-api/src/services/repositories/banks-repo.js
  dtfs-central-api/src/services/repositories/banks-repo.test.ts
  dtfs-central-api/src/services/repositories/banks-repo.ts
  dtfs-central-api/src/services/repositories/utilisation-data-repo.js
  dtfs-central-api/src/services/repositories/utilisation-data-repo.test.ts
  dtfs-central-api/src/services/repositories/utilisation-data-repo.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/index.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/update-report-status.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.js
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
  dtfs-central-api/src/types/currency.d.ts
  dtfs-central-api/src/types/date.d.ts
  dtfs-central-api/src/types/db-models/tfm-users.d.ts
  dtfs-central-api/src/types/db-models/users.d.ts
  dtfs-central-api/src/types/db-models/utilisation-data.d.ts
  dtfs-central-api/src/types/db-models/utilisation-reports.d.ts
  dtfs-central-api/src/types/portal/portal-role.d.ts
  dtfs-central-api/src/types/portal/portal-session-user.d.ts
  dtfs-central-api/src/types/session-bank.d.ts
  dtfs-central-api/src/types/tfm/tfm-session-user.d.ts
  dtfs-central-api/src/types/types-helper.ts
  dtfs-central-api/src/types/utilisation-reports.d.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/utilisation-report-validator.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js
Labels: Type: Fintech

#2566 fix(FN-1051): correct open reports DB query
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts
  dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
Labels: Type: Fintech

#2565 fix(FN-1363): add constant for landing pages
  portal/.eslintrc.js
  portal/api-test.jest.config.js
  portal/jest.common.config.js
  portal/jest.config.js
  portal/package-lock.json
  portal/package.json
  portal/server/constants/index.js
  portal/server/constants/landing-pages.ts
  portal/server/controllers/login/login-with-sign-in-link.js
  portal/server/controllers/login/login-with-sign-in-link.test.js
  portal/server/routes/default/index.js
  portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/types/landing-pages.ts
  portal/server/types/types-helper.ts
  portal/tsconfig.json
Labels: Type: Fintech

#2567 fix(FN-1536): move payload parameters from query to body
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/server/helpers/date.js
  trade-finance-manager-ui/server/services/utilisation-report-service.test.js
  trade-finance-manager-ui/server/services/utilisation-report-service.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
Labels: Type: Fintech

#2490 chore(main): release 1.1.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2579 fix: update .d.ts files to .ts where applicable
  dtfs-central-api/src/types/azure-file-info.ts
  dtfs-central-api/src/types/currency.ts
  dtfs-central-api/src/types/date.ts
  dtfs-central-api/src/types/db-models/banks.ts
  dtfs-central-api/src/types/db-models/db-collection-name.ts
  dtfs-central-api/src/types/db-models/db-model.ts
  dtfs-central-api/src/types/db-models/tfm-users.ts
  dtfs-central-api/src/types/db-models/users.ts
  dtfs-central-api/src/types/db-models/utilisation-data.ts
  dtfs-central-api/src/types/db-models/utilisation-reports.ts
  dtfs-central-api/src/types/portal/portal-role.ts
  dtfs-central-api/src/types/portal/portal-session-user.ts
  dtfs-central-api/src/types/session-bank.ts
  dtfs-central-api/src/types/tfm/team.ts
  dtfs-central-api/src/types/tfm/tfm-session-user.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  portal-api/src/external-api/types/bank-holidays.ts
  portal-api/src/scheduler/types/scheduler-job.ts
  trade-finance-manager-api/src/types/bank-holidays.ts
  trade-finance-manager-api/src/types/date.ts
  trade-finance-manager-api/src/types/db-models/tfm-users.ts
  trade-finance-manager-api/src/types/fileshare.ts
  trade-finance-manager-api/src/types/team-id.ts
  trade-finance-manager-api/src/types/team.ts
  trade-finance-manager-api/src/types/tfm-session-user.d.ts
  trade-finance-manager-api/src/types/tfm-session-user.ts
  trade-finance-manager-api/src/types/types-helper.ts
  trade-finance-manager-api/src/types/utilisation-reports.ts
  trade-finance-manager-api/src/v1/__mocks__/mock-tfm-session-user.ts
  trade-finance-manager-ui/server/types/bank-holidays.ts
  trade-finance-manager-ui/server/types/date.ts
  trade-finance-manager-ui/server/types/team-id.ts
  trade-finance-manager-ui/server/types/tfm-session-user.ts
  trade-finance-manager-ui/server/types/types-helper.ts
  trade-finance-manager-ui/server/types/utilisation-reports.ts
Labels: Type: Fix, Type: Fintech

#2583 fix(DTFS-6959): Deployment strategy
  .github/workflows/deploy.sh
  .husky/commit-msg
Labels: Type: Fix

#2587 feat(FN-2052): add 'SUBMITTED' to utilisation report filename
  portal/server/api.js
  portal/server/constants/file-upload.js
  portal/server/constants/index.js
Labels: Type: Fintech

#2588 feat(FN-2051): allow numeric months in filename
  portal/server/constants/index.js
  portal/server/constants/month-names.ts
  portal/server/constants/monthNames.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js
Labels: Type: Fintech

#2581 feat(FN-2021): remove mark report as done for `PDC_READ` users
  trade-finance-manager-ui/component-tests/table-cell-checkbox.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/server/types/custom-express-request.ts
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/_macros/table-cell-checkbox.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
Labels: Type: Fintech

#2591 chore: log sign-in link when in development
  portal-api/src/v1/users/sign-in-link.service.js
Labels: Type: chore

#2586 chore(DTFS2-6952): update node and npm versions
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: chore

#2593 feat(FN-2050): handle non-ascii characters in csv files
  portal/server/utils/csv-utils.js
Labels: Type: Fintech

#2602 feat(FN-2070): move bank reports primary navigation
  trade-finance-manager-ui/templates/_partials/primary-navigation.njk
Labels: Type: Fintech

#2590 fix(DTFS2-6963): patch user `disabled` feature to sign in link
  e2e-tests/portal/cypress/e2e/journeys/login/navigating-using-sign-in-link.spec.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/disablePortalUserByUsername.js
  e2e-tests/support/user-tasks.js
  portal-api/api-tests/v1/users/login-with-sign-in-link.api-test.js
  portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
  portal-api/src/v1/email/index.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/controller.test.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/passport.js
  portal-api/src/v1/users/repository.js
  portal-api/src/v1/users/repository.test.js
  portal-api/src/v1/users/sign-in-link.controller.js
  portal-api/src/v1/users/sign-in-link.service.create-and-email-sign-in-link.test.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal-api/src/v1/users/sign-in-link.service.login-user.test.js
  portal/api-tests/common-tests/role-validation-api-tests.js
  portal/server/api.js
  trade-finance-manager-api/src/v1/controllers/user/helpers/loginCallback.helper.js
  trade-finance-manager-api/src/v1/controllers/user/helpers/loginCallback.helper.test.js
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
Labels: security fix

#2603 feat(FN-2074): remove dividers when no buttons on 'Bank Reports' page
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/styles/layout.scss
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
Labels: Type: Fintech

#2598 fix(DTFS2-6963): Holistic user service approach to block users who have `disabled` `true`
  e2e-tests/portal/cypress/e2e/journeys/login/navigating-using-sign-in-link.spec.js
  portal-api/api-tests/v1/users/login-with-sign-in-link.api-test.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/src/constants/http-error-causes.js
  portal-api/src/constants/index.js
  portal-api/src/constants/passport-validation-results.js
  portal-api/src/generateApp.js
  portal-api/src/v1/errors/user-blocked.error.js
  portal-api/src/v1/errors/user-disabled.error.js
  portal-api/src/v1/errors/user-disabled.error.test.js
  portal-api/src/v1/errors/user-not-found.error.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/controller.test.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/passport.js
  portal-api/src/v1/users/reset-password.controller.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/sign-in-link.controller.js
  portal-api/src/v1/users/sign-in-link.service.create-and-email-sign-in-link.test.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal-api/src/v1/users/sign-in-link.service.login-user.test.js
  portal-api/src/v1/users/user.service.js
  portal-api/src/v1/users/user.service.test.js
  portal/api-tests/login/get-check-your-email.api-test.js
  portal/api-tests/login/send-new-sign-in-link-api-tests.js
  portal/server/constants/http-error-causes.js
  portal/server/controllers/login/login-with-sign-in-link.js
  portal/server/routes/middleware/validatePartialAuthToken/index.js
  portal/server/routes/middleware/validatePartialAuthToken/index.test.js
Labels: security fix

#2601 feat(DTFS2-6911): Regression QAT prior deployment
  .github/workflows/deployment.yml
  .github/workflows/development_deploy.yml
  .github/workflows/lint.yml
  .github/workflows/production_deploy.yml
  .github/workflows/sca.yml
  .github/workflows/staging_deploy.yml
  .github/workflows/test.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/api-tests/api.ts
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: chore, Type: Fix

#2606 feat(FN-2081): add "visible in TFM" flag to banks
  dtfs-central-api/api-tests/mocks/banks.ts
  dtfs-central-api/src/constants/payloads.js
  dtfs-central-api/src/types/db-models/banks.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-reports-reconciliation-summary.js
  portal-api/src/constants/payloads.js
  trade-finance-manager-ui/server/types/custom-express-request.ts
  utils/mock-data-loader/banks/index.js
Labels: Type: Fintech

#2681 refactor: update main stbr tfm 5
  .github/workflows/deployment.yml
  .github/workflows/development_deploy.yml
  .github/workflows/feature_deploy.yml
  .github/workflows/lint.yml
  .github/workflows/production_deploy.yml
  .github/workflows/sca.yml
  .github/workflows/staging_deploy.yml
  .github/workflows/test.yml
  azure-functions/acbs-function/package-lock.json
  azure-functions/acbs-function/package.json
  azure-functions/number-generator-function/package-lock.json
  azure-functions/number-generator-function/package.json
  dtfs-central-api/package-lock.json
  dtfs-central-api/package.json
  external-api/api-tests/api.ts
  external-api/package-lock.json
  external-api/package.json
  gef-ui/package-lock.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/package-lock.json
  portal-api/package.json
  portal/package-lock.json
  portal/package.json
  trade-finance-manager-api/package-lock.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package-lock.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/mock-data-loader/package-lock.json
  utils/mock-data-loader/package.json
Labels: Type: Fintech

#2682 fix(deployment): updated environment variable reference name
  .github/workflows/deployment.yml
Labels: Type: Fix

#2683 fix(gha): checkout with ref
  .github/workflows/deployment.yml
Labels: Type: Fix

#2685 fix(deployment): functions slot container source image
  .github/workflows/deployment.yml
Labels: Type: Fix

#2686 chore: update stbr tfm 5 with recent changes
  .github/workflows/deployment.yml
Labels: Type: Fintech

#2585 chore(main): release 1.2.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2469 feat(FN-1261): enable healthcheck on webapps
  .github/workflows/bicep_workflow_feature.yml
  infrastructure/resource_group_level/modules/webapps/webapp.bicep
Labels: Type: Fintech

#2692 fix(DTFS2-7003): refer to email property as opposed to username
  .github/workflows/sca.yml
  portal-api/src/v1/users/controller.js
Labels: Type: Fix

#2694 chore(main): release 1.2.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2696 fix(deployment)!: changed branch name to prod
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/test.yml
Labels: Type: Fix, BREAKING

#2701 fix(dTFS2-7007): Ensure EC wording is correct
  utils/mock-data-loader/bss/eligibilityCriteria.js
Labels: Type: Fix
