Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-04, with the labels that each got.

#2979 feat(FN-2561): update error text
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.test.js
Labels: Type: Fintech

#2951 feat(FN-1853): add cascade delete to fee record table
  dtfs-central-api/api-tests/sql-db-helper.ts
  e2e-tests/support/tasks.js
  libs/common/src/sql-db-connection/migrations/1711652127585-AddFeeRecordCascadeDelete.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  portal-api/api-tests/sql-db-helper.ts
Labels: Type: Fintech

#2987 feat(FN-2353): refactor imports in tfm-ui to use the common package
  libs/common/src/types/tfm/team-id.ts
  package-lock.json
  trade-finance-manager-ui/component-tests/case/tasks/_macros/tasks-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentRequestDate.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/bankDecision.controller.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/leadUnderwriter.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/leadUnderwriter.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/underwriterManagerDecision.test.js
  trade-finance-manager-ui/server/controllers/case/parties/helpers.js
  trade-finance-manager-ui/server/controllers/case/parties/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/facility-risk-profile/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/helpers.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/loss-given-default/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/loss-given-default/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/helpers.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/helpers.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/underwriter-managers-decision/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.test.js
  trade-finance-manager-ui/server/controllers/home/index.test.ts
  trade-finance-manager-ui/server/controllers/home/index.ts
  trade-finance-manager-ui/server/controllers/login/index.test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/server/helpers/date.js
  trade-finance-manager-ui/server/helpers/user.test.ts
  trade-finance-manager-ui/server/helpers/user.ts
  trade-finance-manager-ui/server/middleware/validateUserTeam/index.js
  trade-finance-manager-ui/server/routes/utilisation-reports/index.js
  trade-finance-manager-ui/server/services/utilisation-report-service.ts
  trade-finance-manager-ui/server/test-mocks/amendment-test-mocks.js
  trade-finance-manager-ui/server/test-mocks/mock-tfm-session-user.ts
  trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.ts
  trade-finance-manager-ui/server/types/bank-holidays.ts
  trade-finance-manager-ui/server/types/date.ts
  trade-finance-manager-ui/server/types/team-id.ts
  trade-finance-manager-ui/server/types/tfm-session-user.ts
  trade-finance-manager-ui/server/types/types-helper.ts
  trade-finance-manager-ui/server/types/utilisation-reports.ts
  trade-finance-manager-ui/tsconfig.json
Labels: Type: Fintech

#2950 chore(FN-1853): create new mongo db connection string env var for tests
  .env.sample
  .github/workflows/test.yml
  utils/mock-data-loader/.env.sample
  utils/mock-data-loader/database/database.config.js
  utils/sql-db-seeder/.env.sample
  utils/sql-db-seeder/src/helpers/get-from-mongo-db.ts
Labels: Type: Fintech

#2985 feat(FN-2353): move get formatted report period helper to common
  libs/common/src/helpers/date.test.ts
  libs/common/src/helpers/date.ts
  libs/common/src/utils/date.ts
  libs/common/src/utils/report-period.test.ts
  libs/common/src/utils/report-period.ts
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.test.ts
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.ts
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-details.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
  portal/server/helpers/date.test.ts
  portal/server/helpers/date.ts
  portal/server/helpers/getFormattedReportPeriod.test.ts
  portal/server/helpers/getFormattedReportPeriod.ts
  portal/server/helpers/index.js
Labels: Type: Fintech

#2992 feat(FN-1613): add primary navigation keys to tfm-ui
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-status.component-test.js
  trade-finance-manager-ui/server/constants/index.js
  trade-finance-manager-ui/server/constants/primary-navigation-keys.ts
  trade-finance-manager-ui/server/constants/team-ids.ts
  trade-finance-manager-ui/server/constants/utilisation-report-reconciliation-status.ts
  trade-finance-manager-ui/server/controllers/deals/index.js
  trade-finance-manager-ui/server/controllers/deals/index.test.js
  trade-finance-manager-ui/server/controllers/facilities/index.js
  trade-finance-manager-ui/server/controllers/facilities/index.test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts
Labels: Type: Fintech

#3002 fix(DTFS2-7099): update TFM accessibility statement
  trade-finance-manager-ui/templates/accessibility-statement.njk
Labels: Type: Fix

#3003 fix(DTFS2-7103): auto close stale pull requests
  .github/workflows/pr.yml
  README.md
Labels: Type: Fix

#2772 feat(FN-2253): add MongoDB to SQL Server data migrator
  cspell.json
  libs/common/src/types/index.ts
  package-lock.json
  utils/data-migration/.eslintrc.js
  utils/data-migration/package.json
  utils/data-migration/sql/utilisation-reports/README.md
  utils/data-migration/sql/utilisation-reports/helpers/ejson.helper.ts
  utils/data-migration/sql/utilisation-reports/helpers/index.ts
  utils/data-migration/sql/utilisation-reports/helpers/transformers.helper.ts
  utils/data-migration/sql/utilisation-reports/index.ts
  utils/data-migration/sql/utilisation-reports/mongodb-ejson/utilisationData.json
  utils/data-migration/sql/utilisation-reports/mongodb-ejson/utilisationReports.json
  utils/data-migration/tfm/migrate-tfm-users.js
  utils/data-migration/tsconfig.eslint.json
  utils/data-migration/tsconfig.json
Labels: Type: Fintech

#3005 Feat/dtfs2 7093/update crown favicon
  README.md
  gef-ui/templates/index.njk
  portal/templates/index.njk
  service-unavailable/index.html
  trade-finance-manager-ui/templates/index.njk
Labels: Type: Feature, Type: Fix

#3010 feat(dtfs2 7096): update static folder
  README.md
  portal/server/generateApp.ts
  trade-finance-manager-ui/server/generateApp.js
Labels: Type: Feature

#3009 feat(FN-2562): TFM mark as complete checkbox design
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
Labels: Type: Fintech

#2943 feat(FN-1853): squash migrations
  .github/workflows/feature_deploy.yml
  libs/common/src/sql-db-connection/migrations/1707317495910-AddUtilisationReportTables.ts
  libs/common/src/sql-db-connection/migrations/1709731032407-AddOnDeleteCascadeToAzureFileInfo.ts
  libs/common/src/sql-db-connection/migrations/1710248062308-RenameUtilisationDataToFeeRecord.ts
  libs/common/src/sql-db-connection/migrations/1710250937910-UpdateNullableColumnTypes.ts
  libs/common/src/sql-db-connection/migrations/1710259065447-UpdateFeeRecordColumns.ts
  libs/common/src/sql-db-connection/migrations/1711452223370-UpdateActivityLogsColumns.ts
  libs/common/src/sql-db-connection/migrations/1711652127585-AddFeeRecordCascadeDelete.ts
  libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts
Labels: Type: Fintech

#2932 feat(DTFS2-7083): add audit logs to update facility endpoint
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facility-put.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/facility/tfm-update-facility.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/facility.controller.js
  trade-finance-manager-api/src/v1/controllers/tfm.controller.js
  trade-finance-manager-api/src/v1/controllers/update-facilities.js
  trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
Labels: Type: Feature

#3021 fix(stale-pr): Ensure stale PR GH is executed
  .github/workflows/pr.yml
Labels: Type: Fix

#3023 fix(DTFS2-7091): Handle invalid TFM-UI user session
  package-lock.json
  portal-api/src/v1/controllers/deal-status.controller.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/underwriting/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
Labels: Type: Fix

#3027 feat(FN-2183): reorder table columns
  libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts
Labels: Type: Fintech

#3032 fix(DTFS2-7091): increased delay and enhanced logging
  portal-api/src/v1/controllers/deal-status.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Labels: Type: Fix

#3037 fix(DTFS2-7091): validation before updating details deal object
  dtfs-central-api/src/v1/controllers/portal/deal/update-deal.controller.js
  portal-api/src/v1/controllers/deal-status.controller.js
  portal-api/src/v1/controllers/deal-status/update-submission-count.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/helpers/delay.js
Labels: Type: Fix

#2948 feat(DTFS2-7082): add audit logs to update deal snapshot endpoint
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-bss-deal.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deal.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-post-amendments.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-submit-deal.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  dtfs-central-api/src/v1/swagger-definitions/audit-details.ts
  libs/common/src/helpers/change-stream/validate-audit-details.test.ts
  libs/common/src/helpers/change-stream/validate-audit-details.ts
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Labels: Type: Feature

#3034 feat(DTFS2-7087): add audit logs to create user endpoint
  dtfs-central-api/api-tests/v1/tfm/users/tfm-users.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-users.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
Labels: Type: Feature

#3007 feat(DTFS2-7085): add audit details to update facility ammendment endpoint
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-get.api-test.js
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-post.api-test.js
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-put.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-post-amendments.controller.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-put-amendments.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.test.js
  trade-finance-manager-api/src/v1/rest-mappings/helpers/amendment.helpers.test.js
Labels: Type: Feature

#3031 feat(DTFS2-7086): add audit logs to create team endpoint
  dtfs-central-api/api-tests/v1/tfm/users/tfm-teams.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-teams.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  package-lock.json
  package.json
  utils/mock-data-loader/.eslintrc.js
  utils/mock-data-loader/package.json
  utils/mock-data-loader/tfm/api.js
  utils/mock-data-loader/tfm/insert-mocks-tfm.js
  utils/mock-data-loader/tsconfig.eslint.json
  utils/mock-data-loader/tsconfig.json
Labels: Type: Feature

#3045 feat(DTFS2-7105): unified prettier configuration
  .github/workflows/github.yml
  .husky/commit-msg
  .prettierrc.json
  azure-functions/acbs-function/package.json
  e2e-tests/package.json
  external-api/.prettierrc.json
  external-api/package.json
  gef-ui/package.json
  libs/common/.eslintrc.js
  libs/common/src/cron-scheduler/scheduler.ts
  libs/common/src/cron-scheduler/scheduler.types.ts
  libs/common/src/helpers/change-stream/generate-audit-database-record.test.ts
  libs/common/src/helpers/change-stream/generate-audit-details.test.ts
  libs/common/src/helpers/change-stream/validate-audit-details.test.ts
  libs/common/src/helpers/change-stream/validate-audit-details.ts
  libs/common/src/helpers/string.ts
  libs/common/src/helpers/validation.test.ts
  package-lock.json
  package.json
  portal-api/.prettierrc.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/data-migration/package-lock.json
  utils/data-migration/package.json
  utils/data-migration/tfm/migrate-tfm-users.js
  utils/mock-data-loader/package-lock.json
  utils/package.json
Labels: Type: Feature, Type: Fix

#3041 feat(DTFS2-7124): Add `Shawbrook` bank to portal
  .github/workflows/test.yml
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  e2e-tests/portal/cypress/e2e/pages/login/index.js
  portal/templates/_partials/before-you-start.njk
Labels: Type: Fix

#3033 fix(dtfs2 6119): update prevent double click occuring
  gef-ui/public/js/disableFormSubmitOnSubmission.js
  gef-ui/public/js/disableFormSubmitOnSubmission.js.map
  gef-ui/templates/index.njk
  gef-ui/webpack.common.config.js
  libs/common/src/ui-scripts/disable-form-submit-on-submission.js
  portal/public/css/styles.css
  portal/public/js/disableFormSubmitOnSubmission.js
  portal/public/js/disableFormSubmitOnSubmission.js.map
  portal/public/js/govukFrontend.js.map
  portal/templates/index.njk
  portal/webpack.common.config.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/disableFormSubmitOnSubmission.js
  trade-finance-manager-ui/public/js/disableFormSubmitOnSubmission.js.map
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: Fix

#3038 feat(DTFS2-7118): add audit logs to portal-api open router
  dtfs-central-api/api-tests/helpers/with-validate-audit-details.api-tests.ts
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-put.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-bss-deal.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-bss-deals-put-submit.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-put-tfm.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deals-get-query-field.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deal.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deals-put-submit.api-test.js
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facilities-get-facilities-for-deal.api-test.js
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facility-put.api-test.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  libs/common/.eslintrc.js
  libs/common/package.json
  libs/common/src/helpers/change-stream/generate-audit-database-record.test.ts
  libs/common/src/helpers/change-stream/generate-audit-database-record.ts
  libs/common/src/helpers/change-stream/generate-audit-details.ts
  libs/common/src/helpers/change-stream/validate-audit-details.ts
  libs/common/src/helpers/date.ts
  libs/common/src/test-helpers/generate-mock-audit-database-record.ts
  libs/common/src/types/audit-database-record.ts
  libs/common/src/types/audit-details.ts
  libs/common/src/types/date.ts
  package-lock.json
  package.json
  portal-api/api-tests/v1/feedback/feedback.api-test.js
  portal-api/src/constants/payloads.js
  portal-api/src/v1/controllers/feedback.controller.js
  portal-api/src/v1/gef/routes.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/controller.test.js
  portal-api/src/v1/users/repository.js
  portal-api/src/v1/users/repository.test.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
  portal-api/src/v1/users/sign-in-link.controller.create-and-email-sign-in-link.test.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal/package.json
  portal/server/routes/feedback.js
  trade-finance-manager-api/api-tests/v1/feedback/feedback.api-test.js
  trade-finance-manager-api/src/v1/controllers/feedback-controller.js
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/feedback/index.js
  trade-finance-manager-ui/server/controllers/feedback/index.test.js
Labels: Type: Feature

#3050 feat(FN-1615): add seeder for fee records
  .github/workflows/test.yml
  utils/sql-db-seeder/.env.sample
  utils/sql-db-seeder/src/fee-record/fee-record.helper.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.helper.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.seed.ts
Labels: Type: Fintech

#3046 feat(DTFS2-7120): add audit logs to gef routes of portal api
  portal-api/api-tests/v1/gef/application-submit.api-test.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/clone-gef-deal.api-test.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
  portal-api/src/v1/gef/controllers/application-submit.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
  portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/files.controller.js
  portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
  portal-api/src/v1/gef/models/application.js
  portal-api/src/v1/gef/models/eligibilityCriteria.js
  portal-api/src/v1/gef/models/facilities.js
  portal-api/src/v1/gef/models/files.js
  portal-api/src/v1/gef/models/mandatoryCriteria.js
  portal-api/src/v1/users/routes.js
Labels: Type: Feature
