Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-07, with the labels that each got.

#3249 feat(FN-1720): add unit tests for zod schemas
  dtfs-central-api/src/v1/routes/middleware/payload-validation/schemas/currency.schema.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/schemas/mongo-object-id.schema.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/schemas/mongo-object-id.schema.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/schemas/tfm-session-user.schema.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/schemas/tfm-team.schema.test.ts
Labels: Type: Fintech

#3262 feat(FN-1720): add confirm delete payment page
  dtfs-central-api/api-tests/v1/utilisation-reports/delete-payment.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-payment-details-by-id.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-payment-details-by-id.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-payment-details-by-id.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-payment-details-by-id.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/payment-details-response-body.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api-response-types/payment-details-response-body.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/delete-payment.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/delete-payment.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-payment-details-by-id.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-payment-details-by-id.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/component-tests/assertions.js
  trade-finance-manager-ui/component-tests/utilisation-reports/confirm-delete-payment.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/edit-payment.component-test.js
  trade-finance-manager-ui/server/api-response-types/get-payment-details-response-body.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/edit-payment-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/edit-payment-helper.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/confirm-delete-payment-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/templates/utilisation-reports/confirm-delete-payment.njk
  trade-finance-manager-ui/templates/utilisation-reports/edit-payment.njk
  trade-finance-manager-ui/test-helpers/payment-details-response-body.ts
Labels: Type: Fintech

#3260 feat(dtfs2-6966): add audit details to updateGefFacility and refactor
  dtfs-central-api/api-tests/v1/gef-deals/add-min-activities.api-test.js
  dtfs-central-api/api-tests/v1/gef-facilities/gef-facility-put.api-test.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
  dtfs-central-api/src/v1/controllers/portal/gef-facility/update-facility.controller.js
  libs/common/package.json
  libs/common/src/errors/deal-not-found.error.test.ts
  libs/common/src/errors/deal-not-found.error.ts
  libs/common/src/errors/facility-not-found.error.test.ts
  libs/common/src/errors/facility-not-found.error.ts
  libs/common/src/errors/index.ts
  libs/common/src/errors/invalid-deal-id.error.test.ts
  libs/common/src/errors/invalid-deal-id.error.ts
  libs/common/src/errors/invalid-facility-id.error.test.ts
  libs/common/src/errors/invalid-facility-id.error.ts
  package-lock.json
  portal-api/src/v1/gef/controllers/application.controller.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/update-facilities.js
  trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/payment-form-helpers.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/payment-form-helpers.ts
Labels: Type: Feature

#3264 feat(FN-2054): add edit permission check for utilisation report reconciliation
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.js
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3287 feat(FN-1720): add e2e tests for deleting payments
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/e2e-fixtures/dbCollections.ts
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/delete-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/mark-report-as-done.spec.js
  e2e-tests/tfm/cypress/e2e/pages/index.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportConfirmDeletePaymentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportEditPaymentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportsPage.js
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
Labels: Type: Fintech

#3261 fix(DTFS2-7248): disabled countries in mock
  external-api/src/external-api/countries.ts
  portal-api/src/external-api/__mocks__/countries.js
Labels: Type: Fix

#3227 feat(FN-1617): add facility filter button to premium payments page
  dtfs-central-api/src/constants/index.js
  dtfs-central-api/src/constants/regex.js
  dtfs-central-api/src/helpers/get-fee-record-payment-entity-groups-from-fee-record-entities.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/constants/regex.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-add-payment-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-add-payment-error-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-and-clear-fields-from-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-and-clear-fields-from-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/styles/styles.scss
  trade-finance-manager-ui/styles/utilisation-reports.scss
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3288 feat(FN-1718): add edit payment e2e tests
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportEditPaymentPage.js
  trade-finance-manager-ui/templates/utilisation-reports/edit-payment.njk
Labels: Type: Fintech

#3290 feat(FN-1617): add e2e tests for filtering by facility id
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/delete-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-fee-records-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/mark-report-as-done.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
  e2e-tests/tfm/cypress/e2e/pages/index.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportsSummaryPage.js
Labels: Type: Fintech

#3233 feat(DTFS2-7171): add facility end date to about facility page
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  dtfs-central-api/package.json
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
  e2e-tests/.eslintrc.js
  e2e-tests/e2e-fixtures/dbCollections.ts
  e2e-tests/e2e-fixtures/deal-versioning.fixture.ts
  e2e-tests/gef/cypress/e2e/facility/about-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/version-0-facility.spec.js
  e2e-tests/gef/cypress/e2e/pages/about-facility.js
  e2e-tests/gef/cypress/support/commands.js
  e2e-tests/gef/cypress/support/commands/insertVersion0Deal.js
  e2e-tests/gef/cypress/support/commands/insertVersion0Facility.js
  e2e-tests/support/tasks.js
  external-api/package.json
  gef-ui/component-tests/partials/about-facility.component-test.js
  gef-ui/package.json
  gef-ui/server/controllers/about-facility/index.about-facility.test.js
  gef-ui/server/controllers/about-facility/index.js
  gef-ui/server/controllers/about-facility/index.validate-and-update-about-facility.test.js
  gef-ui/server/controllers/about-facility/validation.js
  gef-ui/server/routes/about-facility.js
  gef-ui/templates/_macros/about-facility/facility-end-date.njk
  gef-ui/templates/partials/about-facility.njk
  libs/common/src/errors/deal-version.error.test.ts
  libs/common/src/errors/deal-version.error.ts
  libs/common/src/errors/index.ts
  libs/common/src/errors/invalid-parameter-error.test.ts
  libs/common/src/errors/invalid-parameter-error.ts
  libs/common/src/helpers/gef-deal-versioning.test.ts
  libs/common/src/helpers/gef-deal-versioning.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/is-feature-flag-enabled.test.ts
  libs/common/src/helpers/is-feature-flag-enabled.ts
  package-lock.json
  portal-api/api-tests/deal-versioning.api-test.js
  portal-api/api-tests/v1/gef/application-submit.api-test.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/package.json
  portal-api/src/v1/gef/controllers/application-submit.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/models/application.js
  portal-api/src/v1/gef/models/facilities.js
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: Feature

#3293 feat(FN-1722): add generate keying data event handler
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/src/errors/index.ts
  dtfs-central-api/src/errors/no-matching-fee-records.error.test.ts
  dtfs-central-api/src/errors/no-matching-fee-records.error.ts
  dtfs-central-api/src/repositories/fee-record-repo/fee-record.repo.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event-type.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/fee-record-keyed/fee-record-keyed.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/fee-record-keyed/fee-record-keyed.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/fee-record-keyed/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event-type.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-keying-data-payload.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  libs/common/src/sql-db-connection/migrations/1720103206301-AddKeyingSheetColumns.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-keying-data.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-keying-data.controller.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/keying-data/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/keying-data/index.ts
  utils/sql-db-seeder/src/fee-record/fee-record.helper.ts
Labels: Type: Fintech

#3302 feat(DTFS2-NONE): reset process.env correctly in tests
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/services/changeStream/changeStreamApi.test.ts
  libs/common/src/helpers/gef-deal-versioning.test.ts
  libs/common/src/helpers/is-feature-flag-enabled.test.ts
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.test.ts
  portal-api/src/cron-scheduler-jobs/send-report-due-emails-job/index.test.ts
  portal-api/src/cron-scheduler-jobs/send-report-overdue-emails-job/index.test.ts
  portal-api/src/cron-scheduler-jobs/send-report-submission-period-start-emails-job/index.test.ts
  portal-api/src/v1/services/utilisation-report/email-service.test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/search-reports-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts
  trade-finance-manager-ui/server/services/utilisation-report-service.test.js
Labels: Type: chore

#3285 feat(FN-3011): remove sql ledger with migration scripts
  cspell.json
  doc/sql-db.md
  libs/common/package.json
  libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts
  libs/common/src/sql-db-connection/migrations/1716990167763-AddPaymentTable.ts
  libs/common/src/sql-db-connection/migrations/1717746522387-PaymentTableUpdateAmountColumns.ts
  libs/common/src/sql-db-connection/remove-ledger.sh
  libs/common/src/sql-db-entities/payment/payment.entity.ts
  package.json
  utils/data-migration/remove-sql-ledger/README.md
  utils/data-migration/remove-sql-ledger/copy-and-remove-ledger.feature.sql
  utils/data-migration/remove-sql-ledger/copy-and-remove-ledger.prod.sql
Labels: Type: Fintech

#3304 fix(acbs-durable-functions): resolve durable functions container startup error
  azure-functions/acbs-function/Dockerfile
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/constants/index.js
  azure-functions/acbs-function/constants/request.js
  azure-functions/acbs-function/package.json
  external-api/tsconfig.json
  gef-ui/package.json
  package-lock.json
  portal/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: ACBS, Type: Fix

#3303 feat(FN-1719): add backend payment fee removal functionality
  dtfs-central-api/api-tests/v1/utilisation-reports/post-remove-fees-from-payment-group.api-test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-removed-from-group/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-removed-from-group/other-fee-removed-from-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-removed-from-group/other-fee-removed-from-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/remove-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/remove-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event-type.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event-type.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-remove-fees-from-payment-group-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-remove-fees-from-payment-group-payload.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.test.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-remove-fees-from-payment.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-remove-fees-from-payment.controller.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.ts
Labels: Type: Fintech

#3311 feat(FN-1719): add E2E test for removing fees from payment
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/remove-fees-from-payment.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportEditPaymentPage.js
Labels: Type: Fintech

#3310 feat(FN-1722): update SQL seeder
  doc/sql-db.md
  package-lock.json
  utils/package.json
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.helpers.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.seed.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.seeder.ts
  utils/sql-db-seeder/src/fee-record-payment-group/index.ts
  utils/sql-db-seeder/src/fee-record/fee-record.helper.ts
  utils/sql-db-seeder/src/helpers/get-from-mongo-db.ts
  utils/sql-db-seeder/src/helpers/get-random-currency.ts
  utils/sql-db-seeder/src/helpers/get-random-financial-amount.ts
  utils/sql-db-seeder/src/helpers/index.ts
  utils/sql-db-seeder/src/index.ts
  utils/sql-db-seeder/src/reset-seeder.ts
  utils/sql-db-seeder/src/seeding-data-source.ts
  utils/sql-db-seeder/src/utilisation-report/index.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.helper.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.seed.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.seeder.ts
Labels: Type: Fintech

#3314 fix(DTFS2-7284): optional chaining on bond parties
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/src/cron-scheduler-jobs/check-azure-acbs-function.js
  trade-finance-manager-api/src/v1/helpers/all-parties-have-urn.js
Labels: Type: ACBS, Type: Fix

#3284 feat(DTFS2-7164): add facility end date on summary page
  e2e-tests/README.md
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/utils/display-items.js
  gef-ui/server/utils/display-items.test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/validation/facilities.js
  portal-api/src/v1/gef/controllers/validation/facilities.test.js
  portal-api/src/v1/gef/models/facilities.js
Labels: Type: Feature

#3318 feat(FN-1726): add fee to existing payment button
  dtfs-central-api/api-tests/v1/utilisation-reports/get-selected-fee-record-details.api-test.ts
  dtfs-central-api/src/repositories/payment-repo/payment.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.ts
  libs/common/src/types/selected-fee-records-details.ts
  trade-finance-manager-api/src/v1/api-response-types/selected-reported-fees-details-response.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/add-payment.component-test.js
  trade-finance-manager-ui/server/api-response-types/selected-reported-fees-details-response.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/types/view-models/add-payment-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/add-payment.njk
  trade-finance-manager-ui/test-helpers/test-data/add-payment-view-model.ts
Labels: Type: Fintech

#3313 feat(FN-1724): keying sheet principal adjustment
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/delete-payment.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-fee-records-to-key.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-payment-details-by-id.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-selected-fee-record-details.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports-reconciliation-summary.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/patch-payment.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-payment.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-remove-fees-from-payment-group.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/put-keying-data-mark-as-to-do.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-principal-balance-adjustment.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-principal-balance-adjustment.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
  e2e-tests/README.md
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/previous-reports/list-previous-reports.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-no-longer-upload-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/insertUtilisationReports.js
  e2e-tests/portal/cypress/support/portal/removeAllUtilisationReports.js
  e2e-tests/support/tasks.js
  libs/common/src/sql-db-connection/migrations/1721227404776-AddFacilityUtilisationDataTable.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.types.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/index.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/test-helpers/mock-data/facility-utilisation-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/utilisation-report.entity.mock-builder.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.seeder.ts
  utils/sql-db-seeder/src/index.ts
Labels: Type: Fintech

#3336 fix(DTFS2-7292): downgraded MSSQL to 2022
  .gitignore
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  libs/common/src/sql-db-connection/Dockerfile
  libs/common/src/sql-db-connection/init.sh
  utils/copy-env-vars/index.ts
Labels: Type: Fix

#3332 feat(FN-1745): add 'Add to an existing payment' screen
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-to-an-existing-payment.spec.js
  e2e-tests/tfm/cypress/e2e/pages/index.js
  e2e-tests/tfm/cypress/e2e/pages/utilisationReportAddToAnExistingPaymentPage.js
  trade-finance-manager-ui/component-tests/utilisation-reports/add-to-an-existing-payment.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/payment-form-helpers.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/selected-reported-fees-details-view-model-mapper.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/add-payment-view-model.ts
  trade-finance-manager-ui/server/types/view-models/add-to-an-existing-payment-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/server/types/view-models/selected-reported-fees-details-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/add-to-an-existing-payment.njk
  trade-finance-manager-ui/test-helpers/test-data/add-to-an-existing-payment-view-model.ts
Labels: Type: Fintech

#3325 feat(FN-3196): persist form values on the edit a payment screen
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/remove-fees-from-payment.spec.js
  package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/get-and-clear-fields-from-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/get-and-clear-fields-from-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/edit-payment-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/edit-payment-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.ts
  trade-finance-manager-ui/server/helpers/remove-fees-from-payment-helper.ts
  trade-finance-manager-ui/server/middleware/validatePostRemoveFeesFromPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostRemoveFeesFromPaymentRequestBody/index.ts
  trade-finance-manager-ui/server/types/express-session.d.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-details-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/edit-payment.njk
Labels: Type: Fintech

#3339 feat(FN-NONE): fix tfm scripts build
  e2e-tests/gef/cypress/e2e/facility/about-facility.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-proceed.spec.js
  trade-finance-manager-ui/public/js/disableFormSubmitOnSubmission.js
  trade-finance-manager-ui/public/js/govukFrontend.js
  trade-finance-manager-ui/public/js/jsEnabled.js
  trade-finance-manager-ui/public/js/main.js
  trade-finance-manager-ui/public/js/mojFrontend.js
  trade-finance-manager-ui/templates/index.njk
Labels: Type: Fix
