Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-12, with the labels that each got.

#4015 chore(DTFS2-7680): update threeDaysAgoPlusThreeMonths date constant
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
Labels: Type: chore

#3959 feat(DTFS2-7617): admin role creation
  e2e-tests/gef/cypress/e2e/exporter/about-exporter.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/ukef.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/is-ukef-email.test.ts
  libs/common/src/helpers/is-ukef-email.ts
  package-lock.json
  package.json
  portal-api/src/v1/users/validation/index.applyCreateRules.test.js
  portal-api/src/v1/users/validation/index.applyUpdateRules.test.js
  portal-api/src/v1/users/validation/index.js
  portal-api/src/v1/users/validation/index.test.js
  portal-api/src/v1/users/validation/rules/admin-from-ukef-only.js
  portal-api/src/v1/users/validation/rules/admin-from-ukef-only.test.js
  portal-api/src/v1/users/validation/rules/read-only-role-cannot-be-assigned-with-other-roles.js
Labels: Type: Feature, security fix

#3967 feat(DTFS2-7668): add bank abc to portal
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  portal/templates/_partials/before-you-start.njk
  utils/mock-data-loader/banks/index.js
Labels: Type: Fix

#3961 feat(FN-3577): persist transient record correction values (PUT)
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/put-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/fee-record-correction-transient-form-data.repo.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/index.ts
  dtfs-central-api/src/repositories/fee-record-repo/fee-record.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-transient-form-data-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-transient-form-data-payload.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/record-correction-reasons.js
  libs/common/src/constants/max-character-count.ts
  libs/common/src/sql-db-connection/migrations/1732729037950-AddFeeRecordCorrectionTransientFormDataTable.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/fee-record-correction-transient-form-data.entity.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/fee-record-correction-transient-form-data.types.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/index.ts
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-transient-form-data.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/put-fee-record-correction-transient-form-data.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/put-fee-record-correction-transient-form-data.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/validate-form-values.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/validate-form-values.ts
  utils/mock-data-loader/re-insert-mocks.js
Labels: Type: Fintech

#3963 feat(DTFS2-7669): add portal amendments feature flag middleware
  gef-ui/server/middleware/feature-flags/portal-facility-amendments.test.ts
  gef-ui/server/middleware/feature-flags/portal-facility-amendments.ts
  libs/common/src/middleware/feature-flags/deal-cancellation.ts
  libs/common/src/middleware/feature-flags/index.ts
  libs/common/src/middleware/feature-flags/validate-feature-flag-enabled.test.ts
  libs/common/src/middleware/feature-flags/validate-feature-flag-enabled.ts
  trade-finance-manager-ui/server/middleware/feature-flags/deal-cancellation.test.ts
  trade-finance-manager-ui/server/middleware/feature-flags/deal-cancellation.ts
Labels: Type: Feature

#3954 feat(DTFS2-7652): deal cancellation - gef activity entry - past/present
  dtfs-central-api/api-tests/v1/gef-deals/add-min-activities.api-test.js
  dtfs-central-api/src/constants/index.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.test.ts
  dtfs-central-api/src/repositories/portal/portal-activity.repo.test.ts
  dtfs-central-api/src/repositories/portal/portal-activity.repo.ts
  dtfs-central-api/src/services/portal/deal.service.add-deal-cancelled-activity.test.ts
  dtfs-central-api/src/services/portal/deal.service.ts
  dtfs-central-api/src/services/portal/deal.service.update-status.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-disabled/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-disabled/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-enabled/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-enabled/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/fixtures/constants.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/templates/partials/application-activity.njk
  libs/common/src/constants/portal/activity.ts
  libs/common/src/constants/portal/index.ts
  libs/common/src/types/mongo-db-models/activity-author.ts
  libs/common/src/types/mongo-db-models/deals.ts
  libs/common/src/types/mongo-db-models/index.ts
  libs/common/src/types/mongo-db-models/tfm-activity.ts
  libs/common/src/types/portal/activity.ts
  libs/common/src/types/portal/index.ts
  portal-api/api-tests/v1/gef/application-submit.api-test.js
  portal-api/api-tests/v1/gef/portal-activities.controller.api-test.js
  portal-api/src/v1/gef/controllers/portal-activities.controller.js
  portal-api/src/v1/gef/services/clone/clone-deal.service.test.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-deal.test.ts
  portal-api/src/v1/portalActivity-object-generator/activityConstants.js
  portal/templates/contract/about/components/about-submission-details.njk
  portal/templates/contract/about/components/legally-distinct-counter-indemnifier_slash_guarantor.njk
  portal/templates/contract/about/components/supplier-correspondence-address.njk
  trade-finance-manager-ui/server/controllers/case/activity/helpers/map-activities.ts
  trade-finance-manager-ui/templates/case/_macros/supplier-type.njk
  trade-finance-manager-ui/templates/case/facility/_macros/facility_details.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-agent-area.njk
  trade-finance-manager-ui/templates/case/parties/_macros/parties-indemnifier-area.njk
  utils/create-keying-sheet-tfm-facilities/mock-data/deal.ts
Labels: Type: Feature, Type: chore

#3956 feat(DTFS2-7644): add e2e test for risk expired filter
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/deal-cancellation-disabled/dashboard-facilities-filter-by-facility-stage.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/deal-cancellation-disabled/dashboard-facilities-filters.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/deal-cancellation-enabled/dashboard-facilities-filter-by-facility-stage.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/fixtures/index.js
  e2e-tests/portal/cypress/e2e/pages/dashboardFacilities.js
Labels: Type: Feature

#3962 feat(DTFS2-7525): add portal GEF facility amendments button
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/e2e-fixtures/mock-gef-facilities.js
  e2e-tests/gef/cypress/e2e/amendments/portal-amendments-disabled/make-a-change-button.spec.js
  e2e-tests/gef/cypress/e2e/amendments/portal-amendments-enabled/make-a-change-button.spec.js
  e2e-tests/gef/cypress/e2e/pages/application-preview.js
  gef-ui/component-tests/includes/application-preview/facilities.component-test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/utils/canUserAmendIssuedFacilities.test.ts
  gef-ui/server/utils/canUserAmendIssuedFacilities.ts
  gef-ui/templates/includes/application-preview/facilities.njk
  libs/common/src/constants/portal/facility-stage.ts
Labels: Type: Feature

#3964 feat(FN-3614): create fee record correction endpoint
  README.md
  doc/gotchas.md
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/post-fee-record-correction.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/fee-record-correction-transient-form-data.repo.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-requested/correction-requested.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-requested/correction-requested.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-requested/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event-type.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-fee-record-correction-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-fee-record-correction-payload.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  e2e-tests/README.md
  libs/common/src/constants/fee-record-status.ts
  libs/common/src/sql-db-connection/migrations/1732803141766-AddFeeRecordCorrectionTable.ts
  libs/common/src/sql-db-entities/fee-record-correction/fee-record-correction.entity.test.ts
  libs/common/src/sql-db-entities/fee-record-correction/fee-record-correction.entity.ts
  libs/common/src/sql-db-entities/fee-record-correction/fee-record-correction.types.ts
  libs/common/src/sql-db-entities/fee-record-correction/index.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/sql-db-entities/partial-entities/fee-record-correction-requested-by.partial-entity.ts
  libs/common/src/sql-db-entities/partial-entities/index.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction-transient-form-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/types/fee-record-correction.ts
  libs/common/src/types/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-fee-record-display-status.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-fee-record-display-status.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
Labels: Type: Feature

#3915 feat(FN-2870): send email if create utilisation report job fails
  .env.sample
  .github/workflows/test.yml
  docker-compose.yml
  dtfs-central-api/src/constants/email-template-ids.ts
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.ts
Labels: Type: Feature, Type: Fintech

#4022 feat(FN-3577): persist transient record correction values (GET)
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-reasons.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data-response-body.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-request-error-states/create-fee-record-correction-request-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  libs/common/src/test-helpers/test-cases-backend/index.ts
  libs/common/src/test-helpers/test-cases-backend/with-mongo-id-path-parameter-validation-tests.ts
  libs/common/src/test-helpers/test-cases-backend/with-sql-and-mongo-id-path-parameter-validation-tests.ts
  libs/common/src/test-helpers/test-cases-backend/with-sql-id-path-parameter-validation-tests.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-transient-form-data.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-transient-form-data.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/index.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/validate-form-values.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/create-record-correction-request-view-model.ts
Labels: Type: Fintech

#4020 feat(FN-3578): confirmation screen data
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-request-review.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-request-review.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  e2e-tests/tfm/cypress/e2e/partials/index.js
  e2e-tests/tfm/cypress/fixtures/banks.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api-response-types/fee-record-correction-request-review-response-body.ts
  trade-finance-manager-api/src/v1/api-response-types/index.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-request-review.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-request-review.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/index.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
  trade-finance-manager-ui/server/api-response-types/fee-record-correction-request-review-response-body.ts
  trade-finance-manager-ui/server/api-response-types/index.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/helpers/record-correction-reason-mapper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/helpers/record-correction-reason-mapper.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-request-information-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/record-correction-request-information-view-model.ts
Labels: Type: Feature

#4029 feat(FN-3614): add post controller for check the info page
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/post-fee-record-correction.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/post-fee-record-correction.controller.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/fee-record-status.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-status.component-test.ts
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-fee-record-display-status.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-fee-record-display-status.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-status.njk
Labels: Type: Feature

#4037 feat(FN-3612): record correction history tab setup
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/bank-utilisation-report-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/record-correction-history-no-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/keying-sheet-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/payment-details-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/premium-payments-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/record-correction-history-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/utilisation-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Feature, Type: Fintech

#4031 feat(FN-3575): decode html entities in additional info field
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  libs/common/package.json
  libs/common/src/helpers/decode-html-entities.test.ts
  libs/common/src/helpers/decode-html-entities.ts
  libs/common/src/helpers/index.ts
  package-lock.json
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/form-helpers.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/form-helpers.ts
  utils/data-migration/bss-ewcs/migrate-deals.js
  utils/package.json
Labels: Type: Fintech

#3965 chore(FN-3665): added documentation for mock data loader script
  .github/workflows/test.yml
  README.md
  e2e-tests/e2e-fixtures/dateConstants.js
  package.json
Labels: Type: chore

#4038 feat(FN-3579): add record correction data change links
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/fee-record-correction/checkFeeRecordCorrectionRequestPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/index.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
Labels: Type: Fintech

#3968 feat(DTFS2-7673): create get portal amendment endpoint
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-get.api-test.ts
  dtfs-central-api/src/helpers/amendments/filter-and-sort-completed-effective-amendments.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/aggregate-pipelines/amendments-by-facility-id-and-amendment-id.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/aggregate-pipelines/index.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.findOneAmendmentByFacilityIdAndAmendmentId.test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-amendment.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-amendment.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-put-amendments.controller.ts
  dtfs-central-api/src/v1/routes/portal-routes.js
  dtfs-central-api/src/v1/swagger-definitions/portal/portal-amendments.js
  dtfs-central-api/test-helpers/test-data/tfm-facility.ts
  libs/common/src/constants/amendments.ts
  libs/common/src/types/mongo-db-models/tfm-facilities.ts
  trade-finance-manager-api/src/v1/rest-mappings/helpers/amendment.helpers.js
Labels: Type: Feature

#4041 feat(FN-3582): record correction request emails
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/post-fee-record-correction.api-test.ts
  dtfs-central-api/src/constants/email-template-ids.ts
  dtfs-central-api/src/repositories/fee-record-repo/fee-record.repo.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.ts
  libs/common/src/helpers/fee-record-corrections/index.ts
  libs/common/src/helpers/fee-record-corrections/record-correction-reason-mapper.test.ts
  libs/common/src/helpers/fee-record-corrections/record-correction-reason-mapper.ts
  libs/common/src/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
Labels: Type: Feature, Type: Fintech

#4025 chore(DTFS2-7532): gov design library - character count updates
  e2e-tests/portal/cypress/e2e/journeys/maker-bond/bond-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/clone-deal/clone-deal.spec.js
  e2e-tests/portal/cypress/e2e/pages/bondDetails.js
  e2e-tests/portal/cypress/e2e/pages/cloneDeal.js
  gef-ui/templates/application-abandon.njk
  gef-ui/templates/application-details-comments.njk
  gef-ui/templates/partials/provided-facility.njk
  package-lock.json
  portal/templates/before-you-start/before-you-start-bank-deal.njk
  portal/templates/bond/_macros/bond-stage-issued-form-fields.njk
  portal/templates/bond/bond-details.njk
  portal/templates/contract/about/about-supply-buyer.njk
  portal/templates/contract/about/components/legally-distinct-counter-indemnifier_slash_guarantor.njk
  portal/templates/contract/about/components/supplier-name-and-address-lookup.njk
  portal/templates/contract/contract-clone.njk
  portal/templates/eligibility/eligibility-criteria.njk
  portal/templates/loan/_macros/name-field.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-add-managers-decision-cover-end-date.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-add-managers-decision-facility-value.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments-summary.njk
Labels: Type: chore

#4026 chore(DTFS2-7535-7538): gov design library - word break, role attributes
  e2e-tests/portal/cypress/e2e/journeys/maker/dashboard/deals/dashboard-empty.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/dashboard/deals/dashboard-pagination.spec.js
  e2e-tests/portal/cypress/e2e/pages/dashboardDeals.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-pagination.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/facility/facilities-pagination.spec.js
  e2e-tests/tfm/cypress/e2e/pages/dealsPage.js
  e2e-tests/tfm/cypress/e2e/pages/facilitiesPage.js
  gef-ui/public/css/styles.css
  gef-ui/public/js/govukFrontend.js.map
  gef-ui/styles/footer.scss
  gef-ui/styles/styles.scss
  gef-ui/templates/includes/application-preview/ukef-decision.njk
  gef-ui/templates/includes/footer.njk
  gef-ui/templates/includes/header.njk
  gef-ui/templates/index.njk
  portal/component-tests/test-helpers/pagination/itShouldRenderNavigationList.js
  portal/component-tests/test-helpers/pagination/itShouldRenderOuterDivAndDisplayTotalItems.js
  portal/public/css/styles.css
  portal/public/js/govukFrontend.js.map
  portal/styles/footer.scss
  portal/styles/styles.scss
  portal/styles/totals-table.scss
  portal/templates/_macros/pagination.njk
  portal/templates/_partials/footer.njk
  portal/templates/_partials/header.njk
  portal/templates/contract/components/totals-table.njk
  portal/templates/index.njk
  service-unavailable/index.html
  trade-finance-manager-ui/component-tests/test-helpers/pagination/itShouldRenderNavigationList.js
  trade-finance-manager-ui/component-tests/test-helpers/pagination/itShouldRenderOuterDivAndDisplayTotalItems.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/public/js/mojFilterHide.js
  trade-finance-manager-ui/public/js/mojFilterHide.js.map
  trade-finance-manager-ui/styles/footer.scss
  trade-finance-manager-ui/styles/typography.scss
  trade-finance-manager-ui/templates/_macros/header.njk
  trade-finance-manager-ui/templates/_macros/pagination.njk
  trade-finance-manager-ui/templates/_partials/footer.njk
  trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
  trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments-summary.njk
  trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: chore

#4032 feat(DTFS2-7523): add what needs to change page template
  gef-ui/api-tests/amendments/what-needs-to-change.api-test.ts
  gef-ui/component-tests/includes/application-preview/facilities.component-test.js
  gef-ui/component-tests/partials/amendments/what-needs-to-change.component-test.js
  gef-ui/server/constants/emails.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/what-needs-to-change.get.test.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/what-needs-to-change.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/routes/index.js
  gef-ui/server/types/deal.ts
  gef-ui/server/types/view-models/amendments/what-needs-to-change-view-model.ts
  gef-ui/templates/_macros/change-something-else-details.njk
  gef-ui/templates/includes/application-preview/facilities.njk
  gef-ui/templates/partials/amendments/what-needs-to-change.njk
Labels: Type: Feature

#4030 feat(DTFS2-7602): portal information banner facilities
  e2e-tests/gef/cypress/e2e/application/application-preview.spec.js
  e2e-tests/gef/cypress/e2e/pages/application-preview.js
  e2e-tests/gef/cypress/support/commands.js
  e2e-tests/gef/cypress/support/commands/createApplicationAndSetStatus.js
  gef-ui/templates/includes/application-preview/facilities.njk
Labels: Type: Feature

#4042 feat(DTFS2-6892): update test api error constructor
  dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-amendment.controller.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-report-data-validation.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-done.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-to-do.controller/index.test.ts
  libs/common/src/test-helpers/test-api-error.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/delete-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/get-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/update-deal-cancellation.controller.test.ts
Labels: Type: Feature

#4047 fix(DTFS2-7684): gov design library - update beta phase banner copy
  e2e-tests/gef/cypress/e2e/page-header.spec.js
  e2e-tests/gef/cypress/e2e/pages/page-banner.js
  e2e-tests/portal/cypress/e2e/journeys/portal-header.spec.js
  e2e-tests/portal/cypress/e2e/pages/header.js
  e2e-tests/tfm/cypress/e2e/journeys/login/login.spec.js
  e2e-tests/tfm/cypress/e2e/partials/header.js
  gef-ui/templates/includes/beta-banner.njk
  gef-ui/templates/partials/application-activity.njk
  gef-ui/templates/partials/application-preview.njk
  portal/templates/_partials/beta-banner.njk
  trade-finance-manager-ui/templates/_partials/beta-banner.njk
Labels: Type: chore

#4054 fix(DTFS2-7694): argument as an object
  azure-functions/acbs-function/src/functions/acbs-amend-facility-master-record.js
  azure-functions/acbs-function/src/functions/acbs-issue-facility.js
  azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
  azure-functions/acbs-function/src/functions/activity-get-facility-master.js
Labels: Type: ACBS, Type: Fix

#4048 chore(DTFS2-7565): remove service-unavailable directory
  README.md
  service-unavailable/assets/fonts/bold-affa96571d-v2.woff
  service-unavailable/assets/fonts/bold-b542beb274-v2.woff2
  service-unavailable/assets/fonts/light-94a07e06a1-v2.woff2
  service-unavailable/assets/fonts/light-f591b13f7d-v2.woff
  service-unavailable/assets/images/favicon.ico
  service-unavailable/assets/images/govuk-apple-touch-icon-152x152.png
  service-unavailable/assets/images/govuk-apple-touch-icon-167x167.png
  service-unavailable/assets/images/govuk-apple-touch-icon-180x180.png
  service-unavailable/assets/images/govuk-apple-touch-icon.png
  service-unavailable/assets/images/govuk-crest-2x.png
  service-unavailable/assets/images/govuk-crest.png
  service-unavailable/assets/images/govuk-logotype-crown.png
  service-unavailable/assets/images/govuk-logotype-tudor-crown.png
  service-unavailable/assets/images/govuk-mask-icon.svg
  service-unavailable/assets/images/govuk-opengraph-image.png
  service-unavailable/govuk-frontend-5.7.1.min.css
  service-unavailable/index.html
Labels: Type: chore

#4057 fix(DTFS2-7616): manual dev deployment
  .github/workflows/deployment.yml
  .github/workflows/test.yml
Labels: security fix

#4060 fix(DTFS2-7616): effecient deployment
  .github/actions/functions/action.yml
  .github/actions/mssql/action.yml
  .github/actions/webapp/action.yml
  .github/workflows/deployment.yml
  .github/workflows/release.yml
Labels: Type: Fix

#4033 feat(DTFS2-7653): scheduled deal cancellation - gef activity entries
  dtfs-central-api/src/repositories/portal/portal-activity.repo.test.ts
  dtfs-central-api/src/services/portal/deal.service.add-gef-deal-cancellation-pending-activity.test.ts
  dtfs-central-api/src/services/portal/deal.service.add-gef-deal-cancelled-activity.test.ts
  dtfs-central-api/src/services/portal/deal.service.ts
  dtfs-central-api/src/services/portal/deal.service.update-status.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.getTfmDealCancellationResponse.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.processPendingCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  libs/common/src/constants/portal/activity.ts
  libs/common/src/types/mongo-db-models/activity-author.ts
  libs/common/src/types/portal/activity.ts
Labels: Type: Feature, Type: chore

#4019 feat(DTFS2-7659): deal cancellation - gef activity entry - design update
  e2e-tests/gef/cypress/e2e/application/application-activities-AIN.spec.js
  e2e-tests/gef/cypress/e2e/application/application-activities-MIA.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-disabled/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-disabled/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-enabled/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-enabled/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/pages/application-activities.js
  e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
  gef-ui/component-tests/partials/application-activity.component-test.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/utils/mocks/mock-author.js
  gef-ui/templates/_macros/application-activity/activity-html.njk
  gef-ui/templates/_macros/application-activity/deal-cancelled.njk
  gef-ui/templates/_macros/application-activity/facility.njk
  gef-ui/templates/_macros/application-activity/status-change.njk
  gef-ui/templates/partials/application-activity.njk
  libs/common/src/constants/date-formats.ts
  trade-finance-manager-api/src/v1/__mocks__/mock-author.js
  trade-finance-manager-ui/templates/case/activity/activity.njk
Labels: Type: Feature, Type: chore

#4066 fix(DTFS2-7616): removed ref attribute
  .github/workflows/release.yml
Labels: Type: Fix

#4068 Chore/merge release 2.5.0 to main
  .github/workflows/README.md
  azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
  azure-functions/acbs-function/src/functions/activity-get-facility-master.js
  portal/README.md
Labels: Type: chore

#4069 chore(merge): release-2.5.0-gamma to main
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-validate-utilisation-report-data.api-test.ts
  dtfs-central-api/src/constants/batch-saving.ts
  dtfs-central-api/src/constants/index.ts
  dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts
  dtfs-central-api/src/helpers/execute-with-sql-transaction.ts
  dtfs-central-api/src/helpers/get-keying-sheet-calculation-facility-values.test.ts
  dtfs-central-api/src/helpers/get-keying-sheet-calculation-facility-values.ts
  dtfs-central-api/src/helpers/get-previous-report-period.test.ts
  dtfs-central-api/src/helpers/get-previous-report-period.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/services/facility-utilisation-data/facility-utilisation-data.service.test.ts
  dtfs-central-api/src/services/facility-utilisation-data/facility-utilisation-data.service.ts
  dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-fixed-fee.test.ts
  dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-fixed-fee.ts
  dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-utilisation-and-fixed-fee.test.ts
  dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-utilisation-and-fixed-fee.ts
  dtfs-central-api/src/services/facility-utilisation-data/helpers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.ts
  dtfs-central-api/src/types/tfm/tfm-facility.ts
  dtfs-central-api/test-helpers/test-data/tfm-facility.ts
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/generate-fixed-fee-adjustment-with-amendments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/generate-keying-sheet.spec.js
  e2e-tests/ukef/cypress/fixtures/tfm-facility.js
  libs/common/src/test-helpers/mock-data/utilisation-report-mock-csv-data.ts
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.test.js
  portal/server/helpers/filterReportJsonToRelevantKeys.js
  portal/server/helpers/filterReportJsonToRelevantKeys.test.js
  portal/templates/_partials/before-you-start.njk
  utils/mock-data-loader/banks/index.js
Labels: Type: chore

#4078 fix(DTFS2-7616): corrected mssql schema migration
  .github/actions/mssql/action.yml
  .github/workflows/deployment.yml
  .github/workflows/release.yml
Labels: Type: Fix

#4072 fix(DTFS2-7694): facility issuance reconciliation with TFM
  trade-finance-manager-api/src/v1/__mocks__/mock-durable-tasks.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.test.js
Labels: Type: Fix

#4079 feat(FN-3612): hide record correction tab behind feature flag
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-disabled/record-correction-tab-not-visible.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-history-no-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/bank-utilisation-report-page.spec.js
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Feature, Type: Fintech

#4076 feat(FN-3581): add record correction request sent screen
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/post-fee-record-correction.api-test.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/fee-record-correction/feeRecordCorrectionRequestSentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/index.js
  trade-finance-manager-api/src/v1/api-response-types/fee-record-correction-response-body.ts
  trade-finance-manager-api/src/v1/api-response-types/index.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-transient-form-data.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/post-fee-record-correction.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/post-fee-record-correction.controller.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/request-sent.component-test.ts
  trade-finance-manager-ui/server/api-response-types/index.ts
  trade-finance-manager-ui/server/api-response-types/post-fee-record-correction-response-body.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/request-sent/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/request-sent/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/express-session.d.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-request-sent-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/request-sent.njk
  trade-finance-manager-ui/test-helpers/get-fee-record-response-body.ts
  trade-finance-manager-ui/test-helpers/index.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/index.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/record-correction-request-sent-view-model.ts
Labels: Type: Fintech

#4055 feat(DTFS2-7671): add amendments get endpoint to portal-api
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-amendment.controller.test.ts
  gef-ui/server/services/__mocks__/api.js
  gef-ui/server/services/__tests__/api.test.js
  gef-ui/server/services/api.js
  libs/common/src/schemas/portal-amendment.ts
  libs/common/src/types/portal/amendment.ts
  libs/common/src/types/portal/index.ts
  portal-api/api-tests/types/test-user.ts
  portal-api/api-tests/v1/gef/amendments/amendments.get.api-test.ts
  portal-api/api-tests/v1/gef/amendments/get-amendment-url.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/amendments/get-amendment.controller.ts
  portal-api/src/v1/controllers/amendments/get-amendment.test.ts
  portal-api/src/v1/gef/routes.js
  portal-api/src/v1/validation/route-validators/route-validators.js
Labels: Type: Feature

#4084 chore(DTFS2-7717): visit TFM url in deal cancellation tests
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-pending-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-pending-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/deal-cancellation-maker-unable-issue-facility.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-pending-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-pending-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/deal-cancellation-maker-unable-issue-facility.spec.js
  libs/common/src/constants/tfm/index.ts
  libs/common/src/constants/tfm/url.ts
Labels: Type: chore

#4091 chore(DTFS2-7708): fixed incorrect dependabot directory name
  .github/dependabot.yml
Labels: Type: Bug, Type: chore

#4085 feat(DTFS2-7705): get cover end date template and add unit tests
  gef-ui/api-tests/amendments/cover-end-date.api-test.ts
  gef-ui/component-tests/partials/amendments/cover-end-date.component-test.ts
  gef-ui/server/controllers/amendments/cover-end-date/get-cover-end-date.test.ts
  gef-ui/server/controllers/amendments/cover-end-date/get-cover-end-date.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/cover-end-date-view-model.ts
  gef-ui/server/utils/mocks/mock-applications.js
  gef-ui/templates/partials/amendments/cover-end-date.njk
Labels: Type: Feature

#4095 fix(DTFS2-7616): added ms notifications web hook
  .github/workflows/deployment.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/release.yml
  .github/workflows/staging_infrastructure.yml
Labels: Type: chore

#4097 chore(deps): dependencies updates
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: chore

#4094 feat(FN-3581): fix "request sent" email line break
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/request-sent.component-test.ts
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/styles/typography.scss
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/request-sent.njk
Labels: Type: Fintech

#4098 fix(DTFS2-7728): only active users are mapped
  .github/workflows/development_infrastructure.yml
  .github/workflows/feature_deploy.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  azure-functions/acbs-function/package.json
  dtfs-central-api/Dockerfile
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/Dockerfile
  external-api/package.json
  gef-ui/Dockerfile
  gef-ui/package.json
  libs/common/package.json
  libs/common/src/constants/tfm/index.ts
  libs/common/src/constants/tfm/user-status.ts
  package-lock.json
  package.json
  portal-api/Dockerfile
  portal-api/package.json
  portal/Dockerfile
  portal/package.json
  reverse-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-api/api-tests/api-test-users.ts
  trade-finance-manager-api/api-tests/types/test-user.ts
  trade-finance-manager-api/api-tests/v1/teams/get-team-members.api-test.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/constants/index.js
  trade-finance-manager-api/src/constants/user.js
  trade-finance-manager-api/src/v1/__mocks__/mock-users.js
  trade-finance-manager-api/src/v1/controllers/team.controller.js
  trade-finance-manager-api/src/v1/controllers/team.controller.test.js
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
  trade-finance-manager-api/src/v1/repo/user.repo.create-user.test.ts
  trade-finance-manager-api/src/v1/repo/user.repo.ts
  trade-finance-manager-api/src/v1/repo/user.repo.update-user-by-id.test.ts
  trade-finance-manager-api/src/v1/services/user.service.upsert-user-from-entra-id-user.test.ts
  trade-finance-manager-api/src/v1/teams/routes.js
  trade-finance-manager-ui/Dockerfile
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: Fix

#4099 chore(deps): dependencies updates
  dtfs-central-api/package.json
  package-lock.json
  package.json
  portal-api/package.json
Labels: Type: chore

#4100 fix(DTFS2-3236-3455): upgraded dependencies
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  portal/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: Fix
