Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-05, with the labels that each got.

#3054 feat(DTFS2-7119): add audit logs to portal-api auth router
  portal-api/api-tests/v1/deals/expectAddedFields.js
  portal-api/api-tests/v1/eligibility-criteria/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/mandatory-criteria/mandatory-criteria.api-test.js
  portal-api/api-tests/v1/users/reset-password.api-test.js
  portal-api/src/v1/controllers/banks.controller.js
  portal-api/src/v1/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/controllers/mandatoryCriteria.controller.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/controller.test.js
  portal-api/src/v1/users/login.controller.js
  portal-api/src/v1/users/login.controller.test.js
  portal-api/src/v1/users/reset-password.controller.js
  portal-api/src/v1/users/routes.js
  portal-api/src/v1/users/routes.test.js
Labels: Type: Feature

#3063 feat(FN-1615): add seeder for fee records
  .github/workflows/test.yml
  cspell.json
  doc/sql-db.md
  utils/sql-db-seeder/src/fee-record/fee-record.helper.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.helper.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.seed.ts
Labels: Type: Fintech

#3056 feat(FN-2734): add batch save to migrator
  .github/workflows/test.yml
  utils/data-migration/sql/utilisation-reports/helpers/transformers.helper.ts
  utils/data-migration/sql/utilisation-reports/index.ts
Labels: Type: Fintech

#3052 fix(DTFS2-6888): deal validation before submitting to ACBS
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  portal-api/package.json
  portal/package.json
  portal/server/controllers/dashboard/deals/index.test.js
  portal/server/controllers/dashboard/facilities/index.test.js
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deal-controller.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/constants/deals.js
  trade-finance-manager-api/src/constants/facilities.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.test.js
  trade-finance-manager-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.tasks.js
  trade-finance-manager-api/src/v1/controllers/estore.controller.js
  trade-finance-manager-api/src/v1/controllers/party.controller.js
  trade-finance-manager-api/src/v1/controllers/party.controller.test.js
  trade-finance-manager-api/src/v1/controllers/should-update-deal-from-MIA-to-MIN.js
  trade-finance-manager-api/src/v1/helpers/can-submit-to-acbs.js
  trade-finance-manager-api/src/v1/helpers/can-submit-to-acbs.test.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.js
  trade-finance-manager-api/src/v1/helpers/is-facility-unissued-acbs.js
  trade-finance-manager-api/src/v1/helpers/is-facility-unissued-acbs.test.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
  utils/mock-data-loader/package.json
  utils/package.json
Labels: Type: ACBS, Type: Fix

#3093 fix(deployment-script): standardised deployment script
  .env.sample
  .github/workflows/feature_deploy.yml
  .github/workflows/test.yml
  doc/sql-db.md
  utils/mock-data-loader/.env.sample
  utils/mock-data-loader/database/database.config.js
  utils/sql-db-seeder/.env.sample
  utils/sql-db-seeder/src/helpers/get-from-mongo-db.ts
Labels: Type: chore

#3099 fix(deployment-script): conditional database deployment script
  .github/workflows/deployment.yml
Labels: Type: Fix

#3101 chore: update-feature-deploy-workflow-trigger
  .github/workflows/feature_deploy.yml
Labels: Type: Fintech

#3070 feat(FN-1615): add premium payments table
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/package.json
  dtfs-central-api/src/helpers/fee-record.helper.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  dtfs-central-api/src/v1/swagger-definitions/currency.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-report-reconciliation-details.js
  libs/common/package.json
  libs/common/src/constants/fee-record-status.ts
  libs/common/src/constants/index.ts
  libs/common/src/helpers/currency.ts
  libs/common/src/helpers/index.ts
  libs/common/src/sql-db-connection/migrations/1714741183254-AddFeeRecordStatusColumn.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.test.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  libs/common/src/types/currency.ts
  libs/common/src/types/utilisation-reports.ts
  package-lock.json
  portal-api/api-tests/sql-db-helper.ts
  trade-finance-manager-api/api-tests/v1/amendments/create-amendment-tfm-object-on-amendment-completion.api-test.js
  trade-finance-manager-api/src/constants/facilities.js
  trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-api/src/v1/controllers/should-update-deal-from-MIA-to-MIN.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/rest-mappings/deal-with-amendment-bss.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/deal-with-amendment-gef.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/helpers/amendment.helpers.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/deal/mapTotals.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/deal/mapTotals.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityValue.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityValue.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityValueExporterCurrency.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapUkefExposure.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/fee-record-status.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/api-response-types/index.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  utils/mock-data-loader/gef/facilities.js
  utils/sql-db-seeder/src/fee-record/fee-record.helper.ts
Labels: Type: Fintech

#3107 feat(FN-1615): add default value for fee record status column
  libs/common/src/sql-db-connection/migrations/1715613302494-AddFeeRecordStatusColumn.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
Labels: Type: Fintech

#3110 fix(deployment): added release-2.0 to deployment
  .github/workflows/deployment.yml
Labels: Type: Fix

#3111 fix(deployment-script): changed release-1.5 to release-2.9
  .github/workflows/deployment.yml
Labels: Type: Fix

#3112 fix(deployment): updated release-1.5 to release-2.0
  .github/workflows/deployment.yml
  .github/workflows/test.yml
Labels: Type: Fix

#2697 chore(main): release 2.0.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3113 fix(deployment): change release-1.5 to release-2.0
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
Labels: Type: Fix

#3115 fix(test.yml): ensure variable names are correct
  .github/workflows/test.yml
Labels: Type: Fix

#3116 fix(release-2.0): formatt `README.md`
  .github/workflows/README.md
  azure-functions/README.md
  azure-functions/acbs-function/README.md
  dtfs-central-api/README.md
  e2e-tests/README.md
  external-api/README.md
  gef-ui/README.md
  reverse-proxy/README.md
  trade-finance-manager-api/README.md
  trade-finance-manager-ui/README.md
  utils/README.md
  utils/data-migration/README.md
Labels: Type: Fix

#3109 feat(FN-1615): fix migration adding status to work with ledger tables
  libs/common/src/sql-db-connection/migrations/1715613302494-AddFeeRecordStatusColumn.ts
Labels: Type: Fintech

#3091 feat(FN-1488): add find reports by year page
  trade-finance-manager-api/api-tests/v1/banks/get-all-banks.api-test.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api-response-types/bank-response.ts
  trade-finance-manager-api/src/v1/api-response-types/index.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/banks.controller.js
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/component-tests/utilisation-reports/find-utilisation-reports-by-year.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/previous-bank-reports-by-year.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/constants/index.js
  trade-finance-manager-ui/server/constants/regex.js
  trade-finance-manager-ui/server/constants/regex.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/search-input-validator.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/search-input-validator.ts
  trade-finance-manager-ui/server/helpers/validateIds.js
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/test-mocks/mock-banks.ts
  trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.ts
  trade-finance-manager-ui/server/types/banks.ts
  trade-finance-manager-ui/server/types/primary-navigation-key.ts
  trade-finance-manager-ui/server/types/view-models/find-utilisation-reports-by-year-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/server/types/view-models/previous-bank-reports-by-year-view-model.ts
  trade-finance-manager-ui/templates/case/_macros/back-link.njk
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/find-utilisation-reports-by-year.njk
  trade-finance-manager-ui/templates/utilisation-reports/previous-bank-reports-by-year.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
  trade-finance-manager-ui/test-helpers/test-data/bank-report-period-schedule.ts
  trade-finance-manager-ui/test-helpers/test-data/bank.ts
Labels: Type: Fintech

#3103 feat(FN-1865): add db:seed:reset command to reset sql seeder
  doc/sql-db.md
  package.json
  utils/package.json
  utils/sql-db-seeder/src/helpers/get-from-mongo-db.ts
  utils/sql-db-seeder/src/mongo-db-client/index.ts
  utils/sql-db-seeder/src/reset-seeder.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.helper.ts
Labels: Type: Fintech

#3119 fix(github-actions): updated deprecated gha package
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/sca.yml
  gef-ui/package.json
  package-lock.json
  package.json
  portal/package.json
  trade-finance-manager-ui/package.json
Labels: Type: Fix

#3121 feat(FN-1692): update fee record statuses
  libs/common/src/constants/fee-record-status.ts
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/fee-record-status.component-test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-status.njk
  trade-finance-manager-ui/test-helpers/fee-record-item.ts
  trade-finance-manager-ui/test-helpers/index.ts
Labels: Type: Fintech

#3124 fix(FN-1615): add update query to fee record status migration
  libs/common/src/sql-db-connection/migrations/1715613302494-AddFeeRecordStatusColumn.ts
Labels: Type: Fintech

#3123 feat(FN-1692): add select all checkbox and hidden js elements
  trade-finance-manager-ui/component-tests/_macros/select-all-table-cell-checkbox.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/enableSelectAllTableCheckbox.js
  trade-finance-manager-ui/public/js/enableSelectAllTableCheckbox.js.map
  trade-finance-manager-ui/scripts/enable-select-all-table-checkbox.js
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/_macros/select-all-table-cell-checkbox.njk
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: Fintech

#3125 feat(FN-1615): update the formatting for the currency and amount string
  libs/common/src/helpers/currency.test.ts
  libs/common/src/helpers/currency.ts
Labels: Type: Fintech

#3126 chore(DTFS2-7156): add env copy script
  package.json
  utils/copy-env-vars/index.ts
  utils/package.json
Labels: Type: chore

#3128 feat(FN-1616): add sort by status to premium payments table
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
Labels: Type: Fintech

#3064 feat(FN-2420): ukef utilisation report email notifications to multiple addresses
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/feature_deploy.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  package-lock.json
  portal-api/package.json
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.test.js
  portal-api/src/v1/errors/index.js
  portal-api/src/v1/errors/invalid-report-status.error.test.ts
  portal-api/src/v1/errors/invalid-report-status.error.ts
  portal-api/src/v1/services/utilisation-report/azure-file-service.js
  portal-api/src/v1/services/utilisation-report/azure-file-service.test.js
  portal-api/src/v1/services/utilisation-report/email-service.test.ts
  portal-api/src/v1/services/utilisation-report/email-service.ts
  portal-api/src/v1/validation/utilisation-report/utilisation-report-validator.test.ts
  portal-api/src/v1/validation/utilisation-report/utilisation-report-validator.ts
Labels: Type: Fintech

#3129 feat(FN-1616): sort premium payments table
  package-lock.json
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-key-to-currency-and-amount-sort-value-map-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-key-to-currency-and-amount-sort-value-map-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/test-helpers/fee-record-view-model-item.ts
  trade-finance-manager-ui/test-helpers/index.ts
Labels: Type: Fintech

#3131 feat(dtfs2-7116): add tag for trusted user
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
  e2e-tests/portal/cypress/e2e/pages/admin/users/users.js
  libs/common/src/schemas/audit-database-record.test.ts
  portal/templates/admin/dashboard.njk
Labels: Type: Feature

#3135 feat(FN-1697): add a payment button
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.js
  trade-finance-manager-ui/public/js/enableSelectAllTableCheckbox.js
  trade-finance-manager-ui/public/js/enableSelectAllTableCheckbox.js.map
  trade-finance-manager-ui/scripts/enable-select-all-table-checkbox.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/search-input-validator.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-add-payment-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-add-payment-error-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-and-clear-add-payment-fields-from-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-and-clear-add-payment-fields-from-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/middleware/index.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/express-session.d.ts
  trade-finance-manager-ui/server/types/view-models/error-summary-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/_macros/table-cell-checkbox.njk
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/fee-record-view-model-item.ts
Labels: Type: Fintech

#3106 feat(FN-1615): add fee record state machine
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/add-a-payment/add-a-payment.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/add-a-payment/add-a-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/add-a-payment/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/base-fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event-type.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
Labels: Type: Fintech

#3158 feat(FN-2882): update premium payments table alignment
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
Labels: Type: Fintech

#3141 feat(dtfs2-7067): update portal footer
  .github/workflows/development_infrastructure.yml
  .github/workflows/dns.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  e2e-tests/package.json
  e2e-tests/portal/cypress.config.js
  e2e-tests/portal/cypress/e2e/journeys/login/reset-password.spec.js
  gef-ui/server/nunjucks-configuration/index.js
  gef-ui/templates/includes/contact-us.njk
  gef-ui/templates/includes/footer.njk
  package-lock.json
  portal/component-tests/componentRenderer.js
  portal/component-tests/login/temporarily-suspended.component-test.js
  portal/component-tests/login/we-have-sent-you-another-link.component-test.js
  portal/component-tests/pageRenderer.js
  portal/component-tests/test-helpers/with-contact-us-email-address.component-tests.js
  portal/server/nunjucks-configuration/index.js
  portal/templates/_partials/contact-us.njk
  portal/templates/_partials/footer.njk
  portal/templates/accessibility-statement.njk
  portal/templates/login/index.njk
  service-unavailable/index.html
Labels: Type: Feature

#3152 feat(dtfs2-7069): update dtfs helpdesk hyperlink
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  trade-finance-manager-ui/server/nunjucks-configuration/index.js
  trade-finance-manager-ui/templates/_partials/footer.njk
  trade-finance-manager-ui/templates/accessibility-statement.njk
Labels: Type: Feature

#3160 feat(FN-1697): implement payment added to fee record event
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-added-to-fee-record/payment-added-to-fee-record.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-added-to-fee-record/payment-added-to-fee-record.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
Labels: Type: Fintech

#3159 feat(FN-2900): update local SQL to use ledger tables
  doc/sql-db.md
  libs/common/package.json
  libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts
  libs/common/src/sql-db-connection/reset-database.sh
  package-lock.json
Labels: Type: Fintech

#3171 feat(FN-1739): add payment table
  libs/common/src/sql-db-connection/migrations/1716990167763-AddPaymentTable.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/sql-db-entities/payment/index.ts
  libs/common/src/sql-db-entities/payment/payment.entity.ts
  libs/common/src/sql-db-entities/payment/payment.types.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/payment.entity.mock-builder.ts
Labels: Type: Fintech

#3174 feat(FN-1488): handle find reports by year form submission with empty params
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.ts
Labels: Type: Fintech
