Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-10, with the labels that each got.

#3596 chore(DTFS2-7439): align some unit test naming conventions
  dtfs-central-api/src/helpers/fee-record-matching.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.test.ts
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
  portal-api/src/v1/users/validation/rules/current-password-must-match.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-8-characters.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-lowercase.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-number.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-special-character.test.js
  portal-api/src/v1/users/validation/rules/passwords-at-least-one-uppercase.test.js
  portal-api/src/v1/users/validation/rules/passwords-cannot-be-reused.test.js
  portal-api/src/v1/users/validation/rules/passwords-must-match.test.js
  trade-finance-manager-api/api-tests/v1/amendments/update-tfm-deal-amendment-completion.api-test.js
  trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-bank-request-date.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-effective-from-date.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.test.ts
  trade-finance-manager-ui/server/helpers/date.test.js
Labels: Type: chore

#3541 chore(tests): split up e2e tests - tfm case
  .github/workflows/test.yml
  e2e-tests/tfm/cypress/e2e/journeys/case/AIN/deal-AIN.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/GEF/deal-GEF.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/MIA/deal-MIA.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/agent/agent.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond/bond-beneficiary.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond/bond-issuer.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/buyer/buyer.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/exporter/exporter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/indemnifier/indemnifier.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/tasks/AIN/tasks-AIN.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/tasks/MIA/tasks-MIA-EC-11-false.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/tasks/MIA/tasks-MIA-all-tasks.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/tasks/MIA/tasks-MIA.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-bss.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
Labels: Type: chore

#3597 feat(DTFS2-7296): update db on bank request date page
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
Labels: Type: Feature

#3595 feat(FN-3450-51): utilisation report page read-only banner and conditional text
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/reconcile-fee-records.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportsSummaryPage.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/is-pdc-reconcile-user.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/is-pdc-reconcile-user.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-reports-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/pdc-read-only-notification-banner.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk
Labels: Type: Feature, Type: Fintech

#3604 feat(DTFS2-7300): update db on effective from date page
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts
Labels: Type: Feature

#3631 feat(DTFS2-7300): fix effective from date page test
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
Labels: Type: Feature

#3630 chore(DTFS2-7427): remove FFs from e2e test config
  e2e-tests/gef/cypress.config.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-disabled/provided-facility-back-link.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/provided-facility-back-link.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/provided-facility.spec.js
  e2e-tests/tfm/cypress.config.js
Labels: Type: chore

#3599 fix(FN-3494): utilisation report exporter name fix
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-base-currency-errors/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-base-currency-errors/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-errors-for-mismatched-facility-values/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-errors-for-mismatched-facility-values/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-facility-utilisation-errors/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-facility-utilisation-errors/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
  e2e-tests/portal/cypress/fixtures/invalid-matching-utilisation-report-February_2023_monthly.csv
  e2e-tests/portal/cypress/fixtures/invalid-matching-utilisation-report-February_2024_quarterly.csv
Labels: Type: Fix, Type: Fintech

#3601 feat(FN-3449): utilisation report premium payments tab copy update
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Feature

#3575 feat(dtfs2-6892): add redirect to entra id login url
  .env.sample
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  cspell.json
  libs/common/src/constants/api-error-code.ts
  libs/common/src/errors/index.ts
  libs/common/src/errors/user-session-not-defined.error.ts
  libs/common/src/errors/user-session-not-defined.test.ts
  libs/common/src/errors/user-session.error.ts
  libs/common/src/errors/user-token-not-defined.error.ts
  libs/common/src/errors/user-token-not-defined.test.ts
  package-lock.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/configs/entra-id.config.test.ts
  trade-finance-manager-ui/server/configs/entra-id.config.ts
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.get-login.test.ts
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.logout.test.ts
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.post-login.test.ts
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.test.js
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.ts
  trade-finance-manager-ui/server/controllers/login/loginSso/login.controller.get-login.test.ts
  trade-finance-manager-ui/server/controllers/login/loginSso/login.controller.get-logout.test.ts
  trade-finance-manager-ui/server/controllers/login/loginSso/login.controller.ts
  trade-finance-manager-ui/server/helpers/express-session.test.ts
  trade-finance-manager-ui/server/helpers/express-session.ts
  trade-finance-manager-ui/server/routes/login/configs/loginNonSso.ts
  trade-finance-manager-ui/server/routes/login/configs/loginSso.ts
  trade-finance-manager-ui/server/services/entra-id.service.get-auth-code-url.test.ts
  trade-finance-manager-ui/server/services/entra-id.service.ts
  trade-finance-manager-ui/server/third-party-apis/entra-id.api.get-authority-metadata-url.test.ts
  trade-finance-manager-ui/server/third-party-apis/entra-id.api.ts
  trade-finance-manager-ui/server/types/entra-id.ts
  trade-finance-manager-ui/server/types/express-session.d.ts
  trade-finance-manager-ui/test-helpers/mocks/entra-id.api.mock.builder.ts
  trade-finance-manager-ui/test-helpers/mocks/entra-id.config.mock.builder.ts
  trade-finance-manager-ui/test-helpers/mocks/extra-id.service.mock.builder.ts
  trade-finance-manager-ui/test-helpers/mocks/index.ts
  trade-finance-manager-ui/test-helpers/mocks/mock-builder.mock.builder.ts
Labels: Type: Feature

#3635 fix(DTFS2-7317): set mongodb to version range 4.17.2 and 4.2.0 on dockerfile
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/package.json
  mongodb/Dockerfile
  package-lock.json
  portal-api/package.json
  trade-finance-manager-api/package.json
Labels: Type: chore, Type: Fix

#3598 feat(DTFS2-7440): standardised docker setup
  .github/workflows/test.yml
  azure-functions/acbs-function/Dockerfile
  azure-functions/acbs-function/docker-compose.yml
  azure-functions/acbs-function/package.json
  docker-compose.yml
  dtfs-central-api/Dockerfile
  external-api/Dockerfile
  gef-ui/Dockerfile
  package-lock.json
  package.json
  portal-api/Dockerfile
  portal-api/package.json
  portal/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/Dockerfile
Labels: Type: Feature, Type: chore

#3582 feat(FN-2311): refactor existing premium payments UI logic
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-fee-records-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/extract-query-and-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/extract-query-and-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/handle-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/handle-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3573 feat(FN-2311): add backend payment details filtering
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups-by-facility-id.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups-by-facility-id.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/parse-filters.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/parse-filters.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  libs/common/src/constants/currency.ts
  libs/common/src/helpers/validation.test.ts
  libs/common/src/helpers/validation.ts
  libs/common/src/types/utilisation-reports.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/validate-payment-form-values.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.ts
Labels: Type: Fintech

#3636 feat(DTFS2-7446): add delete cancellation endpoint in tfm-api
  trade-finance-manager-api/api-tests/api.ts
  trade-finance-manager-api/api-tests/types/test-api.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.delete.api-test.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/delete-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/delete-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/deals/routes.js
Labels: Type: Feature

#3639 feat(DTFS2-7297): add deal cancellation check details page
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/check-details.spec.js
  e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/check-details.js
  trade-finance-manager-ui/component-tests/case/cancellation/check-details.component-test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/server/routes/case/cancellation.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/check-details-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/templates/case/cancellation/check-details.njk
  trade-finance-manager-ui/test-helpers/test-data/check-answers-view-model.ts
Labels: Type: Feature

#3640 feat(DTFS2-7445): add cancel cancellation template
  package-lock.json
  trade-finance-manager-ui/component-tests/case/cancellation/bank-request-date.component-test.ts
  trade-finance-manager-ui/component-tests/case/cancellation/cancel.component-test.ts
  trade-finance-manager-ui/component-tests/case/cancellation/effective-from-date.component-test.ts
  trade-finance-manager-ui/component-tests/case/cancellation/reason-for-cancelling.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-group-input.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/add-payment.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/add-to-an-existing-payment.component-test.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.ts
  trade-finance-manager-ui/server/routes/case/cancellation.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/cancel-cancellation-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/templates/case/cancellation/cancel.njk
  trade-finance-manager-ui/test-helpers/test-data/index.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/add-payment-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/add-to-an-existing-payment-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/bank-request-date-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/cancel-cancellation-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/effective-from-date-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/index.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/reason-for-cancelling-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/index.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/payment-group-inputs-view-model.ts
Labels: Type: Feature

#3638 feat(FN-2311): fix broken premium payments column sorting
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/sort-premium-payments.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/find-utilisation-reports-by-year.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3644 fix(DTFS2-7444): eStore void job validation
  external-api/src/cron/index.ts
  external-api/src/helpers/cron.ts
Labels: Type: Fix

#3645 fix(DTFS2-7444): added void cron job validation
  external-api/src/cron/index.ts
  external-api/src/helpers/cron.ts
Labels: Type: Fix

#3658 chore(DTFS2-7463): `release-2.3` merge to `prod`
  portal-api/api-tests/v1/gef/external-api.api-test.js
Labels: chore

#3655 fix(DTFS2-6616): facility covenant and guarantee record variable correction
  azure-functions/acbs-function/src/functions/acbs-amend-facility-covenant-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-guarantee-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  azure-functions/acbs-function/src/functions/activity-update-facility-covenant.js
  azure-functions/acbs-function/src/functions/activity-update-facility-guarantee.js
Labels: Type: Fix

#3642 feat(DTFS2-7414): add continue cancellation button
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-cancellation-enabled/deal-cancellation-button.spec.js
  trade-finance-manager-ui/component-tests/case/deal/deal.component-test.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/templates/case/deal/deal.njk
Labels: Type: Feature

#3653 fix(DTFS2-7444): edge case estore exceptional handling
  external-api/api-tests/v1/eStore.api-test.ts
  external-api/src/cron/eStoreDocumentsCreationJob.cron.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  external-api/src/v1/routes/external-apis.route.ts
Labels: Type: Fix

#3660 fix(DTFS2-7463): merge prod changes to main
  portal-api/src/external-api/__mocks__/countries.js
  trade-finance-manager-ui/templates/_partials/footer.njk
Labels: Type: chore

#3633 chore(main): release 2.3.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3637 feat(dtfs2-6892): handle entra redirect to accept sso redirect form
  external-api/package.json
  package-lock.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/public/js/ssoRedirectAutoSubmit.js
  trade-finance-manager-ui/public/js/ssoRedirectAutoSubmit.js.map
  trade-finance-manager-ui/scripts/sso-redirect-auto-submit.ts
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.post-sso-redirect.test.ts
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.ts
  trade-finance-manager-ui/server/controllers/login/loginSso/index.ts
  trade-finance-manager-ui/server/generateApp.js
  trade-finance-manager-ui/server/routes/auth/configs/index.get-unauthenticated-auth-router.test.ts
  trade-finance-manager-ui/server/routes/auth/configs/index.ts
  trade-finance-manager-ui/server/routes/auth/configs/unauthenticated-auth-sso.ts
  trade-finance-manager-ui/server/routes/auth/index.ts
  trade-finance-manager-ui/server/routes/login/configs/index.test.ts
  trade-finance-manager-ui/server/routes/login/configs/index.ts
  trade-finance-manager-ui/server/routes/login/configs/login-non-sso.ts
  trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
  trade-finance-manager-ui/server/routes/user/configs/index.test.ts
  trade-finance-manager-ui/server/routes/user/configs/index.ts
  trade-finance-manager-ui/server/routes/user/configs/user-non-sso.ts
  trade-finance-manager-ui/server/routes/user/configs/user-sso.ts
  trade-finance-manager-ui/server/routes/user/configs/userSso.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.decoded-auth-code-request-state.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.entra-id-auth-code-redirect-response-body-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.ts
  trade-finance-manager-ui/server/schemas/index.ts
  trade-finance-manager-ui/server/types/entra-id.ts
  trade-finance-manager-ui/server/types/get-router.ts
  trade-finance-manager-ui/templates/auth/accept-sso-redirect.njk
  trade-finance-manager-ui/test-helpers/index.ts
  trade-finance-manager-ui/test-helpers/with-schema.tests.ts
  trade-finance-manager-ui/tsconfig.json
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: Feature

#3661 feat(DTFS2-7450): add e2e tests for cancel cancellation
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/cancel-cancellation.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
  e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/cancel-cancellation.js
Labels: Type: Feature

#3648 feat(FN-2294): send email to bank if report reconciled
  dtfs-central-api/src/constants/email-template-ids.ts
  dtfs-central-api/src/external-api/api.ts
  dtfs-central-api/src/external-api/send-email.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/generate-report-reconciled-email-variables.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/generate-report-reconciled-email-variables.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/send-report-reconciled-email.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/send-report-reconciled-email.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-reconciled/mark-fee-records-as-reconciled.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-reconciled/mark-fee-records-as-reconciled.event-handler.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/email/index.test.ts
  dtfs-central-api/src/v1/email/index.ts
  libs/common/src/helpers/date.test.ts
  libs/common/src/helpers/date.ts
  libs/common/src/helpers/format-date-for-email.ts
  libs/common/src/helpers/formate-date-for-email.test.ts
  libs/common/src/helpers/index.ts
  portal-api/src/utils/date.js
  portal-api/src/utils/date.test.js
  portal-api/src/v1/services/utilisation-report/email-service.ts
  portal/server/controllers/utilisation-report-service/previous-reports/helpers/previous-reports-view-model-mapper.ts
  portal/server/helpers/getMonthName.js
  portal/server/helpers/getMonthName.test.js
Labels: Type: Feature, Type: Fintech

#3647 feat(DTFS2-7303): change links on deal cancellation summary page
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/check-details.spec.js
  trade-finance-manager-ui/component-tests/case/cancellation/bank-request-date.component-test.ts
  trade-finance-manager-ui/component-tests/case/cancellation/effective-from-date.component-test.ts
  trade-finance-manager-ui/component-tests/case/cancellation/reason-for-cancelling.component-test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/helpers/get-previous-page-url.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/helpers/get-previous-page-url.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/bank-request-date-view-model.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/base-cancellation-view-model.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/effective-from-date-view-model.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/reason-for-cancelling-view-model.ts
  trade-finance-manager-ui/templates/case/cancellation/bank-request-date.njk
  trade-finance-manager-ui/templates/case/cancellation/check-details.njk
  trade-finance-manager-ui/templates/case/cancellation/effective-from-date.njk
  trade-finance-manager-ui/templates/case/cancellation/reason-for-cancelling.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/bank-request-date-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/effective-from-date-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/cancellation/reason-for-cancelling-view-model.ts
Labels: Type: Feature

#3646 feat(FN-2311): add frontend payment details filtering logic
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/parse-filters.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/parse-filters.ts
  libs/common/src/constants/max-character-count.ts
  libs/common/src/helpers/validation.test.ts
  libs/common/src/helpers/validation.ts
  libs/common/src/types/index.ts
  libs/common/src/types/radio-item.ts
  libs/common/src/types/utilisation-reports.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-filters-form.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-filters-panel.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/validate-payment-form-values.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/extract-query-and-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/extract-query-and-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-payment-details-filters.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-payment-details-filters.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-premium-payments-filters.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-premium-payments-filters.ts
  trade-finance-manager-ui/server/helpers/map-currencies-to-radio-items.test.ts
  trade-finance-manager-ui/server/helpers/map-currencies-to-radio-items.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-filters-form.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-filters-panel.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/currency-radio-item.ts
Labels: Type: Fintech

#3589 feat(FN-3272): store initial utilisation and fee based on supplied and facility values
  dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
  dtfs-central-api/src/helpers/calculate-fixed-fee-from-days-remaining.test.ts
  dtfs-central-api/src/helpers/calculate-fixed-fee-from-days-remaining.ts
  dtfs-central-api/src/helpers/get-previous-report-period.test.ts
  dtfs-central-api/src/helpers/get-previous-report-period.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-fixed-fee.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-fixed-fee.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-utilisation-and-fixed-fee.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-utilisation-and-fixed-fee.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-base-currency-errors/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-base-currency-errors/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-facility-utilisation-errors/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-facility-utilisation-errors/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.ts
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  libs/common/src/helpers/date-validation.test.ts
  libs/common/src/helpers/date-validation.ts
  libs/common/src/helpers/facility-calculations/index.test.ts
  libs/common/src/helpers/facility-calculations/index.ts
  libs/common/src/helpers/index.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.types.ts
  libs/common/src/types/utilisation-reports.ts
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
Labels: Type: Feature, Type: Fintech

#3668 chore(DTFS2-NONE): fix flakey test
  libs/common/src/helpers/date.test.ts
Labels: Type: chore

#3659 feat(dtfs2-6892): create and auto submit accept sso redirect form
  libs/common/src/utils/date.test.ts
  trade-finance-manager-ui/server/constants/entra-id-user-groups.ts
  trade-finance-manager-ui/server/constants/entra-id-user.ts
  trade-finance-manager-ui/server/controllers/login/login-non-sso/index.get-login.test.ts
  trade-finance-manager-ui/server/controllers/login/login-non-sso/index.logout.test.ts
  trade-finance-manager-ui/server/controllers/login/login-non-sso/index.post-login.test.ts
  trade-finance-manager-ui/server/controllers/login/login-non-sso/index.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-logout.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
  trade-finance-manager-ui/server/controllers/user/user-non-sso/index.js
  trade-finance-manager-ui/server/routes/login/configs/login-non-sso.ts
  trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
  trade-finance-manager-ui/server/routes/user/configs/user-non-sso.ts
  trade-finance-manager-ui/server/schemas/entra-id-user.schema.entra-id-user-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id-user.schema.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.decoded-auth-code-request-state-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.entra-id-auth-code-redirect-response-body-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.entra-id-authentication-result-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.ts
  trade-finance-manager-ui/server/schemas/index.ts
  trade-finance-manager-ui/server/schemas/with-entra-id-user-schema.tests.ts
  trade-finance-manager-ui/server/types/entra-id-user.ts
  trade-finance-manager-ui/server/types/entra-id.ts
  trade-finance-manager-ui/test-helpers/with-schema.tests.ts
Labels: Type: Feature

#3650 fix(FN-3422): calculate fixed fee from report period end date
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/generate-keying-sheet.spec.js
  libs/common/src/types/utilisation-reports.ts
Labels: Type: Fix

#3669 chore(DTFS2-7462): replace toBe instances with toEqual
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.post-sso-redirect.test.ts
  trade-finance-manager-ui/server/routes/auth/configs/index.get-unauthenticated-auth-router.test.ts
  trade-finance-manager-ui/test-helpers/with-schema.tests.ts
Labels: Type: chore

#3675 feat(FN-2594): remove disabled year and autocomplete fix on find report by year tfm page
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/find-utilisation-reports-by-bank-and-year.spec.js
  trade-finance-manager-ui/public/js/enableFindReportsByYearDropdown.js
  trade-finance-manager-ui/public/js/enableFindReportsByYearDropdown.js.map
  trade-finance-manager-ui/public/js/mojFilterHide.js
  trade-finance-manager-ui/public/js/mojFilterHide.js.map
  trade-finance-manager-ui/public/js/ssoRedirectAutoSubmit.js
  trade-finance-manager-ui/public/js/ssoRedirectAutoSubmit.js.map
  trade-finance-manager-ui/scripts/enable-find-reports-by-year-dropdown.ts
  trade-finance-manager-ui/templates/utilisation-reports/find-utilisation-reports-by-year.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Feature, Type: Fintech

#3663 chore(main): release 2.4.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3671 feat(DTFS2-6892): commonise entra user schema and refactor tests
  libs/common/src/constants/tfm/entra-id-user-groups.ts
  libs/common/src/constants/tfm/index.ts
  libs/common/src/schemas/audit-database-record.test.ts
  libs/common/src/schemas/index.ts
  libs/common/src/schemas/iso-date-time-stamp.test.ts
  libs/common/src/schemas/object-id.test.ts
  libs/common/src/schemas/portal-user.create.test.ts
  libs/common/src/schemas/portal-user.test.ts
  libs/common/src/schemas/portal-user.update.test.ts
  libs/common/src/schemas/tfm/entra-id-user.schema.entra-id-user-schema.test.ts
  libs/common/src/schemas/tfm/entra-id-user.schema.ts
  libs/common/src/schemas/tfm/index.ts
  libs/common/src/schemas/with-schema-validation.tests.ts
  libs/common/src/test-helpers/index.ts
  libs/common/src/test-helpers/schemas/index.ts
  libs/common/src/test-helpers/schemas/with-entra-id-user-schema.tests.ts
  libs/common/src/test-helpers/schemas/with-schema.tests.ts
  libs/common/src/types/tfm/entra-id-user.ts
  libs/common/src/types/tfm/index.ts
  trade-finance-manager-ui/server/constants/entra-id-user.ts
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.ts
  trade-finance-manager-ui/server/schemas/entra-id-user.schema.entra-id-user-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.decoded-auth-code-request-state-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.entra-id-auth-code-redirect-response-body-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.entra-id-authentication-result-schema.test.ts
  trade-finance-manager-ui/server/schemas/entra-id.schema.ts
  trade-finance-manager-ui/server/schemas/index.ts
  trade-finance-manager-ui/server/types/entra-id-user.ts
  trade-finance-manager-ui/server/types/entra-id.ts
Labels: Type: Feature

#3667 feat(FN-3484): download report link on utilisation tab
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/view-utilisation.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/utilisation-details-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/utilisation-details-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3673 fix(FN-3502-3503): fix keying sheet adjustments UI
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/generate-keying-sheet.spec.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
Labels: Type: Fintech

#3656 feat(FN-2311): split premium payments and payment detail types
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-to-fee-record-payment-groups.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-to-fee-record-payment-groups.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-to-payment-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-to-payment-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-to-premium-payments-groups.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-to-premium-payments-groups.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-report-reconciliation-details.js
  dtfs-central-api/test-helpers/test-data/fee-record-payment-entity-group.ts
  dtfs-central-api/test-helpers/test-data/index.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-payment-details.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-payment-details/filter-payment-details-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-payment-details/filter-payment-details-by-payment-currency.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-payment-details/filter-payment-details-by-payment-reference.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-payment-details/filter-payment-details.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-api/test-helpers/utilisation-report-reconciliation-details.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
  trade-finance-manager-ui/test-helpers/fee-record-payment-group-item.ts
  trade-finance-manager-ui/test-helpers/index.ts
  trade-finance-manager-ui/test-helpers/payment-details-item.ts
  trade-finance-manager-ui/test-helpers/premium-payments-group-item.ts
Labels: Type: chore, Type: Fintech

#3674 feat(DTFS2-7489): create submit cancellation endpoint tfm api
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/update-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-api/src/v1/middleware/validate-post-submit-deal-cancellation-payload.test.ts
  trade-finance-manager-api/src/v1/middleware/validate-post-submit-deal-cancellation-payload.ts
  trade-finance-manager-api/src/v1/middleware/validate-put-deal-cancellation-payload.ts
Labels: Type: Feature

#3683 feat(DTFS2-7528): submit cancellation in tfm-ui
  trade-finance-manager-ui/component-tests/case/cancellation/check-details.component-test.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.js
  trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.test.js
  trade-finance-manager-ui/server/nunjucks-configuration/filter-formatUnixTimestamp.ts
  trade-finance-manager-ui/server/nunjucks-configuration/index.js
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/check-details-view-model.ts
  trade-finance-manager-ui/templates/case/cancellation/check-details.njk
  trade-finance-manager-ui/test-helpers/test-data/check-answers-view-model.ts
Labels: Type: Feature

#3692 feat(FN-3493): persist selected records on add payment screen
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
  trade-finance-manager-ui/component-tests/utilisation-reports/add-payment.component-test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/types/view-models/add-payment-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/add-payment.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/add-payment-view-model.ts
Labels: Type: Fintech

#3672 chore(DTFS2-6892): commonise london timezone
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  CHANGELOG.md
  e2e-tests/gef/cypress.config.js
  e2e-tests/portal/cypress.config.js
  e2e-tests/tfm/cypress.config.js
  e2e-tests/ukef/cypress.config.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/nunjucks-configuration/filter-localiseTimestamp.ts
  libs/common/src/index.ts
  libs/common/src/schemas/timezone.ts
  libs/common/src/types/date-iana-timezones.ts
  libs/common/src/types/index.ts
  portal/component-tests/admin/user-edit.component-test.js
  portal/component-tests/bond/_macros/bond-submission-details.component-test.js
  portal/component-tests/contract/components/bond-transactions-table.component-test.js
  portal/component-tests/contract/components/contract-overview-table.component-test.js
  portal/component-tests/contract/components/loan-transactions-table.component-test.js
  portal/component-tests/contract/contract-submission-details.component-test.js
  portal/component-tests/contract/contract-view.component-test.js
  portal/component-tests/loan/_macros/loan-submission-details.component-test.js
  portal/server/constants/date.ts
  portal/server/nunjucks-configuration/filter-localiseTimestamp.test.ts
  portal/server/nunjucks-configuration/filter-localiseTimestamp.ts
Labels: Type: Feature, Type: chore

#3694 chore(dtfs2-6892): fix issue with pages not using default timezone
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/application-details/index.js
Labels: Type: chore

#3698 fix(DTFS2-7440): acbs docker file reference
  .github/workflows/deployment.yml
Labels: Type: Fix

#3693 feat(dtfs2-6892): fix docker config and update routers to avoid issue with unbound methods
  docker-compose.yml
  trade-finance-manager-ui/server/routes/auth/configs/unauthenticated-auth-sso.ts
  trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
Labels: Type: Feature

#3700 fix(acbs-deployment): acbs dockerfile reference fix
  .github/workflows/deployment.yml
Labels: Type: Fix

#3697 feat(DTFS2-7553): add status to deal cancellation
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-deal-cancellation-get.api-test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/v1/controllers/tfm/deal-cancellation/tfm-get-deal-cancellation.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/deal-cancellation/tfm-put-update-deal-cancellation.controller.ts
  libs/common/src/constants/cancellation-status.ts
  libs/common/src/constants/index.ts
  libs/common/src/types/mongo-db-models/index.ts
  libs/common/src/types/mongo-db-models/tfm-deal-cancellation.ts
  libs/common/src/types/mongo-db-models/tfm-deals.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.get.api-test.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/get-deal-cancellation.controller.test.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
Labels: Type: Feature

#3701 feat(DTFS2-7557): acbs build test
  .github/dependabot.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/dns.yml
  .github/workflows/dns_tfm.yml
  .github/workflows/feature_deploy.yml
  .github/workflows/github.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/pr.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/publish.yml
  .github/workflows/sca.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  docker-compose.yml
Labels: Type: Feature

#3750 chore(DTFS2-7562): dependencies updates
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: chore

#3751 chore(DTFS2-7458): align facility identifier and facility
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/mappings/facility/facility-loan.js
  azure-functions/acbs-function/mappings/facility/facility-master-amend.js
  azure-functions/acbs-function/mappings/facility/facility-master.js
  azure-functions/acbs-function/mappings/facility/facility-update.js
  azure-functions/acbs-function/mappings/facility/helpers/get-maximum-liability.test.js
  azure-functions/acbs-function/mappings/facility/helpers/get-next-quarter-date.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-covenant-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-guarantee-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-master-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  azure-functions/acbs-function/src/functions/acbs-facility.js
  azure-functions/acbs-function/src/functions/acbs-issue-facility.js
  azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
  azure-functions/acbs-function/src/functions/activity-get-facility-master.js
  azure-functions/acbs-function/src/functions/activity-update-facility-covenant.js
  azure-functions/acbs-function/src/functions/activity-update-facility-guarantee.js
  azure-functions/acbs-function/src/functions/activity-update-facility-loan-amount.js
  azure-functions/acbs-function/src/functions/activity-update-facility-loan.js
  azure-functions/acbs-function/src/functions/activity-update-facility-master.js
  external-api/api-tests/v1/acbs.api-test.ts
  external-api/src/v1/controllers/acbs.controller.ts
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.test.js
Labels: Type: chore

#3748 feat(DTFS2-7550): add cron job to schedule cancellations
  .env.sample
  .github/workflows/test.yml
  docker-compose.yml
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.ts
  dtfs-central-api/src/cron-scheduler-jobs/index.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.findScheduledDealCancellations.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  libs/common/src/constants/tfm/deal-stage.ts
  libs/common/src/types/mongo-db-models/tfm-deals.ts
Labels: Type: Feature

#3690 feat(DTFS2-7490): send email on cancellation submission
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.submitDealCancellation.test.ts
  libs/common/src/constants/date-formats.ts
  libs/common/src/types/mongo-db-models/deals.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/constants/email-template-ids.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/controllers/feedback-controller.js
  trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js
  trade-finance-manager-api/src/v1/controllers/task-emails.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.test.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/helpers/format-facility-ids.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/helpers/format-facility-ids.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/helpers/get-ukef-facility-ids.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/helpers/get-ukef-facility-ids.ts
  trade-finance-manager-api/src/v1/services/send-tfm-email.js
  trade-finance-manager-api/src/v1/services/send-tfm-email.test.js
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/templates/case/cancellation/check-details.njk
Labels: Type: Feature

#3752 feat(DTFS2-7555): map cancellation activity in tfm-ui
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-put-tfm.api-test.js
  e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
  libs/common/src/constants/tfm/activity-types.ts
  libs/common/src/constants/tfm/index.ts
  libs/common/src/types/date.ts
  libs/common/src/types/mongo-db-models/index.ts
  libs/common/src/types/mongo-db-models/tfm-activity.ts
  libs/common/src/types/mongo-db-models/tfm-deals.ts
  trade-finance-manager-api/src/constants/activity.js
  trade-finance-manager-api/src/v1/__mocks__/mock-TFM-deal-AIN-submitted.js
  trade-finance-manager-api/src/v1/helpers/activity.js
  trade-finance-manager-api/src/v1/rest-mappings/filters/filterActivities.js
  trade-finance-manager-api/src/v1/rest-mappings/filters/filterActivities.test.js
  trade-finance-manager-api/src/v1/rest-mappings/filters/filterTasks.test.js
  trade-finance-manager-ui/component-tests/case/activity/_macros/cancellation-activity-html.component-test.ts
  trade-finance-manager-ui/server/controllers/case/activity/helpers/map-activities.test.ts
  trade-finance-manager-ui/server/controllers/case/activity/helpers/map-activities.ts
  trade-finance-manager-ui/server/controllers/case/activity/index.js
  trade-finance-manager-ui/server/controllers/case/activity/index.test.js
  trade-finance-manager-ui/templates/case/activity/_macros/cancellation-activity-html.njk
  trade-finance-manager-ui/templates/case/activity/activity.njk
Labels: Type: Feature

#3771 fix(DTFS2-7567): acbs container initilisation
  azure-functions/acbs-function/Dockerfile
  azure-functions/acbs-function/package.json
  package-lock.json
Labels: Type: Fix

#3765 feat(DTFS2-7573): call submit cancellation in tfm-api
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/as-non-pim-user.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/cancel-cancellation.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/check-details.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts
Labels: Type: Feature

#3767 feat(DTFS2-7298): improve facility mapping consistency
  trade-finance-manager-api/src/v1/rest-mappings/facility.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/facility.js
  trade-finance-manager-api/src/v1/rest-mappings/facility.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/deal/mapDealSnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/deal/mapDealSnapshot.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilities.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilities.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilities.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilities.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacility.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacility.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.test.js
Labels: Type: chore

#3772 fix(DTFS2-7440): acbs microservice docker communication
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  docker-compose.yml
Labels: Type: Fix

#3770 feat(DTFS2-7298): update facility stage in the db on cancel
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-submit-deal-cancellation-post.api-test.ts
  dtfs-central-api/src/helpers/get-ukef-facility-ids.test.ts
  dtfs-central-api/src/helpers/get-ukef-facility-ids.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.submitDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-in-past.spec.js
  e2e-tests/tfm/cypress/e2e/pages/caseDealPage.js
  libs/common/src/types/tfm-deal-cancellation.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.test.js
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts
Labels: Type: Feature

#3776 feat(DTFS2-7298): improve readability of snapshot mapping files
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.js
Labels: Type: Feature

#3775 feat(DTFS2-7298): update deal cancellation in progress logic
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts
Labels: Type: Feature

#3778 fix(DTFS2-7576): facility amendment empty tasks graceful handle
  trade-finance-manager-api/src/v1/rest-mappings/filters/filterTasks.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/filters/filterTasks.js
  trade-finance-manager-ui/server/controllers/helpers/tasks.helper.js
Labels: Type: Fix

#3769 feat(DTFS2-7556): add activity on deal cancellation
  dtfs-central-api/api-tests/helpers/create-tfm-user.ts
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-submit-deal-cancellation-post.api-test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.submitDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  libs/common/src/change-stream/generate-audit-details.ts
  libs/common/src/change-stream/validate-audit-details.ts
  libs/common/src/types/audit-details.ts
Labels: Type: Feature

#3781 feat(DTFS2-7298): display deal cancellation success message
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-in-past.spec.js
  e2e-tests/tfm/cypress/e2e/partials/index.js
  package-lock.json
  portal/server/helpers/getFlashSuccessMessage.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.test.js
  trade-finance-manager-ui/component-tests/_macros/success-banner.component-test.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/generateApp.js
  trade-finance-manager-ui/server/helpers/getFlashSuccessMessage.test.ts
  trade-finance-manager-ui/server/helpers/getFlashSuccessMessage.ts
  trade-finance-manager-ui/server/test-mocks/index.js
  trade-finance-manager-ui/templates/_macros/success-banner.njk
  trade-finance-manager-ui/templates/_partials/case_sub_navigation.njk
  trade-finance-manager-ui/templates/case/case.njk
Labels: Type: Feature

#3786 fix(DTFS2-7567): working directory for azure functions
  azure-functions/acbs-function/Dockerfile
  azure-functions/acbs-function/README.md
Labels: Type: Fix

#3785 feat(DTFS2-7469): display 'Risk Expired' on All Facilities page
  dtfs-central-api/src/repositories/tfm-facilities-repo/aggregate-pipelines/all-facilities-and-facility-count.ts
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-in-past.spec.js
  trade-finance-manager-ui/component-tests/facilities/_macros/facilities-table.component-test.js
  trade-finance-manager-ui/templates/facilities/_macros/facilities-table.njk
Labels: Type: Feature

#3783 feat(FN-3398): replace source platform string literals
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/mark-as-ready-to-key/mark-as-ready-to-key.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/mark-as-reconciled/mark-as-reconciled.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-added-to-payment-group/other-fee-added-to-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-removed-from-payment-group/other-fee-removed-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-added/payment-added.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-edited/payment-edited.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/remove-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/add-a-payment.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-fees-to-an-existing-payment-group/add-fees-to-an-existing-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/edit-payment/edit-payment.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-ready-to-key/mark-fee-records-as-ready-to-key.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-reconciled/mark-fee-records-as-reconciled.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/patch-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/patch-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-done.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-to-do.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.ts
  dtfs-central-api/test-helpers/test-data/db-request-source.ts
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.test.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.test.ts
  libs/common/src/sql-db-entities/payment/payment.entity.test.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.test.ts
  libs/common/src/test-helpers/mock-data/facility-utilisation-data.entity.mock-builder.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.helpers.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.seeder.ts
  utils/sql-db-seeder/src/utilisation-report/utilisation-report.seeder.ts
Labels: Type: Fintech

#3790 fix(DTFS2-7486): improved exceptional handling
  azure-functions/acbs-function/src/functions/acbs-amend-facility-master-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  azure-functions/acbs-function/src/functions/acbs-issue-facility.js
  azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
  azure-functions/acbs-function/src/functions/activity-get-facility-master.js
  dtfs-central-api/src/repositories/tfm-facilities-repo/aggregate-pipelines/all-facilities-and-facility-count.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deal.controller.js
  gef-ui/templates/includes/primary-navigation.njk
  gef-ui/templates/index.njk
  gef-ui/templates/partials/upload-supporting-documents.njk
  portal/public/css/styles.css
  portal/public/js/disableFormSubmitOnSubmission.js
  portal/public/js/govukFrontend.js
  portal/public/js/guaranteeFeePayableByBank.js
  portal/public/js/jsEnabled.js
  portal/public/js/main.js
  portal/public/js/main.js.map
  portal/public/js/maskedInputs.js
  portal/public/js/maskedInputs.js.map
  portal/public/js/mojFilters.js
  portal/public/js/mojFrontend.js
  portal/public/js/mojFrontend.js.map
  portal/public/js/multiFileUpload.js
  portal/public/js/printPage.js
  portal/public/js/ukefexposure.js
  portal/public/js/ukefexposure.js.map
  portal/server/constants/landing-pages.ts
  portal/server/controllers/login/check-your-email.js
  portal/server/controllers/login/login-with-sign-in-link.js
  portal/server/helpers/getApiData.js
  portal/server/routes/default/index.js
  portal/server/routes/login/index.js
  portal/server/utils/destroy-session-and-redirect-to-start.js
  portal/styles/moj-filter.scss
  portal/templates/_macros/facility-inputs/guarantee-fee-payable-by-bank.njk
  portal/templates/_macros/facility-inputs/ukef-exposure.njk
  portal/templates/_partials/primary-navigation.njk
  portal/templates/_partials/print-button.njk
  portal/templates/index.njk
  trade-finance-manager-api/src/v1/controllers/facility.controller.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/deal/mapDeals.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
Labels: Type: chore, Type: Fix

#3795 fix(DTFS2-7593): fix incorrect requestedCoverStartDate dates in e2e facility
  e2e-tests/portal/cypress/e2e/journeys/maker-facilities/MIA-accepted-deal-status-maker-cannot-resubmit-until-confirmed-all-issued-facilities-cover-start-date/MIA-deal-with-accepted-status-issued-facilities.js
Labels: Type: Fix, Type: Fintech
