Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-06, with the labels that each got.

#3204 fix(deployment): added local.settings.json to .gitignore
  .gitignore
  gef-ui/README.md
Labels: Type: chore

#3177 chore(dtfs2-none): merge release 1.6 into release 2.0
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/dns.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  e2e-tests/package.json
  e2e-tests/portal/cypress.config.js
  e2e-tests/portal/cypress/e2e/journeys/login/reset-password.spec.js
  gef-ui/server/nunjucks-configuration/index.js
  gef-ui/templates/includes/contact-us.njk
  gef-ui/templates/includes/footer.njk
  package-lock.json
  portal/component-tests/componentRenderer.js
  portal/component-tests/login/temporarily-suspended.component-test.js
  portal/component-tests/login/we-have-sent-you-another-link.component-test.js
  portal/component-tests/pageRenderer.js
  portal/component-tests/test-helpers/with-contact-us-email-address.component-tests.js
  portal/server/nunjucks-configuration/index.js
  portal/templates/_partials/contact-us.njk
  portal/templates/_partials/footer.njk
  portal/templates/accessibility-statement.njk
  portal/templates/login/index.njk
  service-unavailable/index.html
  trade-finance-manager-ui/server/nunjucks-configuration/index.js
  trade-finance-manager-ui/templates/_partials/footer.njk
  trade-finance-manager-ui/templates/accessibility-statement.njk
Labels: Type: chore

#3183 feat(FN-2846): add ordering to utilisation reports request
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report-sql.repo.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/utilisationReportUpload.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
  portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk
Labels: Type: Fintech

#3146 chore(dtfs2-none): fix typo
  e2e-tests/e2e-fixtures/bss/mandatoryCriteria.fixture.js
  e2e-tests/gef/cypress/e2e/exporter/exporter-correspondence-address.spec.js
  e2e-tests/gef/cypress/fixtures/constants.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-validation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-supply-contract-create-element.spec.js
  e2e-tests/portal/cypress/fixtures/constants.js
  external-api/api-tests/test-mocks/companies-house-number.ts
  gef-ui/server/test-mocks/companies-house-number.js
  gef-ui/server/utils/validateIds.test.js
  gef-ui/templates/partials/companies-house.njk
  gef-ui/templates/partials/provided-facility.njk
  portal-api/api-tests/fixtures/companies-house-number.js
  portal-api/api-tests/fixtures/gef/mandatoryCriteriaVersioned.js
  portal-api/api-tests/fixtures/mandatoryCriteria.js
  portal-api/src/v1/validation/validateIds.test.js
  portal/component-tests/fixtures/deal-fully-completed.js
  portal/server/test-mocks/companies-house-number.js
  portal/server/validation/validate-ids.test.js
  utils/mock-data-loader/bss/mandatoryCriteria.js
  utils/mock-data-loader/gef/mandatoryCriteriaVersioned.js
Labels: Type: chore

#3162 feat(dtfs2-6966): add audit logs to create deal endpoint
  dtfs-central-api/api-tests/helpers/create-deal.js
  dtfs-central-api/api-tests/helpers/with-validate-audit-details.api-tests.ts
  dtfs-central-api/api-tests/v1/deals/create-deal.api-test.js
  dtfs-central-api/api-tests/v1/deals/deal.api-test.js
  dtfs-central-api/api-tests/v1/deals/delete-deal.api-test.js
  dtfs-central-api/api-tests/v1/deals/expectAddedFields.js
  dtfs-central-api/api-tests/v1/deals/get-deal.api-test.js
  dtfs-central-api/api-tests/v1/deals/update-deal-status.api-test.js
  dtfs-central-api/api-tests/v1/deals/update-deal.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facilities.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facility-delete.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facility-get.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facility-post.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facility-put.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facility.api-test.js
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-get.api-test.js
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-post.api-test.js
  dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-put.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-bss-deal.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-bss-deals-put-submit.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-put-tfm.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deals-get.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deal.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deals-put-submit.api-test.js
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facility-get.api-test.js
  dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facility-put.api-test.js
  dtfs-central-api/api-tests/v1/tfm/users/tfm-teams.api-test.js
  dtfs-central-api/api-tests/v1/tfm/users/tfm-users.api-test.js
  dtfs-central-api/src/v1/controllers/portal/deal/create-deal.controller.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-post-amendments.controller.js
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-put-amendments.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-submit-deal.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-teams.controller.js
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-users.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  libs/common/src/change-stream/generate-audit-database-record.test.ts
  libs/common/src/change-stream/test-helpers/add-audit-record-to-expected-response.ts
  libs/common/src/change-stream/test-helpers/generate-mock-audit-database-record.ts
  libs/common/src/change-stream/test-helpers/index.ts
  libs/common/src/constants/audit-user-types.ts
  libs/common/src/constants/index.ts
  libs/common/src/types/audit-details.ts
  libs/common/src/types/audit-user-types.ts
  libs/common/src/types/index.ts
  portal-api/api-tests/v1/deals/deal-clone.api-test.js
  portal-api/api-tests/v1/deals/deals.api-test.js
  portal-api/api-tests/v1/deals/expectAddedFields.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/deal-clone.controller.js
  portal-api/src/v1/controllers/deal.controller.js
  trade-finance-manager-api/api-tests/v1/amendments/update-tfm-deal-amendment-completion.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
Labels: Type: Feature

#3102 fix(DTFS2-5885): amendment underwriter tasks are not assigned to lead underwriter
  cspell.json
  e2e-tests/tfm/cypress/e2e/common-tests/assessmentTasksAssignedTo.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-amendment-request-check-previous.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-proceed.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-withdraw.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-lead-underwriter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendments-version-order.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/underwriting-page-unassigned.spec.js
  e2e-tests/tfm/cypress/e2e/pages/amendments/amendmentsPage.js
  e2e-tests/tfm/cypress/e2e/pages/underwriting/underwritingPage.js
  e2e-tests/tfm/cypress/fixtures/constants.js
  trade-finance-manager-api/src/v1/__mocks__/mock-amendment-tasks-assign-by-team.js
  trade-finance-manager-api/src/v1/__mocks__/mock-amendment.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller-updateFacilityAmendment.test.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper-getTasksAssignedToUserByGroup.test.js
  trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.api-test.js
  trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.js
  trade-finance-manager-ui/templates/case/amendments/amendment-lead-underwriter.njk
  utils/mock-data-loader/insert-mocks-gef.js
Labels: Type: Bug, Type: Feature

#3218 feat(FN-1739): update table column names and data types
  doc/sql-db.md
  dtfs-central-api/api-tests/v1/utilisation-reports/post-payment.api-test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/add-a-payment.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/helpers.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/helpers.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.ts
  libs/common/src/sql-db-connection/migrations/1717746522387-PaymentTableUpdateAmountColumns.ts
  libs/common/src/sql-db-connection/reset-database.sh
  libs/common/src/sql-db-entities/custom-columns/monetary-column.ts
  libs/common/src/sql-db-entities/payment/payment.entity.ts
  libs/common/src/sql-db-entities/payment/payment.types.ts
  libs/common/src/test-helpers/mock-data/payment.entity.mock-builder.ts
Labels: Type: Fintech

#3220 fix(security.txt): updated the Expires value
  portal/server/routes/static.js
Labels: Type: Fix

#3214 feat(DTFS2-7055): update docker-compose.gha.yml to use replica set
  docker-compose.gha.yml
Labels: Type: Feature

#3223 feat(FN-2902): disable sorting when payments columns are empty
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3226 chore(DTFS2-NONE): add sleep to utilisation recon summary test
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports-reconciliation-summary.api-test.ts
Labels: Type: chore

#3208 feat(DTFS2-7175): add deletion audit logs to portal-api endpoints
  docker-compose.gha.yml
  dtfs-central-api/api-tests/v1/deals/delete-deal.api-test.js
  libs/common/src/change-stream/test-helpers/generate-mock-audit-database-record.ts
  libs/common/src/change-stream/test-helpers/with-delete-one.api-tests.ts
  libs/common/src/constants/mongo-db-collections.ts
  portal-api/api-tests/database-helper.js
  portal-api/api-tests/v1/banks/bank-builder.js
  portal-api/api-tests/v1/banks/banks.api-test.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/eligibility-criteria/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/feedback/feedback.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/loan/loan-issue-facility.api-test.js
  portal-api/api-tests/v1/mandatory-criteria/mandatory-criteria.api-test.js
  portal-api/api-tests/v1/users/users.api-test.js
  portal-api/src/drivers/db-client.ts
  portal-api/src/v1/controllers/banks.controller.js
  portal-api/src/v1/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/controllers/eligibilityCriteria.test.js
  portal-api/src/v1/controllers/feedback.controller.js
  portal-api/src/v1/controllers/mandatoryCriteria.controller.js
  portal-api/src/v1/users/controller.findByEmail.test.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/controller.test.js
  portal-api/src/v1/users/routes.js
Labels: Type: Feature

#3212 feat(DTFS2-7049): use new APIM endpoint "/emails"
  README.md
  external-api/api-tests/v1/email.api-test.ts
  external-api/package.json
  external-api/src/constants/index.ts
  external-api/src/constants/mdm.constant.ts
  external-api/src/v1/controllers/email.controller.ts
  package-lock.json
  portal-api/__mocks__/notifications-node-client.js
  portal-api/package.json
  portal-api/src/v1/email/index.js
  portal-api/src/v1/email/index.test.js
Labels: Type: Feature, chore

#3222 chore(DTFS2-NONE): add TTL env var to test.yml
  .github/workflows/test.yml
Labels: Type: chore

#3217 feat(FN-1739): add execute with transaction helper
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/errors/transaction-failed.error.ts
  dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts
  dtfs-central-api/src/helpers/execute-with-sql-transaction.ts
  dtfs-central-api/src/helpers/index.js
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/helpers/isNumber.js
  dtfs-central-api/src/helpers/isNumber.test.ts
  dtfs-central-api/src/helpers/isNumber.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.ts
  dtfs-central-api/test-helpers/mock-query-runner.ts
Labels: Type: Fintech

#3219 feat(FN-1739): link add payment frontend to backend
  trade-finance-manager-api/src/types/custom-express-request.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-payment.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-payment.controller.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-api/test-helpers/tfm-session-user.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/add-payment-form-values-validator.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/add-payment-form-values-validator.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/types/view-models/add-payment-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/add-payment-view-model.ts
Labels: Type: Fintech

#3136 feat(DTFS2-7151): use new APIM endpoint "/geospatial/addresses/postcode"
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  external-api/README.md
  external-api/api-tests/v1/geospatial-addresses.api-test.ts
  external-api/api-tests/v1/ordnance-survey.api-test.ts
  external-api/src/helpers/swagger-definitions/geospatial-addresses.ts
  external-api/src/helpers/swagger-definitions/ordnance-survey.ts
  external-api/src/helpers/swagger.ts
  external-api/src/v1/controllers/geospatial-addresses.controller.ts
  external-api/src/v1/controllers/ordnance-survey.controller.ts
  external-api/src/v1/routes/external-apis.route.ts
  external-api/src/validations/schemas.ts
  external-api/tsconfig.json
  gef-ui/server/services/api.js
  libs/common/src/constants/geospatial.constant.ts
  libs/common/src/constants/index.ts
  portal-api/api-tests/v1/gef/address.api-test.js
  portal-api/api-tests/v1/gef/external-api.api-test.js
  portal-api/src/external-api/__mocks__/api.js
  portal-api/src/external-api/__mocks__/geospatial-addresses.js
  portal-api/src/external-api/__mocks__/ordnance-survey.js
  portal-api/src/external-api/api.js
  portal-api/src/external-api/geospatial-addresses.js
  portal-api/src/v1/gef/controllers/externalApi.controller.js
  portal-api/src/v1/gef/routes.js
Labels: Type: Feature, chore

#3143 feat(DTFS2-7165): implement delete many with audit logs
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  dtfs-central-api/api-tests/v1/cron-jobs/cron-jobs.api-test.js
  dtfs-central-api/api-tests/v1/durable-functions/durable-functions.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-delete.api-test.js
  dtfs-central-api/package.json
  dtfs-central-api/src/cron-scheduler-jobs/delete-acbs-durable-function-logs/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/delete-acbs-durable-function-logs/index.ts
  dtfs-central-api/src/repositories/durable-functions-repo.test.ts
  dtfs-central-api/src/repositories/durable-functions-repo.ts
  dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.js
  dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.ts
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.js
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.ts
  libs/common/src/change-stream/config.ts
  libs/common/src/change-stream/delete-many.ts
  libs/common/src/change-stream/delete-one.ts
  libs/common/src/change-stream/index.ts
  libs/common/src/change-stream/test-helpers/index.ts
  libs/common/src/change-stream/test-helpers/with-delete-many.api-tests.ts
  libs/common/src/change-stream/test-helpers/with-delete-one.api-tests.ts
  package-lock.json
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  utils/mock-data-loader/gef/api.js
  utils/mock-data-loader/tfm/api.js
Labels: Type: Feature

#3120 chore(main): release 2.1.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3232 fix(DTFS2-7051): removed companies house envionment variable
  .env.sample
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  .github/workflows/test.yml
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
  external-api/src/validations/schemas.ts
Labels: Type: Fix

#3231 chore(main): release 2.2.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3148 fix(DTFS2-6709): add validation text for create new user page
  dtfs-central-api/api-tests/mocks/test-users/api-test-users.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/pages/admin/users/createUser.js
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/common-tests/role-authorisation-tests.js
  portal-api/api-tests/v1/bank-holidays/bank-holidays.api-test.js
  portal-api/api-tests/v1/banks/banks.api-test.js
  portal-api/api-tests/v1/bonds/bond-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/bonds/bonds.api-test.js
  portal-api/api-tests/v1/countries/countries.api-test.js
  portal-api/api-tests/v1/currencies/currencies.api-test.js
  portal-api/api-tests/v1/deals/deal-clone.api-test.js
  portal-api/api-tests/v1/deals/deal-eligibility-criteria.api-test.js
  portal-api/api-tests/v1/deals/deal-eligibility-documentation.api-test.js
  portal-api/api-tests/v1/deals/deal-name.api-test.js
  portal-api/api-tests/v1/deals/deals-status.api-test.js
  portal-api/api-tests/v1/deals/deals-submission-details.api-test.js
  portal-api/api-tests/v1/deals/deals.api-test.js
  portal-api/api-tests/v1/eligibility-criteria/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/feedback/feedback.api-test.js
  portal-api/api-tests/v1/gef/address.api-test.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/api-tests/v1/gef/files.api-test.js
  portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
  portal-api/api-tests/v1/industry-sectors/industry-sectors.api-test.js
  portal-api/api-tests/v1/loan/loan-change-cover-start-date.api-test.js
  portal-api/api-tests/v1/loan/loan.api-test.js
  portal-api/api-tests/v1/mandatory-criteria/mandatory-criteria.api-test.js
  portal-api/api-tests/v1/reports/review-ukef-decision.api-test.js
  portal-api/api-tests/v1/reports/unissued-facilities.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/due-report-periods.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/last-uploaded.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/next-report-period.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/previous-reports.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-download.api-test.js
  portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js
  portal-api/api-tests/v1/validate/validate-token.api-test.js
  portal-api/src/constants/banks.js
  portal-api/src/constants/index.js
  portal-api/src/v1/users/validation/index.js
  portal-api/src/v1/users/validation/rules/firstName-must-not-be-empty.js
  portal-api/src/v1/users/validation/rules/firstName-must-not-be-empty.test.js
  portal-api/src/v1/users/validation/rules/select-at-least-one-bank.js
  portal-api/src/v1/users/validation/rules/select-at-least-one-bank.test.js
  portal-api/src/v1/users/validation/rules/select-at-least-one-role.js
  portal-api/src/v1/users/validation/rules/select-at-least-one-role.test.js
  portal-api/src/v1/users/validation/rules/surname-must-not-be-empty.js
  portal-api/src/v1/users/validation/rules/surname-must-not-be-empty.test.js
  portal/server/routes/admin/users.js
  portal/templates/admin/user-edit.njk
  utils/mock-data-loader/portal-users/index.js
Labels: Type: Fix

#3237 feat(FN-1739): add parser to parse form values before sending
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/parse-validated-add-payment-form-values.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/parse-validated-add-payment-form-values.ts
  trade-finance-manager-ui/server/types/add-payment-form-values.ts
Labels: Type: Fintech

#3235 feat(FN-1743): display grouped fee records and payments
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.api-test.ts
  dtfs-central-api/src/helpers/calculate-total-currency-and-amount.test.ts
  dtfs-central-api/src/helpers/calculate-total-currency-and-amount.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/mapping/payment-mapper.test.ts
  dtfs-central-api/src/mapping/payment-mapper.ts
  dtfs-central-api/src/repositories/payment-repo/index.ts
  dtfs-central-api/src/repositories/payment-repo/payment.repo.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/index.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report.repo.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller/index.test.ts
  trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-api/test-helpers/utilisation-report-reconciliation-details.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/api-response-types/index.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.test.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/types/premium-payments-table-checkbox-id.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/fee-record-item.ts
  trade-finance-manager-ui/test-helpers/fee-record-payment-group-item.ts
  trade-finance-manager-ui/test-helpers/fee-record-view-model-item.ts
  trade-finance-manager-ui/test-helpers/index.ts
  trade-finance-manager-ui/test-helpers/utilisation-report-reconciliation.ts
Labels: Type: Fintech

#3241 feat(FN-2731): remove unused mongodb references for utilisation reports
  dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-data.ts
  dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-reports.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/index.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/utilisation-data-repo.test.ts
  dtfs-central-api/src/repositories/utilisation-data-repo/utilisation-data-repo.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.test.ts
  libs/common/src/constants/mongo-db-collections.ts
  libs/common/src/types/mongo-db-models/db-model.ts
  libs/common/src/types/mongo-db-models/index.ts
  libs/common/src/types/utilisation-reports.ts
  utils/data-migration/sql/utilisation-reports/helpers/transformers.helper.ts
  utils/data-migration/sql/utilisation-reports/index.ts
  utils/data-migration/sql/utilisation-reports/types/index.ts
  utils/data-migration/sql/utilisation-reports/types/mongo-azure-file-info.ts
  utils/data-migration/sql/utilisation-reports/types/mongo-utilisation-data.ts
  utils/data-migration/sql/utilisation-reports/types/mongo-utilisation-report.ts
Labels: Type: Fintech

#3164 feat(dtfs2-6966): add audit logs to create deal comment endpoint
  dtfs-central-api/src/v1/controllers/portal/deal/add-deal-comment.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  portal-api/api-tests/api-ssrf.api-test.js
  portal-api/api-tests/v1/deals/deal-comments.api-test.js
  portal-api/api-tests/v1/deals/deals-status.api-test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/deal-comments.controller.js
  portal-api/src/v1/controllers/deal-status.controller.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-underwriter-managers-decision.controller.js
Labels: Type: Feature

#3242 feat(FN-1751): add edit payment link to payments table
  dtfs-central-api/src/mapping/payment-mapper.test.ts
  dtfs-central-api/src/mapping/payment-mapper.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-report-reconciliation-details.js
  trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3244 feat(FN-2731): remove sql data migrator
  .github/workflows/lint.yml
  utils/data-migration/sql/utilisation-reports/README.md
  utils/data-migration/sql/utilisation-reports/helpers/ejson.helper.ts
  utils/data-migration/sql/utilisation-reports/helpers/index.ts
  utils/data-migration/sql/utilisation-reports/helpers/transformers.helper.ts
  utils/data-migration/sql/utilisation-reports/index.ts
  utils/data-migration/sql/utilisation-reports/mongodb-ejson/utilisationData.json
  utils/data-migration/sql/utilisation-reports/mongodb-ejson/utilisationReports.json
  utils/data-migration/sql/utilisation-reports/types/index.ts
  utils/data-migration/sql/utilisation-reports/types/mongo-azure-file-info.ts
  utils/data-migration/sql/utilisation-reports/types/mongo-utilisation-data.ts
  utils/data-migration/sql/utilisation-reports/types/mongo-utilisation-report.ts
Labels: Type: Fintech

#3165 feat(dtfs2-6966): add audit logs to create facility endpoint
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-bss-deals-put-submit.api-test.js
  dtfs-central-api/src/v1/controllers/portal/facility/create-facility.controller.js
  portal-api/api-tests/v1/bonds/bonds.api-test.js
Labels: Type: Feature

#3216 chore(FN): fix type-check:all script
  azure-functions/acbs-function/package.json
  tsconfig.eslint.json
  tsconfig.json
  utils/.eslintrc.js
  utils/data-migration/tsconfig.json
  utils/mock-data-loader/tsconfig.eslint.json
  utils/tsconfig.eslint.json
  utils/tsconfig.json
Labels: Type: Fintech

#3166 feat(dtfs2-6966): add audit logs to create multiple facilities endpoint
  dtfs-central-api/api-tests/v1/facilities/facilities.api-test.js
  dtfs-central-api/src/v1/controllers/portal/facility/create-multiple-facilities.controller.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
Labels: Type: Feature

#3175 feat(DTFS2-7174): implement deletion helper in portal-api gef routes
  dtfs-central-api/api-tests/v1/cron-jobs/cron-jobs.api-test.js
  dtfs-central-api/api-tests/v1/durable-functions/durable-functions.api-test.js
  dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-delete.api-test.js
  dtfs-central-api/src/cron-scheduler-jobs/delete-acbs-durable-function-logs/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/delete-acbs-durable-function-logs/index.ts
  dtfs-central-api/src/errors/index.ts
  dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.ts
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.ts
  dtfs-central-api/src/v1/controllers/portal/deal/delete-deal.controller.ts
  dtfs-central-api/src/v1/controllers/portal/facility/delete-facility.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-teams.controller.js
  dtfs-central-api/src/v1/controllers/tfm/users/tfm-users.controller.js
  libs/common/.eslintrc.js
  libs/common/package.json
  libs/common/src/change-stream/delete-many.ts
  libs/common/src/change-stream/delete-one.ts
  libs/common/src/change-stream/test-helpers/generate-mock-audit-database-record.ts
  libs/common/src/change-stream/test-helpers/with-delete-many.api-tests.ts
  libs/common/src/change-stream/test-helpers/with-delete-one.api-tests.ts
  libs/common/src/constants/mongo-db-collections.ts
  libs/common/src/errors/database.error.test.ts
  libs/common/src/errors/database.error.ts
  libs/common/src/errors/document-not-deleted.error.ts
  libs/common/src/errors/document-not-found.error.ts
  libs/common/src/errors/index.ts
  libs/common/src/errors/write-concern.error.test.ts
  libs/common/src/errors/write-concern.error.ts
  libs/common/src/test-helpers/expect-to-be-object-id.d.ts
  libs/common/src/test-helpers/expect-to-be-object-id.ts
  package-lock.json
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/api-tests/v1/gef/files.api-test.js
  portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
  portal-api/src/v1/controllers/banks.controller.js
  portal-api/src/v1/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/controllers/feedback.controller.js
  portal-api/src/v1/controllers/mandatoryCriteria.controller.js
  portal-api/src/v1/gef/controllers/application.controller.js
  portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/files.controller.js
  portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
  portal-api/src/v1/gef/utils.service.js
  portal-api/src/v1/users/controller.js
  portal-api/src/v1/users/routes.js
  trade-finance-manager-api/src/v1/controllers/user/user.controller.js
  trade-finance-manager-api/src/v1/controllers/user/user.routes.js
Labels: Type: Feature

#3179 feat(dtfs2-6966): add audit logs to update facility endpoint
  dtfs-central-api/api-tests/v1/facilities/facility-put.api-test.js
  dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  e2e-tests/portal/cypress/support/central-api/api.js
  e2e-tests/tfm/cypress/support/central-api/api.js
  portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.js
  portal-api/src/v1/controllers/facilities.controller.js
  portal-api/src/v1/controllers/loans.controller.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/update-facilities.js
  trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
  trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.js
  utils/mock-data-loader/centralApi.js
Labels: Type: Feature

#3180 feat(dtfs2-6966): add audit logs to update facility status endpoint
  dtfs-central-api/api-tests/v1/facilities/facility-put.api-test.js
  dtfs-central-api/api-tests/v1/facilities/facility-status-put.api-test.js
  dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
  dtfs-central-api/src/v1/routes/portal-routes.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/update-facilities.js
  trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
Labels: Type: Feature

#3252 feat(dtfs2-6966): add audit logs to update deal edited by portal
  dtfs-central-api/src/v1/controllers/portal/deal/update-deal.controller.js
  dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
Labels: Type: Feature

#3253 feat(dtfs2-6966): add audit logs to update deal status endpoint
  dtfs-central-api/api-tests/v1/deals/update-deal-status.api-test.js
  dtfs-central-api/api-tests/v1/gef-deals/gef-deal-status-put.api-test.js
  dtfs-central-api/src/v1/controllers/portal/deal/update-deal-status.controller.js
  dtfs-central-api/src/v1/controllers/portal/deal/update-deal.controller.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/put-gef-deal.status.controller.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/api-test-users.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-underwriter-managers-decision.controller.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.test.js
Labels: Type: Feature

#3250 feat(DTFS2-7230): added yaml validation
  .github/workflows/lint.yml
  package-lock.json
  package.json
Labels: Type: Feature

#3257 feat(FN-1714): update query when getting reports
  dtfs-central-api/api-tests/v1/utilisation-reports/get-fee-records-to-key.api-test.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report.repo.ts
Labels: Type: Fintech

#3256 feat(DTFS2-7196): add `Societe Generale` bank
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  portal/templates/_partials/before-you-start.njk
Labels: Type: Feature

#3255 feat(dtfs2-6966): update missing gef endpoint
  docker-compose.yml
  dtfs-central-api/api-tests/v1/gef-deals/gef-deal-put.api-test.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/update-deal.controller.js
  package.json
  portal-api/api-tests/v1/gef/facilities.api-test.js
  portal-api/src/v1/gef/controllers/facilities.controller.js
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.js
Labels: Type: Feature

#3259 feat(FN-1714): fix check keying data error text
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.ts
Labels: Type: Fintech

#3246 fix(DTFS2-6713): eStore site directory creation
  dtfs-central-api/src/types/custom-express-request.ts
  external-api/api-tests/v1/eStore.api-test.ts
  external-api/package.json
  external-api/src/constants/eStore.constant.ts
  external-api/src/cron/eStoreSiteCreationJob.cron.ts
  external-api/src/cron/eStoreTermStoreCreationJob.cron.ts
  external-api/src/cron/index.ts
  external-api/src/database/mongo-client.ts
  external-api/src/helpers/cron.ts
  external-api/src/helpers/date.ts
  external-api/src/helpers/errors/estore-internal-server-error.ts
  external-api/src/helpers/types/estore.ts
  external-api/src/helpers/validIds.test.ts
  external-api/src/interfaces/eStore.interface.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  external-api/src/v1/controllers/estore/eStoreApi.ts
  libs/common/package.json
  libs/common/src/helpers/custom-axios-validate-status.test.ts
  libs/common/src/helpers/custom-axios-validate-status.ts
  libs/common/src/helpers/index.ts
  libs/common/src/types/express-custom-request.ts
  libs/common/src/types/index.ts
  package-lock.json
  package.json
Labels: Type: Fix, dependencies

#3247 feat(FN-1720): delete payment endpoint
  dtfs-central-api/api-tests/v1/utilisation-reports/delete-payment.api-test.ts
  dtfs-central-api/src/helpers/fee-record-matching.test.ts
  dtfs-central-api/src/helpers/fee-record-matching.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/repositories/payment-repo/index.ts
  dtfs-central-api/src/repositories/payment-repo/payment.repo.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event-type.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/helpers.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-removed-from-fee-record/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-removed-from-fee-record/payment-removed-from-fee-record.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-removed-from-fee-record/payment-removed-from-fee-record.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event-type.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-delete-payment-payload.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/test-helpers/test-data/db-request-source.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
Labels: Type: Fintech
