Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-08, with the labels that each got.

#3324 feat(FN-1722): generate and display keying sheet rows for auto matched zero payment fee records
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/types/fee-records.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.ts
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/keying-sheet.js
  trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.helpers.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.seed.ts
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.seeder.ts
Labels: Type: Fintech

#3358 fix(DTFS2-7305): code consistency
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-fee-records-to-key.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-selected-fee-records-details.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-reports-by-bank-and-year.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/update-utilisation-report-status.controller.ts
Labels: Type: Fix

#3365 feat(FN-3289): remove the keying sheet accruals columns
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/types/fee-records.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.ts
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/keying-sheet.js
  libs/common/src/sql-db-connection/migrations/1722868553795-RemoveFeeRecordAccrualsColumn.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table.component-test.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table.njk
  utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.helpers.ts
Labels: Type: Fintech

#3362 feat(FN-1725): keying sheet fixed fee calculation
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/package.json
  dtfs-central-api/src/helpers/convert-timestamp-to-date.test.ts
  dtfs-central-api/src/helpers/convert-timestamp-to-date.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/helpers/tfm-facilities.helper.test.ts
  dtfs-central-api/src/helpers/tfm-facilities.helper.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/test-helpers/test-data/index.ts
  dtfs-central-api/test-helpers/test-data/tfm-facility-amendment.ts
  dtfs-central-api/test-helpers/test-data/tfm-facility.ts
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/reconcile-fee-records.spec.js
  package-lock.json
Labels: Type: Fintech

#3363 fix(DTFS2-6889): ensure ACBS DOF payload is correctly constructed
  azure-functions/acbs-function/.eslintrc.js
  azure-functions/acbs-function/src/functions/acbs.js
  dtfs-central-api/.eslintrc.js
  dtfs-central-api/src/v1/controllers/portal/deal/update-deal.controller.js
  external-api/.eslintrc.js
  gef-ui/.eslintrc.js
  libs/common/.eslintrc.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/payload-verification.ts
  portal-api/.eslintrc.js
  portal/.eslintrc.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal-acbs.js
  trade-finance-manager-api/src/v1/__mocks__/mock-deal.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.test.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/controllers/party.controller.js
  trade-finance-manager-api/src/v1/controllers/party.controller.test.js
  trade-finance-manager-ui/.eslintrc.js
  utils/.eslintrc.js
  utils/mock-data-loader/insert-mocks-gef.js
Labels: Type: Fix

#3371 feat(DTFS2-7169): update env vars in docker compose
  docker-compose.gha.yml
  docker-compose.replica-set.yml
  docker-compose.yml
Labels: Type: Feature

#3374 fix(dtfs2-7311): update integer in jsdocs when incorrect
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-currency-exchange-rate.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-amount.js
  azure-functions/acbs-function/mappings/facility/helpers/get-interest-or-fee-rate.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-amount-difference.js
  utils/data-migration/helpers/format.js
Labels: Type: Fix

#3376 feat(DTFS2-7308): added Danske bank
  cspell.json
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  libs/common/src/sql-db-connection/Dockerfile
  libs/common/src/sql-db-connection/init.sh
  portal-api/api-tests/v1/gef/external-api.api-test.js
  portal-api/src/v1/gef/controllers/validation/external.js
  portal/templates/_partials/before-you-start.njk
Labels: Type: Feature

#3377 feat(FN-1725): util to create keying sheet tfm facilities
  .github/workflows/test.yml
  e2e-tests/gef/cypress/support/commands/loadData.js
  package.json
  utils/README.md
  utils/create-keying-sheet-tfm-facilities/database-client/facility-client.ts
  utils/create-keying-sheet-tfm-facilities/database-client/index.ts
  utils/create-keying-sheet-tfm-facilities/database-client/mongo-db-client.ts
  utils/create-keying-sheet-tfm-facilities/database-client/tfm-facility-client.ts
  utils/create-keying-sheet-tfm-facilities/helpers/generate-random-tfm-facility-for-facility.ts
  utils/create-keying-sheet-tfm-facilities/helpers/get-sql-facility-ids.ts
  utils/create-keying-sheet-tfm-facilities/helpers/get-valid-gef-deal-id-generator.ts
  utils/create-keying-sheet-tfm-facilities/helpers/index.ts
  utils/create-keying-sheet-tfm-facilities/index.ts
  utils/create-keying-sheet-tfm-facilities/mock-data/facility.ts
  utils/create-keying-sheet-tfm-facilities/mock-data/index.ts
  utils/create-keying-sheet-tfm-facilities/mock-data/tfm-facility-amendment.ts
  utils/mock-data-loader/tfm/clean-all-tables-tfm.js
  utils/package.json
Labels: Type: Fintech

#3361 feat(DTFS2-7232): add current facility end date to amendments
  dtfs-central-api/src/constants/amendments.ts
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.ts
  libs/common/src/constants/amendment-status.ts
  libs/common/src/constants/amendments.ts
  libs/common/src/constants/index.ts
  libs/common/src/types/amendment-status.ts
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/amendments/create-amendment-tfm-object-on-amendment-completion.api-test.js
  trade-finance-manager-api/src/constants/amendments.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.test.js
  trade-finance-manager-ui/server/api-response-types/amendments.ts
  trade-finance-manager-ui/server/api-response-types/index.ts
  trade-finance-manager-ui/server/api-ssrf.test.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentFacilityEndDate.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentFacilityEndDate.get.api-test.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentFacilityEndDate.post.api-test.js
  trade-finance-manager-ui/templates/case/amendments/amendment-facility-end-date.njk
Labels: Type: Feature

#3382 feat(FN-3187): create entity for fee record payment join table
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/sql-db-entities/join-tables/fee-record-payment/fee-record-payment.join-table.entity.ts
  libs/common/src/sql-db-entities/join-tables/fee-record-payment/index.ts
  libs/common/src/sql-db-entities/join-tables/index.ts
Labels: Type: Fintech

#3375 fix(dtfs2-7312): update jsdocs to avoid not awaiting promises
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/src/functions/acbs-http.js
  azure-functions/acbs-function/src/functions/activity-get-acbs-country-code.js
  e2e-tests/support/tasks.js
  external-api/src/v1/controllers/acbs.controller.ts
  gef-ui/server/controllers/unissued-facilities/index.js
  gef-ui/server/controllers/unissued-facilities/validation.js
  portal-api/src/external-api/bank-holidays.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/section-status/about.js
  portal/server/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
  trade-finance-manager-api/src/v1/controllers/deal.party-db.js
  trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/src/v1/helpers/activity.js
  trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.js
  trade-finance-manager-api/src/v1/tasks/assign-group-tasks-to-one-user.js
  trade-finance-manager-api/src/v1/tasks/map-task-object.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/parties/index.js
  trade-finance-manager-ui/server/controllers/helpers/dealsAndFacilities.helper.js
  utils/data-migration/helpers/database.js
  utils/data-migration/helpers/io.js
  utils/reporting/tfm/rad-reporting.js
  utils/reporting/tfm/tfm-reporting.js
Labels: Type: Fix

#3385 feat(FN-3267): update facility utilisation data with keying data
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/src/errors/transaction-failed.error.ts
  dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts
  dtfs-central-api/src/helpers/execute-with-sql-transaction.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-to-an-existing-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/reconcile-fee-records.spec.js
  libs/common/src/sql-db-connection/migrations/1723453818266-AddFacilityUtilisationDataFixedFeeColumn.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.test.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.types.ts
  libs/common/src/test-helpers/mock-data/facility-utilisation-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
  libs/common/src/utils/report-period.test.ts
  libs/common/src/utils/report-period.ts
Labels: Type: Fintech

#3386 fix(DTFS2-7316): remove transactions from deletion audit logs
  libs/common/src/change-stream/delete-many.ts
  libs/common/src/change-stream/delete-one.test.ts
  libs/common/src/change-stream/delete-one.ts
  libs/common/src/change-stream/test-helpers/with-delete-many.api-tests.ts
  libs/common/src/change-stream/test-helpers/with-delete-one.api-tests.ts
  portal-api/api-tests/deal-versioning.api-test.js
  portal-api/api-tests/v1/gef/facilities/facilities.delete.api-test.js
Labels: Type: Bug

#3309 feat(dtfs2-6616): automatically amend facility covenant in acbs
  azure-functions/acbs-function/api.api-test.js
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/helpers/currency.js
  azure-functions/acbs-function/helpers/currency.test.js
  azure-functions/acbs-function/jest.common.config.js
  azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-value.js
  azure-functions/acbs-function/mappings/facility/facility-covenant-amend.js
  azure-functions/acbs-function/mappings/facility/facility-covenant-amend.test.js
  azure-functions/acbs-function/mappings/facility/helpers/get-facility-value.js
  azure-functions/acbs-function/mappings/facility/helpers/get-fee-amount.js
  azure-functions/acbs-function/mappings/facility/helpers/get-interest-or-fee-rate.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/get-maximum-liability.test.js
  azure-functions/acbs-function/mappings/facility/index.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-covenant-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-master-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  azure-functions/acbs-function/src/functions/activity-update-facility-covenant.js
  azure-functions/acbs-function/tsconfig.json
  azure-functions/acbs-function/unit.jest.config.js
Labels: Type: Feature

#3391 fix(DTFS2-7316): add update and replace to deletion change stream
  dtfs-central-api/src/services/changeStream/setupChangeStream.ts
Labels: Type: Bug

#3381 feat(FN-3226): add util to check database facility ids
  package-lock.json
  utils/README.md
  utils/package.json
  utils/validate-facility-ids/database-client/index.ts
  utils/validate-facility-ids/database-client/mongo-db-client.ts
  utils/validate-facility-ids/helpers/get-unique-fee-record-facility-ids.ts
  utils/validate-facility-ids/helpers/get-unique-tfm-facilities-ukef-facility-ids.ts
  utils/validate-facility-ids/helpers/index.ts
  utils/validate-facility-ids/index.ts
Labels: Type: Fintech

#3389 chore(DTFS2-7317): align docker-compose, remove docker-compose.replica-set
  README.md
  docker-compose.gha.yml
  docker-compose.replica-set.yml
Labels: Type: chore

#3393 feat(FN-2308): add empty payment details tab text
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3400 fix(dtfs2-7313): add logging to identify remote only issue
  dtfs-central-api/src/v1/routes/middleware/payload-validation/create-validation-middleware-for-schema.ts
  dtfs-central-api/src/v1/validation/route-validators/express-validator-result-handler.js
  dtfs-central-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-api/src/v1/api.js
Labels: Type: Fix

#3379 feat(FN-3187): display many-to-many payments on keying sheet
  dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
  dtfs-central-api/src/mapping/fee-record-mapper.test.ts
  dtfs-central-api/src/mapping/fee-record-mapper.ts
  dtfs-central-api/src/mapping/keying-sheet-mapping.test.ts
  dtfs-central-api/src/mapping/keying-sheet-mapping.ts
  dtfs-central-api/src/repositories/fee-record-repo/fee-record.repo.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/get-keying-sheet-fee-payment-shares-for-fee-records.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/get-keying-sheet-fee-payment-shares-for-fee-records.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/types/fee-records.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-keying-sheet-for-report-id.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-keying-sheet-for-report-id.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.ts
  libs/common/src/sql-db-connection/migrations/1723631218686-AddPaymentAmountUsedForFeeRecordColumn.ts
  libs/common/src/sql-db-entities/join-tables/fee-record-payment/fee-record-payment.join-table.entity.ts
  libs/common/src/sql-db-entities/join-tables/fee-record-payment/fee-record-payment.join-table.types.ts
Labels: Type: Fintech

#3397 chore(DTFS2-7317): remove docker-compose.gha
  .github/workflows/test.yml
  README.md
  docker-compose.gha.yml
  docker-compose.yml
Labels: chore

#3410 feat(FN-2309): display payments in payment details tab
  trade-finance-manager-ui/component-tests/assertions.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3411 fix(dtfs2-7313): add logging to identify remote only bug
  dtfs-central-api/src/v1/routes/middleware/bug-fix-logs.js
  dtfs-central-api/src/v1/routes/middleware/index.js
  dtfs-central-api/src/v1/routes/middleware/payload-validation/create-validation-middleware-for-schema.ts
  dtfs-central-api/src/v1/routes/tfm-routes.js
  dtfs-central-api/src/v1/validation/route-validators/express-validator-result-handler.js
Labels: Type: Fix

#3418 feat(FN-1725): add e2e test for keying sheets
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/generate-keying-sheet.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
Labels: Type: Fintech

#3419 fix(DTFS2-6713): enable db migrate
  .github/workflows/deployment.yml
Labels: Type: Fix

#3380 feat(DTFS2-7217): add facility end date page
  e2e-tests/gef/cypress/e2e/facility/facility-end-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-issued-to-unissued.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facilities-change-to-issued-3-months-after.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facility-change-from-preview-specialIssuedPermission.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/unissued-facility-to-issued-cover-start-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/version-0-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/version-0-unissued-facility.spec.js
  gef-ui/api-tests/facility-end-date.get.api-test.js
  gef-ui/api-tests/facility-end-date.post.api-test.js
  gef-ui/component-tests/partials/facility-end-date.component-test.js
  gef-ui/server/controllers/bank-review-date/index.ts
  gef-ui/server/controllers/bank-review-date/validation.test.ts
  gef-ui/server/controllers/bank-review-date/validation.ts
  gef-ui/server/controllers/facility-end-date/index.ts
  gef-ui/server/controllers/facility-end-date/validation.test.ts
  gef-ui/server/controllers/facility-end-date/validation.ts
  gef-ui/server/controllers/unissued-facilities/index.js
  gef-ui/server/controllers/unissued-facilities/index.test.js
  gef-ui/server/routes/__tests__/unissued-facilities.test.js
  gef-ui/server/routes/facilities/facility-end-date.ts
  gef-ui/server/routes/unissued-facilities.js
  gef-ui/server/types/errors-or-date.ts
  gef-ui/server/types/validation-error.ts
  gef-ui/server/types/view-models/facility-end-date-view-model.ts
  gef-ui/server/utils/day-month-year-validation.test.ts
  gef-ui/server/utils/day-month-year-validation.ts
  gef-ui/server/utils/get-cover-start-date-or-start-of-today.ts
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/templates/partials/facility-end-date.njk
  gef-ui/templates/partials/unissued-change-about-facility.njk
  portal-api/src/v1/gef/models/facilities.js
Labels: Type: Feature

#3414 fix(dtfs2-7313): delete logging used for bug identification
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-post-amendments.controller.ts
  dtfs-central-api/src/v1/routes/middleware/bug-fix-logs.js
  dtfs-central-api/src/v1/routes/middleware/index.js
  dtfs-central-api/src/v1/routes/middleware/payload-validation/create-validation-middleware-for-schema.ts
  dtfs-central-api/src/v1/routes/tfm-routes.js
  dtfs-central-api/src/v1/validation/route-validators/express-validator-result-handler.js
  dtfs-central-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
Labels: Type: Fix

#3405 feat(FN-3274): add script to migrate ACBS utilisation data to TFM
  libs/common/src/constants/index.ts
  libs/common/src/constants/request-platform-type.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.types.ts
  libs/common/src/sql-db-entities/helpers/user-id.helper.ts
  utils/data-migration/migrate-acbs-utilisation-data-to-tfm/README.md
  utils/data-migration/migrate-acbs-utilisation-data-to-tfm/index.ts
  utils/package.json
Labels: Type: Fintech

#3424 feat(FN-2310): display payment link on payment details page
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3429 feat(FN-3389): add docstrings to event handlers and entities
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/mark-as-ready-to-key/mark-as-ready-to-key.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/mark-as-reconciled/mark-as-reconciled.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-added-to-payment-group/other-fee-added-to-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/other-fee-removed-from-payment-group/other-fee-removed-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-added/payment-added.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-edited/payment-edited.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/remove-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/add-a-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-fees-to-an-existing-payment-group/add-fees-to-an-existing-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/due-report-initialised/due-report-initialised.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/edit-payment/edit-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/fee-records-match-attached-payments.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-ready-to-key/mark-fee-records-as-ready-to-key.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-reconciled/mark-fee-records-as-reconciled.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  libs/common/src/sql-db-entities/azure-file-info/azure-file-info.entity.ts
  libs/common/src/sql-db-entities/base-entities/auditable.base-entity.ts
  libs/common/src/sql-db-entities/custom-columns/exchange-rate-column.ts
  libs/common/src/sql-db-entities/custom-columns/monetary-column.ts
  libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/join-tables/fee-record-payment/fee-record-payment.join-table.entity.ts
  libs/common/src/sql-db-entities/partial-entities/month-and-year.partial-entity.ts
  libs/common/src/sql-db-entities/partial-entities/report-period.partial-entity.ts
  libs/common/src/sql-db-entities/payment/payment.entity.ts
  libs/common/src/sql-db-entities/utilisation-report/utilisation-report.entity.ts
Labels: Type: Fintech

#3430 feat(DTFS2-7168): add FED & BRD to emails
  libs/common/src/constants/date-formats.ts
  libs/common/src/constants/index.ts
  trade-finance-manager-api/src/v1/__mocks__/mock-cash-contingent-facilities.js
  trade-finance-manager-api/src/v1/controllers/deal.party-db.test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.test.js
  trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.test.js
  trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/bss-email-variables.test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-content-strings.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/generate-email-variables.api-test.js
  trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/generate-email-variables.js
  trade-finance-manager-api/src/v1/emails/MIA-confirmation/bss-email-variables.test.js
  trade-finance-manager-api/src/v1/emails/MIA-confirmation/generate-email-variables.test.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.test.js
Labels: Type: Feature
