Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-09, with the labels that each got.

#3434 feat(FN-2594): disable input before bank is selected
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/find-utilisation-reports-by-bank-and-year.spec.js
  trade-finance-manager-ui/public/js/enableFindReportsByYearDropdown.js
  trade-finance-manager-ui/public/js/enableFindReportsByYearDropdown.js.map
  trade-finance-manager-ui/scripts/enable-find-reports-by-year-dropdown.ts
  trade-finance-manager-ui/templates/index.njk
Labels: Type: Fintech

#3399 feat(FN-3293): add back and cancel links to 'add to an existing payment' screen
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-to-an-existing-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-fee-records-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportAddPaymentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportAddToAnExistingPaymentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/url-character-allowances.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-group-input.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/add-to-an-existing-payment.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/get-link-to-premium-payments-tab.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/get-link-to-premium-payments-tab.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/add-to-an-existing-payment-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/add-to-an-existing-payment-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/available-payment-group-view-model-mapper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/available-payment-group-view-model-mapper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/validate-payment-form-values.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/validate-payment-form-values.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/extract-query-and-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/extract-query-and-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-and-clear-fields-from-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-and-clear-fields-from-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-is-checkbox-checked.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-is-checkbox-checked.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-selected-fee-record-ids-from-query.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/get-selected-fee-record-ids-from-query.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/handle-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/handle-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.test.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.test.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.ts
  trade-finance-manager-ui/server/types/view-models/add-to-an-existing-payment-view-model.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-group-input.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/add-to-an-existing-payment.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/test-data/add-to-an-existing-payment-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/payment-group-inputs-view-model.ts
Labels: Type: Fintech

#3449 feat(FN-3417): add batch saving for facility utilisation data
  dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
Labels: Type: Fintech

#3450 feat(FN-2069): align columns across all report reconciliation tables on bank reports page
  package-lock.json
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.ts
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/mojFrontend.js.map
  trade-finance-manager-ui/styles/layout.scss
  trade-finance-manager-ui/styles/table.scss
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
Labels: Type: Fintech

#3461 feat(FN-3377): fix report received email template TFM URL
  .github/workflows/development_infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  docker-compose.yml
  portal-api/src/constants/email-template-ids.js
  portal-api/src/v1/services/utilisation-report/email-service.test.ts
  portal-api/src/v1/services/utilisation-report/email-service.ts
Labels: Type: Fintech

#3463 feat(FN-2069): hide horizontal scrollbar on report reconciliation table when at full width
  trade-finance-manager-ui/styles/table.scss
Labels: Type: Fintech

#3466 chore(deps): bump dependencies
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: dependencies, chore

#3390 fix(DTFS2-6713): estore buyer, deal, facilities and documents upload
  .env.sample
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .husky/commit-msg
  .husky/pre-commit
  .markdownlint.json
  azure-functions/acbs-function/package.json
  azure-functions/acbs-function/unit.ff.jest.config.js
  doc/docstring.md
  docker-compose.yml
  dtfs-central-api/package.json
  dtfs-central-api/unit.ff.jest.config.js
  e2e-tests/gef/cypress/support/commands/loadData.js
  external-api/api-tests/v1/eStore.api-test.ts
  external-api/package.json
  external-api/src/constants/eStore.constant.ts
  external-api/src/constants/emailTemplates.constant.ts
  external-api/src/cron/eStoreBuyerDirectoryCreationJob.cron.ts
  external-api/src/cron/eStoreDealDirectoryCreationJob.cron.ts
  external-api/src/cron/eStoreDealFolderCreationJob.cron.ts
  external-api/src/cron/eStoreDocumentsCreationJob.cron.ts
  external-api/src/cron/eStoreFacilityDirectoryCreationJob.cron.ts
  external-api/src/cron/eStoreFacilityFolderCreationJob.cron.ts
  external-api/src/cron/eStoreSiteCreationJob.cron.ts
  external-api/src/cron/eStoreTermStoreCreationJob.cron.ts
  external-api/src/cron/index.ts
  external-api/src/helpers/cron.ts
  external-api/src/helpers/types/estore.ts
  external-api/src/helpers/validIds.test.ts
  external-api/src/interfaces/eStore.interface.ts
  external-api/src/repositories/estore/estore-repo.ts
  external-api/src/v1/controllers/estore/eStore.controller.ts
  external-api/src/v1/controllers/estore/eStoreApi.ts
  external-api/src/v1/routes/external-apis.route.ts
  external-api/unit.ff.jest.config.js
  gef-ui/package.json
  gef-ui/server/utils/facility-helpers.js
  gef-ui/unit.ff.jest.config.js
  libs/common/package.json
  libs/common/unit.ff.jest.config.js
  mongodb/Dockerfile
  package-lock.json
  package.json
  portal-api/package.json
  portal-api/unit.ff.jest.config.js
  portal/package.json
  portal/unit.ff.jest.config.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/getLatestFacilityEndDateValues.test.ts
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/getLatestFacilityEndDateValuest.ff-test.ts
  trade-finance-manager-api/unit.ff.jest.config.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/index.ff-test.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
  trade-finance-manager-ui/unit.ff.jest.config.js
  utils/README.md
  utils/package.json
Labels: Type: Fix

#3472 chore(tests): simplify some unit test descriptions, align file names
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.test.ts
  e2e-tests/gef/cypress/e2e/checker/application-details-submit-to-checker.spec.js
  gef-ui/server/controllers/application-details/canUpdateUnissuedFacilitiesCheck.test.js
  gef-ui/server/controllers/submit-to-ukef/index.test.js
  gef-ui/server/utils/deal-helpers.test.js
  gef-ui/server/utils/display-items.test.js
  gef-ui/server/utils/facility-helpers.test.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/server/utils/mocks/mock-applications.js
  gef-ui/server/utils/mocks/mock-facilities.js
  gef-ui/server/utils/mocks/mock-requests.js
  gef-ui/server/utils/mocks/mock-users.js
  portal-api/api-tests/v1/gef/application.api-test.js
  portal-api/api-tests/v1/users/post-create-user.api-test.js
  trade-finance-manager-api/api-tests/v1/feedback/feedback.api-test.js
Labels: Type: chore

#3464 feat(FN-2310): add custom behaviour for edit payment redirect
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/delete-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/remove-fees-from-payment.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/e2e/partials/index.js
  e2e-tests/tfm/cypress/support/ui/click-events/click-back-link.js
  e2e-tests/tfm/cypress/support/ui/click-events/index.js
  e2e-tests/tfm/cypress/support/ui/index.js
  trade-finance-manager-ui/component-tests/componentRenderer.ts
  trade-finance-manager-ui/component-tests/pageRenderer.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/fee-record-details-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table-manual-reconciliation.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/add-to-an-existing-payment.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/edit-payment.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/find-utilisation-reports-by-year.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/constants/reconciliation-for-report-tabs.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/edit-payment-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/edit-payment-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-reconciliation-for-report-href.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-reconciliation-for-report-href.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.ts
  trade-finance-manager-ui/server/middleware/validatePostRemoveFeesFromPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostRemoveFeesFromPaymentRequestBody/index.ts
  trade-finance-manager-ui/server/types/reconciliation-for-report-tab.ts
  trade-finance-manager-ui/server/types/view-models/confirm-delete-payment-view-model.ts
  trade-finance-manager-ui/server/types/view-models/edit-payment-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-details-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/edit-payment.njk
  trade-finance-manager-ui/test-helpers/edit-payment-view-model.ts
  trade-finance-manager-ui/test-helpers/fee-record-payment-group-view-model-item.ts
  trade-finance-manager-ui/test-helpers/index.ts
Labels: Type: Fintech

#3473 feat(FN-2069): recompile css files for table width fix
  trade-finance-manager-ui/public/css/styles.css
Labels: Type: Fintech

#3462 feat(FN-3162): validate that report data facility ids exist
  dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/post-validate-utilisation-report-data.api-test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/types/validation-error-generator.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-report-data-validation.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-report-data-validation.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-upload-utilisation-report-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-upload-utilisation-report-payload.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/utilisationReportUpload.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/utilisation-reports/assertUploadReportValidationErrorTableRowContains.js
  portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
Labels: Type: Fintech

#3458 feat(DTFS2-7294): add cancel deal button and Feature flag
  .env.sample
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/tfm/cypress.config.js
  libs/common/src/constants/deal-submission-type.ts
  libs/common/src/constants/index.ts
  libs/common/src/helpers/is-feature-flag-enabled.ts
  libs/common/src/types/tfm/deal-submission-type.ts
  libs/common/src/types/tfm/index.ts
  trade-finance-manager-ui/component-tests/case/deal/deal.component-test.js
  trade-finance-manager-ui/server/controllers/case/index.ff-test.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.test.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.ts
  trade-finance-manager-ui/server/controllers/helpers/index.js
  trade-finance-manager-ui/templates/case/deal/deal.njk
Labels: Type: Feature

#3496 feat(DTFS2-7346): await send email promises
  trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
  trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
  trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js
Labels: Type: Feature

#3502 feat(DTFS2-7374): deployment script
  .github/workflows/deployment.yml
  package.json
Labels: Type: Fix

#3507 feat(DTFS2-7374): conditional environment set
  .github/workflows/deployment.yml
Labels: Type: Fix

#3508 fix(DTFS2-7375): codebase vulnerabilities resolutions
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: chore, Type: Fix

#3482 chore(tests): split up e2e tests - unissued facilities
  .github/workflows/test.yml
  e2e-tests/gef/cypress/e2e/facility/pre-submission/about-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/bank-review-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities-change-facility-end-date-to-bank-review-date-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities-change-from-details-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-confirm-deletion.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-currency.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-guarantee.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-value.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/provided-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-bank-review-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-facility-end-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/version-0/version-0-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/version-0/version-0-unissued-facility.spec.js
Labels: Type: chore

#3516 fix(deployment): release based deployment
  .github/workflows/deployment.yml
Labels: Type: Fix

#3518 fix(deployment): release deployment
  .github/workflows/deployment.yml
Labels: dependencies

#3520 fix(deployment): deployment YAML syntax fix
  .github/workflows/deployment.yml
Labels: Type: Fix

#3522 fix(deployment): release deployment
  .github/workflows/deployment.yml
Labels: Type: Fix

#3523 fix(deployment): release based deployment
  .github/workflows/deployment.yml
Labels: Type: Fix

#3490 feat(FN-2311): filter only premium payments
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.api-test.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/parse-filters.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/parse-filters.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-report-reconciliation-details.js
  libs/common/src/types/utilisation-reports.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/fee-record-payment-group-view-model-item.ts
  trade-finance-manager-ui/test-helpers/utilisation-report-reconciliation.ts
Labels: Type: Fintech

#3529 fix(DTFS2-7288): deployment pipeline
  .github/workflows/deployment.yml
  libs/common/package.json
  package-lock.json
Labels: Type: Fix

#3530 fix(DTFS2-7375): dockerfile image update
  dtfs-central-api/Dockerfile
  external-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reverse-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: Type: chore, Type: Fix

#3536 chore(DTFS-7379): dry cypress command - keyboardInput - gef
  e2e-tests/gef/cypress/e2e/application/application-activities-MIA.spec.js
  e2e-tests/gef/cypress/e2e/application/name-application-create-element.spec.js
  e2e-tests/gef/cypress/e2e/application/name-application.spec.js
  e2e-tests/gef/cypress/e2e/checker/application-details-submit-to-checker.spec.js
  e2e-tests/gef/cypress/e2e/checker/submit-to-checker-mia.spec.js
  e2e-tests/gef/cypress/e2e/clone/clone-gef-deal.spec.js
  e2e-tests/gef/cypress/e2e/exporter/about-exporter.spec.js
  e2e-tests/gef/cypress/e2e/exporter/enter-exporters-corr-address.spec.js
  e2e-tests/gef/cypress/e2e/exporter/exporter-correspondence-address.spec.js
  e2e-tests/gef/cypress/e2e/exporter/exporters-address-create-element.spec.js
  e2e-tests/gef/cypress/e2e/exporter/exporters-address.spec.js
  e2e-tests/gef/cypress/e2e/exporter/exporters-incomplete-details.spec.js
  e2e-tests/gef/cypress/e2e/exporter/select-exporters-corr-address.spec.js
  e2e-tests/gef/cypress/e2e/external/companies-house.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/about-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/bank-review-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities-change-facility-end-date-to-bank-review-date-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities-change-from-details-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-value.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/provided-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-bank-review-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-facility-end-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/e2e/maker/return-to-maker-mia.spec.js
  e2e-tests/gef/cypress/e2e/maker/return-to-maker.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/eligibility-criterion-16/eligibility-criterion-16.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-add-document.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-delete-document.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-deleted-facility.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-edited-facility.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-eligibility-criteria.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-security-questions.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-submit-to-checker.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/makers-input.spec.js
  e2e-tests/gef/cypress/e2e/security/security-details.spec.js
  e2e-tests/gef/cypress/e2e/ukef/submit-to-ukef-mia.spec.js
  e2e-tests/gef/cypress/e2e/upload/upload-files-to-azure.spec.js
  e2e-tests/gef/cypress/support/commands.js
  e2e-tests/gef/cypress/support/commands/fillInBankReviewDate.js
  e2e-tests/gef/cypress/support/commands/insertElement.js
  e2e-tests/gef/cypress/support/commands/portal/enterUsernameAndPassword.js
  e2e-tests/gef/cypress/support/utils/keyboardInput.js
Labels: Type: chore

#3510 chore(tests): split up e2e tests - portal maker
  .github/workflows/test.yml
  e2e-tests/gef/cypress/.DS_Store
  e2e-tests/portal/cypress/e2e/journeys/maker/abandon-a-deal/abandon-a-deal.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bank-details/bank-details-created-field.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bank-details/bank-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/before-you-start/before-you-start.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bss-mandatory-criteria/bss-mandatory-criteria.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/edit-deal-name/edit-deal-name.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/eligibility/eligibility-criteria.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/eligibility/eligibility-documentation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/eligibility/eligibility.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/proceed-to-review/proceed-to-review.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/select-scheme/select-scheme.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/xss/xss.spec.js
Labels: Type: chore

#3534 chore(DTFS2-7380): dry cypress commands - keyboardInput - tfm
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/1. add-amendment-request.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/2. amendment-request-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/3. amendment-effective-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/4. amendment-options.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/5. facility-value.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/6. cover-end-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/7. amendment-details-automatic-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/8. amendment-details-manual-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-amendment-request-check-previous.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-proceed.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-underwriter-declined.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision-withdraw.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-lead-underwriter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-underwriter-decision.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-changes-multiple-single-amendments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-in-progress-deal-stage.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-should-change-all-facilities-values.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-tasks-automatic.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-tasks-manual.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-underwriting-page-multiple-amendments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendments-version-order.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/bss-deal-expect-no-facility-end-date-features.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-disabled/gef-deal-expect-no-facility-end-date-features.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-add-bank-review-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-add-facility-end-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-add-multiple-amendments-impacting-facility-end-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-amend-facility-end-date-and-then-change-to-bank-review-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/underwriting-page-unassigned.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/loss-given-default.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/pricing-and-risk.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/probability-of-default.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/underwriter-managers-decision-decline.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/underwriter-managers-decision.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/agent.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond-beneficiary.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond-issuer.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/buyer.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/exporter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/parties/indemnifier.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-pagination.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/facility/facilities-pagination.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/facility/facilities.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/feedback/feedback.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/login/login.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-fee-records-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/find-utilisation-reports-by-bank-and-year.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/remove-fees-from-payment.spec.js
  e2e-tests/tfm/cypress/support/commands.js
  e2e-tests/tfm/cypress/support/ui/amendments/navigate-to-is-using-facility-end-date-page.js
  e2e-tests/tfm/cypress/support/ui/index.js
  e2e-tests/tfm/cypress/support/ui/logIn.js
  e2e-tests/tfm/cypress/support/ui/type-without-delay.js
  e2e-tests/tfm/cypress/support/utils/keyboardInput.js
Labels: Type: chore

#3537 fix(DTFS2-7288): deployment pipeline
  .github/workflows/deployment.yml
  libs/common/package.json
  package-lock.json
Labels: Type: Fix

#3509 chore(tests): split up e2e tests - tfm amendments
  .github/workflows/test.yml
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision/add-bank-decision-proceed.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision/add-bank-decision-underwriter-declined.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision/add-bank-decision-withdraw.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-underwriter-decision/add-lead-underwriter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-underwriter-decision/add-underwriter-decision.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-changes-multiple-single-amendments/amendment-changes-multiple-single-amendments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-should-change-all-facilities-values/amendment-should-change-all-facilities-values.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendment-underwriting-page-multiple-amendments/amendment-underwriting-page-multiple-amendments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/amendments-version-order/amendments-version-order.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/bss-deal-expect-no-facility-end-date-features/bss-deal-expect-no-facility-end-date-features.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/in-progress/amendment-in-progress-deal-stage.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/request-when-previously-submitted/request-amendment-when-previously-submitted.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/show-amendment-button/show-amendment-button.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/tasks/amendment-tasks-automatic.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/tasks/amendment-tasks-manual.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/underwriting-page-unassigned/underwriting-page-unassigned.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/1. add-amendment-request.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/2. amendment-request-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/3. amendment-effective-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/4. amendment-options.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/5. facility-value.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/6. cover-end-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/7. amendment-details-automatic-approval.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/8. amendment-details-manual-approval.spec.js
Labels: Type: chore

#3538 chore(DTFS2-7381): dry cypress commands - keyboardInput - ukef suite
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter-managers-approved-decision-updates-portal-deal-and-submission-type-to-MIN/MIA-underwriter-managers-approved-decision-updates-portal-deal-and-submission-type-to-MIN.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-with-conditions-updates-portal-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-without-conditions-updates-portal-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-refused-updates-portal-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN-deal-creates-default-credit-rating-in-tfm/submit-AIN-deal-creates-default-credit-rating-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN-deal-creates-tasks-in-tfm/submit-AIN-deal-creates-tasks-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN-deal-creates-tfm-deal-stage-and-product/submit-AIN-deal-creates-tfm-deal-stage-and-product.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN-deal-updates-portal-deal-status/submit-AIN-deal-updates-portal-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA-deal-TFM-approves-resubmit-MIA-deal-becomes-MIN/submit-MIA-deal-TFM-approves-resubmit-MIA-deal-becomes-MIN.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA-deal-creates-tasks-in-tfm/submit-MIA-deal-creates-tasks-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA-deal-creates-tfm-deal-stage-and-product/submit-MIA-deal-creates-tfm-deal-stage-and-product.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA-deal-updates-portal-deal-status/submit-MIA-deal-updates-portal-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN-changes-tfm-stage-to-confirmed/submit-MIN-changes-tfm-stage-to-confirmed.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN-deal-does-not-create-credit-rating-in-tfm/submit-MIN-deal-does-not-create-credit-rating-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN-deal-updates-portal-deal-status/submit-MIN-deal-updates-portal-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-adds-risk-profile-to-facilities/submit-deal-adds-risk-profile-to-facilities.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-converts-contract-value-to-gbp/submit-deal-converts-contract-value-to-gbp.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-creates-loss-given-and-probability-defaults-in-tfm/submit-deal-creates-loss-given-and-probability-defaults-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-with-non-gbp-facilities/submit-deal-with-non-gbp-facilities.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued.spec.js
  e2e-tests/ukef/cypress/support/commands.js
  e2e-tests/ukef/cypress/support/portal/enterUsernameAndPassword.js
  e2e-tests/ukef/cypress/support/trade-finance-manager-ui/login.js
  e2e-tests/ukef/cypress/support/utils/keyboardInput.js
Labels: Type: chore

#3469 feat(DTFS2-7294): add deal cancellation update backend
  docker-compose.yml
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-deal-cancellation-put.api-test.js
  dtfs-central-api/src/repositories/tfm-deals-repo/index.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deals-cancellation-repo.test.ts
  dtfs-central-api/src/v1/controllers/tfm/deal-cancellation/tfm-put-update-deal-cancellation.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/create-validation-middleware-for-schema.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-deal-cancellation-payload.ts
  dtfs-central-api/src/v1/routes/tfm-routes.js
  libs/common/package.json
  libs/common/src/constants/tfm/deal-stage.ts
  libs/common/src/constants/tfm/index.ts
  libs/common/src/index.ts
  libs/common/src/middleware/feature-flags/deal-cancellation.test.ts
  libs/common/src/middleware/feature-flags/deal-cancellation.ts
  libs/common/src/middleware/feature-flags/index.ts
  libs/common/src/middleware/index.ts
  libs/common/src/types/index.ts
  libs/common/src/types/mongo-db-models/db-model.ts
  libs/common/src/types/mongo-db-models/deals.ts
  libs/common/src/types/mongo-db-models/index.ts
  libs/common/src/types/mongo-db-models/tfm-deals.ts
  libs/common/src/types/tfm-deal-cancellation.ts
  package-lock.json
  trade-finance-manager-api/api-tests/api-ssrf.api-test.js
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.api-test.ts
  trade-finance-manager-api/src/types/express.d.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-ui/server/api-ssrf.test.js
  trade-finance-manager-ui/server/api.js
Labels: Type: Feature

#3543 chore(DTFS2-7392): refactor mock facilities into functions
  e2e-tests/gef/cypress/e2e/clone/clone-gef-deal.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-bank-review-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-facility-end-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js
Labels: Type: chore

#3498 feat(DTFS2-7370): add RBAC middleware to tfm-api
  package-lock.json
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/api-test-users.js
  trade-finance-manager-api/api-tests/api-test-users.ts
  trade-finance-manager-api/api-tests/api.js
  trade-finance-manager-api/api-tests/api.ts
  trade-finance-manager-api/api-tests/common-tests/with-team-authorisation.api-tests.ts
  trade-finance-manager-api/api-tests/database-helper.ts
  trade-finance-manager-api/api-tests/helpers/submitDeal.js
  trade-finance-manager-api/api-tests/helpers/updateFacilityAmendment.js
  trade-finance-manager-api/api-tests/types/file.ts
  trade-finance-manager-api/api-tests/types/multipart-form.ts
  trade-finance-manager-api/api-tests/types/test-api.ts
  trade-finance-manager-api/api-tests/types/test-user.ts
  trade-finance-manager-api/api-tests/v1/amendments/update-tfm-deal-amendment-completion.api-test.js
  trade-finance-manager-api/api-tests/v1/bank-holidays/bank-holidays.api-test.js
  trade-finance-manager-api/api-tests/v1/banks/get-all-banks.api-test.ts
  trade-finance-manager-api/api-tests/v1/deal-builder.js
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.api-test.ts
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-lead-underwriter.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js
  trade-finance-manager-api/api-tests/v1/feedback/feedback-validation.api-test.js
  trade-finance-manager-api/api-tests/v1/feedback/feedback.api-test.js
  trade-finance-manager-api/api-tests/v1/middleware/api-rate-limiting.api-test.js
  trade-finance-manager-api/api-tests/v1/tasks/tasks-update-task.api-test.js
  trade-finance-manager-api/api-tests/v1/teams/get-team-members.api-test.js
  trade-finance-manager-api/api-tests/v1/users/users.api-test.js
  trade-finance-manager-api/api-tests/v1/utilisation-reports/update-utilisation-report-service.api-test.ts
  trade-finance-manager-api/api-tests/v1/utilisation-reports/utilisation-report-download.api-test.ts
  trade-finance-manager-api/api-tests/v1/utils/submitDeal.js
  trade-finance-manager-api/api-tests/v1/utils/updateFacilityAmendment.util.js
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/constants/teams.js
  trade-finance-manager-api/src/types/db-models/tfm-users.ts
  trade-finance-manager-api/src/types/team-id.ts
  trade-finance-manager-api/src/types/team.ts
  trade-finance-manager-api/src/types/tfm-session-user.ts
  trade-finance-manager-api/src/utils/error-list-order-number.test.js
  trade-finance-manager-api/src/v1/__mocks__/mock-users.js
  trade-finance-manager-api/src/v1/controllers/user/passport.js
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-api/src/v1/middleware/validate-user-is-in-at-least-one-allowed-team.test.ts
  trade-finance-manager-api/src/v1/middleware/validate-user-is-in-at-least-one-allowed-team.ts
  trade-finance-manager-api/src/v1/validation/validateIds.test.js
Labels: Type: Feature

#3546 fix(FN-3460): fix numerical rounding errors during report upload
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2024_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-November_2023_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-September_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-next_week.xlsx
  libs/common/src/constants/floating-point-rounding-decimal-places.ts
  libs/common/src/constants/index.ts
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#3554 fix(company-house): company house not found
  portal-api/api-tests/v1/gef/external-api.api-test.js
Labels: Type: Fix

#3553 feat(DTFS2-7294): use deal type from libs/common
  dtfs-central-api/src/constants/deals.js
  e2e-tests/e2e-fixtures/constants.fixture.js
  gef-ui/server/constants/index.js
  portal-api/src/constants/deal.js
  portal/server/constants/submission-type.js
  trade-finance-manager-api/src/constants/deals.js
  trade-finance-manager-ui/server/constants/deal.js
  utils/data-migration/constant/deal.js
Labels: Type: Feature

#3555 feat(DTFS2-7296): add bank request date template
  trade-finance-manager-ui/component-tests/case/cancellation/bank-request-date.component-test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
  trade-finance-manager-ui/server/routes/case/cancellation.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/bank-request-date-view-model.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/reason-for-cancelling-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/templates/case/cancellation/bank-request-date.njk
  trade-finance-manager-ui/test-helpers/test-data/bank-request-date-view-model.ts
Labels: Type: Feature

#3551 feat(dtfs2-6892): add feature flag around tfm UI router
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.js
  trade-finance-manager-ui/server/controllers/login/loginNonSso/index.test.js
  trade-finance-manager-ui/server/controllers/login/loginSso/index.ts
  trade-finance-manager-ui/server/controllers/user/userNonSso/index.js
  trade-finance-manager-ui/server/routes/index.js
  trade-finance-manager-ui/server/routes/index.test.js
  trade-finance-manager-ui/server/routes/login/configs/index.test.ts
  trade-finance-manager-ui/server/routes/login/configs/index.ts
  trade-finance-manager-ui/server/routes/login/configs/loginNonSso.ts
  trade-finance-manager-ui/server/routes/login/configs/loginSso.ts
  trade-finance-manager-ui/server/routes/login/index.js
  trade-finance-manager-ui/server/routes/login/index.test.js
  trade-finance-manager-ui/server/routes/login/index.ts
  trade-finance-manager-ui/server/routes/user/configs/index.test.ts
  trade-finance-manager-ui/server/routes/user/configs/index.ts
  trade-finance-manager-ui/server/routes/user/configs/userNonSso.ts
  trade-finance-manager-ui/server/routes/user/configs/userSso.ts
  trade-finance-manager-ui/server/routes/user/index.js
  trade-finance-manager-ui/server/routes/user/index.test.js
  trade-finance-manager-ui/server/routes/user/index.ts
  trade-finance-manager-ui/server/types/get-router.ts
Labels: Type: Feature

#3526 feat(FN-2311): add initial payment details filter UI components
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-payment-details.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  package-lock.json
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-filters-action-bar.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-filters-form.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-filters-panel.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/public/js/main.js
  trade-finance-manager-ui/public/js/main.js.map
  trade-finance-manager-ui/public/js/mojFilterHide.js
  trade-finance-manager-ui/public/js/mojFilterHide.js.LICENSE.txt
  trade-finance-manager-ui/public/js/mojFilterHide.js.map
  trade-finance-manager-ui/scripts/moj-filter-hide.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-filters-action-bar.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-filters-form.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-filters-panel.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/find-utilisation-reports-by-year.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/webpack.common.config.js
Labels: Type: Fintech

#3540 feat(DTFS2-7354): add get cancellation endpoint in central api
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-deal-cancellation-get.api-test.ts
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-deal-cancellation-put.api-test.js
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/v1/controllers/tfm/deal-cancellation/tfm-get-deal-cancellation.controller.ts
  dtfs-central-api/src/v1/routes/tfm-routes.js
  libs/common/src/errors/deal-cancellation-not-found.error.test.ts
  libs/common/src/errors/deal-cancellation-not-found.error.ts
  libs/common/src/errors/deal-not-found.error.test.ts
  libs/common/src/errors/index.ts
  libs/common/src/types/mongo-db-models/tfm-deals.ts
Labels: Type: Feature

#3542 feat(DTFS2-7353): add get cancellation endpoint to tfm api
  libs/common/src/middleware/feature-flags/deal-cancellation.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.get.api-test.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.put.api-test.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/get-cancellation-url.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/get-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/get-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/update-deal-cancellation.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/deal-cancellation/update-deal-cancellation.controller.ts
  trade-finance-manager-api/src/v1/deals/routes.js
Labels: Type: Feature

#3548 feat(DTFS2-7361): add middleware validation to deal cancellation endpoint in tfm api
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-delete-payment-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-payment-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-add-fees-to-an-existing-payment-group-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-facility-amendment-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-keying-data-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-payment-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-remove-fees-from-payment-group-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-post-report-data-validation-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-deal-cancellation-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-deal-cancellation-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-facility-amendment-payload.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-keying-data-mark-as-payload.ts
  libs/common/src/middleware/create-validation-middleware-for-schema.test.ts
  libs/common/src/middleware/create-validation-middleware-for-schema.ts
  libs/common/src/middleware/index.ts
  libs/common/src/schemas/deal-cancellation.ts
  libs/common/src/schemas/index.ts
  libs/common/src/types/tfm-deal-cancellation.ts
  package-lock.json
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.put.api-test.ts
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/__mocks__/mock-users.js
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-api/src/v1/middleware/validate-put-deal-cancellation-payload.test.ts
  trade-finance-manager-api/src/v1/middleware/validate-put-deal-cancellation-payload.ts
Labels: Type: Feature

#3565 fix(FN-3481): cherry-pick numerical rounding error fix from #3546 (targeting main)
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2024_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-November_2023_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-September_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-next_week.xlsx
  libs/common/src/constants/floating-point-rounding-decimal-places.ts
  libs/common/src/constants/index.ts
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#3564 fix(FN-3481): cherry-pick numerical rounding error fix from #3546 (targeting release-2.3)
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2024_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-November_2023_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-September_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-next_week.xlsx
  libs/common/src/constants/floating-point-rounding-decimal-places.ts
  libs/common/src/constants/index.ts
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fintech

#3563 feat(DTFS2-7300): add effective from date template
  trade-finance-manager-ui/component-tests/case/cancellation/effective-from-date.component-test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts
  trade-finance-manager-ui/server/routes/case/cancellation.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/effective-from-date-view-model.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/templates/case/cancellation/effective-from-date.njk
  trade-finance-manager-ui/test-helpers/test-data/effective-from-date-view-model.ts
Labels: Type: Feature

#3561 feat(DTFS2-7296): add validation to bank request date
  trade-finance-manager-ui/component-tests/case/cancellation/bank-request-date.component-test.ts
  trade-finance-manager-ui/component-tests/case/cancellation/reason-for-cancelling.component-test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-bank-request-date.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-bank-request-date.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-reason-for-cancelling.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-reason-for-cancelling.ts
  trade-finance-manager-ui/server/routes/case/cancellation.ts
  trade-finance-manager-ui/server/types/view-models/deal-cancellation/bank-request-date-view-model.ts
  trade-finance-manager-ui/templates/case/cancellation/bank-request-date.njk
Labels: Type: Feature

#3568 feat(DTFS2-7367): add e2e tests for deal cancellation
  .github/workflows/test.yml
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-cancellation-disabled/deal-cancellation-button.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-cancellation-enabled/deal-cancellation-button.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
  e2e-tests/tfm/cypress/e2e/pages/caseDealPage.js
  e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/reason-for-cancelling.js
  e2e-tests/ukef/cypress/support/commands.js
  e2e-tests/ukef/cypress/support/commands/click-events/click-submit-button.js
  e2e-tests/ukef/cypress/support/commands/click-events/index.js
  trade-finance-manager-ui/component-tests/case/deal/deal.component-test.js
  trade-finance-manager-ui/templates/case/deal/deal.njk
Labels: Type: Feature

#3567 chore(DTFS2-7393): refactor facility end date feature flag e2e-tests/gef
  .github/workflows/test.yml
  e2e-tests/gef/cypress/e2e/clone/clone-gef-deal.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/bank-review-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities-change-facility-end-date-to-bank-review-date-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facilities-change-from-details-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-disabled/about-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-disabled/facilities-change-from-details-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/about-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/bank-review-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/facilities-change-facility-end-date-to-bank-review-date-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/facilities-change-from-details-journey.spec.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/facility-end-date.spec.js
  e2e-tests/gef/cypress/e2e/maker/facility-end-date-disabled/return-to-maker-mia.spec.js
  e2e-tests/gef/cypress/e2e/maker/facility-end-date-enabled/return-to-maker-mia.spec.js
Labels: Type: chore

#3513 feat(FN-3225): added validation for matching facility id currency and utilisation
  dtfs-central-api/src/services/utilisation-report-data-validator/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-base-currency-errors/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-base-currency-errors/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-errors-for-mismatched-facility-values/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-errors-for-mismatched-facility-values/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-facility-utilisation-errors/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/helpers/generate-facility-utilisation-errors/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/cells/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/cells/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/headers/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/headers/index.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/validate-csv-data/rows/index.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
  e2e-tests/portal/cypress/fixtures/invalid-matching-utilisation-report-February_2023_monthly.csv
  e2e-tests/portal/cypress/fixtures/invalid-matching-utilisation-report-February_2024_quarterly.csv
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2024_quarterly.xlsx
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/utilisation-report-mock-csv-data.ts
  libs/common/src/types/utilisation-reports.ts
  package.json
Labels: Type: Fintech

#3577 chore(DTFS2-7421): refactor review ukef approval tests
  .github/workflows/test.yml
  e2e-tests/e2e-fixtures/mock-gef-facilities.js
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/facility-end-date.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-disabled/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-disabled/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-enabled/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/facility-end-date-enabled/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
Labels: Type: chore

#3584 fix(FN-3460): fix invalid facility utilisation values in e2e report fixtures
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2024_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-November_2023_quarterly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-September_2023_monthly.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-next_week.xlsx
Labels: Type: Fintech

#3591 feat(DTFS2-7296): add to deal cancellation e2e tests
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
  e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/bank-request-date.js
  e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/effective-from-date.js
Labels: Type: Feature

#3583 chore(DTFS2-7394): refactor facility end date feature flag in e2e-tests/tfm
  .github/workflows/test.yml
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-disabled/gef-deal-expect-no-facility-end-date-features.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-add-bank-review-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-add-facility-end-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-add-multiple-amendments-impacting-facility-end-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/facility-end-date/feature-flag-enabled/gef-deal-amend-facility-end-date-and-then-change-to-bank-review-date.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/show-amendment-button/show-amendment-button.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/case/deal-page-GEF.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
Labels: Type: chore

#3580 chore(DTFS2-7423): refactor unissued-facilities/MIN tests
  .github/workflows/test.yml
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/about-unissued-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-disabled/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/facility-end-date-enabled/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
Labels: Type: chore

#3571 feat(DTFS2-7350): update db on reason for cancelling page
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-deal-cancellation-get.api-test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/v1/controllers/tfm/deal-cancellation/tfm-get-deal-cancellation.controller.ts
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
  libs/common/src/errors/deal-cancellation-not-found.error.test.ts
  libs/common/src/errors/deal-cancellation-not-found.error.ts
  libs/common/src/errors/index.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.get.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.test.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.ts
  trade-finance-manager-ui/server/controllers/helpers/index.js
  trade-finance-manager-ui/server/routes/case/cancellation.ts
  trade-finance-manager-ui/server/types/data-transfer-objects/get-deal-response.ts
Labels: Type: Feature
