Repository UK-Export-Finance/dtfs2, pull requests merged in 2024-11, with the labels that each got.

#3788 feat(DTFS2-7429): handle deal cancellations with future date
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.scheduleDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-effective-from-in-future.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-effective-from-in-past.spec.js
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
Labels: Type: Feature

#3846 chore(deps): bump dependencies
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: dependencies

#3793 feat(DTFS2-7469): simplify facility type mappings
  libs/common/src/types/mongo-db-models/facility.ts
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityProduct.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilitySnapshot.test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityType.api-test.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityType.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityType.test.ts
  trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapFacilityType.ts
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.js
  trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilitySnapshot.test.js
Labels: Type: Feature

#3847 fix(DTFS2-7590): facility loan amount amendment
  .github/workflows/deployment.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/dns.yml
  .github/workflows/dns_tfm.yml
  .github/workflows/feature_deploy.yml
  .github/workflows/infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js
Labels: Type: Fix

#3789 feat(DTFS2-7582): add e2e test for adding cancellation activity
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-effective-from-in-past.spec.js
Labels: Type: Feature

#3792 fix(DTFS2-7577): fix console logging in gef api error handler
  gef-ui/server/utils/helpers.js
Labels: Type: Fix

#3852 fix(DTFS2-7590): acbs facility loan mapping
  azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js
Labels: Type: Fix

#3845 chore(DTFS2-7605): update dependabot to run during non working hours
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Type: chore

#3780 feat(FN-3456): use first visible worksheet of bank upload
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-hidden-first-sheet-February_2023_monthly.xlsx
  portal/server/utils/csv-utils.js
Labels: Type: Fintech

#3787 feat(FN-3538): validate payment group completeness
  dtfs-central-api/api-tests/v1/utilisation-reports/post-payment.api-test.ts
  dtfs-central-api/src/repositories/fee-record-repo/fee-record.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/fee-record-validator.test.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/fee-record-validator.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/selected-fee-record-validator.test.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/selected-fee-record-validator.ts
Labels: Type: Fintech

#3895 feat(DTFS2-7580): update gef interest margin percentage hint
  e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-value.spec.js
  e2e-tests/gef/cypress/e2e/pages/facility-value.js
  gef-ui/templates/partials/facility-value.njk
Labels: Type: Feature

#3899 fix(DTFS2-7604): residual comments for PR #3897
  trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.test.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
Labels: Type: Fix

#3901 chore(DTFS2-7592): merge release-2.4.0 to main
  .github/workflows/deployment.yml
  .github/workflows/development_infrastructure.yml
  .github/workflows/dns.yml
  .github/workflows/dns_tfm.yml
  .github/workflows/feature_deploy.yml
  .github/workflows/infrastructure.yml
  .github/workflows/production_infrastructure.yml
  .github/workflows/staging_infrastructure.yml
  azure-functions/acbs-function/package.json
  azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
  dtfs-central-api/src/helpers/get-latest-tfm-facility-values.test.ts
  dtfs-central-api/src/helpers/get-latest-tfm-facility-values.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/get-fixed-fee-for-facility.ts
  e2e-tests/package.json
  external-api/package.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal/package.json
  trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/helpers/amendment.helpers.test.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
Labels: chore

#3782 feat(DTFS2-7578): clone gef deals to v1
  .github/workflows/test.yml
  azure-functions/acbs-function/.eslintrc.js
  dtfs-central-api/.eslintrc.js
  e2e-tests/gef/cypress/e2e/clone/clone-gef-deal.spec.js
  e2e-tests/gef/cypress/e2e/clone/facility-end-date-enabled/clone-v0-to-v1.spec.js
  e2e-tests/gef/cypress/e2e/clone/facility-end-date-enabled/clone-v1-to-v1.spec.js
  e2e-tests/gef/cypress/support/commands.js
  e2e-tests/gef/cypress/support/commands/portal/getDealIdFromUrl.js
  external-api/.eslintrc.js
  gef-ui/.eslintrc.js
  libs/common/.eslintrc.js
  libs/common/src/helpers/gef-deal-versioning.ts
  libs/common/src/types/mongo-db-models/deals.ts
  libs/common/src/types/mongo-db-models/facility.ts
  portal-api/.eslintrc.js
  portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
  portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
  portal-api/src/v1/gef/services/clone/clone-deal.service.test.ts
  portal-api/src/v1/gef/services/clone/clone-deal.service.ts
  portal-api/src/v1/gef/services/clone/clone-facilities.service.test.ts
  portal-api/src/v1/gef/services/clone/clone-facilities.service.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-deal.test.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-deal.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-exporter.test.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-exporter.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-facility.test.ts
  portal-api/src/v1/gef/services/clone/helpers/generate-cloned-facility.ts
  portal-api/src/v1/users/transform-database-user.js
  portal/.eslintrc.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-ui/.eslintrc.js
  utils/.eslintrc.js
  utils/mock-data-loader/gef/facilities.js
Labels: Type: Feature

#3896 feat(FN-3608): use utilisation report event type constant
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/add-a-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-fees-to-an-existing-payment-group/add-fees-to-an-existing-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/due-report-initialised/due-report-initialised.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/edit-payment/edit-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-ready-to-key/mark-fee-records-as-ready-to-key.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-reconciled/mark-fee-records-as-reconciled.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/patch-payment.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/patch-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-done.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-to-do.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.ts
Labels: Type: Fintech

#3844 feat(DTFS2-7595): add deal cancellation success banner across all pages
  azure-functions/acbs-function/.eslintrc.js
  dtfs-central-api/.eslintrc.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-effective-from-in-future.spec.js
  external-api/.eslintrc.js
  gef-ui/.eslintrc.js
  libs/common/.eslintrc.js
  libs/common/src/constants/flash.ts
  libs/common/src/constants/index.ts
  libs/common/src/helpers/get-ukef-deal-id.test.ts
  libs/common/src/helpers/get-ukef-deal-id.ts
  libs/common/src/helpers/index.ts
  libs/common/src/types/flash.ts
  libs/common/src/types/index.ts
  libs/common/src/types/mongo-db-models/deals.ts
  portal-api/.eslintrc.js
  portal/.eslintrc.js
  trade-finance-manager-api/.eslintrc.js
  trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.get.api-test.ts
  trade-finance-manager-api/src/v1/deals/routes.js
  trade-finance-manager-ui/.eslintrc.js
  trade-finance-manager-ui/server/controllers/case/activity/index.js
  trade-finance-manager-ui/server/controllers/case/activity/index.test.js
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
  trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.js
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.test.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getDealSuccessBannerMessage.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getDealSuccessBannerMessage.test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getScheduledCancellationBannerMessage.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getScheduledCancellationBannerMessage.test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.ts
  trade-finance-manager-ui/server/controllers/helpers/index.js
  trade-finance-manager-ui/server/helpers/getFlashSuccessMessage.test.ts
  trade-finance-manager-ui/server/helpers/getFlashSuccessMessage.ts
  trade-finance-manager-ui/server/test-mocks/amendment-test-mocks.js
  utils/.eslintrc.js
Labels: Type: Feature

#3913 feat(DTFS2-7612): refactor get facility controller to have consistent return type
  dtfs-central-api/api-tests/v1/facilities/facility-put.api-test.js
  dtfs-central-api/src/v1/controllers/portal/facility/delete-facility.controller.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-facility.controller.js
  dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
  dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js
Labels: Type: Feature

#3918 fix(DTFS2-6616): re-introduce facility amendment covenant and guarantee
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
Labels: Type: Fix

#3911 feat(DTFS2-7596): update portal status when cancelling
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-submit-deal-cancellation-post.api-test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.scheduleDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.submitDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/services/portal/deal.service.ts
  dtfs-central-api/src/services/portal/deal.service.update-status.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.processScheduledCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  dtfs-central-api/src/v1/controllers/portal/deal/update-deal-status.controller.js
  dtfs-central-api/src/v1/controllers/portal/gef-deal/put-gef-deal.status.controller.js
  dtfs-central-api/src/v1/controllers/tfm/deal-cancellation/tfm-post-submit-deal-cancellation.controller.ts
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  libs/common/src/constants/portal/deal-status.ts
  libs/common/src/types/tfm-deal-cancellation.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts
Labels: Type: Feature

#3908 feat(FN-3573): add create record correction request page
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/_macros/fee-record-summary.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/create-record-correction-request.component-test.ts
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/public/js/mojFilterHide.js
  trade-finance-manager-ui/public/js/mojFilterHide.js.map
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/middleware/index.ts
  trade-finance-manager-ui/server/middleware/validateTfmFeeRecordCorrectionFeatureFlagIsEnabled/index.test.ts
  trade-finance-manager-ui/server/middleware/validateTfmFeeRecordCorrectionFeatureFlagIsEnabled/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/create-record-correction-request-view-model.ts
  trade-finance-manager-ui/styles/block-header.scss
  trade-finance-manager-ui/styles/case-summary.scss
  trade-finance-manager-ui/styles/fee-record-summary.scss
  trade-finance-manager-ui/styles/styles.scss
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/_macros/fee-record-summary.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/create-record-correction-request.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/index.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/create-record-correction-request-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/index.ts
Labels: Type: Fintech

#3921 feat(DTFS2-7574): add ICICI bank
  .env.sample
  cspell.json
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  gef-ui/templates/includes/before-you-start.njk
  portal/templates/_partials/before-you-start.njk
  utils/mock-data-loader/banks/index.js
Labels: Type: Feature

#3912 fix(FN-3616): fix end of row payment currency bug
  .github/workflows/test.yml
  dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-report-raw-csv-data.ts
  dtfs-central-api/src/helpers/fee-record-csv-row-mapper.test.ts
  dtfs-central-api/src/helpers/fee-record-csv-row-mapper.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.ts
  e2e-tests/e2e-fixtures/tfm-users.fixture.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/sort-premium-payments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/view-utilisation.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/ukef/cypress/e2e/journeys/utilisation-reports/utilisation-report-submission.spec.js
  e2e-tests/ukef/cypress/e2e/partials/index.js
  e2e-tests/ukef/cypress/fixtures/february-2023-expected-values.js
  e2e-tests/ukef/cypress/fixtures/tfm-facility.js
  e2e-tests/ukef/cypress/fixtures/valid-utilisation-report-February_2023_monthly.csv
  e2e-tests/ukef/cypress/fixtures/valid-utilisation-report-February_2023_monthly.xlsx
  e2e-tests/ukef/cypress/support/click-events/click-continue-button.js
  e2e-tests/ukef/cypress/support/click-events/index.js
  e2e-tests/ukef/cypress/support/portal/logIn.js
  libs/common/src/types/utilisation-reports.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/utilisation-table.component-test.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/utilisation-table.njk
Labels: Type: Bug

#3924 feat(DTFS2-7609): mandatory criterion updates
  e2e-tests/e2e-fixtures/bss/mandatoryCriteria.fixture.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bss-mandatory-criteria/bss-mandatory-criteria.spec.js
  external-api/package.json
  gef-ui/package.json
  package-lock.json
  package.json
  portal-api/api-tests/fixtures/gef/application.js
  portal-api/api-tests/fixtures/gef/mandatoryCriteriaVersioned.js
  portal-api/api-tests/fixtures/mandatoryCriteria.js
  portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
  portal/component-tests/fixtures/deal-fully-completed.js
  portal/package.json
  trade-finance-manager-ui/package.json
  utils/mock-data-loader/bss/mandatoryCriteria.js
  utils/mock-data-loader/gef/mandatoryCriteriaVersioned.js
Labels: chore

#3678 chore(main): release 2.5.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3926 feat(DTFS2-7598): display risk expired facility status in GEF ui
  gef-ui/server/utils/deal-helpers.test.js
  gef-ui/server/utils/display-items.js
  gef-ui/server/utils/display-items.test.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
Labels: Type: Feature

#3923 feat(DTFS2-7612): update portal facility status to risk expired
  dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-submit-deal-cancellation-post.api-test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.scheduleDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.submitDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/services/portal/facility.service.ts
  dtfs-central-api/src/services/portal/facility.service.update-status.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.getTfmDealCancellationResponse.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.processScheduledCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
  dtfs-central-api/src/v1/controllers/portal/gef-facility/update-facility.controller.js
  dtfs-central-api/test-helpers/test-data/tfm-facility.ts
  libs/common/src/types/portal/facility-status.ts
  libs/common/src/types/portal/index.ts
  libs/common/src/types/tfm-deal-cancellation.ts
  trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
  trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts
Labels: Type: Feature

#3928 feat(DTFS2-7601): add e2e coverage for cancelled bss ewcs in portal
  .github/workflows/test.yml
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/support/commands.js
  e2e-tests/ukef/cypress/support/portal-api/insertOneDeal.js
  e2e-tests/ukef/cypress/support/trade-finance-manager-ui/submit-deal-cancellation.js
Labels: Type: Feature

#3931 feat(DTFS2-7625): add update facilities by deal
  dtfs-central-api/src/repositories/portal/facilities.repo.ts
  dtfs-central-api/src/repositories/portal/facilities.repo.updateByDealId.test.ts
  dtfs-central-api/src/services/portal/facility.service.ts
  dtfs-central-api/src/services/portal/facility.service.update-status.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.processScheduledCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-cancellation-updates-portal.spec.js
  gef-ui/server/utils/display-items.js
  gef-ui/server/utils/display-items.test.js
  libs/common/src/constants/portal/facility-stage.ts
  libs/common/src/constants/portal/facility-status.ts
  libs/common/src/constants/portal/index.ts
  libs/common/src/types/mongo-db-models/facility.ts
Labels: Type: Bug, Type: Feature, Type: chore

#3934 feat(DTFS2-7637): replace scheduled status with pending
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.findPendingDealCancellations.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.scheduleDealCancellation.test.ts
  dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.processPendingCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  libs/common/src/constants/tfm/deal-cancellation-status.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.test.ts
  trade-finance-manager-ui/server/controllers/helpers/deal-cancellation-enabled.helper.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getDealSuccessBannerMessage.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getScheduledCancellationBannerMessage.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.ts
Labels: Type: Feature

#3935 feat(DTFS2-7638): update portal status to pending
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-future-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-past-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-future-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-past-cancellation-updates-portal.spec.js
Labels: Type: Feature

#3939 fix(DTFS2-6616): variable consistency
  azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
  azure-functions/acbs-function/src/functions/activity-get-facility-master.js
Labels: Type: Fix

#3849 chore(DTFS2-7608): add rerun to the pipeline
  .github/modules/rerun/action.yml
  .github/workflows/test.yml
  e2e-tests/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: chore

#3941 feat(FN-3640): require bank report facilities be GEF facilities
  dtfs-central-api/api-tests/v1/utilisation-reports/post-validate-utilisation-report-data.api-test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.test.ts
  dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
  e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
  e2e-tests/ukef/cypress/fixtures/tfm-facility.js
Labels: Type: Fintech

#3916 feat(FN-3573): get fee record details for correction request
  dtfs-central-api/api-tests/v1/utilisation-reports/get-fee-record.api-test.ts
  dtfs-central-api/src/repositories/fee-record-repo/fee-record.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-record.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-record.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-record.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-record.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-response-body.js
  dtfs-central-api/test-helpers/test-data/index.ts
  dtfs-central-api/test-helpers/test-data/session-bank.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api-response-types/fee-record-response-body.ts
  trade-finance-manager-api/src/v1/api-response-types/index.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-fee-record.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-fee-record.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/public/js/mojFilterHide.js
  trade-finance-manager-ui/public/js/mojFilterHide.js.map
  trade-finance-manager-ui/server/api-response-types/get-fee-record-response-body.ts
  trade-finance-manager-ui/server/api-response-types/index.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fintech

#3925 feat(FN-3566): create record correction request button
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/premium-payments-error-states/create-fee-record-correction-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/premium-payments-error-states/add-payment-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/premium-payments-error-states/generate-keying-data-errors.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table/helpers.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table/premium-payments-table-data.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/constants/premium-payment-tab-error-keys.ts
  trade-finance-manager-ui/server/constants/premium-payments-table-error-href.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/check-keying-data/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/check-keying-data/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-add-payment-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-add-payment-error-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/add-payment-error.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/add-payment-error.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/generate-keying-data-error.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/generate-keying-data-error.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/initiate-record-correction-request-error.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/premium-payments-errors/initiate-record-correction-request-error.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/initiate-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/initiate-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/handle-redirect-session-data.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/handle-redirect-session-data.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/helpers/get-premium-payments-facility-id-query-from-referer.test.ts
  trade-finance-manager-ui/server/helpers/get-premium-payments-facility-id-query-from-referer.ts
  trade-finance-manager-ui/server/helpers/map-checked-checkboxes-to-record.test.ts
  trade-finance-manager-ui/server/helpers/map-checked-checkboxes-to-record.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/express-session.d.ts
  trade-finance-manager-ui/server/types/premium-payments-tab-error-keys.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Feature

#3949 fix(DTFS2-7614): facility amendment ukef decision object validation
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/v1/__mocks__/mock-amendment-tasks-assign-by-team.js
  trade-finance-manager-api/src/v1/__mocks__/mock-amendment.ts
  trade-finance-manager-api/src/v1/controllers/amendment.controller-updateFacilityAmendment.test.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentTask.controller.test.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentTasks.controller.js
  utils/package.json
Labels: Type: Fix

#3958 feat(DTFS2-7525): add portal amendments feature flag
  .env.sample
  .github/workflows/test.yml
  docker-compose.yml
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/is-feature-flag-enabled.test.ts
  libs/common/src/helpers/is-feature-flag-enabled.ts
Labels: Type: Feature

#3953 fix(FN-3631): enable deletion of payments against fees below tolerance
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/delete-payment.spec.js
Labels: Type: Bug

#3948 feat(FN-3575): validate create record correction request inputs
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-record.controller/helpers.ts
  libs/common/src/constants/index.ts
  libs/common/src/constants/record-correction-reason.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-reason.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/create-record-correction-request.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/form-helpers.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/form-helpers.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/validate-form-values.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/validate-form-values.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/create-record-correction-request-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/create-record-correction-request.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/create-record-correction-request-view-model.ts
Labels: Type: Fintech

#3950 feat(FN-3575): add initial record correction creation E2E tests
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-request-error-states/create-fee-record-correction-request-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/fee-record-correction/createFeeRecordCorrectionRequestPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/index.js
  e2e-tests/tfm/cypress/e2e/partials/feeRecordSummary.js
  e2e-tests/tfm/cypress/e2e/partials/index.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/_macros/fee-record-summary.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/create-record-correction-request.component-test.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/_macros/fee-record-summary.njk
Labels: Type: Fintech

#3952 fix(DTFS2-7647): fix gef deal cancellation success message
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bss-ewcs/submit-deal-cancellation-effective-from-in-future.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bss-ewcs/submit-deal-cancellation-effective-from-in-past.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/gef/submit-deal-cancellation-effective-from-in-future.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/gef/submit-deal-cancellation-effective-from-in-past.spec.js
  e2e-tests/tfm/cypress/support/commands.js
  libs/common/src/types/tfm/deal-stage.ts
  libs/common/src/types/tfm/index.ts
  libs/common/src/types/tfm/mapped-deal.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getDealSuccessBannerMessage.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getDealSuccessBannerMessage.test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getScheduledCancellationBannerMessage.ff-test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.getScheduledCancellationBannerMessage.test.ts
  trade-finance-manager-ui/server/controllers/helpers/get-success-banner-message.helper.ts
Labels: Type: Fix
