Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-09, with the labels that each got.

#4406 feat(DTFS2-7939): service unavailable page for a schedule maintenance
  .env.sample
  .github/workflows/lint.yml
  .github/workflows/test.yml
  docker-compose.yml
  dtfs-central-api/src/generateApp.ts
  external-api/src/generateApp.ts
  gef-ui/server/generateApp.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/maintenance.ts
  libs/common/src/helpers/is-maintenance-active.test.ts
  libs/common/src/helpers/is-maintenance-active.ts
  libs/common/src/helpers/string-to-boolean.test.ts
  libs/common/src/helpers/string-to-boolean.ts
  libs/common/src/middleware/index.ts
  libs/common/src/middleware/maintainance/index.test.ts
  libs/common/src/middleware/maintainance/index.ts
  package-lock.json
  portal-api/src/generateApp.js
  portal-ui/server/generateApp.ts
  reverse-proxy/Dockerfile
  trade-finance-manager-api/src/generateApp.js
  trade-finance-manager-ui/server/generateApp.js
Labels: Type: Feature

#4402 chore(DTFS2-7071): add is production validation on delete endpoints
  dtfs-central-api/src/v1/routes/portal-routes.js
  dtfs-central-api/src/v1/routes/tfm-routes.js
  dtfs-central-api/src/v1/validation/route-validators/route-validators.js
  portal-api/api-tests/v1/deals/deals.api-test.js
  portal-api/src/v1/controllers/deal.controller.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/validation/route-validators/route-validators.js
Labels: Type: chore

#4392 feat(DTFS2-8024): added future effective date banner to tfm amendment…
  e2e-tests/tfm/cypress/e2e/pages/amendments/amendmentsPage.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/tfm-portal-amendments-future-effective-date-banners.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/tfm-portal-amendments-no-future-effective-date-banners.spec.js
  trade-finance-manager-ui/component-tests/case/_macros/amendment-future-effective-date-facility-bar.component-test.js
  trade-finance-manager-ui/templates/case/amendments/_macros/amendment-future-effective-date-facility-bar.njk
  trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk
  trade-finance-manager-ui/templates/case/facility/facility.njk
Labels: Type: Feature

#4411 feat(DTFS2-7939): service unavailable pages render
  dtfs-central-api/src/v1/routes/middleware/headers/security.js
  external-api/src/middleware/headers/security/index.api-test.ts
  external-api/src/middleware/headers/security/index.ts
  gef-ui/server/middleware/headers/security.middleware.js
  libs/common/src/middleware/maintainance/index.test.ts
  libs/common/src/middleware/maintainance/index.ts
  portal-api/src/v1/middleware/headers/security.js
  portal-ui/server/routes/middleware/headers/security.middleware.js
  trade-finance-manager-api/src/v1/middleware/headers/security.js
  trade-finance-manager-ui/server/middleware/headers/security.js
Labels: Type: Feature

#4426 fix(DTFS2-8119): portal amendements - add submittedBy and effectiveDate to tfm amendment details
  dtfs-central-api/server/services/portal/facility-amendment.service.ts
  dtfs-central-api/server/services/portal/facility-amendment.submitPortalFacilityAmendmentToUkef.service.test.ts
  e2e-tests/tfm/cypress/e2e/pages/amendments/amendmentsPage.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/tfm/tfm-display-portal-amendment-on-amendment-details-page.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/tfm/tfm-display-portal-and-tfm-amendments-on-amendment-details-page.spec.js
  libs/common/src/types/mongo-db-models/tfm-facilities.ts
  trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk
Labels: Type: Fix

#4409 fix(DTFS2-6707): add allBankError validation on user creation
  e2e-tests/e2e-fixtures/banks.fixture.js
  e2e-tests/e2e-fixtures/index.js
  e2e-tests/e2e-fixtures/portal-users.fixture.js
  e2e-tests/portal/cypress/e2e/journeys/admin/activate-deactivate-user/activate-deactivate-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
  e2e-tests/portal/cypress/e2e/journeys/feedback/feedback.spec.js
  e2e-tests/portal/cypress/e2e/journeys/login/change-password.spec.js
  libs/common/src/constants/banks.ts
  libs/common/src/constants/index.ts
  portal-api/api-tests/v1/feedback/feedback-validation.api-test.js
  portal-api/api-tests/v1/users/with-validate-email-is-correct-format.api-tests.js
  portal-api/server/v1/users/validation/index.js
  portal-api/server/v1/users/validation/index.test.js
  portal-api/server/v1/users/validation/rules/email-must-be-valid-email-address.js
  portal-api/server/v1/users/validation/rules/email-must-be-valid-email-address.test.js
  portal-api/server/v1/users/validation/rules/read-only-from-ukef-only.js
  portal-api/server/v1/users/validation/rules/read-only-from-ukef-only.test.js
  portal-api/server/v1/users/validation/rules/select-at-least-one-bank.js
  portal-api/server/v1/users/validation/rules/select-at-least-one-bank.test.js
  portal-api/server/v1/validation/feedback-rules/email-address.js
  portal-ui/server/routes/admin/users.js
Labels: Type: Fix

#4430 feat(DTFS2-8115): add swagger helper to api microservices
  README.md
  dtfs-central-api/package.json
  dtfs-central-api/server/constants/routes.ts
  dtfs-central-api/server/generateApp.ts
  dtfs-central-api/server/v1/routes/index.js
  dtfs-central-api/server/v1/routes/swagger-routes.js
  dtfs-central-api/server/v1/routes/swagger-routes.ts
  external-api/package.json
  external-api/server/generateApp.ts
  external-api/server/helpers/index.ts
  external-api/server/helpers/swagger.ts
  external-api/server/v1/routes/index.ts
  external-api/server/v1/routes/swagger.route.ts
  libs/common/package.json
  libs/common/src/constants/index.ts
  libs/common/src/constants/services.ts
  libs/common/src/constants/swagger.ts
  libs/common/src/interfaces/index.ts
  libs/common/src/interfaces/swagger.ts
  libs/common/src/swagger/create-swagger-router.test.ts
  libs/common/src/swagger/create-swagger-router.ts
  libs/common/src/swagger/index.ts
  libs/common/tsconfig.json
  package-lock.json
  portal-api/package.json
  portal-api/server/generateApp.js
  portal-api/server/v1/routes/swagger.route.ts
  trade-finance-manager-api/README.md
  trade-finance-manager-api/package.json
  trade-finance-manager-api/server/generateApp.js
  trade-finance-manager-api/server/v1/routes.js
  trade-finance-manager-api/server/v1/routes/swagger.route.ts
  trade-finance-manager-api/server/v1/swagger.js
  trade-finance-manager-ui/package.json
Labels: Type: Feature

#4434 chore(merge): merge release-2.10.0 to main
  cspell.json
  dtfs-central-api/package.json
  dtfs-central-api/server/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-total-fees-accrued-currency-error.test.ts
  dtfs-central-api/server/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-total-fees-accrued-currency-error.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/upload-with-invalid-currencies.spec.js
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/upload-with-valid-accrual-currencies.spec.js
  e2e-tests/portal/cypress/fixtures/invalid-utilisation-report-February_2023_monthly-invalid-currencies.xlsx
  e2e-tests/portal/cypress/fixtures/valid-utilisation-report-February_2023_monthly_accrual_currency.xlsx
Labels: Type: chore

#4437 fix(DTFS2-8126): portal-ui build script failure
  .github/workflows/test.yml
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/component-tests/index/index.component-test.js
  gef-ui/package.json
  gef-ui/public/css/styles.css
  gef-ui/public/js/govukFrontend.js
  gef-ui/public/js/govukFrontend.js.map
  gef-ui/templates/index.njk
  libs/common/package.json
  libs/common/src/helpers/calculate-ukef-exposure.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/round-value.ts
  libs/common/src/helpers/ui/decimals-count.test.ts
  libs/common/src/helpers/ui/decimals-count.ts
  libs/common/src/helpers/ui/index.ts
  package-lock.json
  portal-api/package.json
  portal-ui/component-tests/contract/about/financial-details.component-test.js
  portal-ui/component-tests/index/index.component-test.js
  portal-ui/package.json
  portal-ui/public/css/styles.css
  portal-ui/public/js/govukFrontend.js
  portal-ui/public/js/govukFrontend.js.map
  portal-ui/public/js/main.js
  portal-ui/public/js/main.js.map
  portal-ui/public/js/ukefexposure.js
  portal-ui/public/js/ukefexposure.js.map
  portal-ui/scripts/main.js
  portal-ui/scripts/ukef-exposure.js
  portal-ui/server/helpers/sanitizeCurrency.js
  portal-ui/templates/_macros/facility-inputs/ukef-exposure.njk
  portal-ui/templates/index.njk
  portal-ui/webpack.common.config.js
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/component-tests/index/index.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/find-utilisation-reports-by-year.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/public/js/disableFormSubmitOnSubmission.js
  trade-finance-manager-ui/public/js/disableFormSubmitOnSubmission.js.map
  trade-finance-manager-ui/public/js/enableFindReportsByYearDropdown.js
  trade-finance-manager-ui/public/js/enableFindReportsByYearDropdown.js.map
  trade-finance-manager-ui/public/js/enableSelectAllTableCheckbox.js
  trade-finance-manager-ui/public/js/enableSelectAllTableCheckbox.js.map
  trade-finance-manager-ui/public/js/govukFrontend.js
  trade-finance-manager-ui/public/js/govukFrontend.js.LICENSE.txt
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/public/js/main.js
  trade-finance-manager-ui/public/js/main.js.map
  trade-finance-manager-ui/public/js/mojFilterHide.js
  trade-finance-manager-ui/public/js/mojFilterHide.js.map
  trade-finance-manager-ui/public/js/mojFrontend.js
  trade-finance-manager-ui/public/js/mojFrontend.js.map
  trade-finance-manager-ui/templates/index.njk
  trade-finance-manager-ui/templates/utilisation-reports/find-utilisation-reports-by-year.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Fix

#4440 feat(DTFS2-8122): centralised application configuration
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  gef-ui/server/generateApp.js
  libs/common/package.json
  libs/common/src/constants/cookie.ts
  libs/common/src/constants/index.ts
  libs/common/src/helpers/configure-express-application.test.ts
  libs/common/src/helpers/configure-express-application.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/is-https.test.ts
  libs/common/src/helpers/is-https.ts
  package-lock.json
  portal-api/package.json
  portal-ui/package.json
  portal-ui/server/generateApp.ts
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/generateApp.js
  trade-finance-manager-ui/server/session-configuration/index.js
  utils/package.json
Labels: Type: Feature

#4447 feat(DTFS2-8134): add Banco Santander to banks list
  e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/content.spec.js
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  portal-ui/templates/_partials/before-you-start.njk
Labels: Type: Feature

#4448 chore(merge): merge release-2.10.0 to main
  e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/content.spec.js
  e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
  portal-ui/templates/_partials/before-you-start.njk
Labels: Type: chore

#4454 fix(DTFS2-8145): added fix for failing tenor e2e test
  e2e-tests/tfm/cypress/support/utils/facility-tenor.js
Labels: Type: Fix
