Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-01, with the labels that each got.

#4027 feat(DTFS2-6892): add object id schema for tfm sso
  libs/common/src/schemas/audit-database-record.ts
  libs/common/src/schemas/index.ts
  libs/common/src/schemas/object-id.test.ts
  libs/common/src/schemas/object-id.ts
Labels: Type: Feature, Stale

#4075 feat(DTFS2-6892): add initial tfm sso diagram
  doc/assets/tfm-entra-id-auth_page-request.drawio
  doc/assets/tfm-entra-id-auth_page-request.drawio.png
  doc/docstring.md
  doc/tfm-sso.md
Labels: Type: Docs, Type: Feature

#4105 fix(FN-3731): fix assertion dependent on current year
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts
Labels: Type: Fintech

#4089 feat(FN-3668): add bank correction entry screen and endpoint
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction.api-test.ts
  dtfs-central-api/src/repositories/fee-record-correction-repo/fee-record-correction.repo.ts
  dtfs-central-api/src/repositories/fee-record-correction-repo/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-response-body.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data-response-body.js
  libs/common/src/index.ts
  libs/common/src/nunjucks-filters/filter-replaceNewLinesWithBrTags.test.ts
  libs/common/src/nunjucks-filters/filter-replaceNewLinesWithBrTags.ts
  libs/common/src/nunjucks-filters/index.ts
  portal-api/api-tests/sql-db-helper.ts
  portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/get-fee-record-correction.api-test.js
  portal-api/src/v1/api-response-types/get-fee-record-correction-response-body.ts
  portal-api/src/v1/api-response-types/index.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/get-fee-record-correction.controller/index.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/get-fee-record-correction.controller/index.ts
  portal-api/src/v1/controllers/utilisation-report-service/index.js
  portal-api/src/v1/routes.js
  portal-api/test-helpers/test-data/get-fee-record-correction-response-body.ts
  portal/api-tests/utilisation-report-routes.api-test.js
  portal/component-tests/assertions.js
  portal/component-tests/utilisation-report-service/record-correction/_macros/correction-request-details-table.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/provide-utilisation-report-correction.component-test.js
  portal/server/api-response-types/get-fee-record-correction-response-body.ts
  portal/server/api-response-types/index.ts
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/index.js
  portal/server/controllers/utilisation-report-service/record-correction/index.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts
  portal/server/nunjucks-configuration/index.js
  portal/server/routes/utilisation-report-service/index.js
  portal/server/routes/utilisation-report-service/record-correction/index.js
  portal/server/types/primary-nav-key.ts
  portal/server/types/view-models/previous-reports.ts
  portal/server/types/view-models/record-correction/provide-utilisation-report-correction.ts
  portal/templates/utilisation-report-service/record-correction/_macros/correction-request-details-table.njk
  portal/templates/utilisation-report-service/record-correction/provide-utilisation-report-correction.njk
  portal/test-helpers/test-data/get-fee-record-correction-response.ts
  trade-finance-manager-ui/server/nunjucks-configuration/index.js
Labels: Type: Fintech

#4090 feat(FN-3689): rename transient form data references
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/delete-fee-record-correction-request-transient-form-data.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-request-review.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-request-transient-form-data.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/post-fee-record-correction.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction-request-transient-form-data.api-test.ts
  dtfs-central-api/src/repositories/fee-record-correction-request-transient-form-data-repo/fee-record-correction-request-transient-form-data.repo.ts
  dtfs-central-api/src/repositories/fee-record-correction-request-transient-form-data-repo/index.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/delete-fee-record-correction-request-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/delete-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-request-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-request-transient-form-data-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-request-transient-form-data-payload.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data-response-body.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data.js
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  libs/common/src/constants/e2e-fixtures.ts
  libs/common/src/sql-db-connection/migrations/1734541846660-RenameFeeRecordCorrectionRequestTransientFormDataTable.ts
  libs/common/src/sql-db-entities/fee-record-correction-request-transient-form-data/fee-record-correction-request-transient-form-data.entity.ts
  libs/common/src/sql-db-entities/fee-record-correction-request-transient-form-data/fee-record-correction-request-transient-form-data.types.ts
  libs/common/src/sql-db-entities/fee-record-correction-request-transient-form-data/index.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/fee-record-correction-transient-form-data.entity.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/fee-record-correction-transient-form-data.types.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/index.ts
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction-request-transient-form-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction-transient-form-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-request-transient-form-data.ts
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-transient-form-data.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/put-fee-record-correction-transient-form-data.controller.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/validate-form-values.ts
Labels: Type: Fintech

#4108 feat(FN-3578): improve email format for pdc correction request
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-request-information-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/record-correction-request-information-view-model.ts
Labels: Type: Fintech

#4102 feat(FN-3668): add bank correction entry screen fields
  libs/common/src/constants/record-correction-reason.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/map-currencies-to-radio-items.test.ts
  libs/common/src/helpers/map-currencies-to-radio-items.ts
  libs/common/src/test-helpers/currency-radio-item.ts
  portal/component-tests/utilisation-report-service/record-correction/_macros/correction-request-details-table.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/provide-utilisation-report-correction.component-test.js
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts
  portal/server/types/view-models/record-correction/provide-utilisation-report-correction.ts
  portal/templates/utilisation-report-service/record-correction/_macros/correction-request-details-table.njk
  portal/templates/utilisation-report-service/record-correction/provide-utilisation-report-correction.njk
  portal/test-helpers/test-data/view-models/record-corrections/provide-utilisation-report-correction-view-model.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
Labels: Type: Fintech

#4109 fix(DTFS2-7581): enable facility covenant and guarantee amendments in acbs
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
Labels: Type: Fix

#4088 feat(FN-3612): create fee record correction history table
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.api-test.ts
  dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report.repo.ts
  dtfs-central-api/src/types/utilisation-reports.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-utilisation-report-reconciliation-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-history-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/support/ui/index.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/checkRecordCorrectionHistoryTableRowValues.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/completeAndSubmitFeeRecordCorrectionRequestForm.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/completeFeeRecordCorrectionRequestForm.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/index.js
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/record-correction-mock.ts
  libs/common/src/types/fee-record-correction.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-helpers.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-helpers.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/record-correction-history-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
  trade-finance-manager-ui/test-helpers/utilisation-report-reconciliation.ts
Labels: Type: Feature, Type: Fintech

#4115 feat(FN-3612): rename to record correction log and copy update
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-disabled/bank-utilisation-report-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/bank-utilisation-report-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-no-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/checkRecordCorrectionLogTableRowValues.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/index.js
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/record-correction-history-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/record-correction-log-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
Labels: Type: Feature, Type: Fintech

#4112 fix(DTFS2-10543): updated test mocks
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts
Labels: Type: Fix

#4116 feat(FN-3689): add endpoint for persisting bank correction data
  dtfs-central-api/api-tests/sql-db-helper.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/repositories/fee-record-correction-repo/fee-record-correction.repo.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/fee-record-correction-transient-form-data.repo.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/routes/bank-routes.js
  dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-transient-form-data-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-transient-form-data-payload.ts
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-request-transient-form-data-response-body.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-request-transient-form-data.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data.js
  e2e-tests/e2e-fixtures/constants.fixture.js
  e2e-tests/support/tasks.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-form.spec.js
  libs/common/src/constants/e2e-fixtures.ts
  libs/common/src/sql-db-connection/migrations/1734616272101-AddFeeRecordCorrectionTransientFormDataTable.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/fee-record-correction-transient-form-data.entity.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/fee-record-correction-transient-form-data.types.ts
  libs/common/src/sql-db-entities/fee-record-correction-transient-form-data/index.ts
  libs/common/src/sql-db-entities/index.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction-transient-form-data.entity.mock-builder.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-transient-form-data.ts
  portal-api/api-tests/sql-db-helper.ts
Labels: Type: Feature, Type: Fintech

#4123 chore(deps): frivolous workflows removed and dependencies updated
  .github/workflows/feature_deploy.yml
  .github/workflows/notify.yml
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: chore

#4119 feat(FN-3612): update columns and mapping for record correction log table
  dtfs-central-api/src/helpers/map-correction-reasons-to-incorrect-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-incorrect-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/checkRecordCorrectionLogTableRowValues.js
  libs/common/src/test-helpers/mock-data/record-correction-mock.ts
  libs/common/src/types/fee-record-correction.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-helpers.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-helpers.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-table.njk
Labels: Type: Feature, Type: Fintech

#4120 feat(FN-3689): populate correction form with any saved values
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/fee-record-correction-transient-form-data.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/routes/bank-routes.js
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data-request-body.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-transient-form-data-response-body.js
  libs/common/src/test-helpers/mock-data/fee-record-correction-transient-form-data.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/get-fee-record-transient-form-data.api-test.js
  portal-api/src/v1/api-response-types/get-fee-record-correction-transient-form-data-response-body.ts
  portal-api/src/v1/api-response-types/index.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-transient-form-data.controller.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-transient-form-data.controller.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction.controller.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/get-fee-record-correction.controller.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/index.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/pending-corrections.controller.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/pending-corrections.controller.ts
  portal-api/src/v1/controllers/utilisation-report-service/index.ts
  portal-api/src/v1/routes.js
  portal/component-tests/utilisation-report-service/record-correction/pending-corrections.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/provide-utilisation-report-correction.component-test.js
  portal/server/api-response-types/get-fee-record-correction-transient-form-data-response-body.ts
  portal/server/api-response-types/index.ts
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/controller-tests/get-utilisation-report-upload.test.ts
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
  portal/server/types/view-models/record-correction/provide-utilisation-report-correction.ts
  portal/templates/utilisation-report-service/record-correction/pending-corrections.njk
  portal/templates/utilisation-report-service/record-correction/provide-utilisation-report-correction.njk
  portal/test-helpers/test-data/view-models/record-corrections/provide-utilisation-report-correction-view-model.ts
Labels: Type: Feature, Type: Fintech

#4117 feat(DTFS2-7735): refactor Facility End Date validation
  e2e-tests/gef/cypress/e2e/facility/pre-submission/about-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  gef-ui/server/controllers/about-facility/index.validate-and-update-about-facility.test.js
  gef-ui/server/controllers/about-facility/validation.js
  gef-ui/server/controllers/bank-review-date/validation.test.ts
  gef-ui/server/controllers/bank-review-date/validation.ts
  gef-ui/server/controllers/facility-end-date/validation.test.ts
  gef-ui/server/controllers/facility-end-date/validation.ts
  gef-ui/server/utils/day-month-year-validation.test.ts
  gef-ui/server/utils/day-month-year-validation.ts
  gef-ui/server/utils/map-validation-error.test.ts
  gef-ui/server/utils/map-validation-error.ts
  libs/common/src/helpers/date-validation.ts
  libs/common/src/types/index.ts
  libs/common/src/types/validation-error.ts
Labels: Type: Feature

#4121 chore(FN-3733): e2e - refactor utilisation report page E2E selectors
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-disabled/bank-utilisation-report-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-disabled/create-fee-record-correction.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/bank-utilisation-report-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-form-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-form.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/premium-payments-error-states/create-fee-record-correction-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-no-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/add-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/add-to-an-existing-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/bank-utilisation-report-page.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/delete-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/filter-fee-records-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/filter-payment-details/filter-payment-details-by-facility-id.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/filter-payment-details/filter-payment-details-by-payment-currency.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/filter-payment-details/filter-payment-details-by-payment-reference.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/filter-payment-details/filter-payment-details.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/generate-fixed-fee-adjustment-with-amendments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/generate-keying-sheet.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/premium-payments-error-states/add-payment-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/premium-payments-error-states/generate-keying-data-errors.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/reconcile-fee-records.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/remove-fees-from-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/sort-premium-payments.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/view-utilisation.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/support/commands.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/checkRecordCorrectionLogTableRowValues.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/completeFeeRecordCorrectionRequestForm.js
  e2e-tests/tfm/cypress/support/utils/assertUrl.js
  e2e-tests/ukef/cypress/e2e/journeys/utilisation-reports/utilisation-report-submission.spec.js
Labels: Type: chore, Type: Fintech

#4126 feat(FN-3670): add record correction sent page
  libs/common/src/types/portal-session-data/user-session-data.ts
  portal/component-tests/utilisation-report-service/_macros/email-confirmation-list.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/pending-corrections.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/record-correction-sent.component-test.js
  portal/server/controllers/utilisation-report-service/record-correction/index.ts
  portal/server/controllers/utilisation-report-service/record-correction/record-correction-sent/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/record-correction-sent/index.ts
  portal/server/routes/utilisation-report-service/record-correction/index.js
  portal/server/types/view-models/record-correction/record-correction-confirmation.ts
  portal/templates/utilisation-report-service/_macros/email-confirmation-list.njk
  portal/templates/utilisation-report-service/_macros/header-only-panel.njk
  portal/templates/utilisation-report-service/record-correction/correction-sent.njk
  portal/templates/utilisation-report-service/utilisation-report-upload/confirmation.njk
  portal/test-helpers/test-data/index.ts
  portal/test-helpers/test-data/view-models/index.ts
  portal/test-helpers/test-data/view-models/record-corrections/index.ts
  portal/test-helpers/test-data/view-models/record-corrections/pending-corrections-view-model.ts
  portal/test-helpers/test-data/view-models/record-corrections/record-correction-sent-view-model.ts
Labels: Type: Feature, Type: Fintech

#4128 chore(FN-3742): remove all instances of res being passed to a function
  portal/server/controllers/utilisation-report-service/previous-reports/index.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/check-keying-data/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/request-sent/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
Labels: Type: chore, Type: Fintech

#4127 feat(DTFS2-7715): post do you have facility end date endpoint
  gef-ui/api-tests/amendments/do-you-have-a-facility-end-date.get.api-test.ts
  gef-ui/api-tests/amendments/do-you-have-a-facility-end-date.post.api-test.ts
  gef-ui/component-tests/partials/amendments/do-you-have-a-facility-end-date.component-test.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/get-do-you-have-a-facility-end-date.test.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/get-do-you-have-a-facility-end-date.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/post-do-you-have-a-facility-end-date.test.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/post-do-you-have-a-facility-end-date.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/validation.test.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/validation.ts
  gef-ui/server/controllers/amendments/facility-value/validation.ts
  gef-ui/server/controllers/bank-review-date/post-bank-review-date.test.ts
  gef-ui/server/controllers/bank-review-date/post-bank-review-date.ts
  gef-ui/server/controllers/bank-review-date/validation.test.ts
  gef-ui/server/controllers/bank-review-date/validation.ts
  gef-ui/server/controllers/facility-end-date/post-facility-end-date.ts
  gef-ui/server/controllers/facility-end-date/validation.test.ts
  gef-ui/server/controllers/facility-end-date/validation.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/errors-or-value.ts
  gef-ui/server/types/view-models/amendments/do-you-have-a-facility-end-date-view-model.ts
  gef-ui/templates/partials/amendments/do-you-have-a-facility-end-date.njk
Labels: Type: Feature

#4129 feat(DTFS2-7523): what needs to change amendments page
  gef-ui/api-tests/amendments/what-needs-to-change.api-test.ts
  gef-ui/api-tests/amendments/what-needs-to-change.get.api-test.ts
  gef-ui/api-tests/amendments/what-needs-to-change.post.api-test.ts
  gef-ui/component-tests/partials/amendments/what-needs-to-change.component-test.js
  gef-ui/server/controllers/amendments/what-needs-to-change/get-what-needs-to-change.test.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/get-what-needs-to-change.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/post-what-needs-to-change.test.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/post-what-needs-to-change.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/validation.test.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/validation.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/what-needs-to-change.get.test.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/what-needs-to-change-view-model.ts
  gef-ui/templates/partials/amendments/what-needs-to-change.njk
Labels: Type: Feature

#4118 feat(DTFS2-7729): add cancel amendment page
  gef-ui/api-tests/amendments/cancel-portal-facility-amendment.api-test.ts
  gef-ui/component-tests/partials/amendments/cancel-portal-facility-amendment.component-test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/cancel-portal-facility-amendment.get.test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/cancel-portal-facility-amendment.ts
  gef-ui/server/controllers/amendments/cancel-amendment/get-previous-page-url.test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/get-previous-page-url.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/cancel-amendment-view-model.ts
  gef-ui/templates/partials/amendments/cancel.njk
Labels: Type: Feature

#4131 feat(FN-3669): add bank correction review screen
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-review.api-test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-values.ts
  dtfs-central-api/src/repositories/fee-record-correction-repo/fee-record-correction.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/format-form-data-value-for-reason.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/format-form-data-value-for-reason.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-form-data-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-form-data-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-transient-correction-data-to-review-info.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-transient-correction-data-to-review-info.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-review.js
  libs/common/src/test-helpers/fee-record-correction-review-information.ts
  libs/common/src/test-helpers/index.ts
  libs/common/src/types/fee-record-correction-review-information.ts
  libs/common/src/types/index.ts
  portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/get-fee-record-correction-review.api-test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-review.controller.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-review.controller.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/index.ts
  portal-api/src/v1/routes.js
  portal/component-tests/utilisation-report-service/record-correction/check-the-information.component-test.js
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.ts
  portal/server/controllers/utilisation-report-service/record-correction/index.ts
  portal/server/routes/utilisation-report-service/record-correction/index.js
  portal/server/types/view-models/record-correction/utilisation-report-correction-information.ts
  portal/templates/utilisation-report-service/record-correction/check-the-information.njk
  portal/test-helpers/test-data/view-models/record-corrections/utilisation-report-correction-information-view-model.ts
Labels: Type: Feature, Type: Fintech

#4135 feat(FN-3688): add bank correction submit logic (PR 1)
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/routes/bank-routes.js
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-transient-form-data-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-transient-form-data-payload.ts
  libs/common/src/test-helpers/index.ts
  libs/common/src/test-helpers/record-correction-form-values.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-form-values.ts
  portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/put-fee-record-transient-form-data.api-test.js
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-transient-form-data.controller.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-transient-form-data.controller.ts
  portal-api/src/v1/routes.js
  portal/api-tests/utilisation-report-routes.api-test.js
  portal/server/api.js
  portal/server/controllers/utilisation-report-service/record-correction/index.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts
  portal/server/routes/utilisation-report-service/record-correction/index.js
  portal/templates/utilisation-report-service/record-correction/provide-utilisation-report-correction.njk
Labels: Type: Feature, Type: Fintech

#4142 feat(FN-3669): map reported fees amount to monetary value
  libs/common/src/test-helpers/fee-record-correction-review-information.ts
  portal/component-tests/utilisation-report-service/record-correction/check-the-information.component-test.js
  portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.ts
  portal/server/types/view-models/record-correction/utilisation-report-correction-information.ts
  portal/templates/utilisation-report-service/record-correction/check-the-information.njk
  portal/test-helpers/test-data/view-models/record-corrections/utilisation-report-correction-information-view-model.ts
Labels: Type: Feature, Type: Fintech

#4140 feat(DTFS2-7739): display cancelled deal status when amendment in progress
  e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/gef/cancel-deal-with-amendment-in-progress.spec.js
  libs/common/src/types/mongo-db-models/tfm-deals.ts
  trade-finance-manager-ui/server/controllers/case/activity/index.js
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/case/parties/index.js
  trade-finance-manager-ui/server/controllers/case/underwriting/index.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.filterAmendmentsByInProgress.test.js
  trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
  trade-finance-manager-ui/server/controllers/helpers/dealsAndFacilities.helper.deals.test.js
  trade-finance-manager-ui/server/controllers/helpers/overrideDealsIfAmendmentsInProgress.helper.js
  trade-finance-manager-ui/server/controllers/helpers/overrideDealsIfAmendmentsInProgress.helper.test.js
Labels: Type: Feature

#4154 test(DTFS2-7675): fix amendments e2e test
  e2e-tests/gef/cypress/e2e/pages/amendments/what-do-you-need-to-change.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/change-facility-value-journey.happy-path.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/change-facility-value-journey.unhappy-path.spec.js
Labels: Test

#4153 fix(DTFS2-7771): update security.txt
  libs/common/src/helpers/date.test.ts
  libs/common/src/helpers/date.ts
  portal/api-tests/static-routes.api-test.js
  portal/server/routes/static.js
Labels: Type: Fix

#4151 feat(FN-3688): add backend bank record correction validation
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/extract-record-correction-transient-form-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/extract-record-correction-transient-form-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/get-record-correction-transient-form-required-field-validation-errors.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/get-record-correction-transient-form-required-field-validation-errors.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/get-record-correction-transient-form-validation-error.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/get-record-correction-transient-form-validation-error.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/parse-record-correction-transient-form-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/parse-record-correction-transient-form-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/validate-no-unexpected-record-correction-transient-form-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/validate-no-unexpected-record-correction-transient-form-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/validate-record-correction-transient-form-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/validate-record-correction-transient-form-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/provide-correction.spec.js
  libs/common/src/constants/regex.ts
  libs/common/src/helpers/currency.test.ts
  libs/common/src/helpers/currency.ts
  libs/common/src/helpers/monetary-value.test.ts
  libs/common/src/helpers/monetary-value.ts
  libs/common/src/helpers/validation.test.ts
  libs/common/src/helpers/validation.ts
  libs/common/src/test-helpers/index.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-form-value-validation-errors.ts
  portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/put-fee-record-transient-form-data.api-test.js
  portal/server/controllers/utilisation-report-service/record-correction/index.ts
  portal/server/routes/utilisation-report-service/record-correction/index.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/parse-payment-form-values.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/validate-payment-form-values.ts
Labels: Type: Feature, Type: Fintech

#4157 feat(DTFS2-7498): add facility type to page captions on amendments flow
  gef-ui/component-tests/partials/amendments/bank-review-date.component-test.ts
  gef-ui/component-tests/partials/amendments/cancel-portal-facility-amendment.component-test.ts
  gef-ui/component-tests/partials/amendments/cover-end-date.component-test.ts
  gef-ui/component-tests/partials/amendments/do-you-have-a-facility-end-date.component-test.ts
  gef-ui/component-tests/partials/amendments/eligibility.component-test.ts
  gef-ui/component-tests/partials/amendments/facility-end-date.component-test.ts
  gef-ui/component-tests/partials/amendments/facility-value.component-test.ts
  gef-ui/component-tests/partials/amendments/what-needs-to-change.component-test.ts
  gef-ui/server/controllers/amendments/bank-review-date/get-bank-review-date.test.ts
  gef-ui/server/controllers/amendments/bank-review-date/get-bank-review-date.ts
  gef-ui/server/controllers/amendments/cancel-amendment/cancel-portal-facility-amendment.get.test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/cancel-portal-facility-amendment.ts
  gef-ui/server/controllers/amendments/cover-end-date/get-cover-end-date.test.ts
  gef-ui/server/controllers/amendments/cover-end-date/get-cover-end-date.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/get-do-you-have-a-facility-end-date.test.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/get-do-you-have-a-facility-end-date.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/post-do-you-have-a-facility-end-date.test.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/post-do-you-have-a-facility-end-date.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.test.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.ts
  gef-ui/server/controllers/amendments/facility-end-date/get-facility-end-date.test.ts
  gef-ui/server/controllers/amendments/facility-end-date/get-facility-end-date.ts
  gef-ui/server/controllers/amendments/facility-end-date/post-facility-end-date.test.ts
  gef-ui/server/controllers/amendments/facility-end-date/post-facility-end-date.ts
  gef-ui/server/controllers/amendments/facility-value/get-facility-value.test.ts
  gef-ui/server/controllers/amendments/facility-value/get-facility-value.ts
  gef-ui/server/controllers/amendments/facility-value/post-facility-value.test.ts
  gef-ui/server/controllers/amendments/facility-value/post-facility-value.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/get-what-needs-to-change.test.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/get-what-needs-to-change.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/post-what-needs-to-change.test.ts
  gef-ui/server/controllers/amendments/what-needs-to-change/post-what-needs-to-change.ts
  gef-ui/server/types/view-models/amendments/bank-review-date-view-model.ts
  gef-ui/server/types/view-models/amendments/cancel-amendment-view-model.ts
  gef-ui/server/types/view-models/amendments/cover-end-date-view-model.ts
  gef-ui/server/types/view-models/amendments/do-you-have-a-facility-end-date-view-model.ts
  gef-ui/server/types/view-models/amendments/eligibility-view-model.ts
  gef-ui/server/types/view-models/amendments/facility-end-date-view-model.ts
  gef-ui/server/types/view-models/amendments/facility-value-view-model.ts
  gef-ui/server/types/view-models/amendments/what-needs-to-change-view-model.ts
  gef-ui/templates/partials/amendments/bank-review-date.njk
  gef-ui/templates/partials/amendments/cancel.njk
  gef-ui/templates/partials/amendments/cover-end-date.njk
  gef-ui/templates/partials/amendments/do-you-have-a-facility-end-date.njk
  gef-ui/templates/partials/amendments/eligibility.njk
  gef-ui/templates/partials/amendments/facility-end-date.njk
  gef-ui/templates/partials/amendments/facility-value.njk
  gef-ui/templates/partials/amendments/what-needs-to-change.njk
Labels: Type: Feature

#4159 fix(DTFS2-7771): added date helper functions
  libs/common/src/helpers/date.test.ts
  libs/common/src/helpers/date.ts
  portal/api-tests/static-routes.api-test.js
  portal/server/routes/static.js
Labels: Type: Fix

#4169 feat(DTFS2-7498): add eligibility post controller
  gef-ui/api-tests/amendments/eligibility.post.api-test.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.test.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/post-eligibility.test.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/post-eligibility.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/validation.test.ts
  gef-ui/server/controllers/amendments/eligibility-criteria/validation.ts
  gef-ui/server/controllers/amendments/helpers/eligibility.helper.parseEligibilityResponse.test.ts
  gef-ui/server/controllers/amendments/helpers/eligibility.helper.parseStringAsBoolean.test.ts
  gef-ui/server/controllers/amendments/helpers/eligibility.helper.ts
  gef-ui/server/routes/facilities/amendments/index.ts
Labels: Type: Feature

#4161 feat(FN-3675): save and apply fee record correction
  dtfs-central-api/src/helpers/get-correction-corrected-values-from-form-data.test.ts
  dtfs-central-api/src/helpers/get-correction-corrected-values-from-form-data.ts
  dtfs-central-api/src/helpers/get-correction-previous-values-from-fee-record.test.ts
  dtfs-central-api/src/helpers/get-correction-previous-values-from-fee-record.ts
  dtfs-central-api/src/helpers/get-correction-values.test.ts
  dtfs-central-api/src/helpers/get-correction-values.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/repositories/fee-record-correction-repo/fee-record-correction.repo.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/fee-record-correction-transient-form-data.repo.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-received/correction-received.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-received/correction-received.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-received/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event-type.ts
  dtfs-central-api/src/services/state-machines/fee-record/event/fee-record.event.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/helpers/map-fee-records-to-pending-corrections.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.ts
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/correction-sent.spec.js
  libs/common/src/constants/fee-record-status.ts
  libs/common/src/sql-db-connection/migrations/1737047317093-AddCorrectionReceivedColumns.ts
  libs/common/src/sql-db-entities/fee-record-correction/fee-record-correction.entity.test.ts
  libs/common/src/sql-db-entities/fee-record-correction/fee-record-correction.entity.ts
  libs/common/src/sql-db-entities/fee-record-correction/fee-record-correction.types.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.test.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
  libs/common/src/sql-db-entities/partial-entities/fee-record-correction-values.partial-entity.ts
  libs/common/src/sql-db-entities/partial-entities/index.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/record-correction-values.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/pending-corrections.controller.test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/fee-record-status.component-test.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-fee-record-display-status.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-fee-record-display-status.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.test.ts
  trade-finance-manager-ui/server/helpers/premium-payments-table-checkbox-id-helper.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-status.njk
Labels: Type: Feature, Type: Fintech

#4170 feat(DTFS2-7620): add e2e tests to amendments FED flow
  e2e-tests/gef/cypress/e2e/pages/amendments/do-you-have-a-facility-end-date.js
  e2e-tests/gef/cypress/e2e/pages/amendments/facility-end-date.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/change-facility-end-date-journey.happy-path.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/change-facility-end-date-journey.unhappy-path.spec.js
  utils/mock-data-loader/gef/eligibilityCriteriaAmendments.js
Labels: Type: Feature

#4156 feat(DTFS2-7621): add post controller for bank review date
  gef-ui/api-tests/amendments/bank-review-date.post.api-test.ts
  gef-ui/server/controllers/amendments/bank-review-date/post-bank-review-date.test.ts
  gef-ui/server/controllers/amendments/bank-review-date/post-bank-review-date.ts
  gef-ui/server/routes/facilities/amendments/index.ts
Labels: Type: Feature

#4164 feat(FN-3611): browser back button behaviour after correction request submitted
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-request-submission-going-back.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/index.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/pageNotFoundPage.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/status.ts
  libs/common/src/middleware/index.ts
  libs/common/src/middleware/set-no-store-cache-control.test.ts
  libs/common/src/middleware/set-no-store-cache-control.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction-request-review-response-body-mock.ts
  libs/common/src/test-helpers/mock-data/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-request-review.controller.test.ts
  trade-finance-manager-ui/server/api-response-types/fee-record-correction-request-review-response-body.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/is-record-correction-request-review-response-type.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/is-record-correction-request-review-response-type.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-request-already-submitted.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-request-already-submitted.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/index.ts
  trade-finance-manager-ui/server/types/view-models/problem-with-service-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/page-not-found.njk
Labels: Type: Feature, Type: Fintech

#4176 feat(FN-3796): added correctValues and status to record correction log tab
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-old-fee-record-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-old-fee-record-values.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-transient-correction-data-to-review-info.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-transient-correction-data-to-review-info.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-formatted-old-and-correct-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-formatted-old-and-correct-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-correct-records.spec.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/record-correction-status.ts
  libs/common/src/test-helpers/mock-data/record-correction-mock.ts
  libs/common/src/types/fee-record-correction.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-status.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/map-record-correction-status.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/map-record-correction-status.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-helpers.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/record-correction-helpers.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-table.njk
Labels: Type: Feature, Type: Fintech

#4177 feat(FN-3675): send correction received emails
  .github/workflows/test.yml
  docker-compose.yml
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction.api-test.ts
  dtfs-central-api/src/constants/email-template-ids.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/helpers.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/utilisation-report-emails.test.ts
  libs/common/src/helpers/utilisation-report-emails.ts
  portal-api/src/v1/services/utilisation-report/email-service.test.ts
  portal-api/src/v1/services/utilisation-report/email-service.ts
Labels: Type: Feature, Type: Fintech

#4182 feat(DTFS2-7709): add manual approval needed page to amendments
  e2e-tests/gef/cypress/e2e/pages/amendments/eligibility.js
  e2e-tests/gef/cypress/e2e/pages/amendments/manual-approval-needed.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/eligibility.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/manual-approval-needed.spec.js
  gef-ui/api-tests/amendments/manual-approval-needed.get.api-test.ts
  gef-ui/component-tests/partials/amendments/manual-approval-needed.component-test.ts
  gef-ui/server/constants/amendments.ts
  gef-ui/server/controllers/amendments/helpers/navigation.helper.getNextPage.test.ts
  gef-ui/server/controllers/amendments/helpers/navigation.helper.getPreviousPage.test.ts
  gef-ui/server/controllers/amendments/helpers/navigation.helper.ts
  gef-ui/server/controllers/amendments/manual-approval-needed/get-manual-approval-needed.test.ts
  gef-ui/server/controllers/amendments/manual-approval-needed/get-manual-approval-needed.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/ManualApprovalNeededViewModel.ts
  gef-ui/templates/partials/amendments/manual-approval-needed.njk
Labels: Type: Feature

#4178 feat(FN-3671): add bank correction history tab backend endpoint
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-completed-fee-record-corrections.api-test.ts
  dtfs-central-api/src/helpers/index.ts
  dtfs-central-api/src/helpers/map-correction-reasons-and-values-to-formatted-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-and-values-to-formatted-values.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-old-fee-record-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-values.test.ts
  dtfs-central-api/src/helpers/map-correction-reasons-to-formatted-values.ts
  dtfs-central-api/src/helpers/validate-required-correction-field.test.ts
  dtfs-central-api/src/helpers/validate-required-correction-field.ts
  dtfs-central-api/src/repositories/fee-record-correction-repo/fee-record-correction.repo.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-completed-fee-record-corrections.controller/helpers/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-completed-fee-record-corrections.controller/helpers/map-completed-corrections-to-response.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-completed-fee-record-corrections.controller/helpers/map-completed-corrections-to-response.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-completed-fee-record-corrections.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-completed-fee-record-corrections.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/format-form-data-value-for-reason.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/format-form-data-value-for-reason.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-formatted-old-and-correct-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-formatted-old-and-correct-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.test.ts
  dtfs-central-api/src/v1/routes/bank-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/completed-fee-record-correction.js
  portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/get-completed-fee-record-corrections.api-test.js
  portal-api/src/v1/api-response-types/get-completed-fee-record-corrections-response-body.ts
  portal-api/src/v1/api-response-types/index.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/completed-fee-record-corrections.controller.test.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/completed-fee-record-corrections.controller.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/index.ts
  portal-api/src/v1/routes.js
  portal-api/test-helpers/test-data/get-completed-fee-record-corrections-response-body.ts
Labels: Type: Feature, Type: Fintech

#4180 feat(FN-3675): fix facility id correction not working
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction.api-test.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.test.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
Labels: Type: Feature, Type: Fintech
