Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-05, with the labels that each got.

#4314 docs(architecture): azure architecture diagram
  cspell.json
  doc/assets/azure-architecture.drawio
  doc/assets/azure-architecture.svg
Labels: Type: Docs

#4304 feat(DTFS2-7750): submission email maker checker pim
  dtfs-central-api/api-tests/v1/portal-facility-amendments/submit-amendment-patch.api-test.ts
  dtfs-central-api/src/constants/email-template-ids.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-submit-amendment.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-submit-amendment.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-submit-amendment-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-submit-amendment-payload.ts
  gef-ui/api-tests/amendments/submit-amendment-to-ukef.post.api-test.ts
  gef-ui/server/controllers/amendments/check-your-answers/post-check-your-answers.ts
  gef-ui/server/controllers/amendments/helpers/map-common-email-variables.test.ts
  gef-ui/server/controllers/amendments/helpers/map-common-email-variables.ts
  gef-ui/server/controllers/amendments/helpers/map-submitted-to-checker-email-variables.test.ts
  gef-ui/server/controllers/amendments/helpers/map-submitted-to-checker-email-variables.ts
  gef-ui/server/controllers/amendments/helpers/map-submitted-to-ukef-email-variables.test.ts
  gef-ui/server/controllers/amendments/helpers/map-submitted-to-ukef-email-variables.ts
  gef-ui/server/controllers/amendments/submit-amendment-to-ukef/post-submit-amendment-to-ukef.test.ts
  gef-ui/server/controllers/amendments/submit-amendment-to-ukef/post-submit-amendment-to-ukef.ts
  gef-ui/server/services/api.js
  libs/common/src/helpers/generate-amendment-mandatory-criteria.test.ts
  libs/common/src/helpers/generate-amendment-mandatory-criteria.ts
  libs/common/src/helpers/index.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/portal-amendment-to-ukef-email-variables.ts
  libs/common/src/types/portal/amendment.ts
  portal-api/api-tests/v1/gef/amendments/submit-amendment.patch.api-test.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/amendments/patch-submit-amendment-controller.test.ts
  portal-api/src/v1/controllers/amendments/patch-submit-amendment.controller.ts
  portal-api/src/v1/validation/route-validators/amendments/validate-patch-portal-facility-submit-amendment-payload.test.ts
  portal-api/src/v1/validation/route-validators/amendments/validate-patch-portal-facility-submit-amendment-payload.ts
Labels: Type: Feature

#4317 chore(DTFS2-6685): anonymise bank names
  dtfs-central-api/api-tests/mocks/banks.ts
  dtfs-central-api/api-tests/mocks/test-users/mock-portal-user.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports-reconciliation-summary.api-test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/due-report-initialised/due-report-initialised.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers/reconciliation-summary-generator.test.ts
  dtfs-central-api/test-helpers/test-data/bank.ts
  dtfs-central-api/test-helpers/test-data/session-bank.ts
  e2e-tests/e2e-fixtures/portal-users.fixture.js
  e2e-tests/gef/cypress/e2e/application/application-details.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/maker-checker-user-role/maker_checker-should-not-submit-edited-deal-submit-to-checker.spec.js
  e2e-tests/gef/cypress/e2e/scenarios/makers-input.spec.js
  e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/find-utilisation-reports-by-bank-and-year.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/navigating-to-utilisation-reports.spec.js
  e2e-tests/tfm/cypress/fixtures/deal-AIN.js
  e2e-tests/tfm/cypress/fixtures/deal-MIA.js
  e2e-tests/tfm/cypress/fixtures/deal-MIN.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-issued-facilities/test-data/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-non-gbp-facilities/test-data/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued/test-data/dealThatJustNeedsConversionDate.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued/test-data/dealThatJustNeedsConversionDate.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/test-data/AIN-deal-unissued-facilities/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/test-data/AIN-deal/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/test-data/MIA-deal/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/test-data/MIN-deal-unissued-facilities/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/e2e/journeys/portal/test-data/MIN-deal/dealThatJustNeedsDates.json
  e2e-tests/ukef/cypress/fixtures/deal.js
  libs/common/src/test-helpers/portal-session-bank.ts
  portal-api/api-tests/api-test-users.js
  portal-api/api-tests/fixtures/deal-fully-completed.js
  portal-api/api-tests/v1/users/test-data.js
  portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.test.ts
  portal-api/src/v1/controllers/reports/review-ukef-decision.controller.js
  portal-api/src/v1/controllers/reports/unissued-facilities.controller.js
  portal-api/src/v1/controllers/utilisation-report-service/due-report-periods.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/next-report-period.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-download.controller.test.js
  portal-api/src/v1/controllers/utilisation-report-service/validate-utilisation-report-data.controller.test.ts
  portal-api/test-helpers/test-data/banks.ts
  portal/test-helpers/mock-banks.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-agent-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-bond-issuer-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-buyer-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-exporter-area.component-test.js
  trade-finance-manager-ui/component-tests/case/parties/_macros/parties-indemnifier-area.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/find-utilisation-reports-by-year.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports-by-bank-and-year-results.component-test.js
  trade-finance-manager-ui/server/test-mocks/mock-banks.ts
  trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.ts
  trade-finance-manager-ui/test-helpers/test-data/bank.ts
  utils/mock-data-loader/banks/index.js
  utils/mock-data-loader/gef/application.js
  utils/mock-data-loader/portal-users/index.js
Labels: chore

#4323 chore(deps): dependencies updates
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: chore

#4324 fix(DTFS2-7969): updated cookie to 0.7.0 for csurf
  package-lock.json
  package.json
Labels: Type: Fix
