Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-10, with the labels that each got.

#4458 fix(DTFS2-8145): fix failing tenor e2e test
  e2e-tests/tfm/cypress/support/utils/facility-tenor.js
Labels: Type: Fix

#4456 feat(DTFS2-7912): update logo tfm
  trade-finance-manager-ui/public/images/UK-Export-Finance-logo.png
  trade-finance-manager-ui/public/images/UK-Export-Finance-logo.svg
Labels: Type: Feature

#4457 feat(DTFS-8132): csrf middlewares for trade-finance-manager-ui
  gef-ui/server/generateApp.js
  libs/common/package.json
  libs/common/src/test-helpers/api-test/create-api.ts
  libs/common/src/test-helpers/api-test/index.ts
  package-lock.json
  package.json
  portal-ui/server/generateApp.ts
  trade-finance-manager-ui/api-tests/api-rate-limiting.api-test.js
  trade-finance-manager-ui/api-tests/create-api.js
  trade-finance-manager-ui/api-tests/csrf.api-test.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/case/parties/index.test.js
  trade-finance-manager-ui/server/generateApp.js
  trade-finance-manager-ui/server/middleware/csrf-token.middleware.js
Labels: Type: Feature

#4463 fix(DTFS2-7883): fix new cover end date back link
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/portal/general/cover-end-date.spec.js
  gef-ui/templates/partials/amendments/cover-end-date.njk
Labels: Type: Fix

#4465 feat(DTFS2-8042): added effective date to facility amendment
  azure-functions/acbs/mappings/facility/facility-loan-amend.js
  azure-functions/acbs/src/functions/acbs-amend-facility.js
  external-api/server/v1/controllers/acbs.controller.ts
  libs/common/src/helpers/date.test.ts
  libs/common/src/helpers/date.ts
  trade-finance-manager-api/server/v1/controllers/acbs.controller.js
  trade-finance-manager-api/server/v1/controllers/acbs.controller.test.js
  trade-finance-manager-api/server/v1/helpers/amendment.helpers.js
  trade-finance-manager-api/server/v1/helpers/amendment.helpers.test.js
Labels: Type: Feature

#4469 chore(DTFS2-7112): remove submitDealAfterUkefIds from tfm and ukef e2e tests
  dtfs-central-api/server/v1/controllers/tfm/deal/tfm-delete-deal.controller.ts
  dtfs-central-api/server/v1/controllers/tfm/deal/tfm-get-deal.controller.js
  e2e-tests/e2e-fixtures/portal-users.fixture.js
  e2e-tests/portal/cypress/support/trade-finance-manager-api/api.js
  e2e-tests/portal/cypress/support/trade-finance-manager-api/submitDeal.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-buyer.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-exporter.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-product.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-receivedDate-default-sort.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-stage.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-ukefDealId.spec.js
  e2e-tests/tfm/cypress/support/commands.js
  e2e-tests/tfm/cypress/support/portal-api/api.js
  e2e-tests/tfm/cypress/support/portal-api/listAllDeals.js
  e2e-tests/tfm/cypress/support/trade-finance-manager-api/api.js
  e2e-tests/tfm/cypress/support/trade-finance-manager-api/submitDeal.js
  e2e-tests/tfm/cypress/support/trade-finance-manager-api/submitManyDeals.js
  e2e-tests/tfm/cypress/support/utils/loadData.js
  e2e-tests/ukef/cypress/support/trade-finance-manager-api/api.js
  e2e-tests/ukef/cypress/support/trade-finance-manager-api/submitDeal.js
  e2e-tests/ukef/cypress/support/trade-finance-manager-api/submitManyDeals.js
  libs/common/src/test-helpers/e2e/deals/deal-params.ts
  libs/common/src/test-helpers/e2e/deals/mock-AIN-deal.ts
  libs/common/src/test-helpers/e2e/facilities/mock-gef-facilities.ts
  libs/common/src/test-helpers/e2e/index.ts
  package.json
  portal-api/server/v1/controllers/deal.controller.js
  trade-finance-manager-api/server/v1/controllers/deal.submit.controller.js
  trade-finance-manager-api/server/v1/deals/routes.js
  utils/mock-data-loader/e2e/create-mock-deal.js
  utils/mock-data-loader/e2e/deals-search-deals.js
  utils/mock-data-loader/e2e/deals-sort-by-buyer.js
  utils/mock-data-loader/e2e/deals-sort-by-exporter.js
  utils/mock-data-loader/e2e/deals-sort-by-product.js
  utils/mock-data-loader/e2e/deals-sort-by-received-date.js
  utils/mock-data-loader/e2e/deals-sort-by-stage.js
  utils/mock-data-loader/e2e/deals-sort-by-ukef-id.js
  utils/mock-data-loader/e2e/test-deals.js
  utils/mock-data-loader/insert-mocks-gef.js
  utils/mock-data-loader/insert-mocks.js
  utils/mock-data-loader/re-insert-mocks.js
  utils/mock-data-loader/user-helper.js
  utils/package.json
Labels: Type: chore
