Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-04, with the labels that each got.

#4285 feat(DTFS2-7721): added print button to amendment details page
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/supply-contract-preview-print-button.spec.js
  e2e-tests/portal/cypress/e2e/partials/index.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/utils/assertPrintDialogue.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/amendment-details.spec.js
  e2e-tests/ukef/cypress/e2e/partials/index.js
  e2e-tests/ukef/cypress/support/commands.js
  e2e-tests/ukef/cypress/support/utils/assertPrintDialogue.js
  gef-ui/component-tests/index/index.component-test.js
  gef-ui/component-tests/partials/amendments/amendment-details.component-test.ts
  gef-ui/templates/index.njk
  gef-ui/templates/partials/amendments/amendment-details.njk
  gef-ui/templates/partials/print-button.njk
  portal/component-tests/contract/about/check-your-answers.component-test.js
  portal/component-tests/index/index.component-test.js
  portal/public/css/styles.css
  portal/public/js/govukFrontend.js
  portal/public/js/govukFrontend.js.LICENSE.txt
  portal/public/js/govukFrontend.js.map
  portal/public/js/main.js
  portal/public/js/main.js.map
  portal/public/js/printPage.js
  portal/public/js/printPage.js.map
  portal/scripts/print-page.js
  portal/templates/_partials/print-button.njk
  portal/templates/index.njk
Labels: Type: Feature

#4287 fix(DTFS2-7519): fixed currency format
  dtfs-central-api/Dockerfile
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/amendment-details.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-both-cover-end-date-and-facility-value.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-facility-value-journey.spec.js
  external-api/Dockerfile
  gef-ui/Dockerfile
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.test.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.ts
  gef-ui/server/controllers/amendments/check-your-answers/create-check-your-answers-view-model.test.ts
  gef-ui/server/controllers/amendments/check-your-answers/create-check-your-answers-view-model.ts
  gef-ui/server/controllers/amendments/helpers/amendment-summary-view-model.helper.test.ts
  gef-ui/server/controllers/amendments/helpers/amendment-summary-view-model.helper.ts
  portal-api/Dockerfile
  portal/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
Labels: Type: Fix

#4280 chore(DTFS2-7431): replace insert one deal with create bssewcs deal function
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-financial-page-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-supply-contract-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-bond/bond-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-bond/bond-fee-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-bond/bond-financial-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-bond/bond.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-bond/submit-bond-with-created-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-loan/loan-guarantee-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-loan/loan.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-loan/submit-loan-with-created-elements.spec.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/completeAboutBuyerSection.js
  e2e-tests/portal/cypress/support/portal/completeAboutFinancialSection.js
  e2e-tests/portal/cypress/support/portal/completeAboutSupplierSection.js
  e2e-tests/portal/cypress/support/portal/createBssEwcsDeal.js
Labels: chore

#4278 feat(DTFS2-7853): ready for checkers approval checker
  e2e-tests/gef/cypress/e2e/pages/application-preview.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/deal-summary-page-amendment-ready-for-checkers-approval.spec.js
  gef-ui/component-tests/includes/application-preview/facilities.component-test.js
  gef-ui/component-tests/includes/application-preview/summary.component-test.js
  gef-ui/component-tests/includes/application-preview/task-comments.component-test.js
  gef-ui/server/utils/submitted-amendment-details.test.js
  gef-ui/templates/includes/application-preview/facilities.njk
  gef-ui/templates/includes/application-preview/task-comments.njk
Labels: Type: Feature

#4291 chore(DTFS2-7431): clean bss ewcs deal function
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/addBondDetails.js
  e2e-tests/portal/cypress/support/portal/completeAboutBuyerSection.js
  e2e-tests/portal/cypress/support/portal/completeAboutFinancialSection.js
  e2e-tests/portal/cypress/support/portal/completeAboutSupplierSection.js
  e2e-tests/portal/cypress/support/portal/completeBondFeeDetails.js
  e2e-tests/portal/cypress/support/portal/completeBondFinancialDetails.js
  e2e-tests/portal/cypress/support/portal/completeEligibilityCriteria.js
  e2e-tests/portal/cypress/support/portal/completeIssuedBondDetails.js
  e2e-tests/portal/cypress/support/portal/completeUnissuedBondDetails.js
  e2e-tests/portal/cypress/support/portal/createBssEwcsDeal.js
  e2e-tests/portal/cypress/support/portal/fillBankDetails.js
  e2e-tests/portal/cypress/support/portal/proceedToReviewAndApproval.js
  e2e-tests/portal/cypress/support/portal/startNewSubmission.js
Labels: chore

#4290 fix(DTFS2-7521): fixed facility value validation
  gef-ui/api-tests/amendments/facility-value.post.api-test.ts
  gef-ui/server/controllers/amendments/facility-value/post-facility-value.test.ts
  gef-ui/server/controllers/amendments/facility-value/post-facility-value.ts
  gef-ui/server/controllers/amendments/facility-value/validation.test.ts
  gef-ui/server/controllers/amendments/facility-value/validation.ts
  gef-ui/server/controllers/facility-value/index.js
  gef-ui/server/controllers/facility-value/index.test.js
  gef-ui/server/models/facility.js
  gef-ui/templates/partials/amendments/facility-value.njk
  gef-ui/templates/partials/facility-value.njk
Labels: Type: Fix

#4289 feat(DTFS2-7746): amendment details checker
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/amendment-details.spec.js
  gef-ui/api-tests/amendments/amendment-details.get.api-test.ts
  gef-ui/component-tests/partials/amendments/amendment-details.component-test.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.test.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.ts
  gef-ui/server/controllers/amendments/amendment-details/get-amendment-details.test.ts
  gef-ui/server/controllers/amendments/amendment-details/get-amendment-details.ts
  gef-ui/server/controllers/amendments/helpers/amendment-summary-view-model.helper.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/amendment-details-view-model.ts
  gef-ui/templates/partials/amendments/amendment-details.njk
Labels: Type: Feature

#4281 chore(DTFS2-7431): createbssewcs function to replace insertonedeal
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/about-supply-contract-page-titles.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-buyer-page-happy-path.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-buyer-validation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-financial-page-happy-path.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-financial-page-unhappy-path.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-financial-validation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-clearing-data-via-next-page.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-clearing-data-via-save-and-go-back.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-happy-path.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-unhappy-path.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-about-supply-contract-validation.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/fill-in-buyer-page-create-element.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-about-supply-contract/supply-contract-preview-print-button.spec.js
  e2e-tests/portal/cypress/e2e/pages/contract/about/about-buyer.js
  e2e-tests/portal/cypress/e2e/pages/contract/about/about-financial.js
  e2e-tests/portal/cypress/e2e/pages/contract/about/about-preview.js
  e2e-tests/portal/cypress/e2e/pages/contract/about/about-supplier.js
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/inCompleteAboutSupplierSection.js
Labels: chore

#4279 chore(DTFS2-7431): replaced insertOneDeal with createBssEwcs function
  e2e-tests/portal/cypress/e2e/journeys/maker-loan/loan-dates-repayments.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker-loan/loan-financial-details.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/abandon-a-deal/abandon-a-deal.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bss-mandatory-criteria/bss-mandatory-criteria.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/edit-deal-name/edit-deal-name.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/proceed-to-review/proceed-to-review.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/xss/xss.spec.js
  e2e-tests/portal/cypress/e2e/journeys/read-only/abandon-deal/cannot-abandon-a-deal.spec.js
  e2e-tests/portal/cypress/e2e/journeys/read-only/deal/access-contract.spec.js
  e2e-tests/portal/cypress/e2e/journeys/read-only/deal/cannot-abandon-a-deal.spec.js
  e2e-tests/portal/cypress/e2e/journeys/read-only/deal/cannot-modify-an-unissued-deal.spec.js
Labels: chore

#4294 fix(DTFS2-7917): record correction - cancel link
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-form.spec.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/create-record-correction-request.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/cancel-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/cancel-record-correction-request/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/create-record-correction-request.njk
Labels: Type: Fix, Type: Fintech

#4293 feat(DTFS2-7911): mandatory criteria updates
  e2e-tests/e2e-fixtures/bss/mandatoryCriteria.fixture.js
  gef-ui/templates/partials/mandatory-criteria.njk
  libs/common/src/constants/environments.ts
  libs/common/src/constants/index.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/is-production.test.ts
  libs/common/src/helpers/is-production.ts
  portal-api/api-tests/common-tests/role-authorisation-tests.js
  portal-api/api-tests/deal-versioning.api-test.js
  portal-api/api-tests/fixtures/gef/application.js
  portal-api/api-tests/fixtures/gef/mandatoryCriteriaVersioned.js
  portal-api/api-tests/fixtures/mandatoryCriteria.js
  portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
  portal-api/api-tests/v1/mandatory-criteria/mandatory-criteria.api-test.js
  portal-api/src/v1/controllers/mandatoryCriteria.controller.js
  portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
  portal-api/src/v1/gef/models/mandatoryCriteria.js
  portal-api/src/v1/gef/routes.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/users/sign-in-link.service.js
  portal/component-tests/fixtures/deal-fully-completed.js
  trade-finance-manager-ui/server/routes/team-checking/index.ts
  utils/mock-data-loader/bss/mandatoryCriteria.js
  utils/mock-data-loader/gef/mandatoryCriteriaVersioned.js
Labels: Type: Fix

#4296 fix(DTFS2-7749-7721): amendment details - hide print button if js disabled
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-details.spec.js
  gef-ui/public/css/styles.css
  gef-ui/public/js/govukFrontend.js
  gef-ui/public/js/govukFrontend.js.LICENSE.txt
  gef-ui/public/js/govukFrontend.js.map
  gef-ui/public/js/main.js
  gef-ui/public/js/main.js.map
  gef-ui/styles/styles.scss
  gef-ui/styles/visibility.scss
Labels: Type: Fix

#4299 fix(DTFS2-7911): added html and plain text render argument to mc macro
  .github/workflows/deployment.yml
  .github/workflows/purge.yml
  .github/workflows/release.yml
  e2e-tests/portal/cypress/e2e/journeys/maker/before-you-start/mandatory-criteria.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/bss-mandatory-criteria/bss-mandatory-criteria.spec.js
  e2e-tests/portal/cypress/e2e/pages/beforeYouStart.js
  libs/common/src/helpers/generate-mandatory-criteria.test.ts
  libs/common/src/helpers/generate-mandatory-criteria.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/strip-html.test.ts
  libs/common/src/helpers/strip-html.ts
  libs/common/src/types/index.ts
  libs/common/src/types/mandatory-criteria.ts
  portal/component-tests/_macros/mandatory-criteria-box.test.js
  portal/component-tests/assertions.js
  portal/component-tests/contract/contract-submission-details.component-test.js
  portal/templates/_macros/mandatory-criteria-box.njk
  portal/templates/contract/contract-submission-details.njk
  trade-finance-manager-api/src/v1/helpers/generate-mandatory-criteria-string.js
Labels: Type: Fix

#4302 fix(DTFS2-7935): added ParsedQs type to custom express request
  dtfs-central-api/package.json
  dtfs-central-api/src/types/custom-express-request.ts
  dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.ts
  dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.ts
  dtfs-central-api/src/v1/controllers/portal/deal/delete-deal.controller.ts
  dtfs-central-api/src/v1/controllers/portal/facility/delete-facility.controller.ts
  dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/delete-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/delete-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-utilisation-report-pending-corrections.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-request-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/patch-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-done.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-to-do.controller/index.ts
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  libs/common/src/types/express-custom-request.ts
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-api/src/types/custom-express-request.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/delete-fee-record-correction-transient-form-data.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-fee-record-correction-transient-form-data.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/post-fee-record-correction.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/put-fee-record-correction-transient-form-data.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-report-reconciliation-details-by-id.controller/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-fees-to-an-existing-payment.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-payment.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-remove-fees-from-payment.controller.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/cancel-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/remove-fees-from-payment/index.ts
  trade-finance-manager-ui/server/types/custom-express-request.ts
  utils/package.json
Labels: Type: Fix

#4234 chore(main): release 2.8.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#4308 fix(DTFS2-7852): fix checker can call getCheckersApprovalAmendmentDeal when feature flag is enabled
  portal/server/controllers/dashboard/deals/deals-filters-query.ff-test.js
  portal/server/controllers/dashboard/deals/deals-filters-query.js
  portal/server/controllers/dashboard/deals/deals-filters-query.test.js
Labels: Type: Fix

#4310 fix(FN-3923): added hyperlink check for a cell value
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fix
