Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-03, with the labels that each got.

#4242 fix(DTFS2-7842): graceful exceptional handling for TFM page
  dtfs-central-api/Dockerfile
  external-api/Dockerfile
  gef-ui/Dockerfile
  portal-api/Dockerfile
  portal/Dockerfile
  reverse-proxy/Dockerfile
  trade-finance-manager-api/Dockerfile
  trade-finance-manager-ui/Dockerfile
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
  trade-finance-manager-ui/server/controllers/helpers/dealsAndFacilities.helper.deals.test.js
  trade-finance-manager-ui/server/controllers/helpers/dealsAndFacilities.helper.facilities.test.js
  trade-finance-manager-ui/server/controllers/helpers/dealsAndFacilities.helper.js
Labels: Type: Fix

#4243 fix(DTFS2-7827): facilty covenant and guarantee amendment under feature flag
  azure-functions/acbs-function/src/functions/acbs-amend-facility.js
Labels: Type: Fix

#4247 chore(deps): dependencies updates
  dtfs-central-api/package.json
  e2e-tests/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: chore

#4248 chore(deps): dependencies updates
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  portal/package.json
  trade-finance-manager-ui/package.json
Labels: Type: chore

#4240 fix(DTFS2-7820): cancel deal hide clone button
  e2e-tests/portal/cypress/e2e/pages/cloneDeal.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/deal-cancellation-maker-unable-clone-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/deal-cancellation-maker-unable-clone-deal.spec.js
  gef-ui/component-tests/includes/application-details/applicationReferenceAndActions.component-test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/templates/includes/application-details/applicationReferenceAndActions.njk
  portal/component-tests/contract/components/clone-deal-link.component-test.js
  portal/server/routes/contract/index.js
  portal/templates/contract/components/clone-deal-link.njk
  portal/templates/contract/contract-view.njk
Labels: Type: Fix

#4251 fix(DTFS2-7813): estore payload sanitisation
  cspell.json
  libs/common/src/helpers/string.test.ts
  libs/common/src/helpers/string.ts
  trade-finance-manager-api/src/v1/helpers/formatNameForSharepoint.js
  trade-finance-manager-api/src/v1/mappings/map-create-estore.api-test.js
  trade-finance-manager-api/src/v1/mappings/map-create-estore.js
  trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.js
Labels: Type: Fix

#4253 feat(DTFS2-7846): acr purge github action
  .github/actions/acr/action.yml
  .github/actions/functions/action.yml
  .github/actions/mssql/action.yml
  .github/actions/notify/action.yml
  .github/actions/webapp/action.yml
  .github/workflows/README.md
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/feature.yml
  .github/workflows/purge.yml
  .github/workflows/release.yml
Labels: Type: Feature

#4261 fix(DTFS2-7846): feature deployment and ACR purge
  .github/workflows/feature.yml
  .github/workflows/purge.yml
  cspell.json
Labels: Type: Feature

#4257 fix(DTFS2-7825): added all 58 currencies to the currency type literal
  .github/workflows/feature.yml
  dtfs-central-api/src/v1/routes/middleware/payload-validation/schemas/currency.schema.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-facility-amendment-payload.ts
  e2e-tests/tfm/cypress/e2e/journeys/case-amendments/user-flow/9. facility-value-aud-currency.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/facility/facilities.spec.js
  e2e-tests/tfm/cypress/fixtures/deal-AIN.js
  e2e-tests/tfm/cypress/fixtures/deal-MIA.js
  external-api/src/external-api/countries.ts
  external-api/src/external-api/currencies.ts
  external-api/src/external-api/index.ts
  external-api/src/external-api/industry-sectors.ts
  external-api/src/helpers/array.api-test.ts
  external-api/src/helpers/array.test.ts
  external-api/src/helpers/array.ts
  external-api/src/interfaces/country.interface.ts
  external-api/src/interfaces/currency.interface.ts
  external-api/src/interfaces/index.ts
  external-api/src/interfaces/industry-sector.interface.ts
  external-api/src/v1/controllers/countries.controller.ts
  external-api/src/v1/controllers/currencies.controller.ts
  external-api/src/v1/controllers/industry-sectors.controller.ts
  libs/common/src/constants/currency.ts
  libs/common/src/constants/tfm/facility-stage.ts
  libs/common/src/helpers/map-currencies-to-radio-items.test.ts
  libs/common/src/index.ts
  libs/common/src/interfaces/country.ts
  libs/common/src/interfaces/currency.ts
  libs/common/src/interfaces/index.ts
  libs/common/src/interfaces/industry.ts
  libs/common/src/types/currency.ts
  trade-finance-manager-ui/server/controllers/case/index.js
  trade-finance-manager-ui/server/controllers/case/index.test.js
Labels: Type: Fix

#4262 feat(DTFS2-7834): standardised tag colours for E2ETF utilisation reports
  libs/common/src/constants/index.ts
  libs/common/src/constants/utilisation-report-status-tag-colours.ts
  libs/common/src/types/index.ts
  libs/common/src/types/status-tag-colours.ts
  portal/component-tests/utilisation-report-service/_macros/report-reconciliation-status.component-test.js
  portal/server/controllers/utilisation-report-service/previous-reports/helpers/previous-reports-view-model-mapper.test.ts
  portal/server/controllers/utilisation-report-service/previous-reports/helpers/previous-reports-view-model-mapper.ts
  portal/server/controllers/utilisation-report-service/previous-reports/index.test.ts
  portal/server/types/view-models/previous-reports.ts
  portal/templates/utilisation-report-service/previous-reports/_macros/report-reconciliation-status.njk
  portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/fee-record-status.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-status.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/record-correction-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/record-correction-log-details/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/record-correction-log-details/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-log-details-view-model.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/check-keying-data-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-details-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/fee-record-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/keying-sheet-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/premium-payments-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/partials/record-correction-log-html.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/record-correction-log-details.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/create-record-correction-log-details-view-model.ts
Labels: Type: Feature, Type: Fintech

#4263 chore(deps): dependencies updates
  .github/workflows/deployment.yml
  .github/workflows/feature.yml
  .github/workflows/purge.yml
  gef-ui/package.json
  package-lock.json
  package.json
  trade-finance-manager-ui/package.json
Labels: Type: chore

#4265 fix(DTFS2-7577): added timeout to heavy TFM API submission
  dtfs-central-api/package.json
  e2e-tests/ukef/cypress/e2e/journeys/utilisation-reports/utilisation-report-submission.spec.js
  external-api/package.json
  gef-ui/package.json
  gef-ui/server/services/api.js
  gef-ui/server/services/axios.js
  libs/common/src/constants/index.ts
  libs/common/src/constants/timeout.ts
  package-lock.json
  package.json
  portal-api/package.json
  portal-api/src/v1/api.js
  portal/package.json
  portal/server/routes/middleware/virusScanUpload/index.js
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: Fix

#4266 chore(deployment): updated deployment cron schedule
  .github/workflows/deployment.yml
  .github/workflows/feature.yml
  .github/workflows/purge.yml
Labels: Type: Fix

#4258 fix(DTFS2-6838): show validation errors on eligibility criteria page
  e2e-tests/portal/cypress/e2e/journeys/maker/eligibility/eligibility-criteria.spec.js
  e2e-tests/portal/cypress/e2e/journeys/maker/eligibility/eligibility-documentation.spec.js
  portal/server/routes/contract/eligibility/index.js
  portal/server/routes/contract/eligibility/index.test.js
Labels: Type: Bug

#4260 feat(DTFS2-7851): all deals GET endpoint for amendments in progress
  dtfs-central-api/api-tests/v1/portal-facility-amendments/all-amendments-get.api-test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.findAllPortalAmendmentsByStatus.test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-all-amendments.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/get-all-amendments.controller.ts
  dtfs-central-api/src/v1/routes/portal-routes.js
  portal-api/api-tests/v1/gef/amendments/all-amendments.get.api-test.ts
  portal-api/api-tests/v1/gef/amendments/amendment-urls.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/amendments/get-all-amendments.controller.ts
  portal-api/src/v1/controllers/amendments/get-all-amendments.test.ts
  portal-api/src/v1/gef/routes.js
Labels: Type: Feature

#4269 feat(DTFS2-7431): create new createBssEwcsDeal command
  .github/workflows/deployment.yml
  .github/workflows/feature.yml
  e2e-tests/portal/cypress/support/commands.js
  e2e-tests/portal/cypress/support/portal/click-events/click-dashboard-deal-link-by-index.js
  e2e-tests/portal/cypress/support/portal/createBssEwcsDeal.js
  e2e-tests/portal/cypress/support/portal/getDealIdFromUrl.js
  portal-api/api-tests/v1/gef/amendments/all-amendments.get.api-test.ts
Labels: Type: Feature

#4271 fix(DTFS2-7878): remove telephone number
  .env.sample
  docker-compose.yml
  e2e-tests/portal/cypress/e2e/journeys/login/reset-password.spec.js
  e2e-tests/portal/cypress/e2e/pages/user/changePassword.js
  gef-ui/component-tests/includes/contact-us.component-test.js
  gef-ui/templates/includes/contact-us.njk
  portal/component-tests/reset-password.component-test.js
  portal/component-tests/test-helpers/with-contact-us-email-address.component-tests.js
  portal/templates/_partials/contact-us.njk
Labels: Type: Feature

#4276 chore(7431): replace insertOneDeal with createBssEwcs function
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filter-by/dashboard-deals-filter-by-keyword.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filter-by/dashboard-deals-filter-by-notice-type.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filter-by/dashboard-deals-filter-by-status.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filters/dashboard-deals-filters.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filters/dashboard-deals-main-container-filter-remove.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filters/dashboard-deals-panel-filter-remove.spec.js
  e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/filters/dashboard-facilities-filters.spec.js
Labels: chore

#4282 feat(DTFS2-7885): portal amendments - add amendment details page
  cspell.json
  e2e-tests/gef/cypress/e2e/pages/amendments/amendment-shared.js
  e2e-tests/gef/cypress/e2e/pages/amendments/amendment-summary-list.js
  e2e-tests/gef/cypress/e2e/pages/amendments/check-your-answers.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/amendment-details.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/cancel-amendment-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-both-cover-end-date-and-facility-value.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-BRD-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-FED-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-facility-value-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/check-your-answers-change-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/check-your-answers.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/deal-summary-page-amendment-ready-for-checkers-approval.spec.js
  e2e-tests/ukef/cypress/fixtures/check-your-answers-change-journey.js
  e2e-tests/ukef/cypress/support/commands.js
  e2e-tests/ukef/cypress/support/gef/makerMakesPortalAmendmentRequest.js
  e2e-tests/ukef/cypress/support/gef/makerSubmitPortalAmendmentForReview.js
  gef-ui/component-tests/partials/amendments/amendment-details.component-test.ts
  gef-ui/server/constants/amendments.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.test.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.ts
  gef-ui/server/controllers/amendments/amendment-details/get-amendment-details.test.ts
  gef-ui/server/controllers/amendments/amendment-details/get-amendment-details.ts
  gef-ui/server/controllers/amendments/helpers/amendment-summary-view-model.helper.test.ts
  gef-ui/server/controllers/amendments/helpers/amendment-summary-view-model.helper.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/deal.ts
  gef-ui/server/types/view-models/amendments/amendment-details-view-model.ts
  gef-ui/templates/partials/amendments/amendment-details.njk
  libs/common/src/constants/amendments.ts
  libs/common/src/types/gov-uk/summary-list.ts
Labels: Type: Feature

#4283 fix(DTFS2-7521): correct validation error
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/facility-value.spec.js
  gef-ui/api-tests/amendments/facility-value.post.api-test.ts
  gef-ui/server/controllers/amendments/facility-value/validation.test.ts
  gef-ui/server/controllers/amendments/facility-value/validation.ts
Labels: Type: Fix
