Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-06, with the labels that each got.

#4327 fix(DTFS2-7953): acbs tfm reconciliation check
  .github/workflows/deployment.yml
  .github/workflows/feature.yml
  e2e-tests/e2e-fixtures/acbs.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-with-no-acbs-reconciliation.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/about-unissued-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/support/commands.js
  e2e-tests/gef/cypress/support/commands/api.js
  e2e-tests/gef/cypress/support/commands/update-tfm-deal.js
  gef-ui/server/controllers/application-details/canIssueUnissuedFacilities.js
  gef-ui/server/controllers/application-details/canIssueUnissuedFacilities.test.js
  gef-ui/server/controllers/application-details/canUpdateUnissuedFacilitiesCheck.js
  gef-ui/server/controllers/application-details/canUpdateUnissuedFacilitiesCheck.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/controllers/confirm-cover-start-date/index.test.js
  gef-ui/server/models/application.js
  gef-ui/server/services/__mocks__/api.js
  gef-ui/server/services/__tests__/api.test.js
  gef-ui/server/services/api.js
  gef-ui/server/utils/deal-helpers.js
  gef-ui/server/utils/facility-helpers.js
  gef-ui/server/utils/facility-helpers.test.js
  gef-ui/server/utils/helpers.js
  gef-ui/server/utils/helpers.test.js
  gef-ui/templates/includes/application-preview/task-comments.njk
  libs/common/src/constants/acbs-facility-stage.ts
  libs/common/src/constants/index.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/api.test.js
  portal-api/src/v1/controllers/tfm.controller.js
  portal-api/src/v1/controllers/tfm.controller.test.js
  portal-api/src/v1/routes.js
  portal-api/src/v1/validation/route-validators/express-validator-result-handler.ts
Labels: Type: Fix

#4336 feat(DTFS2-7870): set intial utilisation for GEF facility types
  .env.sample
  azure-functions/acbs-function/constants/facility.js
  azure-functions/acbs-function/mappings/facility/helpers/get-gef-facility-fixed-percentage.js
  azure-functions/acbs-function/mappings/facility/helpers/get-gef-facility-fixed-percentage.test.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
  azure-functions/acbs-function/mappings/facility/helpers/index.js
  gef-ui/package.json
  libs/common/src/constants/facility-utilisation-percentage.ts
  libs/common/src/constants/index.ts
  libs/common/src/helpers/facility-calculations/index.test.ts
  libs/common/src/helpers/facility-calculations/index.ts
  libs/common/src/helpers/is-production.ts
  package-lock.json
  portal-api/package.json
  portal/package.json
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
Labels: Type: Feature

#4319 feat(DTFS2-7787): middleware to stop access to amendment pages if unacceptable deal status
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-get-acknowledged.api-test.ts
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/access-amendment-url-with-invalid-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details-maker-cancelled-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-preview-checker-cancelled-deal.spec.js
  gef-ui/api-tests/amendments/approved-by-ukef.get.api-test.ts
  gef-ui/api-tests/amendments/bank-review-date.get.api-test.ts
  gef-ui/api-tests/amendments/cancel-portal-facility-amendment.get.api-test.ts
  gef-ui/api-tests/amendments/cancel-portal-facility-amendment.post.api-test.ts
  gef-ui/api-tests/amendments/check-your-answers.get.api-test.ts
  gef-ui/api-tests/amendments/check-your-answers.post.api-test.ts
  gef-ui/api-tests/amendments/cover-end-date.get.api-test.ts
  gef-ui/api-tests/amendments/create-draft.api-test.ts
  gef-ui/api-tests/amendments/do-you-have-a-facility-end-date.get.api-test.ts
  gef-ui/api-tests/amendments/effective-date.get.api-test.ts
  gef-ui/api-tests/amendments/eligibility.get.api-test.ts
  gef-ui/api-tests/amendments/facility-end-date.get.api-test.ts
  gef-ui/api-tests/amendments/facility-value.get.api-test.ts
  gef-ui/api-tests/amendments/manual-approval-needed.get.api-test.ts
  gef-ui/api-tests/amendments/returned-to-maker.get.api-test.ts
  gef-ui/api-tests/amendments/submitted-for-checking.get.api-test.ts
  gef-ui/api-tests/amendments/what-needs-to-change.get.api-test.ts
  gef-ui/server/middleware/index.js
  gef-ui/server/middleware/validateDealStatusForAmendment/index.test.ts
  gef-ui/server/middleware/validateDealStatusForAmendment/index.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  libs/common/src/constants/amendments.ts
Labels: Type: Feature

#4325 feat(DTFS2-7783): amendment reference number tfm
  dtfs-central-api/src/constants/amendments.ts
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments-by-deal-id.test.ts
  dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-facility-amendment-payload.ts
  libs/common/src/constants/amendments.ts
  trade-finance-manager-api/src/constants/amendments.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller-getAmendmentsByDealId.test.js
  trade-finance-manager-api/src/v1/controllers/amendment.controller.js
  trade-finance-manager-api/test-helpers/index.ts
  trade-finance-manager-api/test-helpers/test-data/index.ts
  trade-finance-manager-api/test-helpers/test-data/tfm-facility-amendment.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentAnswers.controller.js
  trade-finance-manager-ui/server/controllers/case/amendments/amendmentAnswers.post.test.js
Labels: Type: Feature

#4328 feat(DTFS2-7775-7722): add email variables when return to maker
  dtfs-central-api/src/constants/email-template-ids.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.ts
  gef-ui/server/controllers/amendments/helpers/map-return-to-maker-email-variables.test.ts
  gef-ui/server/controllers/amendments/helpers/map-return-to-maker-email-variables.ts
  gef-ui/server/controllers/amendments/return-amendment-to-maker/post-return-amendment-to-maker.test.ts
  gef-ui/server/controllers/amendments/return-amendment-to-maker/post-return-amendment-to-maker.ts
  gef-ui/server/services/api.js
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/portal-amendment-return-to-maker-email-variables.ts
  libs/common/src/types/portal/amendment.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/validation/route-validators/amendments/validate-patch-portal-facility-amendment-status-payload.ts
Labels: Type: Feature

#4333 feat(DTFS2-7758): changed to 1 amendment per facility
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-put.api-test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.findPortalAmendmentsByFacilityIdAndStatus.test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/services/portal/facility-amendment.returnPortalFacilityAmendmentToMaker.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.service.ts
  dtfs-central-api/src/services/portal/facility-amendment.submitPortalFacilityAmendmentToChecker.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.submitPortalFacilityAmendmentToUkef.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.upsertPortalFacilityAmendmentDraft.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.validateNoOtherAmendmentInProgress.service.test.ts
  e2e-tests/gef/cypress/e2e/pages/application-preview.js
  e2e-tests/gef/cypress/e2e/pages/application-status-banner.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/access-amendment-url-with-invalid-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/back-or-cancel-return-amendment-to-maker.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/return-amendment-to-maker-with-comments.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/return-amendment-to-maker-without-comment.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/submit-amendment-to-ukef-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-confirm-your-submission-to-ukef.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-details.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-return-to-maker.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-submitted-approved-by-ukef.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details-mixed-status-amendments.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details-multiple-further-makers-input-amendments.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details-multiple-ready-for-checkers-approval-amendments.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-preview-checker-cancelled-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/deal-summary-page-amendment-ready-for-checkers-approval.spec.js
  e2e-tests/ukef/cypress/support/gef/loginAndSubmitPortalAmendmentRequestToUkef.js
  e2e-tests/ukef/cypress/support/gef/submitToUkefMultipleAmendmentsOnFacility.js
  gef-ui/api-tests/amendments/amendment-details.get.api-test.ts
  gef-ui/component-tests/_macros/submitted-amendment-summary-list.component-test.ts
  gef-ui/component-tests/includes/application-preview/facilities.component-test.js
  gef-ui/component-tests/includes/application-preview/summary.component-test.js
  gef-ui/component-tests/includes/application-preview/task-comments.component-test.js
  gef-ui/server/controllers/amendments/amendment-details/get-amendment-details.test.ts
  gef-ui/server/controllers/amendments/amendment-details/get-amendment-details.ts
  gef-ui/server/controllers/amendments/submit-amendment-to-ukef/get-submit-amendment-to-ukef.ts
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
  gef-ui/server/controllers/confirm-cover-start-date/index.test.js
  gef-ui/server/controllers/mocks/index.js
  gef-ui/server/helpers/add-amendment-params-to-facility.test.ts
  gef-ui/server/helpers/add-amendment-params-to-facility.ts
  gef-ui/server/helpers/map-facility-application-details.test.ts
  gef-ui/server/helpers/map-facility-application-details.ts
  gef-ui/server/middleware/validateDealStatusForAmendment/index.test.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/facility.ts
  gef-ui/server/types/portal-amendments.ts
  gef-ui/server/utils/mocks/mock-applications.js
  gef-ui/templates/_macros/amendments/submitted-amendment-summary-list.njk
  gef-ui/templates/includes/application-preview/facilities.njk
  gef-ui/templates/includes/application-preview/summary.njk
  gef-ui/templates/includes/application-preview/task-comments.njk
  gef-ui/templates/partials/return-to-maker.njk
  libs/common/src/constants/amendments.ts
  libs/common/src/errors/portal-facility-amendment-conflict.error.test.ts
  libs/common/src/errors/portal-facility-amendment-conflict.error.ts
Labels: Type: Feature

#4343 fix(DTFS2-7986): getTfmDeal conditional check on portal
  azure-functions/acbs-function/tsconfig.json
  gef-ui/server/controllers/application-details/canIssueUnissuedFacilities.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/helpers/map-facility-application-details.ts
  gef-ui/tsconfig.json
  libs/common/src/helpers/has-been-submitted-to-tfm.test.ts
  libs/common/src/helpers/has-been-submitted-to-tfm.ts
  libs/common/src/helpers/index.ts
  libs/common/src/types/mongo-db-models/deals.ts
  portal/tsconfig.json
Labels: Type: Fix

#4344 fix(DTFS2-7995): fix getFacilities
  portal-api/src/v1/gef/controllers/facilities.controller.js
  portal-api/src/v1/gef/controllers/facilities.controller.test.js
Labels: Type: Bug

#4345 feat(DTFS2-7778): submit amendment further inputs required
  e2e-tests/gef/cypress/e2e/pages/amendments/amendment-shared.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/abandon-amendment.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-details-further-makers-input-required.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/amendment-details-ready-for-checkers-approval.spec.js
  gef-ui/component-tests/partials/amendments/amendment-details-further-makers-input-required.component-test.ts
  gef-ui/component-tests/partials/amendments/amendment-details-ready-for-checkers-approval.component-test.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.test.ts
  gef-ui/server/controllers/amendments/amendment-details/create-amendment-details-view-model.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/amendment-details-view-model.ts
  gef-ui/templates/includes/submit-amendment/submit-amendment-to-checker.njk
  gef-ui/templates/partials/amendments/amendment-details.njk
Labels: Type: Feature

#4351 chore(pr): update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: chore

#4353 fix(DTFS2-7871): facility amendment loan amount for GUP
  azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
  azure-functions/acbs-function/mappings/facility/helpers/get-loan-amount-difference.js
  dtfs-central-api/package.json
  external-api/package.json
  gef-ui/package.json
  libs/common/package.json
  mongodb/Dockerfile
  package-lock.json
  package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: Fix
