Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-08, with the labels that each got.

#4372 feat(DTFS2-8016): gef fixed fee calculation as per guarantee fee
  libs/common/src/helpers/facility-calculations/index.test.ts
  libs/common/src/helpers/facility-calculations/index.ts
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
  trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
  trade-finance-manager-api/src/v1/controllers/update-facilities.js
  trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js
  trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.test.js
Labels: Type: Feature

#4307 chore(main): release 2.9.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#4374 fix(DTFS2-8062): feature flag cypress test cases for fixed fee record correction
  .github/workflows/deployment.yml
  .github/workflows/feature.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  dtfs-central-api/package.json
  e2e-tests/gef/cypress/e2e/feature-flag-enabled/fee-record-correction/page-header.spec.js
  e2e-tests/gef/cypress/e2e/feature-flag-enabled/page-footer.spec.js
  e2e-tests/gef/cypress/e2e/homepage/page-footer.spec.js
  e2e-tests/gef/cypress/e2e/homepage/page-header.spec.js
  e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/content.spec.js
  e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/fee-record-correction/page-header.spec.js
  e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/page-footer.spec.js
  e2e-tests/portal/cypress/e2e/journeys/homepage/page-footer.spec.js
  e2e-tests/portal/cypress/e2e/journeys/homepage/page-header.spec.js
  external-api/package.json
  gef-ui/package.json
  gef-ui/templates/includes/header.njk
  libs/common/package.json
  package-lock.json
  portal-api/package.json
  portal/package.json
  portal/templates/_partials/header.njk
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
Labels: Type: Fix

#4377 fix(DTFS2-8016): revert fixed fee formula to interest percentage
  libs/common/src/helpers/facility-calculations/index.test.ts
  libs/common/src/helpers/facility-calculations/index.ts
  trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
Labels: Type: Fix

#4385 feat(DTFS2-8060): gef-ui broken CSS link
  gef-ui/component-tests/index/index.component-test.js
  gef-ui/server/controllers/application-details/index.buildBody.test.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/templates/index.njk
  portal/component-tests/index/index.component-test.js
Labels: Type: Fix

#4388 feat(DTFS2-7884-7924): e2e tests
  e2e-tests/gef/cypress/e2e/pages/application-amendments.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/return-amendment-to-maker-disabled-for-checker.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/portal/amendment-details-approved-amendment.spec.js
Labels: Type: Feature

#4390 fix(DTFS2-8073): fix checker unauthorised error on portal amendment deal
  portal-api/api-tests/v1/tfm/tfm-facility-get.api-test.ts
  portal-api/src/v1/routes.js
Labels: Type: Fix

#4381 feat(DTFS2-7930): updated TFM deal summary page if effective date has passed
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/tfm/tfm-latest-portal-amendment-future-effective-date.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/tfm/tfm-multiple-portal-amendments-latest-future-effective-date.spec.js
  e2e-tests/ukef/cypress/support/gef/loginAndSubmitPortalAmendmentRequestToUkef.js
  libs/common/src/helpers/index.ts
  trade-finance-manager-api/src/v1/rest-mappings/helpers/amendment.helpers.js
  trade-finance-manager-api/src/v1/rest-mappings/helpers/amendment.helpers.test.js
Labels: Type: Feature

#4393 chore(DTFS2-8075): fix flaky e2e tests
  e2e-tests/gef/cypress/e2e/application/application-activities-AIN.spec.js
  e2e-tests/gef/cypress/e2e/application/application-activities-MIA.spec.js
  e2e-tests/gef/cypress/e2e/maker/return-to-maker.spec.js
  e2e-tests/gef/cypress/support/commands.js
  e2e-tests/gef/cypress/support/utils/clearSessionCookies.js
  e2e-tests/tfm/cypress/e2e/journeys/deals/deals-sort-by-receivedDate-default-sort.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter/MIA-underwriter-managers-approved-decision-updates-portal-deal-and-submission-type-to-MIN/MIA-underwriter-managers-approved-decision-updates-portal-deal-and-submission-type-to-MIN.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-with-conditions-updates-portal-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-without-conditions-updates-portal-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/MIA-underwriter/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-refused-updates-portal-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-pending-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-pending-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/deal-cancellation-maker-unable-clone-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/deal-cancellation-maker-unable-issue-facility.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-pending-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-pending-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/deal-cancellation-maker-unable-clone-deal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/deal-cancellation-maker-unable-issue-facility.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN/submit-AIN-deal-creates-default-credit-rating-in-tfm/submit-AIN-deal-creates-default-credit-rating-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN/submit-AIN-deal-creates-tasks-in-tfm/submit-AIN-deal-creates-tasks-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN/submit-AIN-deal-creates-tfm-deal-stage-and-product/submit-AIN-deal-creates-tfm-deal-stage-and-product.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN/submit-AIN-deal-updates-portal-deal-status/submit-AIN-deal-updates-portal-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA/submit-MIA-deal-TFM-approves-resubmit-MIA-deal-becomes-MIN/submit-MIA-deal-TFM-approves-resubmit-MIA-deal-becomes-MIN.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA/submit-MIA-deal-creates-tasks-in-tfm/submit-MIA-deal-creates-tasks-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA/submit-MIA-deal-creates-tfm-deal-stage-and-product/submit-MIA-deal-creates-tfm-deal-stage-and-product.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIA/submit-MIA-deal-updates-portal-deal-status/submit-MIA-deal-updates-portal-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN/submit-MIN-changes-tfm-stage-to-confirmed/submit-MIN-changes-tfm-stage-to-confirmed.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN/submit-MIN-deal-does-not-create-credit-rating-in-tfm/submit-MIN-deal-does-not-create-credit-rating-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN/submit-MIN-deal-updates-portal-deal-status/submit-MIN-deal-updates-portal-deal-status.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-MIN/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-adds-risk-profile-to-facilities/submit-deal-adds-risk-profile-to-facilities.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-converts-contract-value-to-gbp/submit-deal-converts-contract-value-to-gbp.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-creates-loss-given-and-probability-defaults-in-tfm/submit-deal-creates-loss-given-and-probability-defaults-in-tfm.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-non-gbp-facilities/submit-deal-with-non-gbp-facilities.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued/submit-deal-with-unissued-bond-and-resubmit-as-issued.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/submit-deal/submit-deal-with-unissued-facilities-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued/submit-deal-with-unissued-loan-and-resubmit-as-issued.spec.js
Labels: Type: chore

#4394 fix(DTFS-8076): fix amendments tab visible with feature flag enabled
  gef-ui/component-tests/includes/application-preview/application-sub-navigation.component-test.ts
  gef-ui/server/controllers/activities-controller/index.ff-test.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/amendments/application-amendments/get-application-amendments.ff-test.ts
  gef-ui/server/controllers/amendments/application-amendments/get-application-amendments.ts
  gef-ui/server/controllers/application-details/index.js
  gef-ui/templates/includes/application-preview/application-sub-navigation.njk
Labels: Type: Bug

#4399 chore(deps): dependencies updates
  azure-functions/acbs-function/package.json
  dtfs-central-api/package.json
  gef-ui/package.json
  libs/common/package.json
  package-lock.json
  package.json
  portal/package.json
  trade-finance-manager-api/package.json
  trade-finance-manager-ui/package.json
  utils/package.json
Labels: Type: chore
