Repository UK-Export-Finance/dtfs2, pull requests merged in 2025-02, with the labels that each got.

#4195 fix(DTFS2-7798): remove duplicate createdBy in portal-amendments swagger definitions
  dtfs-central-api/src/v1/swagger-definitions/portal/portal-amendments.js
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
Labels: Type: Bug

#4185 feat(FN-3671): add bank correction history tab frontend
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.ts
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/correctionLog.js
  libs/common/package.json
  libs/common/src/change-stream/validate-audit-details.test.ts
  libs/common/src/constants/date-formats.ts
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/table-data-sort/get-key-to-date-sort-value-map-helper.test.ts
  libs/common/src/helpers/table-data-sort/get-key-to-date-sort-value-map-helper.ts
  libs/common/src/helpers/table-data-sort/index.ts
  package-lock.json
  portal/api-tests/utilisation-report-routes.api-test.js
  portal/component-tests/assertions.js
  portal/component-tests/partials/primary-navigation.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/_macros/correction-log-table.component-test.js
  portal/component-tests/utilisation-report-service/record-correction/correction-log.component-test.js
  portal/server/api-response-types/get-completed-fee-record-corrections-response-body.ts
  portal/server/api-response-types/index.ts
  portal/server/api.js
  portal/server/constants/primary-nav-key.ts
  portal/server/controllers/utilisation-report-service/record-correction/index.ts
  portal/server/controllers/utilisation-report-service/record-correction/record-correction-log/helpers.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/record-correction-log/helpers.ts
  portal/server/controllers/utilisation-report-service/record-correction/record-correction-log/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/record-correction-log/index.ts
  portal/server/nunjucks-configuration/index.js
  portal/server/routes/utilisation-report-service/record-correction/index.js
  portal/server/types/view-models/record-correction/record-correction-log.ts
  portal/templates/_partials/primary-navigation.njk
  portal/templates/utilisation-report-service/record-correction/_macros/correction-log-table.njk
  portal/templates/utilisation-report-service/record-correction/correction-log.njk
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
Labels: Type: Feature, Type: Fintech

#4186 feat(FN-3805): support actions to fee with TO_DO_AMENDED status
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/remove-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/remove-from-payment-group/remove-from-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/helpers.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-selected-fee-records-details.controller/helpers.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/fee-record-validator.test.ts
  dtfs-central-api/src/v1/validation/utilisation-report-service/fee-record-validator.ts
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-corrections.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-request-submission-going-back.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/to-do-amended-actions/add-corrected-fee-to-existing-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/to-do-amended-actions/add-payment-to-corrected-fee.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/to-do-amended-actions/delete-payment-from-corrected-fee.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/to-do-amended-actions/remove-corrected-fee-from-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/to-do-amended-actions/request-correction-for-corrected-fee.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/delete-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/edit-payment.spec.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/remove-fees-from-payment.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportConfirmDeletePaymentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportEditPaymentPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/addPaymentToFeeRecords.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/fee-record-correction/completeAndSubmitFeeRecordCorrectionRequestForm.js
  e2e-tests/tfm/cypress/support/ui/utilisation-report/index.js
  libs/common/src/helpers/fee-record-status.test.ts
  libs/common/src/helpers/fee-record-status.ts
  libs/common/src/helpers/index.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.test.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
  libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/initiate-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/initiate-record-correction-request/index.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.test.ts
  trade-finance-manager-ui/server/middleware/validatePostAddPaymentRequestBody/index.ts
Labels: Type: Feature, Type: Fintech

#4200 fix(FN-3685): remove parallel db calls within transactions
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/add-a-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-fees-to-an-existing-payment-group/add-fees-to-an-existing-payment-group.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/delete-payment/delete-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/edit-payment/edit-payment.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-ready-to-key/mark-fee-records-as-ready-to-key.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/mark-fee-records-as-reconciled/mark-fee-records-as-reconciled.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/remove-fees-from-payment-group/remove-fees-from-payment-group.event-handler.ts
  libs/common/src/helpers/fee-record-status.test.ts
Labels: Type: Fintech

#4192 feat(FN-3671): add bank correction history tab e2e tests
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/correction-log.spec.js
  e2e-tests/portal/cypress/e2e/pages/index.js
  e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/correctionHistory.js
Labels: Type: Feature, Type: Fintech

#4196 feat(FN-3737): clear old record correction transient form data (portal)
  dtfs-central-api/src/cron-scheduler-jobs/delete-correction-and-correction-request-transient-form-data/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/delete-correction-and-correction-request-transient-form-data/index.ts
  dtfs-central-api/src/cron-scheduler-jobs/delete-correction-request-transient-form-data/index.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/delete-correction-request-transient-form-data/index.ts
  dtfs-central-api/src/cron-scheduler-jobs/index.ts
  dtfs-central-api/src/repositories/fee-record-correction-transient-form-data-repo/fee-record-correction-transient-form-data.repo.ts
Labels: Type: Feature, Type: Fintech

#4179 feat(DTFS2-7730): delete amendment endpoint dtfs central api
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-delete.api-test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.deletePortalFacilityAmendment.test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/v1/controllers/portal/facility/delete-amendment.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/delete-amendment.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-delete-portal-facility-amendment-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-delete-portal-facility-amendment-payload.ts
  dtfs-central-api/src/v1/routes/portal-routes.js
Labels: Type: Feature

#4189 feat(DTFS2-7781): add effective from date e2e tests
  e2e-tests/gef/cypress/e2e/pages/amendments/effective-date.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-both-cover-end-date-and-facility-value.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-BRD-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-FED-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-facility-value-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/effective-date.spec.js
  gef-ui/api-tests/amendments/effective-date.post.api-test.ts
  gef-ui/component-tests/partials/amendments/effective-date.component-test.ts
  gef-ui/server/controllers/amendments/effective-date/get-effective-date.test.ts
  gef-ui/server/controllers/amendments/effective-date/get-effective-date.ts
  gef-ui/server/controllers/amendments/effective-date/post-effective-date.test.ts
  gef-ui/server/controllers/amendments/effective-date/post-effective-date.ts
  gef-ui/server/controllers/amendments/effective-date/validation.test.ts
  gef-ui/server/controllers/amendments/effective-date/validation.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/types/view-models/amendments/effective-date-view-model.ts
  gef-ui/templates/partials/amendments/effective-date.njk
  gef-ui/test-helpers/mock-amendment.ts
  libs/common/src/constants/portal/date-validation.ts
  libs/common/src/schemas/portal-amendment.ts
Labels: Test

#4205 docs(FN-3823): add fee record state machine diagram
  doc/assets/fee-record-state-machine.drawio
  doc/assets/fee-record-state-machine.png
  doc/state-machines.md
Labels: Type: Docs, Type: Fintech

#4206 feat(FN-3615): set up endpoints and template for record correction details
  dtfs-central-api/api-tests/v1/utilisation-reports/get-record-correction-log-details.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-record-correction-log-details.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-record-correction-log-details.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-record-correction-details.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-date-received-and-bank-commentary.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-date-received-and-bank-commentary.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-formatted-old-and-correct-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-formatted-old-and-correct-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-record-correction-fields.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-record-correction-fields.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-log-details.js
  libs/common/src/test-helpers/mock-data/fee-record-correction.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/mock-data/record-correction-log-details.mock.ts
  libs/common/src/types/index.ts
  libs/common/src/types/record-correction-fields.ts
  libs/common/src/types/record-correction-log.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-record-correction-log-details-by-id.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/get-record-correction-log-details-by-id.controller.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/fee-record-correction/index.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/record-correction-log-details.component-test.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/record-correction-log-details/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/record-correction-log-details/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-log-details-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-status.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/record-correction-log-details.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/create-record-correction-log-details-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/index.ts
Labels: Type: Feature, Type: Fintech

#4212 fix(DTFS2-7804): updated property name to facility identifier
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
Labels: Type: Fix

#4193 feat(DTFS2-7793): add update amendment status endpoint to dtfs-central
  dtfs-central-api/api-tests/helpers/create-portal-facility-amendment.ts
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-patch.api-test.ts
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-status-patch.api-test.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
  dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.updatePortalFacilityAmendmentByAmendmentId.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.generatePortalFacilityAmendment.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.service.ts
  dtfs-central-api/src/services/portal/facility-amendment.submitPortalFacilityAmendmentToChecker.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.updatePortalFacilityAmendmentUserValues.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.validateAmendmentIsComplete.service.test.ts
  dtfs-central-api/src/services/portal/facility-amendment.validateNoOtherAmendmentsUnderWayOnDeal.service.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.ts
  dtfs-central-api/src/v1/routes/portal-routes.js
  gef-ui/server/controllers/amendments/bank-review-date/get-bank-review-date.ts
  gef-ui/server/controllers/amendments/do-you-have-a-facility-end-date/get-do-you-have-a-facility-end-date.ts
  gef-ui/server/controllers/amendments/facility-end-date/get-facility-end-date.ts
  gef-ui/server/types/view-models/amendments/bank-review-date-view-model.ts
  gef-ui/server/types/view-models/amendments/facility-end-date-view-model.ts
  libs/common/src/errors/amendment-incomplete.error.test.ts
  libs/common/src/errors/amendment-incomplete.error.ts
  libs/common/src/errors/amendment-not-found.error.test.ts
  libs/common/src/errors/index.ts
  libs/common/src/schemas/portal-amendment.ts
  libs/common/src/test-helpers/mock-data-backend/portal-facility-amendment.ts
  libs/common/src/types/mongo-db-models/tfm-facilities.ts
  portal-api/src/v1/validation/route-validators/amendments/validate-patch-portal-facility-amendment-payload.test.ts
  portal-api/src/v1/validation/route-validators/amendments/validate-put-portal-facility-amendment-payload.test.ts
Labels: Type: Feature

#4208 feat(FN-3724): record correction request design iteration
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-form.spec.js
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/create-record-correction-request.component-test.ts
  trade-finance-manager-ui/public/css/styles.css
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/helpers/get-record-correction-request-cancel-link-href.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/helpers/get-record-correction-request-cancel-link-href.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/helpers/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/create-record-correction-request-view-model.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-request-information-view-model.ts
  trade-finance-manager-ui/styles/fee-record-summary.scss
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/_macros/fee-record-summary.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/create-record-correction-request.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/create-record-correction-request-view-model.ts
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/record-correction-request-information-view-model.ts
Labels: Type: Feature, Type: Fintech

#4197 feat(DTFS2-7731): delete amendment endpoint portal api
  gef-ui/server/services/__mocks__/api.js
  gef-ui/server/services/__tests__/api.test.js
  gef-ui/server/services/api.js
  portal-api/api-tests/v1/gef/amendments/amendment-urls.ts
  portal-api/api-tests/v1/gef/amendments/amendments.delete.api-test.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/amendments/delete-amendment.controller.ts
  portal-api/src/v1/controllers/amendments/delete-amendment.test.ts
  portal-api/src/v1/gef/routes.js
Labels: Type: Feature

#4216 feat(DTFS2-7512): add submitted for checking page
  gef-ui/api-tests/amendments/submitted-for-checking.get.api-test.ts
  gef-ui/component-tests/partials/amendments/submitted-for-checking.component-test.ts
  gef-ui/server/constants/amendments.ts
  gef-ui/server/controllers/amendments/submitted-for-checking/get-submitted-for-checking.test.ts
  gef-ui/server/controllers/amendments/submitted-for-checking/get-submitted-for-checking.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/templates/partials/amendments/submitted-for-checking.njk
  gef-ui/test-helpers/mock-amendment.ts
Labels: Type: Feature

#4214 feat(FN-3671): fix portal "record correction log" table sorting
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/correction-log.spec.js
  portal/component-tests/utilisation-report-service/record-correction/_macros/correction-log-table.component-test.js
  portal/templates/utilisation-report-service/record-correction/_macros/correction-log-table.njk
Labels: Type: Feature, Type: Fintech

#4175 fix(DTFS2-7748): created facility stage helper
  .env.sample
  gef-ui/server/controllers/submit-to-ukef/index.js
  libs/common/src/constants/portal/facility-stage.ts
  libs/common/src/types/portal/dashboard.ts
  libs/common/src/types/portal/facility-stage.ts
  libs/common/src/types/portal/index.ts
  portal-api/src/v1/controllers/facilities.controller.js
  portal/component-tests/contract/contract-submission-details.component-test.js
  portal/component-tests/fixtures/deal-fully-completed.js
  portal/server/controllers/dashboard/facilities/index.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/helpers/index.js
  portal/server/helpers/map-facility-properties.test.ts
  portal/server/helpers/map-facility-properties.ts
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
  trade-finance-manager-api/src/v1/__mocks__/mock-durable-tasks.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.test.js
  trade-finance-manager-ui/component-tests/_macros/success-banner.component-test.js
Labels: Type: Fix

#4215 fix(FN-3843): fix record correction "bank commentary" being stored as an empty string
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/delete-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-review.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/get-fee-record-correction-transient-form-data.api-test.ts
  dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction.api-test.ts
  dtfs-central-api/src/helpers/get-correction-corrected-values-from-form-data.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/event-handlers/correction-received/correction-received.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/fee-record/fee-record.state-machine.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/format-form-data-value-for-reason.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-form-data-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/helpers/map-transient-correction-data-to-review-info.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-review.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/parse-record-correction-transient-form-values.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/helpers/parse-record-correction-transient-form-values.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.test.ts
  libs/common/src/test-helpers/index.ts
  libs/common/src/test-helpers/mock-data/fee-record-correction-transient-form-data.entity.mock-builder.ts
  libs/common/src/test-helpers/record-correction-transient-form-data.ts
  libs/common/src/types/fee-record-correction-review-information.ts
  libs/common/src/types/record-correction-transient-form-data.ts
  portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction-transient-form-data.controller.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.test.ts
  portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts
Labels: Type: Bug, Type: Fintech

#4213 feat(FN-3615): add links, e2e tests, and refactor pdc record correction log
  dtfs-central-api/api-tests/v1/utilisation-reports/get-record-correction-log-details.api-test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-record-correction-log-details.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/get-record-correction-log-details.controller/index.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-record-correction-fields.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-record-correction-fields.ts
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/fee-record-correction-log-details.js
  e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-log-details.spec.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/fee-record-correction/feeRecordCorrectionLogDetailsPage.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/index.js
  e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
  libs/common/src/test-helpers/mock-data/fee-record-correction.entity.mock-builder.ts
  libs/common/src/test-helpers/mock-data/record-correction-log-details.mock.ts
  libs/common/src/types/record-correction-fields.ts
  libs/common/src/types/record-correction-log.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/record-correction-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/record-correction-log-details.component-test.ts
  trade-finance-manager-ui/server/constants/reconciliation-for-report-tabs.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/record-correction-log-details/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/record-correction-log-details/index.ts
  trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-log-details-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/record-correction-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/record-corrections/record-correction-log-details.njk
  trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/create-record-correction-log-details-view-model.ts
Labels: Type: Feature, Type: Fintech

#4204 feat(DTFS2-7494): hide change button when amendment underway
  gef-ui/server/services/__mocks__/api.js
  gef-ui/server/services/__tests__/api.test.js
  gef-ui/server/services/api.js
  gef-ui/server/utils/facility-amendments.helper.ts
  portal-api/api-tests/v1/gef/amendments/amendment-urls.ts
  portal-api/api-tests/v1/gef/amendments/amendmentsOnDeal.get.api-test.ts
  portal-api/src/v1/api.js
  portal-api/src/v1/controllers/amendments/get-amendments-on-deal.controller.ts
  portal-api/src/v1/controllers/amendments/get-amendments-on-deal.test.ts
  portal-api/src/v1/gef/routes.js
Labels: Type: Feature

#4217 feat(DTFS2-7796): post check your answers page
  dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-status-patch.api-test.ts
  dtfs-central-api/src/services/portal/facility-amendment.service.ts
  dtfs-central-api/src/services/portal/facility-amendment.submitPortalFacilityAmendmentToChecker.service.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.test.ts
  dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.test.ts
  dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.ts
  dtfs-central-api/src/v1/routes/portal-routes.js
  gef-ui/api-tests/amendments/check-your-answers.post.api-test.ts
  gef-ui/server/controllers/amendments/check-your-answers/post-check-your-answers.test.ts
  gef-ui/server/controllers/amendments/check-your-answers/post-check-your-answers.ts
  gef-ui/server/controllers/amendments/helpers/navigation.helper.getNextPage.test.ts
  gef-ui/server/controllers/amendments/helpers/navigation.helper.getPreviousPage.test.ts
  gef-ui/server/controllers/amendments/helpers/navigation.helper.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  gef-ui/server/services/api.js
  portal-api/src/v1/api.js
Labels: Type: Feature

#4201 chore(FN-3588): remove payment reconciliation FF
  .env.sample
  .github/workflows/test.yml
  doc/state-machines.md
  docker-compose.yml
  dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-completed/manually-set-completed.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/index.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event-type.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/event/utilisation-report.event.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
  dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.ts
  dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
  dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-report.js
  libs/common/src/helpers/index.ts
  libs/common/src/helpers/is-feature-flag-enabled.test.ts
  libs/common/src/helpers/is-feature-flag-enabled.ts
  libs/common/src/types/utilisation-reports.ts
  trade-finance-manager-api/api-tests/v1/utilisation-reports/update-utilisation-report-service.api-test.ts
  trade-finance-manager-api/src/v1/__mocks__/api.js
  trade-finance-manager-api/src/v1/api.js
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/update-utilisation-report-status.controller.test.ts
  trade-finance-manager-api/src/v1/controllers/utilisation-reports/update-utilisation-report-status.controller.ts
  trade-finance-manager-api/src/v1/routes.js
  trade-finance-manager-api/src/v1/validation/route-validators/route-validators.js
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.test.ts
  trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table-manual-reconciliation.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.ts
  trade-finance-manager-ui/component-tests/utilisation-reports/_macros/search-reports-table.component-test.js
  trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/constants/bank-reports-for-period-table-header-prefix.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
  trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
  trade-finance-manager-ui/server/middleware/index.ts
  trade-finance-manager-ui/server/middleware/validateTfmPaymentReconciliationFeatureFlagIsEnabled/index.test.ts
  trade-finance-manager-ui/server/middleware/validateTfmPaymentReconciliationFeatureFlagIsEnabled/index.ts
  trade-finance-manager-ui/server/middleware/validateTfmPaymentReconciliationFeatureFlagIsNotEnabled/index.test.ts
  trade-finance-manager-ui/server/middleware/validateTfmPaymentReconciliationFeatureFlagIsNotEnabled/index.ts
  trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-reports-by-bank-and-year-view-model.ts
  trade-finance-manager-ui/server/types/view-models/utilisation-reports-view-model.ts
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table-manual-reconciliation.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/_macros/search-reports-table.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports-by-bank-and-year-results.njk
  trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports-manual-reconciliation.njk
Labels: chore, Type: Fintech

#4222 feat(DTFS2-7797): add check your answers e2e tests
  e2e-tests/gef/cypress/e2e/pages/amendments/check-your-answers.js
  e2e-tests/gef/cypress/e2e/pages/amendments/submitted-for-checking.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-both-cover-end-date-and-facility-value.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-BRD-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-FED-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-facility-value-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/check-your-answers.spec.js
  gef-ui/component-tests/_macros/amendment-summary-list.component-test.ts
  gef-ui/component-tests/partials/amendments/check-your-answers.component-test.ts
  gef-ui/templates/_macros/amendments/amendment-summary-list.njk
Labels: Test

#4223 feat(DTFS2-7810): release-2.7 deployment to feature environment
  .github/workflows/feature.yml
Labels: Type: Feature

#4224 feat(DTFS2-7494): add ui logic to show or hide make a change button
  e2e-tests/e2e-fixtures/mock-gef-facilities.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-bank-review-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-facility-end-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/about-unissued-facility.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
  e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details.spec.js
  gef-ui/server/controllers/application-details/index.js
  gef-ui/server/controllers/application-details/index.test.js
Labels: Type: Feature

#4225 feat(FN-3615): fix correction date received formatting
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-date-received-and-bank-commentary.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-date-received-and-bank-commentary.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-formatted-date-received-and-bank-commentary.test.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-formatted-date-received-and-bank-commentary.ts
  dtfs-central-api/src/v1/controllers/utilisation-report-service/helpers/get-record-correction-fields.ts
Labels: Type: Feature, Type: Fintech

#4052 feat(DTFS2-6892): update tfm ui to save token
  libs/common/src/schemas/tfm/handle-sso-redirect-form-request.schema.test.ts
  libs/common/src/schemas/tfm/handle-sso-redirect-form-response.schema.ts
  libs/common/src/schemas/tfm/index.ts
  libs/common/src/schemas/tfm/tfm-session-user.schema.test.ts
  libs/common/src/test-helpers/mock-builders/mock-builder.mock.builder.ts
  libs/common/src/test-helpers/mock-data/get-auth-code-url-response.mock.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/test-helpers/schemas/schema-tests/index.ts
  libs/common/src/test-helpers/schemas/schema-tests/with-tfm-session-user-schema.tests.ts
  libs/common/src/test-helpers/schemas/test-cases/test-case.ts
  libs/common/src/test-helpers/schemas/tests/with-tests-for-testcase.ts
  libs/common/src/types/tfm/handle-sso-redirect-form.ts
  package-lock.json
  trade-finance-manager-api/src/v1/__mocks__/builders/extra-id.service.mock.builder.ts
  trade-finance-manager-api/src/v1/__mocks__/builders/user.service.mock.builder.ts
  trade-finance-manager-api/src/v1/controllers/sso.controller.get-auth-code-url.test.ts
  trade-finance-manager-api/src/v1/controllers/sso.controller.handle-sso-redirect-form.test.ts
  trade-finance-manager-api/src/v1/services/entra-id.service.get-auth-code-url.test.ts
  trade-finance-manager-api/src/v1/services/user.service.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/api.test.js
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-logout.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.handle-sso-redirect-form.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
  trade-finance-manager-ui/server/helpers/express-session.as-a-partially-logged-in-user-session.test.ts
  trade-finance-manager-ui/server/helpers/express-session.as-a-user-session.test.ts
  trade-finance-manager-ui/server/helpers/express-session.assert-partially-logged-in-user.test.ts
  trade-finance-manager-ui/server/helpers/express-session.ts
  trade-finance-manager-ui/server/routes/auth/configs/auth-sso.ts
  trade-finance-manager-ui/server/routes/auth/configs/index.get-auth-router.test.ts
  trade-finance-manager-ui/server/routes/auth/configs/index.ts
  trade-finance-manager-ui/server/routes/auth/index.ts
  trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
  trade-finance-manager-ui/server/services/login.service.handle-sso-redirect-form.test.ts
  trade-finance-manager-ui/server/services/login.service.ts
  trade-finance-manager-ui/server/services/user-session.service.create-logged-in-session.test.ts
  trade-finance-manager-ui/server/services/user-session.service.create-partially-logged-in-session.test.ts
  trade-finance-manager-ui/server/services/user-session.service.ts
  trade-finance-manager-ui/server/types/express-session.d.ts
  trade-finance-manager-ui/test-helpers/mocks/index.ts
  trade-finance-manager-ui/test-helpers/mocks/login.service.mock.builder.ts
  trade-finance-manager-ui/test-helpers/mocks/user-session.service.mock.builder.ts
  trade-finance-manager-ui/test-helpers/test-data/handle-sso-redirect-form-request.ts
  trade-finance-manager-ui/test-helpers/test-data/handle-sso-redirect-form-response.ts
  trade-finance-manager-ui/test-helpers/test-data/index.ts
Labels: Type: Feature

#4194 feat(DTFS2-6892): add redirect to previous page on log in
  libs/common/src/test-helpers/mock-builders/mock-builder.mock.builder.ts
  libs/common/src/test-helpers/mock-data/authorisation-url-request.mock.ts
  libs/common/src/test-helpers/mock-data/get-auth-code-url-request.ts
  libs/common/src/test-helpers/mock-data/index.ts
  libs/common/src/types/tfm/get-auth-code.ts
  trade-finance-manager-api/src/v1/controllers/sso.controller.get-auth-code-url.test.ts
  trade-finance-manager-api/src/v1/controllers/sso.controller.ts
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-login.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.get-logout.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.handle-sso-redirect-form.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
  trade-finance-manager-ui/server/middleware/user-validation.js
  trade-finance-manager-ui/server/middleware/user-validation.test.ts
  trade-finance-manager-ui/server/middleware/user-validation.ts
  trade-finance-manager-ui/server/routes/auth/configs/unauthenticated-auth-sso.ts
  trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
  trade-finance-manager-ui/server/services/login.service.get-auth-code-url.test.ts
  trade-finance-manager-ui/server/services/login.service.handle-sso-redirect-form.test.ts
  trade-finance-manager-ui/server/services/login.service.ts
  trade-finance-manager-ui/server/services/user-session.service.create-logged-in-session.test.ts
  trade-finance-manager-ui/server/services/user-session.service.create-partially-logged-in-session.test.ts
  trade-finance-manager-ui/server/services/user-session.service.ts
  trade-finance-manager-ui/test-helpers/mocks/index.ts
  trade-finance-manager-ui/test-helpers/mocks/login.service.mock.builder.ts
  trade-finance-manager-ui/test-helpers/mocks/user-session.service.mock.builder.ts
  trade-finance-manager-ui/test-helpers/test-data/a-request-session.ts
  trade-finance-manager-ui/test-helpers/test-data/index.ts
  trade-finance-manager-ui/test-helpers/test-data/partially-logged-in-session.ts
Labels: Type: Feature

#4166 feat(dtfs2-6892): fixes to sso following local running
  docker-compose.yml
  libs/common/src/schemas/tfm/entra-id-user-to-upsert-tfm-user-request.schema.test.ts
  libs/common/src/schemas/tfm/entra-id-user-to-upsert-tfm-user-request.schema.ts
  libs/common/src/schemas/tfm/entra-id-user.schema.ts
  libs/common/src/test-helpers/mock-data/entra-id-user.ts
  libs/common/src/test-helpers/schemas/schema-tests/with-entra-id-user-schema.tests.ts
  package-lock.json
  trade-finance-manager-api/src/v1/controllers/sso.controller.ts
  trade-finance-manager-api/src/v1/repo/user.repo.ts
  trade-finance-manager-api/src/v1/services/entra-id.service.ts
  trade-finance-manager-api/src/v1/services/user.service.ts
  trade-finance-manager-api/src/v1/services/user.service.upsert-user-from-entra-id-user.test.ts
  trade-finance-manager-ui/package.json
  trade-finance-manager-ui/public/js/govukFrontend.js.map
  trade-finance-manager-ui/server/api.js
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.post-sso-redirect.test.ts
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
  trade-finance-manager-ui/server/generateApp.js
  trade-finance-manager-ui/server/routes/auth/configs/unauthenticated-auth-sso.ts
  trade-finance-manager-ui/server/routes/index.js
  trade-finance-manager-ui/server/session-configuration/index.js
  trade-finance-manager-ui/templates/auth/accept-sso-redirect.njk
Labels: Type: Feature

#4199 feat(DTFS2-7733): post cancel amendment
  gef-ui/api-tests/amendments/cancel-portal-facility-amendment.get.api-test.ts
  gef-ui/api-tests/amendments/cancel-portal-facility-amendment.post.api-test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/get-cancel-portal-facility-amendment.test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/get-cancel-portal-facility-amendment.ts
  gef-ui/server/controllers/amendments/cancel-amendment/post-cancel-portal-facility-amendment.test.ts
  gef-ui/server/controllers/amendments/cancel-amendment/post-cancel-portal-facility-amendment.ts
  gef-ui/server/routes/facilities/amendments/index.ts
  libs/common/src/middleware/index.ts
  libs/common/src/middleware/validate-mongoId/index.ts
  libs/common/src/middleware/validate-mongoId/validate-mongoId.test.ts
  libs/common/src/middleware/validate-mongoId/validate-mongoId.ts
Labels: Type: Feature

#4211 feat(DTFS2-6892): add validation on sso endpoint
  libs/common/src/schemas/tfm/get-auth-code-params.schema.test.ts
  libs/common/src/schemas/tfm/get-auth-code-params.schema.ts
  libs/common/src/schemas/tfm/get-auth-code-request.schema.test.ts
  libs/common/src/schemas/tfm/get-auth-code-request.schema.ts
  libs/common/src/schemas/tfm/index.ts
  libs/common/src/test-helpers/mock-builders/mock-builder.mock.builder.ts
  libs/common/src/types/tfm/get-auth-code.ts
  trade-finance-manager-api/src/v1/controllers/sso.controller.ts
  trade-finance-manager-api/src/v1/middleware/validate-get-auth-code-url-payload.test.ts
  trade-finance-manager-api/src/v1/middleware/validate-get-auth-code-url-payload.ts
  trade-finance-manager-api/src/v1/services/entra-id.service.ts
  trade-finance-manager-api/src/v1/sso/routes.ts
  trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.handle-sso-redirect-form.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.post-sso-redirect.test.ts
  trade-finance-manager-ui/server/controllers/login/login-sso/login.controller.ts
  trade-finance-manager-ui/server/generateApp.js
  trade-finance-manager-ui/server/middleware/user-validation.test.ts
  trade-finance-manager-ui/server/routes/auth/configs/index.get-auth-router.test.ts
  trade-finance-manager-ui/server/routes/auth/configs/index.ts
  trade-finance-manager-ui/server/routes/auth/index.ts
  trade-finance-manager-ui/server/routes/login/configs/auth-sso.ts
  trade-finance-manager-ui/server/routes/login/configs/index.get-login-router.test.ts
  trade-finance-manager-ui/server/routes/login/configs/index.get-unauthenticated-auth-router.test.ts
  trade-finance-manager-ui/server/routes/login/configs/index.ts
  trade-finance-manager-ui/server/routes/login/configs/unauthenticated-login-sso.ts
  trade-finance-manager-ui/server/routes/login/index.ts
  trade-finance-manager-ui/server/services/user-session.service.ts
Labels: Type: Feature

#3929 chore(main): release 2.6.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#4229 fix(DTFS2-7748): created facility stage helper
  .env.sample
  gef-ui/server/controllers/submit-to-ukef/index.js
  libs/common/src/constants/portal/facility-stage.ts
  libs/common/src/types/portal/dashboard.ts
  libs/common/src/types/portal/facility-stage.ts
  libs/common/src/types/portal/index.ts
  portal-api/src/v1/controllers/facilities.controller.js
  portal/component-tests/contract/contract-submission-details.component-test.js
  portal/component-tests/fixtures/deal-fully-completed.js
  portal/server/controllers/dashboard/facilities/index.js
  portal/server/controllers/dashboard/facilities/index.test.js
  portal/server/helpers/index.js
  portal/server/helpers/map-facility-properties.test.ts
  portal/server/helpers/map-facility-properties.ts
  portal/templates/dashboard/_macros/dashboard-facilities-table.njk
  trade-finance-manager-api/src/v1/__mocks__/mock-durable-tasks.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.js
  trade-finance-manager-api/src/v1/controllers/acbs.controller.test.js
  trade-finance-manager-ui/component-tests/_macros/success-banner.component-test.js
Labels: Type: Fix

#4231 chore(main): release 2.7.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#4230 chore(merge): merge release-2.5.2 to main
  CHANGELOG.md
  e2e-tests/e2e-fixtures/dateConstants.js
  e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
Labels: Type: chore

#4221 feat(DTFS2-7732): cancel amendment e2e tests
  e2e-tests/gef/cypress/e2e/pages/amendments/cancel.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/cancel-amendment-journey.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-both-cover-end-date-and-facility-value.spec.js
  e2e-tests/ukef/cypress/support/commands.js
  e2e-tests/ukef/cypress/support/utils/getAmendmentIdFromUrl.js
Labels: Type: Feature

#4233 chore(merge): merge release-2.5.2 to release-2.7.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Type: chore

#4236 fix(DTFS2-7819): fix rich text bug on report upload
  cspell.json
  e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/upload-report-with-rich-text.spec.js
  e2e-tests/portal/cypress/fixtures/invalid-utilisation-report-February_2023_monthly-rich-text.xlsx
  portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.ts
  portal/server/utils/csv-utils.js
  portal/server/utils/csv-utils.test.js
Labels: Type: Fix, Type: Fintech

#4237 fix(DTFS2-7741): fixed deal cancellation portal activities
  .env.sample
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.test.ts
  dtfs-central-api/src/cron-scheduler-jobs/deal-cancellation/cancel-deal-job.ts
  dtfs-central-api/src/services/portal/deal.service.add-gef-deal-cancellation-pending-activity.test.ts
  dtfs-central-api/src/services/portal/deal.service.add-gef-deal-cancelled-activity.test.ts
  dtfs-central-api/src/services/portal/deal.service.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.processPendingCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
  dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
  dtfs-central-api/src/v1/routes/middleware/rateLimit/index.js
  e2e-tests/gef/cypress/.DS_Store
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-pending-cancellation-updates-portal.spec.js
  e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-pending-cancellation-updates-portal.spec.js
  external-api/src/middleware/rateLimit/index.ts
  gef-ui/component-tests/partials/application-activity.component-test.js
  gef-ui/server/controllers/activities-controller/index.js
  gef-ui/server/controllers/activities-controller/index.test.js
  gef-ui/server/middleware/rateLimit/index.js
  gef-ui/templates/_macros/application-activity/activity-html.njk
  gef-ui/templates/_macros/application-activity/deal-cancelled.njk
  gef-ui/templates/_macros/application-activity/status-change.njk
  gef-ui/templates/partials/application-activity.njk
  libs/common/src/constants/portal/activity.ts
  libs/common/src/helpers/date.test.ts
  libs/common/src/helpers/date.ts
  portal-api/src/v1/middleware/rateLimit/index.js
  portal/server/routes/middleware/rateLimit/index.js
  trade-finance-manager-api/src/v1/middleware/rateLimit/index.js
  trade-finance-manager-ui/server/middleware/rateLimit/index.js
Labels: Type: Fix

#4238 chore(deployment): feature deployment
  .github/workflows/feature.yml
Labels: Type: Fix

#4113 feat(DTFS2-6892): update mock builder, enforce complete defaults, document mocked class methods
  libs/common/src/test-helpers/mock-builders/index.ts
  libs/common/src/test-helpers/mock-builders/mock-builder.ts
  trade-finance-manager-api/src/v1/controllers/sso.controller.get-auth-code-url.test.ts
Labels: Type: Feature

#4239 fix(DTFS2-7826): fix facility covenant and guarantee amendment
  azure-functions/acbs-function/api.js
  azure-functions/acbs-function/helpers/http.js
  azure-functions/acbs-function/mappings/deal/helpers/get-industry-classification.js
  azure-functions/acbs-function/mappings/facility/facility-covenant-amend.js
  azure-functions/acbs-function/mappings/facility/facility-covenant-amend.test.js
  azure-functions/acbs-function/mappings/facility/facility-guarantee-amend.js
  azure-functions/acbs-function/mappings/facility/facility-guarantee-amend.test.js
  azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
  azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
  azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js
  azure-functions/acbs-function/src/functions/activity-create-facility-covenant.js
  azure-functions/acbs-function/src/functions/activity-create-facility-guarantee.js
  azure-functions/acbs-function/src/functions/activity-update-facility-covenant.js
  azure-functions/acbs-function/src/functions/activity-update-facility-guarantee.js
  azure-functions/acbs-function/src/functions/activity-update-facility-loan-amount.js
  azure-functions/acbs-function/src/functions/activity-update-facility-loan.js
  azure-functions/acbs-function/src/functions/activity-update-facility-master.js
Labels: Type: Fix
